### ISSUE TITLE
And, Or, Not links get printed twice

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1016]
For some crazy reason (cog-prt-atomspace) reprints a second time the `And`, `Or` and `Not` links.

Try this

```
(And (Concept "A") (Concept "B"))
(cog-prt-atomspace)
```

Do you see double?

This problem doesn't occur for `Inheritance`, `Set` and plenty others, but occurs for `And`, `Or`, `Not` and perhaps others as well.

**Comment by linas** [comment]
Yeah, I see double. Investigating.

**Comment by linas** [comment]
Yeah, its a kind-of bug in the `cog-prt-atomspace` --it is doubled because AndLink inherits from both UnorderedLink and from EvaluatableLink, and  `cog-prt-atomspace` prints types and subtypes -- so AndLink is a subtype in two different ways.

**Comment by linas** [comment]
Yeah, its a kind-of bug in the `cog-prt-atomspace` --it is doubled because AndLink inherits from both UnorderedLink and from EvaluatableLink, and  `cog-prt-atomspace` prints types and subtypes -- so AndLink is a subtype in two different ways.

**Comment by linas** [comment]
Here's an example:
```
(use-modules (opencog))

(define (prt-all)

   (define (prt-atom h)
      ; print only the top-level atoms.
      (if (null? (cog-incoming-set h))
         (display h))
   #f)
   (define (prt-type type)
		(display "These are the atoms of type ")
      (display type)
      (newline)
      (cog-map-type prt-atom type)
      ; We have to recurse over sub-types
      (for-each prt-type (cog-get-subtypes type))
   )
   (prt-type 'Atom)
)

(And (Concept "A") (Concept "B"))

(prt-all)
```

**Comment by linas** [comment]
pull req #1017 fixes this

**Comment by linas** [comment]
closing should be fixed
