### ISSUE TITLE
ISO C++ forbids declaration of ‘TypeCheckException’ with no type

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/atomspace#1021]
I've cloned the latest atomspace code and tried to `sudo make` it.
This went okay until I ran into the following errors:
```
/home/myname/opencog/atomspace/opencog/atoms/core/PutLink.cc: In member function ‘opencog::Handle opencog::PutLink::do_reduce() const’:
/home/myname/opencog/atomspace/opencog/atoms/core/PutLink.cc:287:17: error: ISO C++ forbids declaration of ‘TypeCheckException’ with no type [-fpermissive]
    catch (const TypeCheckException& ex)
                 ^
/home/myname/opencog/atomspace/opencog/atoms/core/PutLink.cc:287:35: error: expected ‘)’ before ‘&’ token
    catch (const TypeCheckException& ex)
                                   ^
/home/myname/opencog/atomspace/opencog/atoms/core/PutLink.cc:287:35: error: expected ‘{’ before ‘&’ token
/home/myname/opencog/atomspace/opencog/atoms/core/PutLink.cc:287:37: error: ‘ex’ was not declared in this scope
    catch (const TypeCheckException& ex)

```

I don't really know, but I suspect that something is wrong with the code rather than with my compiler or system.
Please advise.

**Comment by misgeatgit** [comment]
May be you didn't install latest cogutils.

**Comment by StrangeTcy** [comment]
@misgeatgit , that's a reasonable suggestion, thanks. Following it, I've made and installed the latest cogutils, and then tried to re`make` atomspace. But it didn't help: the same errors were reported.

**Comment by linas** [comment]
Can you double-check this? TypeCheckException is defined here: https://github.com/opencog/cogutils/blob/master/opencog/util/exceptions.h#L366-L381

**Comment by linas** [comment]
closing, no forward movement.

Most likely explanation is that there are two different copies of cogutils installed in two different locations, and the old/stale location is being picked up by the compiler.
