### ISSUE TITLE
Add Atom::size() method

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1029]
I'm surprised to find no C++ function that calculates the size of an atom (1 if a node, 1 + sizes of its outgoings if a link).

I suggest to add an Atom::size() method.

Knowing the size of an atom can be convenient is some contexts such as biasing search towards smaller atoms, etc.

**Comment by linas** [comment]
Repeat of earlier remark: I don't know of any code anywhere that does anything like this.

The pattern matcher does try to find the "thinnest" atom, which is an atom with the smallest incoming set.  "Thin" atoms are good places to start searches.

**Comment by ngeiswei** [comment]
Cool. Closing then.
