### ISSUE TITLE
Move atom factories to classserver

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1048]
The assorted linking issues associated with the atom factories would be best and most easily resolved by moving them to the ClassServer.  That is, the ClassServer would act as the factory.

I sat down to try this just now, and realized that the design is impacted by the ProtoAtom work (issue #513)  as well as the AttentionBank refatoring (issue https://github.com/opencog/opencog/issues/2333) This it seems unwise to actually do this work until those issues get resolved.

**Comment by ngeiswei** [comment]
:+1:

**Comment by linas** [comment]
Close -- resolved by #1164
