### ISSUE TITLE
Inconsistency when inserting a node between c++ and scheme 

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#1061]
The node inserted has an empty-string for name.

### Content of test.cpp
```c++
#include <opencog/atomspace/AtomSpace.h>

using namespace opencog;

int main(){
    AtomSpace as;

    as.add_node(CONCEPT_NODE, "");

    std::cout << as ;

    return 0;
}
```

### Running the c++ code
```bash
>>  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/opencog
>>  g++ test.cpp -std=c++11 -o test -L/usr/local/lib/opencog  -latomspace -latombase
>> ./test
(ConceptNode "#9012052034790845975") ; [9012052034790845975][0]

```
### Taking similar steps in guile

```scheme
scheme@(guile-user)> (use-modules (opencog))
scheme@(guile-user)> (ConceptNode "")
$1 = (ConceptNode "")

scheme@(guile-user)> (cog-prt-atomspace)
(ConceptNode "")
```

### Code versions
cogtuils-sha  = `ed033e7 Merge pull request #63 from ngeiswei/generalize-rand-element`
atomspace-sha = `09b8f01a6 Fix the instructions for odbc`

**Comment by linas** [comment]
OH -- I know -- it was an old attempt to have "nameless atoms" -- that atoms with empty string would all be different from one-another. The problem with these was that its impossible to delete them, because they cannot be found (by name).

**Comment by linas** [comment]
removed in #1067
