### ISSUE TITLE
SQL store/load procedure is crashing with "Atom is already in the TLB, and UUID's don't match! (/tmp/atomspace/opencog/atomspaceutils/TLB.cc:88)"

### ISSUE THREAD

**Issue by andre-senna** [opencog/atomspace#1070]
We are facing this crash in the stable branch of atomspace/opencog.

The crash may happen or not depending on the set of atoms in the atomspace. But the behaviour seems consistent for a given atomspace. I mean, for a given atomspace either it will always crash or it will always work ok.

To reproduce it, use the files under opencog/tests/testCase2 in this branch: https://github.com/andre-senna/opencog/tree/cstest

Call "guile -l ../tests/testCase2/save.scm" and then "guile -l ../tests/testCase2/load.scm"

**NOTE** If you remove the line (opencog nlp aiml) from save.scm the test will pass OK.

**Comment by linas** [comment]
I can re-create this. How urgent is this bug?

The atomspace was refactored a few months ago, to remove UUID's, and push them out to the modules that actually needed them -- e.g. to the sql subsystem. The removal was clean, but the pushing of them into SQL was kind-of sloppy, a quick hack, with some inefficiencies, and I guess also some bugs. 

I was planning on working on the inefficiencies over the next few days or week, so the timing of this is bug report is fortuitous. Is this a blocker, or can you wait?

**Comment by linas** [comment]
I think I found the bug. Its unrelated to my burblings above; its a very old bug that seems to manifest with new versions of odbc.

**Comment by linas** [comment]
The patch in #1071 fixes this for me...

**Comment by andre-senna** [comment]
Yes it works for me too. Thanks!

**Comment by linas** [comment]
Hmm appears to be a postgres bug. I submitted a bug report, here:
https://www.postgresql.org/list/pgsql-bugs/since/201701130000/
its bug 14494

```
---------- Forwarded message ----------
From: linasvepstas@gmail.com
To: pgsql-bugs@postgresql.org
Cc: 
Date: Fri, 13 Jan 2017 18:38:24 +0000
Subject: BUG #14494: Regression - Null arrays are not queryable
The following bug has been logged on the website:

Bug reference:      14494
Logged by:          Linas Vepstas
Email address:      linasvepstas@gmail.com
PostgreSQL version: 9.6.1
Operating system:   Debian unstable
Description:

Array handling appears to have regressed,
with lots of surprising results for empty
and null arrays.

CREATE TABLE foo (
  name    TEXT,
  outgoing BIGINT[]
);

INSERT INTO FOO VALUES ('one', '{43, 67}');
INSERT INTO FOO VALUES ('two', '{}');
INSERT INTO FOO VALUES ('three', null);

test=> select * from foo;
 name  | outgoing
-------+----------
 one   | {43,67}
 two   | {}
 three |
(3 rows)

very good!

test=> select * from foo where outgoing='{}';
 name | outgoing
------+----------
 two  | {}
(1 row)

very good!

test=> select * from foo where outgoing=null;
 name | outgoing
------+----------
(0 rows)

unexpected: wanted one row here.

test=> select * from foo where outgoing != '{43,67}';
 name | outgoing
------+----------
 two  | {}
(1 row)

unexpected: wanted two rows here. Where did the null row go?
test=> select * from foo where array_length(outgoing,1)=2 ;
 name | outgoing
------+----------
 one  | {43,67}
(1 row)

very good

test=> select * from foo where array_length(outgoing,1)=0 ;
 name | outgoing
------+----------
(0 rows)

Huh? there is at least one array whose length is zero, and another that
doesn't have a length...
```

**Comment by linas** [comment]
Its a regression, as it seems that it works on older versions of postgres:
http://stackoverflow.com/questions/737669/postgres-how-to-check-for-an-empty-array
http://stackoverflow.com/questions/25155666/how-to-check-if-an-array-is-empty-in-postgres
