### ISSUE TITLE
double free or corruption errors

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1083]
after the last couple of updates i started getting "double free or corruption" errors for 3 tests.  any suggestions for approaching this?:
````
atomspace master  239b244
        Start  89: FirstNUTest
*** Error in `/home/biocog/hansonrobotics/opencog/atomspace/build/tests/query/FirstNUTest': double free or corruption (!prev):  0x000000000168fdd0 ***
 89/108 Test  #89: FirstNUTest ......................***Exception: Other  0.33 sec
...
        Start  99: BackwardChainerUTest
*** Error in `/home/biocog/hansonrobotics/opencog/atomspace/build/tests/rule-engine/BackwardChainerUTest': double free or corruption (!prev): 0x0000000001c58cd0 ***
 99/108 Test  #99: BackwardChainerUTest .............***Exception: Other  1.42 sec
        Start 100: RuleUTest
100/108 Test #100: RuleUTest ........................   Passed    0.30 sec
        Start 101: PythonEvalUTest
*** Error in `/home/biocog/hansonrobotics/opencog/atomspace/build/tests/cython/PythonEvalUTest': double free or corruption (fasttop): 0x0000000001ded030 ***
101/108 Test #101: PythonEvalUTest ..................***Exception: Other  0.39 sec

The following tests FAILED:
	 89 - FirstNUTest (OTHER_FAULT)
	 99 - BackwardChainerUTest (OTHER_FAULT)
	101 - PythonEvalUTest (OTHER_FAULT)
````

**Comment by linas** [comment]
I've seen this, but not recently. When I saw it, it only happened when the unit test had passed successfully, but the executable was then trying to exit.  For a while, I thought it might be my new, bleeding-edge compiler. Later, I thought it had something to do with libbfd   I thought this because, on exit, there are several ways that cleanup handlers can get run, and if the distro updates libc, there the _exit() routine lives, and you are still using an earlier version, the cleanup handlers could run twice.  

Of course, this can only happen in unusual circumstances, which is why I thought it was libbfd related 

But then the problem went away.  Try doing a `make clean; git pull; make; make install` cycle, starting with cogutils, which is where libbfd gets linked.

**Comment by mjsduncan** [comment]
ok i did the full make clean before building on cogutils and atomspace (444c558) and BackwardChainerUtest works but now CythonUtilities failed with no helpful comment and FirstNUTest and PythonEvalUTest fail in the same way:
````
        Start  90: FirstNUTest
*** Error in `/home/biocog/hansonrobotics/opencog/atomspace/build/tests/query/FirstNUTest': double free or corruption (!prev): 0x00000000017d6e40 ***
 90/110 Test  #90: FirstNUTest ......................***Exception: Other  0.34 sec
...
        Start 103: PythonEvalUTest
*** Error in `/home/biocog/hansonrobotics/opencog/atomspace/build/tests/cython/PythonEvalUTest': double free or corruption (fasttop): 0x0000000001918360 ***
...
        Start 107: CythonUtilities
107/110 Test #107: CythonUtilities ..................***Failed    0.19 sec
````
in the LastTest.log section, it does seem that the test passes or at least i couldn't find any error messages except at the end where it says ".OK" but then says the test fails:
````
...
90/110 Test: FirstNUTest
Command: "/home/biocog/hansonrobotics/opencog/atomspace/build/tests/query/FirstNUTest"
Directory: /home/biocog/hansonrobotics/opencog/atomspace/build/tests/query
"FirstNUTest" start time: Jan 22 11:23 EST
Output:
----------------------------------------------------------
Running cxxtest tests (6 tests)[2017-01-22 16:23:51:112] [DEBUG] BEGIN TEST: test_simple_satisfying_set
.[2017-01-22 16:23:51:115] [DEBUG] BEGIN TEST: test_disconnected_satisfying_set
.[2017-01-22 16:23:51:117] [DEBUG] BEGIN TEST: test_wrong_args_satisfying_set
.[2017-01-22 16:23:51:136] [DEBUG] BEGIN TEST: test_simple_bindlink
.[2017-01-22 16:23:51:138] [DEBUG] BEGIN TEST: test_disconnected_bindlink
.[2017-01-22 16:23:51:140] [DEBUG] BEGIN TEST: test_wrong_args_bindlink
.OK!
<end of output>
Test time =   0.34 sec
----------------------------------------------------------
Test Failed.
"FirstNUTest" end time: Jan 22 11:23 EST
"FirstNUTest" time elapsed: 00:00:00
----------------------------------------------------------
...
[2017-01-22 16:24:03:549] [DEBUG] [global_python_finalize] Start
.OK!
[2017-01-22 16:24:03:550] [DEBUG] [global_python_finalize] Finish
<end of output>
Test time =   0.39 sec
----------------------------------------------------------
Test Failed.
"PythonEvalUTest" end time: Jan 22 11:24 EST
"PythonEvalUTest" time elapsed: 00:00:00
----------------------------------------------------------
````
this is the output for the CythonUtilities test.  if it keeps cropping up i'll make it a seperate issue.
````
107/110 Test: CythonUtilities
Command: "/usr/local/bin/nosetests" "-vs" "/home/biocog/hansonrobotics/opencog/atomspace/tests/cython/utilities/"
Directory: /home/biocog/hansonrobotics/opencog/atomspace/build/tests/cython
"CythonUtilities" start time: Jan 22 11:24 EST
Output:
----------------------------------------------------------
Failure: ImportError (/home/biocog/hansonrobotics/opencog/atomspace/build/opencog/atoms/base/libatombase.so: undefined symbol: _ZNK7opencog9AtomTable10in_environERKSt10shared_ptrINS_4AtomEE) ... ERROR

======================================================================
ERROR: Failure: ImportError (/home/biocog/hansonrobotics/opencog/atomspace/build/opencog/atoms/base/libatombase.so: undefined symbol: _ZNK7opencog9AtomTable10in_environERKSt10shared_ptrINS_4AtomEE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/biocog/hansonrobotics/opencog/atomspace/tests/cython/utilities/test_utilities.py", line 3, in <module>
    from opencog.type_constructors import *
ImportError: /home/biocog/hansonrobotics/opencog/atomspace/build/opencog/atoms/base/libatombase.so: undefined symbol: _ZNK7opencog9AtomTable10in_environERKSt10shared_ptrINS_4AtomEE

----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)
<end of output>
````

**Comment by linas** [comment]
Like I said: the test passes: it prints "OK". The crash occurs in the exit handlers, after main() {} has returned to the C-library `_start` function.  Recall that the operating system calls `_start`, which then performs initialization, include the loading of some shared libraries, and calling the initializers on them (the contents of the `.init` section of the ELF object; aka `__attribute__((constructor))` in C/C++ and only then called `main()`   After main exits, the various finalizers for the shared libraries are called   These would be everything in the `.fini` section of the ELF object, aka `__attribute__((destructor))` in C/C++.

For some reason, the finalizers are being called twice, for you. Don't just 'make clean`, do an `rm -r` to make sure that no cached ELF files are getting re-used.

If that doesn't clear it .. I dunno.   I'm guessing that either your compiler, or your C library were recently upgraded, and there's some conflicting older, non-compatible version lying around somewhere.  Possibly some 32-bit/64-bit conflict: if I recall, your system was set up for dual 32/64-bit operation, and that could be borking it.  Remove everything that's 32-bit. 

Make sure that all the files in /usr/lib and /usr/lib/*64 are actually owned by one of the ubnutu packages  Do this by doing a `dpkg -S libwhatever.so` on each library in these directories. If it's not owned by any package, then it is some left-over garbage from back in the day (look at the datestamp - that's a clue)  and just remove that file.   Doing this will probably solve a bunch of problems for you.

I don't know how you might have scrambled your system to have this kind of junk in it, but I know how I've done it in the past (installing ubunt on top of slackware, installed debian on top of ubuntu, etc. etc. all this leaves behind crap in the filesystem)

**Comment by linas** [comment]
The crash in cythonutilities is due to a mssing `-flto` in the makefile. I just fixed it.  I don't know why, but some systems seem to need this; mine doesn't.

**Comment by mjsduncan** [comment]
thanks, linus!  cythonutilities and PythonEvalUTest pass now after nuking the build folders.  pg persist isn't working but i put that in a new issue.  lib32 gets installed because nvidia drivers need libc6-i386 so i can't get rid of it if i want to use the gpu.  i'm sorting through /usr/lib vs /usr/lib64 now.  at one point i did have to link opencog libraries from /usr/lib to /usr/lib64 to get anything to run at all, for some reason things are getting installed in one place and looked for in the other!  any suggestion on how to sort that out?

**Comment by linas** [comment]
The file `/etc/ld.so.conf` and the files in `/etc/ld.so.conf.d` control where to search for shared libraries.

as far as I know, ubuntu does not use `/usr/lib64` for anythig, so this is a rather foreign thing that got onto your system, somehow.

Anyway, you an just add it to `/etc/ld.so.conf` -- just add it on a line by itself.

**Comment by linas** [comment]
Closing; I think this was due to a screwy distro install problem. Right?  Reopen if it happens again.
