### ISSUE TITLE
Persistence related opencog and scm commands are not working

### ISSUE THREAD

**Issue by misgeatgit** [opencog/atomspace#1092]
I was going through the [Postgres setup instructions](https://github.com/opencog/atomspace/tree/master/opencog/persist/sql) and I have encountered the following issues:
  - All sql opencog commands are not being found ( i.e sql-open, sql-load, sql-store)
  - (store-atom ATOM) throws ```unbounded variable store-atom``` error message even after prompting ```(use-modules (opencog) (opencog persist-sql))```

**Comment by linas** [comment]
Works great for me; I've been using this heavily for the last 3 weeks, and have fixed many bugs.  Anything more specific?

**Comment by linas** [comment]
oh, try also `(use-modules (opencog persist))`  (without the -sql) you need both  that it
```
(use-modules (opencog persist) (opencog persist-sql))
```

the first one is generic, the second is for sql-only.

**Comment by linas** [comment]
closing, I believe that this should really work just fine.  Please reopen if above suggesttion doesn't fix it.

**Comment by misgeatgit** [comment]
Your suggestion solved the command not found issue error but another error as shown below occurred.
```
guile> (use-modules (opencog persist) (opencog persist-sql))

guile> (sql-open "mycogdata" "opencog_user" "cheese")
Backtrace:
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 1511aa0> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 1511aa0>]
In ice-9/boot-9.scm:
 157: 8 [catch #t #<catch-closure 1511980> ...]
In unknown file:
   ?: 7 [apply-smob/1 #<catch-closure 1511980>]
   ?: 6 [call-with-input-string "(sql-open \"mycogdata\" \"opencog_user\" \"cheese\")\n" ...]
In ice-9/boot-9.scm:
2320: 5 [save-module-excursion #<procedure 1041cc0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 4 [read-and-eval #<input: string 9f10d0> #:lang ...]
  37: 3 [lp (sql-open "mycogdata" "opencog_user" "cheese")]
In unknown file:
   ?: 2 [opencog-extension sql-open ("mycogdata" "opencog_user" "cheese")]
In ice-9/boot-9.scm:
 102: 1 [#<procedure f1fc00 at ice-9/boot-9.scm:97:6 (thrown-k . args)> C++-EXCEPTION ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 1511940> C++-EXCEPTION ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure sql-open: Cannot conect to database (/home/OPENCOG/atomspace/opencog/persist/sql/multi-driver/ll-pg-cxx.cc:75)
Function args:
(mycogdata opencog_user cheese)
ABORT: C++-EXCEPTION
```

**Comment by linas** [comment]
OK, make sure that postgres is allowing you to connect:
the following should work:
```
psql -U opencog_user -W mycogdata
```
if it says invalid passwd then you have to edit `/etc/postgresql/9.6/main/pg_hba.conf` and add a line
```
local   all             all                                     md5
```
up where all the othre local lines are.

**Comment by linas** [comment]
if its still invalid password, then you have to 
```
ALTER USER opencog_user PASSWORD 'cheese';
```

**Comment by linas** [comment]
the point is that `-h localhost` hides the fact that hba.conf was preventing you from connecting with unix domain sockets.

**Comment by linas** [comment]
I just now 1) improved the error message 2) altered the login to 'try again' if unix-domain sockets are not configured. This avoid the need to change the `pg_hba.conf` file.
