### ISSUE TITLE
Constify the AtomSpace API

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#114]
# Proposal

I think the AtomSpace API can be properly constified. I had tried many months ago but this time I got a bit further. I think this is sufficiently important to get some attention. Ultimately it might help to avoid some bugs.

For instance

``` C++
const Handle h;
```

would not allow to modify the atom attributes referred by h.

Or perhaps one may want to define a ConstHandle type (like const_iterator in STL). I personally don't think it would be necessary. I don't think we care in practice to have the freedom of modifying a Handle while not having the freedom of modifying its constant. So a mere const Handle, meaning

1. Can't change Handle
2. Can't change Atom

would do.
# Failed attempt

I tried but failed, thought I think it's possible. The mutex _mtx needs to be mutable. And one needs to use for the const accessors AtomConstPtr, NodeConstPtr, LinkConstPtr, etc beside AtomPtr, etc.
# Any remarks?

I would like to hear about your remarks before I try again.

**Comment by vsbogd** [comment]
@ngeiswei , looks like all `Atom` methods except `evaluate`, `execute` and `foreach_incoming` are `const`. As far as I see there is no problem to make these three `const` too. Do you see another steps need to be taken to close this issue?

**Comment by vsbogd** [comment]
To let you know: I have tried adding `const` to methods above, and there is only one small issue with `_silent` in `RewriteLink`.

**Comment by ngeiswei** [comment]
@vsbogd , the Atom class seems to be well constified, I suppose it's been taken care of over the years.

I don't know if `evaluate`, `execute` and `foreach_incoming` should be const, maybe they should I would have think about it, you seem to say is that they could, just need to set `RewriteLink::_silent` mutable, maybe that is correct. And if that seems the right thing to do to you, you can do it. Otherwise I suppose the issue can be closed.

**Comment by linas** [comment]
Re constifying `evaluate` and `execute`: I think I kind-of don't care, except that:

* I'm not sure I believe that there is much of, if any real performance difference from doing this.
* Constifying can be a kind of a straight-jacket, making certain things that could have been simple quite complicated.
* Although Atoms are "in principle" immutable, they sometimes need to hold hidden, cached state. If `evaluate` and `execute` are const, then it becomes hard for these two functions to set or update the cache. Of course, as Nil points out, we can use the `mutable` keyword to manage and markup the hidden or cached data... 
* Net-net it seems to be a matter of taste, I'm not sure I care very much one way or the other, right now.

**Comment by vsbogd** [comment]
Agree that using `const` in complex methods like `evaluate` and `execute` is not very handy.
Ok, I think it makes sense to make `foreach_incoming` const and close this issue
