### ISSUE TITLE
Provide Python API for values/protoAtoms

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1161]
See issue #513 for the general description.

**Comment by linas** [comment]
The correct API for this contains an abstraction for "Values".   A Value can be:

* a list of floats
* a list of strings
* a list of other Values
* (todo) an abstract object that wraps video and audio feeds, that tracks tensorflow nodes, and other rapidly changing data.

Given an atom and a key, one can fetch the Value on that atom, at that key.  One can store a new Value, at that atom, for that key.

TruthValue and AttentionValue (which are exposed in cython) are special cases of values. For historical reasons, they have a distinct API, which I guess we can keep for a while, but maybe (???) move away from eventually.

Wherever you can put a Value, you can also put an Atom.  (but not vice-versa)  So, given an Atom, and a key,  you can store another Atom at that key.  When you ask "what is the Value at this key?"  you can get back a Value, which might be a vector of floats, but it might be an atom. It might be a list of Values, and some of those Values might be Atoms.  

That's what the API should be. ProtoAtoms should be invisible, a behind-the-scenes implementation detail.  Note that there is no API for ProtoAtoms in scheme; only the Value API, described above.

I also hate the name "ProtoAtom"  That was a working title that never got fixed.  I'd like to change the name to something that starts with the letter "a" so that the git directories would be "athing", "base" and "core" in alphabetical order.

The problem with Value (upper-case V) is that its the same word as value (lower-case v)  and this can lead to a lot of confusion.  I cannot think of a good alternative.

The (atom, key,  Value) triple is a "valuation". Some people (e.g. wikipedia) call these "EAV"s, short for "Entity Attribute Value". Note that a collect of attribute-value pairs for a single entity looks like a "KVP database" or a "noSQL database" at that entity.  KVP==key-value-pair.  The name "valuation" comes from logic/model-theory.

**Comment by vsbogd** [comment]
I would like to stop after https://github.com/opencog/atomspace/pull/1819 and switch to another task.
Things which are not done:

(1) LinkValue which can contain Atom instances

When LinkValue.to_list() method is called we should return the atom constructed from C++ Atom handle. This change requires additional constructor for ```atom.pyx``` Cython class to construct it from C++ Atom class instance without passing atomspace.

(2) (todo) an abstract object that wraps video and audio feeds, that tracks tensorflow nodes, and other rapidly changing data

The idea described in https://github.com/opencog/atomspace/pull/1815 looks ok for me. The only restriction I see is: if value is constructed purely in Python it means that it cannot be processed by C++ code. May be it is acceptable restriction. I think we can return to this when use cases for such API will be more clear.

**Comment by linas** [comment]
Hi @vsbogd yes, that's fine. 

(1) is probably pretty important .. except that no one is using LinkValue for anything, yet. (I thought that the attention-allocation people would use it, but they are not)

(2) I do not expect you to personally solve this. Rather, this arose during email conversations, and the details of different possible solutions will become clear as the actual need becomes stronger and more urgent.

**Comment by linas** [comment]
BTW: "value is constructed purely in Python it means that it cannot be processed by C++ code" -- um, but that is the whole point of `PythonEval` -- it calls python code from C++ code.

**Comment by AmeBel** [comment]
@linas LinkValue is being used in ghost & ghost-procedures

**Comment by vsbogd** [comment]
Hi @linas, "the whole point of PythonEval -- it calls python code from C++ code." - thank you for this comment I didn't think about it from this perspective before

**Comment by linas** [comment]
Closing, Done in  #2011
