### ISSUE TITLE
Chainer Unit tests fail after pull req #1164

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1165]
Pull req #1164 changes a lot of code, but conceptually does very little: it just moves the atom factories over to the classserver.  This causes, in some cases, constructors for certain atom types to run earlier than before.  These constructors perform some checks to make sure the atom is in a valid format ... and the chainer unit tests seem to be tripping on some invalidly-formated atoms.

I am not sure why this is the case, there is nothing obvious that pops up.  Easiest to understand is BITUTest: the VariableList constructor prints the message below.  The message seems accurate: the variably list contains a TypeChoice that is just not attached to anything, and it also includes an EvaluationLink which clearly cannot belong there.  It would appear that something somewhere is missing a few parenthesis in the right place.
 
```
In BITUTest::test_expand_1:
/home/linas/src/atomspace/tests/rule-engine/BITUTest.cxxtest:44: Error: Test failed: Expected a VariableNode or a TypedVariableLink, got: EvaluationLink
VariableList is (VariableList
  (TypedVariableLink
    (TypedVariableLink
      (VariableNode "$X") ; [6809909406030619949][1]
      (TypeNode "ConceptNode") ; [3788388250666256890][1]
    ) ; [17718894144153964593][18446744073709551615]
    (TypeChoice
      (TypeNode "TypedVariableLink") ; [1359653833156464510][1]
      (TypeNode "VariableNode") ; [5989952939322278073][1]
      (TypeNode "VariableList") ; [7311909679895453518][1]
    ) ; [11822067860997730867][18446744073709551615]
  ) ; [16814188638364779502][18446744073709551615]
  (EvaluationLink
    (PredicateNode "contain") ; [6339226537938665996][1]
    (ListLink
      (ConceptNode "treatment-1") ; [1169226509931710999][1]
      (ConceptNode "compound-A") ; [5571266438078870282][1]
    ) ; [16887940857902133716][18446744073709551615]
  ) ; [15649912025792571919][18446744073709551615]
) ; [17958762067029919729][18446744073709551615]
 (/home/linas/src/atomspace/opencog/atoms/core/VariableList.cc:62)
.
Failed 1 and Skipped 0 of 3 tests
Success rate: 66%
```

**Comment by ngeiswei** [comment]
@linas I suspect the scope link no longer detects its variables correctly, still investigating...

**Comment by ngeiswei** [comment]
Hmm, apparently it does detect its variables, I still don't understand what's going on.

**Comment by linas** [comment]
FYI, if you got to `VariableList.cc` and comment out the line at the end, the `DEFINE_LINK_FACTORY`, then the VariableList ctor won't run when the atom is inserted into the atomspace. This puts it back into how it used to be -- this and several other ctors did not run until triggered much much later.   If you comment it out, then the test goes a fair ways further, but then crashes in some code that tries to extract variables.

**Comment by ngeiswei** [comment]
@linas I still don't understand the problem but I was able to isolate it in a small unit test `ScopeLinkUTest::test_get_variables_2()`. If you can have a look at it today that would awesome, otherwise I'll take it over tomorrow.

**Comment by linas** [comment]
Fixed in commit ea1047c855373b4c1999038b177bcc53c96c67b0 -- I simply forgot to create a factory for the ImplicationScope, and so it's constructuor never ran

**Comment by linas** [comment]
However, fixing that unit test does not fix BITUTest

**Comment by linas** [comment]
After this fix, UnifyUTest passes. But BIT and BackwardChainer segfault, and RuleUTest fails, and prints messages of the style above.

**Comment by ngeiswei** [comment]
OK, thanks already.

**Comment by ngeiswei** [comment]
I fully understand the problem. The new code has more factory checking and doesn't allow me to construct ill-formed variable declaration. Fine, I just need to have my code be more careful and not construct ill-formed vardecls in the first place.

**Comment by linas** [comment]
I did not any additional checking at all. I simply forced all of the constructors to run when the atom is first added to the atomspace.  Before, some the constructors ran during insert, while others ran only later.   They ran later only because of the python/guile dependency craziness.

viz, the checking was always there, but it was not being performed.
