### ISSUE TITLE
ERROR: Unbound variable: cog-undefined-handle when trying to export-all-atoms from atomspace

### ISSUE THREAD

**Issue by Bitseat** [opencog/atomspace#1227]
I followed the following steps to export atoms from the atom space
1.start cog server http://wiki.opencog.org/w/Starting_cogserver
2. on another terminal start relex
$<opencog_repo>/relex
$./opencog-server.sh
3. on another terminal telnet to 17001
$ rlwrap telnet localhost 17001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

opencog> scm
guile>(use-modules (opencog) (opencog nlp) (opencog nlp chatbot) (opencog nlp relex2logic) (opencog atom-types))
guile>(clear)
guile>(parse-all nlp-parse  "<directory>/file_to_parse.txt")
guile>(export-all-atoms "<directory>/parsed.scm")
=============================
it used to work before. I recently clone and install opencog and it doesn't work any more. instead generate the following error.
Backtrace:
In ice-9/boot-9.scm:
 157: 17 [catch #t #<catch-closure 2d4c9e0> ...]
In unknown file:
   ?: 16 [apply-smob/1 #<catch-closure 2d4c9e0>]
In ice-9/boot-9.scm:
 157: 15 [catch #t #<catch-closure 2d4c8c0> ...]
In unknown file:
   ?: 14 [apply-smob/1 #<catch-closure 2d4c8c0>]
   ?: 13 [call-with-input-string "(export-all-atoms \"../parsed.scm\")\n" ...]
In ice-9/boot-9.scm:
2320: 12 [save-module-excursion #<procedure 2533db0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 11 [read-and-eval #<input: string 3d16680> #:lang ...]
  37: 10 [lp (export-all-atoms "../parsed.scm")]
In ice-9/eval.scm:
 432: 9 [eval # #]
In srfi/srfi-1.scm:
 619: 8 [for-each #<procedure 2533ba0 at ice-9/eval.scm:416:20 (a)> #]
In ice-9/eval.scm:
 399: 7 [eval # #]
 387: 6 [eval # #]
 387: 5 [eval # #]
 386: 4 [eval # #]
 393: 3 [eval #<memoized cog-undefined-handle> (# #<output: ../parsed.scm 28> . #)]
In unknown file:
   ?: 2 [memoize-variable-access! # #]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 32a6440 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 2d4c880> unbound-variable ...]

ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: cog-undefined-handle
ABORT: unbound-variable

How can I fix this?
Thanks!

**Comment by AmeBel** [comment]
cog-undefined-handle was removed in https://github.com/opencog/atomspace/commit/2cacf146fe49fbaa0d3914bc0c04b7a641e3363a

**Comment by linas** [comment]
I think I fixed this in #1230 but did not actually test this.

**Comment by Bitseat** [comment]
It works. Thanks!
