### ISSUE TITLE
Have scheme support multiple loggers

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1269]
For now scheme has only bindings for the default logger, the C++ factory `logger()`. Multiple loggers are supported for C++ but scheme has no way to access them. And one would want to easily control the level or filename, etc, of each logger independently outside of C++, in a scheme script for instance. This is becoming very pressing as we're moving towards greater integration.

I suggest
1. to have the logger bindings take a logger pointer as first argument (and have binding for all existing C++ loggers, so far the default and ure). So for instance
```
(cog-logger-info "message")
```
would become
```
(cog-logger-info (default-logger) "message")
```
or
```
(cog-logger-info (ure-logger) "message")
```
where `(default-logger)` and `(ure-logger)` would point to `logger()` and `ure_logger()` respectively.
2. Add a scheme binding to create a new logger instance, such as
```
(cog-new-logger "component-name")
```
that way a scheme only code can create its own logger with
```
(define my-logger (cog-new-logger "my-component's-logger")
(cog-logger-info my-logger "message")
```

On top of that scheme function helpers would be defined to easily use existing loggers, for instance
```
(cog-logger-info (default-logger) "message")
```
would become
```
(default-logger-info "message")
```
and
```
(cog-logger-info (ure-logger) "message")
```
would become
```
(ure-logger-info "message")
```

Of course one may as will define helpers for new loggers defined in scheme. For instance
```
(cog-logger-info openpsi-logger "message")
```
would become
```
(openpsi-logger-info "message")
```

**Comment by ngeiswei** [comment]
@AmeBel (and others) let me know what you think.

**Comment by AmeBel** [comment]
This will be great. One thing I don't like however is having the helper functions. Having choices with no additional values is a headache, so I think `(cog-logger-info component-logger "message")` should suffice.

**Comment by ngeiswei** [comment]
Well the additional value is compactness, but I see your point, choice has a cost and its not clear whether it's worth it. I guess practice will tell, so for now I probably won't bother with the helpers, and we'll see how it goes.

**Comment by ngeiswei** [comment]
It would be good if `define_scheme_primitive` could support optional arguments, that way functions like `cog-logger-info` could use the default logger when it is not specified. `cog-new-logger` would also need that in order to create a new logger using the settings of an existing one (as the C++ constructor offers).
