### ISSUE TITLE
Consume DontExecLink

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1303]
It seems to me we want `DontExecLink` to be consumed by an execution, just like a `QuoteLink`. For instance, given the atomspace populated with
```
(EvaluationLink (stv 1 1)
   (PredicateNode "URE:BC:and-BIT")
   (BindLink
      (AndLink)
      (Concept "Hello World")))
```
Running
```
(cog-bind
  (BindLink
    (TypedVariableLink
      (VariableNode "$A")
      (TypeNode "BindLink")
    )
    (EvaluationLink
      (PredicateNode "URE:BC:and-BIT")
      (VariableNode "$A")
    )
    (DontExecLink
      (VariableNode "$A")
    )
  )
)
```
produces
```
(SetLink
   (DontExecLink
      (BindLink
         (AndLink
         )
         (ConceptNode "Hello World")
      )
   )
)
```
but, I believe, should produce instead
```
(SetLink
   (BindLink
      (AndLink
      )
      (ConceptNode "Hello World")
   )
)
```

**Comment by linas** [comment]
Yes, that sounds right. I think that was the original intent, but I do not have a clear memory of that any more, and I don't know if it got carefully documented.

**Comment by linas** [comment]
See also #992

**Comment by ngeiswei** [comment]
I'll look into the syntax-case thing. Though probably merely fix `DontExecLink` for now.

**Comment by ngeiswei** [comment]
Actually, after experimenting a bit I would like to remove this feature. The reason being that I need to pass these `BindLinks` around from function calls to function calls and keep treating them as objects. After consuming the first `DontExecLink` the function becomes vulnerable to executions. I tried various tricks like inserting `DontExecLink` in multiple places or adding `QuoteLink` but it doesn't work, so the best way I was is to revert this change (though I won't revert the commit because I want to keep the unit test).

I assume it's OK since it was this in the first place.

**Comment by linas** [comment]
Yeah, I guess so. This is one of those kinds of problems where some short-term arbitrary quick-fix is good enough, but the correct, best long-term answer requires a fair amount of thinking and design.

**Comment by linas** [comment]
Is it still the case that you do not want to consume the DontExecLink ?  Or did this fall by the wayside?

**Comment by ngeiswei** [comment]
Yes I still want to have DontExecLink, or else something else, that do not get consumed.
