### ISSUE TITLE
Bug in AtomSpace::get_handles_by_type

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1336]
`AtomSpace::get_handles_by_type` manages to fetch the same atom twice, moreover one of them is orphan while the other has incoming link. By same atom I can confirm that there are identical, by content, not just by hash value.

I don't have a simple way to reproduce the bug yet, will edit this issue as soon as I can.

**Comment by ngeiswei** [comment]
Found more, there are 2 atoms, identical by content, stored in the TypeIndex. I can tell since they have 2 different memory addresses.

I have no idea how that can happen. The atoms are all created via a scheme script. I should mention that the script manages multiple atomspaces and copy atoms from one atomspace to another, in case that's relevant.

**Comment by ngeiswei** [comment]
This is the first offer
```
[2017-08-16 07:39:25:901] [DEBUG] AtomSpace::add atom = (QuoteLink
  (ImplicationScopeLink
    (UnquoteLink
      (VariableNode "$V-4fe729a2") ; [8925185760973662502][76]
    ) ; [18175843278382742799][76]
    (UnquoteLink
      (VariableNode "$P-42099628") ; [1261471462976964581][76]
    ) ; [10512128980386044878][76]
    (UnquoteLink
      (VariableNode "$Q-209c03b2") ; [1012044293022762668][76]
    ) ; [10262701810431842965][76]
  ) ; [12268298862788601796][76]
) ; [12295003801203452998][76]

[2017-08-16 07:39:25:903] [DEBUG] TypeIndex::insertAtom [0x339e220] = [12295003801203452998][76]
[2017-08-16 07:39:25:905] [DEBUG] AtomSpace::add atom = (QuoteLink
  (ImplicationScopeLink
    (UnquoteLink
      (VariableNode "$V-4fe729a2") ; [8925185760973662502][76]
    ) ; [18175843278382742799][76]
    (UnquoteLink
      (VariableNode "$P-42099628") ; [1261471462976964581][76]
    ) ; [10512128980386044878][76]
    (UnquoteLink
      (VariableNode "$Q-209c03b2") ; [1012044293022762668][76]
    ) ; [10262701810431842965][76]
  ) ; [12268298862788601796][76]
) ; [12295003801203452998][76]

[2017-08-16 07:39:25:906] [DEBUG] TypeIndex::insertAtom [0x3371460] = [12295003801203452998][76]
```

happening here continuously.

**Comment by linas** [comment]
Copying atoms between atomspaces has some very subtle (aka "undefined") semantics.

Its "undefined" because when I last thought about it, there were some crazy cases which did not seem to have any good answers.  They mostly involved adding and deleting atoms in different orders in child and parent atomspaces. I can't think of any good examples just right now.

Naively, I'd say that what you describe should not happen...  are you sure this is in the same atomspace, and not in two different atomsapces?  So for example:

```
aschi is child of asmain
add atom A to aschi
add atom A to asmain
```
will result in two copies of Atom A, one in the child, one in main.  This is as it should be: there is no way for the second add (the add to main) to go out, reach into the child, and rip it out of there.

If you then delete A from the child, and then ask the child about A, the parent-A will become visible.

**Comment by ngeiswei** [comment]
I'm sure it's the same atomspace. It seems the URE is actually the culprit, yet it shouldn't happen, I'm still investigating.

**Comment by linas** [comment]
FYI, while implementing #255 I discovered a bug in the atom-space remove function. Atoms are not being removed correctly from the hash table. This might affect later adds or copies. I should have a fix that's merged in a few hours.

**Comment by linas** [comment]
Try this:
```
--- a/opencog/atomspace/AtomTable.cc
+++ b/opencog/atomspace/AtomTable.cc
@@ -613,6 +613,7 @@ AtomPtrSet AtomTable::extract(Handle& handle, bool recursive)
     // deleting it.
     AtomPtr atom(handle);
     atom = getHandle(atom);
+    handle = atom;
 
     if (nullptr == atom or atom->isMarkedForRemoval()) return result;
 
```
the above fixes my delete/extract bug, it might fix yours!?

**Comment by linas** [comment]
OK, I just merged a whole lotta changes, and I am hoping that these may fix your bug(s). There are really only two that are relevant.  One is the above, which was merged in pull req #1339.  It fixes an issue where an atom is only partially removed from the atomspace; thus, adding it back in might have caused it to appear twice... Hmm. You know, I did not check the TypeIndex, though. Let me check that too.

The other is #1341 with #1343 which cause BackwardChainerUTest to fail, per bug #1342 ... This caused removed/deleted atoms to float around in scheme, which may have been getting added to atomspaces in unexpected ways.

**Comment by linas** [comment]
If the problem continues, asking for the atomspace size will help isolate where/when it happened. The atomspace size method is no wired up to make sure that the size of the typeIndex and the size of the has table are all in agreement with the expected atomspace size, which should help pinpoint duplicated entries in the typeIndex.

**Comment by ngeiswei** [comment]
Thanks Linas! I'm no longer having that problem. However I'm having another problem, `cog-map-type` is able to stumble on `#<Invalid handle>` atoms.

**Comment by ngeiswei** [comment]
Regarding `cog-map-type`, I'm unfortunately unable to reproduce it simply, all I know at the moment is that it seems to come after a URE call. Will look further into it on Monday.

**Comment by linas** [comment]
There's a simple explanation for this. Your pseudo-code looks like this:
```
(cog-new-atomspace)
(define bunch-of-atoms-some-of-which-are-in-new-atomspace  (blah))
(delete new-atomspace)
(format #t "my atoms are ~A\n" bunch-of-atoms-some-of-which-are-in-new-atomspace)
```
So, because the atomspace got deleted, some of the atoms in the scheme list bunch-of-atoms are deleted too. When you try to access those, you now get    #<Invalid handle>  which by the way is `(equal? '() invalid-handle)`  so you can test for them.  In the past, it "worked" and you were accessing atoms that were in your list, but not in any atomspace.  With the new code, you need either to explicitly test for deleted atoms, or regenerate the list after deletion.

**Comment by ngeiswei** [comment]
@linas I've changed my script so that AtomSpaces are never deleted but I'm still getting that problem.

After putting debug messages all over the atomspace code I found that for some weird reason the AtomSpace associated to the culprit (or should I say victim) atom becomes invalid after being copied by https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomTable.h#L234 in `AtomTable::getHandleByTypes`.

Putting debug messages in https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/Handle.h#L86 makes the problem disappears. Something fishy is going on!

**Comment by ngeiswei** [comment]
Some update: putting `std::cout` debug messages doesn't make it disappear, but put `logger()` messages makes it disappear.

**Comment by ngeiswei** [comment]
Should mention that `logger()` must be sync (async flag set to false), which I suppose points to a multi-threading issue.

**Comment by ngeiswei** [comment]
I've added
```
std::this_thread::sleep_for(std::chrono::milliseconds(100));
```
right after the `get_handles_by_type` call https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAtom.cc#L300 but it doesn't prevent the culprit atom to get invalid, letting think that it is not a multi-threading/race-condition issue.

Another weird thing, I need to run it at least once to have the problem, in a new bash environment, or after re-installing the atomspace, the first time I launch my guile script it doesn't crash. I'm starting to think that it's a guile bug.

I can reproduce that problem on my laptop (guile 2.2.2) and desktop (guile 2.0.11). With the atomspace compiled in Release or Debug mode, under a debugger. Here's how to

```
cd <OPENCOG_REPO>/examples/pln/inference-control-learning.scm
```

as I said you need to run at least twice.

I'm gonna try to simplify the script to its minimum to help identify the problem.

**Comment by ngeiswei** [comment]
I managed to simplify the script, you may run
```
cd <OPENCOG_REPO>/examples/pln/inference-control-learning
guile -l bug.scm
(run-bug)
```
to reproduce it.

I think the culprit atom somehow manages to get de-allocated, yet still remains in the atomspace. It could be a URE bug indeed, but I still don't get how the atomspace can let it happen.

**Comment by ngeiswei** [comment]
I'm not sure, but it seems the problem is that `(clear)` would have already deleted the atom as it was in the outgoings of another one deleted by the `extract-type`. If that's the case I'm surprised this bug wouldn't bother more people.

**Comment by ngeiswei** [comment]
Bingo! The following generates the same error
```
(List (Set (List (List (List (List))))))
(Set (Set (List (List (List (List))))))
(clear)
ERROR: In procedure cog-extract-recursive:
ERROR: In procedure cog-extract-recursive: Wrong type argument in position 1 (expecting opencog atom): #<Invalid handle>
```
Likely explanation: `extract-type` is gonna start removing the List wrapped in the `Set` (before it occurs before List in the atom type order). By the time `ss_map_type` arrives to the call of `extract-type` occuring on `List`, the first `extract-type` call on `Set` isn't probably over, thus some `List` are still in the index, with an invalid atomspace about to be removed.

**Comment by ngeiswei** [comment]
OK, I know exactly what is going on, `cog-extract-recursive` (called from `cog-type-map`, itself called from `clear`) removes incoming links of a certain atom. If some of these incoming links have the same type they will no longer be in the atomspace but still processed by `ss_map_type` since the list of atoms to process is built before hand, see https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAtom.cc#L299

So what is the right way to fix that?

I would assume that we merely need to had a conditional before https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAtom.cc#L307 to make sure that the atom is still valid.

@linas do you think it's the best fix? Or is there a safer alternative?

**Comment by linas** [comment]
Sorry for lack of replies, been out, the fix #1357 looks good.

**Comment by linas** [comment]
I'm reading your comments above... does #1357 fix the issue(s)?

**Comment by ngeiswei** [comment]
It does thanks!

**Comment by ngeiswei** [comment]
It does thanks!
