### ISSUE TITLE
sql backing store unit tests failing due to invocation of odbc

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1345]
is this now a requirement or can the odbc tests be turned off?

thanks, linas!

**Comment by mjsduncan** [comment]
somehow unixodbc was reinstalled on my machine.  all unit tests pass after removal.

**Comment by linas** [comment]
all unit tests should pass if unixodbc is installed. (although it does need to be configured after install)

**Comment by mjsduncan** [comment]
the unit tests work for me without unixodbc as well.  the notes said using odbc was significantly slower, is that still true?

**Comment by linas** [comment]
unixodbc is about 2x slower. Unit tests should pass, whether or not it's installed.
