### ISSUE TITLE
Inconsistency in gearman module documentation

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1398]
The readme tells that the second argument of `dist-eval` is `worker-id-name`
```
(dist-eval “scheme-expr” “worker-id-name”)

   This sends the indicated scheme expression to be evaluated on
   the indicated worker. It will block until a reply is received.
   The reply is expected to be a string.
```

but the code says that it should be the client id, not the worker id, see https://github.com/opencog/atomspace/blob/master/opencog/persist/gearman/DistSCM.cc#L45

To be honest I don't understand why we need to specify the client ID, neither the worker ID for that matter.

**Comment by linas** [comment]
won't fix, gearman being removed
