### ISSUE TITLE
Persistent storage access via guile crashes

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1404]
I followed the instructions in https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md#database-setup-1 including creating a user, with the same unix user name `nilg`. I know the next section https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md#user-setup says not to, but since it is optional I thought I'm sticking with the simplest way.

I was able to initialize my table following https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md#table-initialization Then I tried to access the persistent storage within guile as explained in https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md#access-via-guile but it crashes 
```
scheme@(guile-user)> (use-modules (opencog persist) (opencog persist-sql))
scheme@(guile-user)> (sql-open "postgres:///mycogdata?user=nilg")
Segmentation fault (core dumped)
```
the core dump doesn't reveal anything (just a bunch of `?`).

What did I do wrong to make it crash?

**Comment by linas** [comment]
Beats me. I've never seen anything like that (on multiple OS'es, e.g. debian and ubuntu flavors) Without a stack trace, I don't know how to diagnose.  All I can think of is the usual suspects: stale libraries/shared objects being loaded.

Does `(sql-stats)` work before the open? It should print something like "no database is open".  If it doesn't work, then there's some issue with the guile module.

Make sure your `cogserver.conf` or `opencog.conf` files does NOT load any SQL cogserver modules (there should not be any such modules any more, except for stale ones left-over in your filessytem). Remove any other SQL config paramters from the conf file.

**Comment by ngeiswei** [comment]
`(sql-stats)` does return `Database not open`.

I'm not using the cogserver at all, only guile, so I don't it should be related to `opencog.conf`.

My version is postgresql is 9.5.

Table initialization as explained here https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md#table-initialization works.

**Comment by linas** [comment]
without a stack trace, I dunno. Are you using guile-2.2 or guile-2.0?   I think it should not make a difference, but the guile stack traces do contain lots of ??? in them because execution bounces around through bytecode, rather than through subroutine calls.   There should be some C calls visible in the stack trace ....

**Comment by ngeiswei** [comment]
I've installed guile-2.2 and it not longer crashes!

**Comment by linas** [comment]
OK, so that's weird and unexpected.
