### ISSUE TITLE
content_based_handle_less isn't correct over scope links not in atomspace

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1446]
See unit test added in https://github.com/opencog/atomspace/commit/8c7ca0f7d2f92bf5941b2b7e3f93226cbb5cbb65

@linas could you confirm that you see this as a bug as well?

**Comment by mjsduncan** [comment]
did you update the unit test yet?
```
...
[2017-11-29 16:54:38:136] [INFO] BEGIN TEST: test_content_less

In ScopeLinkUTest::test_content_less:
/home/mjsd/oc/atomspace/build/tests/atoms/../../../tests/atoms/ScopeLinkUTest.cxxtest:188: Error: Assertion failed: not lt(scY, scX)
Failed 1 and Skipped 0 of 6 tests
```

**Comment by ngeiswei** [comment]
I have updated the unit test with what I believe to be a bug. I have committed a fix #1448 but I'm waiting for Linas feedback.

**Comment by linas** [comment]
Yes, the unit test addition in 8c7ca0f seems like it should pass.

**Comment by linas** [comment]
I think this bug can be closed.
