### ISSUE TITLE
Crash guile on (ExecutionOutputLink (Variable "$X") (Variable "$Y"))

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1451]
I know it is more or less ill formed, one should use instead
```
(Quote (ExecutiontOutput (Unquote (Variable "$X")) (Unquote (Variable "$Y"))))
```
and the latter works, but still the former shouldn't crash guile.

**Comment by ngeiswei** [comment]
Wait! This crashes on Debian 8.7.1 but not on Ubuntu 17.10!!!

**Comment by ngeiswei** [comment]
@linas that constructor

https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/ExecutionOutputLink.cc#L79

misses the call of `check_schema`. Anyway reason for that?

I'm asking because I noticed a discrepancy between adding `ExecutionOutputLink` with proper quotes with the schema interface and with the C++ interface (the C++ interface raise the exception in `check_schema`, but the scheme interface doesn't [weirdly enough in spite of using the C++ interface, I'm really confused]).

**Comment by linas** [comment]
Can you provide a fuller example? This resmbles #1450 but is somehow diferent, so I'm unclear on the question/problem.

**Comment by linas** [comment]
> misses the call of check_schema. Anyway reason for that?

No. Its a bug, should have been checked.

**Comment by ngeiswei** [comment]
Full example
```
(use-modules (opencog exec)
(define el (ExecutionOutputLink (Variable "$X") (Variable "$Y")))
(cog-execute! el)
```
results in
```
Segmentation fault (core dumped)
```
Still crashes with lattest update a319aa8c8

**Comment by ngeiswei** [comment]
Just to be clear, it's a not urgent as far as I am concerned since I wrap that in quotations.

**Comment by linas** [comment]
What do you mean "crashes"?  I get this:  
```
scheme@(guile-user)> (use-modules (opencog) (opencog exec)
)
scheme@(guile-user)> 
scheme@(guile-user)> (define el (ExecutionOutputLink (Variable "$X") (Variable "$Y")))
ERROR: In procedure cog-new-link:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-new-link" "ExecutionOutputLink must have schema! Got (VariableNode \"$X\") ; [6809909406030619949][1]\n (/home/linas/src/novamente/src/atomspace-git/opencog/atoms/execution/ExecutionOutputLink.cc:51)\nFunction args:\n((VariableNode \"$X\")\n (VariableNode \"$Y\")\n)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> 
```

**Comment by linas** [comment]
Since you get a core dump instead of an exception ... are you using guile-2.0 or guile-2.2? Tghis should not make a difference, but maybe it does.   Possibly you have old libraries in your path, linking to something that can't quite handle the exception frame correctly.

**Comment by ngeiswei** [comment]
I'm indeed using `guile-2.0`.

**Comment by ngeiswei** [comment]
I'm closing, it seems more to be a problem with guile than opencog.
