### ISSUE TITLE
extended GlobUTest fails

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1454]
I just added a different kind of glob test in pull req #1453 and it causes the test to fail.

Man Hin -- I am assigning this to you, since you are the last one to look at this code.

If you are busy or the thought of looking at this code makes your head hurt, a plausible course of action is to ignore this and/or maybe even disable the failing subtest.  Can't tell if ghost will or will not need it.

**Comment by mjsduncan** [comment]
```
[2017-12-03 04:10:47:689] [DEBUG] BEGIN TEST: test_glob_backtoo
backtoo (SetLink
) ; [9223723880575656588][1]


In GlobUTest::test_glob_backtoo:
/home/mjsd/oc/atomspace/build/tests/query/../../../tests/query/GlobUTest.cxxtest:443: Error: Expected (1 == backtoo->get_arity()), found (1 != 0)
/home/mjsd/oc/atomspace/build/tests/query/../../../tests/query/GlobUTest.cxxtest:461: Error: Expected (backtoo == response), found ({ 10 00 70 03 00 00 00 00 ... } != { 20 2D 6F 03 00 00 00 00 ... })
[2017-12-03 04:10:47:706] [DEBUG] END TEST: test_glob_backtoo
[2017-12-03 04:10:47:707] [DEBUG] BEGIN TEST: test_glob_multiple
ma (SetLink
  (ListLink
    (ConceptNode "FOO") ; [3610779189989521226][1]
  ) ; [12846342611772816061][1]
) ; [12857953454561881801][1]

[2017-12-03 04:10:47:712] [DEBUG] END TEST: test_glob_multiple
.
Failed 1 and Skipped 0 of 13 tests
Success rate: 92%
<end of output>
Test time =   1.39 sec
----------------------------------------------------------
Test Failed.
"GlobUTest" end time: Dec 03 12:10 CST
"GlobUTest" time elapsed: 00:00:01
----------------------------------------------------------
```

**Comment by linas** [comment]
Hi Mike,

Yes, that's right. At this point, there are four choices: 1) ignore that error, 2) stub out `test_glob_backtoo` so tht it doesn't run, 3) fix the glob code to pass the test, 4) get someone else to fix the glob code.

**Comment by mjsduncan** [comment]
sure, but what's the use case being tested for test_glob_backtoo?  i don't have enough info to apply the decision tree...

**Comment by linas** [comment]
Well, look at the unit test itself. It explicitly shows what the expected answer should be.

Globs were originally invented to handle AIML-style pattern matching, and are used fairly heavily by ghost.  Globs are the same thing as wild-cards in regexes.

In this unit test, the data is the `list a b c d e f g h i` and the pattern is `* * *`  so the first * can match one or more letters from the begining of the string, the second * can match letters from the middle, and the third * matches letters from the end.   Then there is a grounded predicate not that rejects all matches unless the middle star is `d e f`.   What the current pattern matcher does is to try every possible 3-way split, but the middle third is always taken to be one letter, never 2 or more, so the unit test fails.

The code to split a list of atoms into every possible N-way combination of them is kind of gnarly.  I wrote the original version, it was imperfect, Man Hin wrote the revised version.

How likely is ghost to hit this?  Well, suppose ghost has an AIML-like rule "* you said that * is a kind of *" that was trying to match "Micheal J Fox you said that a blue vase is a kind of expensive pottery" -- is that middle star going to be able to pick out "blue vase"?    Hmm Dunno. I bet it cannot.

**Comment by linas** [comment]
hang on ..

**Comment by linas** [comment]
I think I found a bug

**Comment by linas** [comment]
Yeah, seems that my extension of the unit test had a bug in it.  It should pass now.

**Comment by mjsduncan** [comment]
thanks for the fix and the detailed explanation, linus!
