### ISSUE TITLE
Rule names not populated with the new URE configuration format

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/atomspace#155]
@ngeiswei 
Nil, with the new URE config scheme format, Rule objects are no longer populated with their names. I think we need the rule names for, e.g., inference trail history, debugging, etc.

**Comment by eddiemonroe** [comment]
@ngeiswei btw, I am not seeing a way to populate the names through a C++ code addition with the current configuration scheme, because the rules get associated with the rbs in the atomspace as the rule Bindlinks, which do not include the rule name info.

**Comment by ngeiswei** [comment]
@eddiemonroe I decided to do that (put the BindLink directly as member) cause DefineLink wasn't completely implemented and EquivalenceLink seemed inappropriate.

I'm thinking of actually completing DefineLink, then fixing that.

**Comment by linas** [comment]
what more do you need for DefineLink? ??

**Comment by ngeiswei** [comment]
@linas this then DefineLink has been fully implemented so it's alright.
