### ISSUE TITLE
Problems making Atomspace in Ubuntu 16.04

### ISSUE THREAD

**Issue by glicerico** [opencog/atomspace#1551]
I am having problem when building the latest atomspace on Ubuntu 16.04.
Using:
   gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5

[ 60%] Linking CXX executable profile_bindlink
../cython/libPythonEval.so: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
opencog/benchmark/CMakeFiles/profile_bindlink.dir/build.make:113: recipe for target 'opencog/benchmark/profile_bindlink' failed
make[2]: *** [opencog/benchmark/profile_bindlink] Error 1
CMakeFiles/Makefile2:1134: recipe for target 'opencog/benchmark/CMakeFiles/profile_bindlink.dir/all' failed
make[1]: *** [opencog/benchmark/CMakeFiles/profile_bindlink.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ngeiswei** [comment]
Maybe it comes from the fact that you're using an different version of gcc than the one boost has been built with. I say that because the default version of gcc of Ubuntu 17.10 is not 4.8 if I recall correctly. Just a guess...

**Comment by linas** [comment]
Is this still an issue?

**Comment by linas** [comment]
I just checked standard 16.04 - it uses a different compiler version:
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

I'm guessing you have an incomplete system upgrade.  Try this:
```
sudo apt-get update
sudo apt-get dist-upgrade
```

This will probably cause hundreds of packages to install, and it will probably fix the problem.

**Comment by glicerico** [comment]
@linas I changed to the same gcc version that you showed:

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609

but I still get the same error

**Comment by linas** [comment]
Did you `make clean`?  Better yet, `rm -r build; mkdir build; cd build; cmake ..; make`  just so that you get a clean start?

Another possibility is that you have multiple conflicting boost libraries installed: oneof them is probably something you installed by hand, or use pip or ezinstall or anaconda to install. Remove all those version.

Best way to do this is to remove *all* versions, verify that they really are all gone, and then re-install the version of boost by saying `apt-get install libboost-dev`

**Comment by linas** [comment]
also, when you say "I changed to the same gcc version" that makes me deeply suspicious. It is highly unusual for ordinary programmers to "change" gcc versions.  There's pretty much no reason for this, so the fact that you ended up with a system that had some old, archaic compiler on it, which you then "changed" .. it feels like you asked for trouble, then actually got trouble ... and now you want help ... !?
