### ISSUE TITLE
Wrongly consuming quotation while executing

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1561]
Here's the following pattern
```
(LambdaLink
  (VariableList
    (VariableNode "$sha-arg-0") ; [949102443632971434][1]
    (VariableNode "$sha-arg-1") ; [4859387568654154175][1]
  ) ; [9448388737473849152][1]
  (LocalQuoteLink
    (AndLink
      (VariableNode "$sha-arg-0") ; [949102443632971434][1]
      (VariableNode "$sha-arg-1") ; [4859387568654154175][1]
    ) ; [9237651940852305971][1]
  ) ; [9268420674243330182][1]
) ; [9607689798623181459][1]
```
executing this pattern (via cog-execute!) outputs
```
(LambdaLink
   (VariableList
      (VariableNode "$sha-arg-0")
      (VariableNode "$sha-arg-1")
   )
   (AndLink
      (VariableNode "$sha-arg-0")
      (VariableNode "$sha-arg-1")
   )
)
```
which changes the meaning of that pattern.

The former means: *any binary AndLink*.

The latter means: *2 independent clauses*.

That is obviously wrong, but besides that, why quotation should be systematically consumed by execution? I can understand that patterns processed by the pattern matcher should have their quotations consumed so that matching patterns can be turned into proper instances (during the rewriting process of the `BindLink`), but besides that, I see no reason they should be.

**Comment by ngeiswei** [comment]
Yeah the problem is really running deeper, the following
```
(QuoteLink
   (LambdaLink
      (UnquoteLink
         (VariableNode "$vardecl")
      )
      (UnquoteLink
         (VariableNode "$body")
      )
   )
)
```
executes into
```
(LambdaLink
   (VariableNode "$vardecl")
   (VariableNode "$body")
)
```
another non-sense.

So really `Instantiator::walk_expr` shouldn't consume quotations. I'm thinking of disabling it and relying instead on `RewriteLink::consume_ill_quotations()` when substitution occurs (during term rewriting by `PutLink` or `BindLink`).

**Comment by linas** [comment]
?? But I thought that was the whole point of quotations: that they would be consumed by execution.

If they are not consumed, then what's the point of having them?  If they are not consumed, how does it ever become possible to remove them?  And if you never need to remove them, then why do you need them at all?

**Comment by ngeiswei** [comment]
QuoteLink semantics over some atom is *match itself instead of execute*, but the notion of matching itself is only relevant when the atom is involve with the pattern matcher.

What I'm suggesting is that outside of pattern matching there is no reason to consume quotations. Within pattern matching use, however there is all reasons for that, due to rewriting operation by `PutLink` or `BindLink`.

Anyway, upon further reflection, I have concluded that it's better to consume quotations in so far as the semantics is preserved, which currently isn't the case, as exhibited by the examples.

**Comment by ngeiswei** [comment]
I mean, you expect `2+3=5` not `2+3=4`, execution, beta-reduction, etc, is expected to be compatible with semantics equality. And the semantics should be at least that if A turns into B by execution, both A and B should return the same results when run by the pattern matcher. The examples I bring forward break that.

**Comment by ngeiswei** [comment]
I think I have fixed all problems pertaining to that issue.
