### ISSUE TITLE
Add Link method for recreating link and copying values

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1581]
The following 2 lines often occur
```c++
		Handle nh(createLink(t, oset));
		nh->copyValues(h);
```
we probably want to wrap that in a function like `recreateLink` that is similar to `createLink` but takes an extra argument with the original atom recreated to copy its values.

I suspect that copying values when recreating a link has been omitted in a few places so having such function would help to mitigate that kind of omission.

**Comment by linas** [comment]
Often occur where? The atomspace de-duplicates atoms, so the above really makes sense only if the new link is different from the old one -- I guess you changed the type, or the oset ... Stuff like the above is done in some very special places in the atomtable, and in the sql backend, but these are very special-case type situations, which have to be carefully handled on a case-by case basis.

**Comment by ngeiswei** [comment]
Here are all instances I found

https://github.com/opencog/atomspace/blob/f707d428aeaf5e57a09c0f9cf193d6fb262f3dca/opencog/rule-engine/Rule.cc#L488
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/core/RewriteLink.cc#L414
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/core/RewriteLink.cc#L469
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/execution/Instantiator.cc#L135
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/execution/Instantiator.cc#L498
https://github.com/opencog/atomspace/blob/b841b52724d77a3f14b33f7ab875b4bd3832f5fd/opencog/atomutils/Substitutor.h#L76

it's not that much, but I suspect some value copyings are missing...

**Comment by ngeiswei** [comment]
They occur when an atom's outgoing is being changed and it's values must be copied. So I was thinking of a function like
```c++
Handle recreateLink(const HandleSet& new_oset, const Handle& old_h);
```
and what the code would do is create a link of type `old_h->get_type()` and copy its values and return it. (Maybe `LinkPtr` should be used instead of `Handle`).

**Comment by linas** [comment]
I don't think I like it. It doesn't make the code any clearer or easier to understand -- when reading this code, I would have to go grep for `recreateLink` to see what it does, and then try to remember that.  This takes extra time and effort, and there are more than enough things to remember already, so saving one line of code in five different places just doesn't seem an adequate payoff for the extra mental strain.

**Comment by ngeiswei** [comment]
Here are all instances of `createLink` that **might** be missing a call of `copyValues`

https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/core/RewriteLink.cc#L97
https://github.com/opencog/atomspace/blob/5b3b7c7fd68d5666adecc627139203418e287616/opencog/atoms/reduct/PlusLink.cc#L109
https://github.com/opencog/atomspace/blob/5b3b7c7fd68d5666adecc627139203418e287616/opencog/atoms/reduct/PlusLink.cc#L161
https://github.com/opencog/atomspace/blob/14e3b338dc3c4613cb661acece24e10310033ad9/opencog/atoms/core/PutLink.cc#L355
https://github.com/opencog/atomspace/blob/14e3b338dc3c4613cb661acece24e10310033ad9/opencog/atoms/core/PutLink.cc#L362
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/atoms/execution/Instantiator.cc#L302
https://github.com/opencog/atomspace/blob/5b3b7c7fd68d5666adecc627139203418e287616/opencog/atoms/reduct/TimesLink.cc#L111
https://github.com/opencog/atomspace/blob/5b3b7c7fd68d5666adecc627139203418e287616/opencog/atoms/reduct/ArithmeticLink.cc#L152
https://github.com/opencog/atomspace/blob/f707d428aeaf5e57a09c0f9cf193d6fb262f3dca/opencog/atoms/core/Variables.cc#L262
https://github.com/opencog/atomspace/blob/14e3b338dc3c4613cb661acece24e10310033ad9/opencog/atoms/core/PrenexLink.cc#L78
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/unify/Unify.cc#L337
https://github.com/opencog/atomspace/blob/75e486e295f7e3125ad462202f4357c33e9991ca/opencog/unify/Unify.cc#L382
https://github.com/opencog/atomspace/blob/b841b52724d77a3f14b33f7ab875b4bd3832f5fd/opencog/persist/zmq/atomspace/ProtocolBufferSerializer.cc#L252
https://github.com/opencog/atomspace/blob/b841b52724d77a3f14b33f7ab875b4bd3832f5fd/opencog/persist/sql/postgres-dead/PGAtomStorage.cc#L521
https://github.com/opencog/atomspace/blob/b841b52724d77a3f14b33f7ab875b4bd3832f5fd/opencog/persist/sql/postgres-dead/PGAtomStorage.cc#L1738
https://github.com/opencog/atomspace/blob/cf52aba1775cc3f74e95c92433714497e626ee6d/opencog/persist/sql/multi-driver/SQLAtomStorage.cc#L1655

let me clear, I don't know if they miss `copyValue` I would need to carefully review the code, I'm just suspecting they might.

**Comment by linas** [comment]
It is a worthy exercise to grep for all uses of createLink, to see if they are all correct.

**Comment by ngeiswei** [comment]
If it's just for 5 or 6 occurrences I agree, but as I was looking into it, it stroke me that maybe it is frequent pattern that might have been missed (as I recall I had to fix a bug once because of such omission).

**Comment by ngeiswei** [comment]
I'll look at them and let you the ones I don't understand enough...

**Comment by linas** [comment]
OK, quick review: any use in `atomspace/opencog/atoms/reduct/` should not copy values. That knocks out 4 cases. The  `postgres-dead` directory is dead code, and should be removed. the third posgres usage is correct. So that knocks out 3 more. 

`PutLink` and `PrenexLink`  - my knee-jerk reaction is that these should not copy values.  It would be strange if they did. but I suppose that is worth thinking about, arguing about.

`Unify` - no clue.

`Variables` - almost surely not.

`zmq` Oof. I think that dead code anyway.

That leaves `RewriteLink`, which should copy values, except that -- clearly, alpha conversion is wrong, so my initial reaction is that the methods called 'alpha conversion' should be removed.  Its the wrong concept for the atomspace.

**Comment by ngeiswei** [comment]
Thanks!

**Comment by ngeiswei** [comment]
OK, I suppose in order to determine when values must be copied or not we need to set some assumptions. For instance that they are no values of interest attached to links like `QuoteLink`, etc. Let me try to collect these assumptions

1. No value on quotations, so no value on `QuoteLink`, `UnquoteLink` and `LocalQuoteLink`. Relates to `Instantiator::walk_tree` and `RewriteLink::consume_quotations`.
2. No value on variable declarations or list of arguments applied to schema or predicate. Relates to `atomspace/opencog/atoms/reduct`, `PutLink::do_reduce` and ``Unify::substitute_vardecl`.
3. No value on `PutLink`. Relates to `PrenexLink::reassemble`. (I'm not sure I like this one because a `PutLink` can potentially be a function or predicate, and we want to be able to assign some values to them).

If I make these assumptions then the only cases left are (besides `zmq` and `postgres-dead`):

https://github.com/opencog/atomspace/blob/f707d428aeaf5e57a09c0f9cf193d6fb262f3dca/opencog/atoms/core/Variables.cc#L262
https://github.com/opencog/atomspace/blob/cf52aba1775cc3f74e95c92433714497e626ee6d/opencog/persist/sql/multi-driver/SQLAtomStorage.cc#L1655

Also, it's not clear to me if equivalent atoms should hold equivalent values. In principle I'd say no, but we can't ask the user/agent to take care of maintaining values on unconscious/automatic transformed atoms.

**Comment by linas** [comment]
The atoms in SQLAtomStorage.cc are being recreated from the database; all values are stored in the database too, and there is a very strict semantics about how those values get restored from disk. These interactions are important to get right; I think they are mostly tested in the unit test cases, and I certainly depend on them working correctly for the language learning project, where a large variety of values are stored to, and read from storage. I believe that particular line of code is 100% correct; the atom is being created/recreated for the first time, and the path for restoring the values comes in a different path; see lines 291 ff, 327 ff 348 ff 817 thru 930 lines 970 ff 1745ff culminating in lines 1812 and 1868 -- these last two are I thnk what you are looking for.

**Comment by linas** [comment]
For Variables.cc, if you back up and look at teh routine that is calling creteLink, you get to lines 178-184 which indicate that it is yet another variant of the same kind of logic, and operation as PutLink.  Just like PutLink, it is being assembled from two parts: an initial template/pattern with variables in it, and values to plug into those variables. I don't see any particular reason to copy values from the initial template/pattern to the final instance.

As to why this code is similar-to-but-different from similar logic in Instantiator.cc and PutLink.cc -- that I cannot easily answer, except that I believe that Instantiator.cc and PutLink.cc call Variables.cc to actually perform the substitution, or something like that.  The code is trying to be modular, but apparently, the act of replacing variables with values has a way of spilling over into several different places.

**Comment by ngeiswei** [comment]
Regarding copying values on a `PutLink`, if one may authorize to set values on a `PutLink` then one would probably want to have these values copied after substitution.

Let me give an example, imagine you have for instance
```
PutLink
  (Lambda X (Inheritance (Variable "$X") (Concept "A")))
  (Lambda Y (Or (Concept "B") (Variable "$Y"))
```
Now let say you set the TV of that predicate
```
PutLink (stv 0.1 0.5)
  (Lambda X (Inheritance (Variable "$X") (Concept "A")))
  (Lambda Y (Or (Concept "B") (Variable "$Y"))
```
Then substitute. The result is equivalent to the PutLink above, and thus you might expect the TV would be preserved
```
(Lambda (stv 0.1 0.5)
  (Variable "$Y")
  (Inheritance (Or (Variable "$Y") (Concept "B")) (Concept "A")))
```

Alternatively this could perhaps be let to another process, a rewriting rule that explicitly copies values, or certain types of values upon reduction/execution.

Anyway, I agree that at this time there is no need to take action. Thanks for your patience on what turned out to be a likely meaningless issue at that point.

**Comment by linas** [comment]
The meta issue is that some values are truth values, in which case, one can apply PLN-type reasoning to encourage certain results.  Other values are not truth values: I use the so-called "matrix" code to represent (extremely) sparse matrices in the atomspace; the matrix entries have all kinds of values attached to them, as well as yet more values to hold row and column marginal sums (marginal probabilities).  If or when to copy these is manifestly unclear.   Yet clearly, there are complex patterns encoded in there.

Look, I view the design of the atoms and the atomspace as this kind of vague, murky groping for some kind of poorly-defined compute platform that is suitable for knowledge representation, reasoning, and computation with some kind-of unknown, murky AGI-ish algorithms that do something AGI-ish.  So in that sense, it is not at all clear that the atomspace is the "right" design: somedays it feels like a jumbled mish-mash of poorly-thought-out ideas. However, that is not an excuse for sloppy coding or sloppy thinking: just because the problem is poorly defined, and the AGI answer is unknown...well, that is all the more reason the be very careful in one's thinking, and very strict about what one is doing.
