### ISSUE TITLE
PutLinkUTest

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1600]
As of right now, PutLinkUTest fails

**Comment by shujingke** [comment]
And it is very very slow, and cause my vm dead every time. 
It ouputs: Start  25:PutLinkUTest 
Then waiting for a relatively long time (like 15 minutes), there is no further outputs. But my vm just dies and have to restart the vm.

**Comment by ngeiswei** [comment]
Yep, as I recall it can end up in infinite loops. The follow PR https://github.com/opencog/atomspace/pull/1593 fixes that but we're waiting for @linas approval or suggestion.

**Comment by linas** [comment]
I'm swamped, I've got a half-finished fix for the AbsentLink bug that I wanted to do first.  I'm not sure when I can get to this; can the failing part of the test be stubbed out?

**Comment by linas** [comment]
Pull req #1676 fixes this. Closing.
