### ISSUE TITLE
BackwardChainerUTest fails

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1604]
This unit test passed yesterday. Today it fails.

**Comment by shujingke** [comment]
This UTest was already failed for me when I run it before modified it. I just cancelled my new added test functions (#1611) and it still failed. It got several below errors:
[ERROR] UREConfig - invalid rulebase specified! (/home/rainkekeke/atomspace/opencog/rule-engine/UREConfig.cc:46).
It seems the rule base is not defined for some test functions.

**Comment by linas** [comment]
Hmm The test was passing last week. Can you bisect, and find out which commit broke it? Use `git bisect` to bisect.
https://stackoverflow.com/questions/4713088/how-to-use-git-bisect
https://git-scm.com/docs/git-bisect
