### ISSUE TITLE
Bug or feature? deleting an atom using a variable in scm shell does remove the atom from the atomspace but not from the scheme enviroment.

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#162]
### 1. Inpute atoms
```
opencog> (clear)
Entering scheme shell; use ^D or a single . on a line by itself to exit.
guile> 
guile> (cog-prt-atomspace)

guile> (define x (cog-new-node 'ConceptNode "abc")) 

guile> (cog-prt-atomspace)
(ConceptNode "abc")

guile> (define y (cog-new-node 'ConceptNode "def")) 

guile> (cog-prt-atomspace)
(ConceptNode "def")
(ConceptNode "abc")

guile> (define l (cog-new-link 'ListLink x y)) 

guile> (cog-prt-atomspace)
(ListLink
   (ConceptNode "abc")
   (ConceptNode "def")
)
```
### 2. delete the link 
```
guile> (cog-delete l)
#t
guile> (cog-prt-atomspace)
(ConceptNode "def")
(ConceptNode "abc")

```
### 3. part that caused me to doubt what the scheme shell does, 
@williampma informed me that the following was always the case.
```
guile> l
(ListLink
   (ConceptNode "abc")
   (ConceptNode "def")
)

guile> (cog-prt-atomspace)
(ConceptNode "def")
(ConceptNode "abc")

guile> (cog-handle l)
59
guile> (cog-outgoing-set l)
((ConceptNode "abc")
 (ConceptNode "def")
)
guile> (cog-atom (cog-handle l))
#<Invalid handle>

guile> (SetLink l)
(SetLink (av 0 0 0)
   (ListLink
      (ConceptNode "abc")
      (ConceptNode "def")
   )
)

guile> (cog-prt-atomspace)
(SetLink (av 0 0 0)
   (ListLink
      (ConceptNode "abc")
      (ConceptNode "def")
   )
)

```
My assumption (used to think that I knew, thus this issue) was that on evaluating the varaible `l` , after deleting the atom, the print out on the shell was a confirmation that the atom has been reinserted into the atomspace, which is not the case. So, is this a bug or a feature? @linas

**Comment by AmeBel** [comment]
woops I should have opened this issue in opencog.

**Comment by williampma** [comment]
Yeah, first discovered https://github.com/opencog/opencog/pull/825#issuecomment-45301736

I guess it could be a problem, as you and Mandeep said, when there are multiple processes working on the AtomSpace.  Any scheme variables will become invalid at any moment.

**Comment by ngeiswei** [comment]
This is tied to that issue #127 as well.

**Comment by linas** [comment]
Its a .. err. its a feature bug. The scheme cog-delete and cog-purge functions should be modified that when the indicated atom is deleted, then any guile symbol that refers to the atom should be tracked down, and that symbol should be decoupled from its definition. That would then convert the symbol l above into a scheme "undefined symbol".  I'm guessing this should not be too hard, but it would require studying guile symbols and their definitions a bit,  and muddling through all that.

**Comment by linas** [comment]
Pull request #226 should fix this.  The fix was to clobber the handle that scheme is holding on to. Does not require messing ith guile symbols or variables.

**Comment by AmeBel** [comment]
After (cog-delete l)
```
guile> l                                   
#<Undefined atom handle>                   
```
Thanks for the fix

**Comment by ngeiswei** [comment]
Very cool fix, thanks!
