### ISSUE TITLE
add option to not install obdc version of sql persist

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1634]
what is the use-case for using obdc if it's slower than without?

**Comment by linas** [comment]
Dunno. Maybe some peoople want to run this on microsoft or apple or oracle or something like that.  ODBC is a classic microsoft boondoggle, "one ring to rule them all".

Don't know what you mean by "not install". If you don't want to use it, don't use it... don't even build with it.  I don't see why we should do extra work to "not install" it, if the user took the needed steps to build with it.

**Comment by mjsduncan** [comment]
the point is that your installation instuctions suggest it's use is preffered, octools installs it, and cmake builds it, yet a footnote in your lengthy documentation claims it's use is actually slower than without.  not using it requires uninstalling the odbc packages.

<div>-------- Original message --------</div><div>From: Linas Vepštas <notifications@github.com> </div><div>Date:25/04/2018  14:31  (GMT-05:00) </div><div>To: opencog/atomspace <atomspace@noreply.github.com> </div><div>Cc: mjsduncan <mjsduncan@gmail.com>,Author <author@noreply.github.com> </div><div>Subject: Re: [opencog/atomspace] add option to not install obdc version of sql
  persist (#1634) </div><div>
</div>Dunno. Maybe some peoople want to run this on microsoft or apple or oracle or something like that. ODBC is a classic microsoft boondoggle, "one ring to rule them all".

Don't know what you mean by "not install". If you don't want to use it, don't use it... don't even build with it. I don't see why we should do extra work to "not install" it, if the user took the needed steps to build with it.

**Comment by linas** [comment]
Last I looked, the instructions state - clearly, that odbc is deprecated.  Where does it not state that?
