### ISSUE TITLE
Can't import opencog.atomspace for python.

### ISSUE THREAD

**Issue by joejnke** [opencog/atomspace#1650]
I was exercising on the [Manipulating Atoms in Python](https://wiki.opencog.org/w/Manipulating_Atoms_in_Python) tutorial but i get this error
ImportError: No module named opencog.atomspace
I tried to add "export PYTHONPATH=usr/local/share/opencog/python:$PYTHONPATH" into ~/.bashrc , but the opencog folder doesn't contains python folder
what can i do to fix this?

**Comment by linas** [comment]
try putting a slash in from of /usr

**Comment by linas** [comment]
Ooops, sorry, right. That is not where python lives. The tutorial is wrong.  Python will be in one of the "standard" python locations `/usr//local/lib/python3.5/dist-packages/opencog` for me, and similar places for other python versions. 

Try `find /usr |grep opencog |grep python`

**Comment by linas** [comment]
If this is still a problem, try pulling the latest code; fix #1667 might fix this.

Also be sure you are using python3 and not python when running the system.
