### ISSUE TITLE
cmake automatically builds odbc infrastructure if it finds unixodbc, even though obdc is depricated

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1651]
if odbc is depricated it shouldn't be built unless specifically asked for since it could exist for other programs unrelated to opencog.  since all the oc build tools currently install the odbc packages, odbc always gets built unless unixodbc is removed by hand.

**Comment by linas** [comment]
It's completely harmless to build it. It does not affect anything at run-time, if you don't actually use it.  Conversely, the system is not any faster, nor is it more stable, if you don't build it. Its just a driver; it's presence causes no damage, no harm, no inconvenience.
