### ISSUE TITLE
pull req #1638 breaks BackwardChainerUTest

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1655]
pull req #1638 breaks BackwardChainerUTest. See discussion at #1638 for more.

I'm opening this, to create a record, so that we don't forget to deal with this at some point.

**Comment by ngeiswei** [comment]
Yep, `BackwardChainerUTest` fails once in a while for me.

**Comment by linas** [comment]
No, not "once in a while".  I mean, now it fails 100% of the time, always, after merging this.  Before merging this, it failed maybe 1 out of 20 times.

**Comment by ngeiswei** [comment]
Weird, for me it seems to fail a quarter of the time for me, and when it fails it produces
```
double free or corruption (!prev)
```

**Comment by linas** [comment]
For me, I never get the double-free thing (that went away a long time ago; I think it has something to do with .o files that should have been recompiled, but were not; if/when it does show up, it always goes away after a `make clean`).

I get a normal failure 100% of the time - I just tried 7 or 8 times in a row, while I wrote this.  Looking at stdout, I see
```
In BackwardChainerUTest::test_conditional_instantiation_1:
tests/rule-engine/backwardchainer/BackwardChainerUTest.cxxtest:321: Error: Expected (results == expected), found ({ F0 7A 92 35 93 55 00 00 ... } != { B0 C8 8D 35 93 55 00 00 ... })

[DEBUG] results = (SetLink
  (EvaluationLink (stv 1.000000 1.000000)
    (PredicateNode "are-friends") ; [2199865091715407979][1]
    (ListLink
      (ConceptNode "Mary") ; [7604740497491375293][1]
      (ConceptNode "John") ; [8815061338448900139][1]
    ) ; [11257715806838216709][1]
  ) ; [11771339802182777471][1]
  (EvaluationLink (stv 1.000000 1.000000)
    (PredicateNode "are-friends") ; [2199865091715407979][1]
    (ListLink
      (ConceptNode "Cyril") ; [6575878972943561186][1]
      (ConceptNode "John") ; [8815061338448900139][1]
    ) ; [14198773644179454410][1]
  ) ; [14712397639524015172][1]
) ; [16283090719306008025][1]

[DEBUG] expected = (SetLink
  (EvaluationLink
    (PredicateNode "are-friends") ; [2199865091715407979][1]
    (ListLink
      (ConceptNode "Edward") ; [2559322974712314487][1]
      (ConceptNode "John") ; [8815061338448900139][1]
    ) ; [10779634218515174655][1]
  ) ; [11293258213859735417][1]
  (EvaluationLink (stv 1.000000 1.000000)
    (PredicateNode "are-friends") ; [2199865091715407979][1]
    (ListLink
      (ConceptNode "Mary") ; [7604740497491375293][1]
      (ConceptNode "John") ; [8815061338448900139][1]
    ) ; [11257715806838216709][1]
  ) ; [11771339802182777471][1]
  (EvaluationLink (stv 1.000000 1.000000)
    (PredicateNode "are-friends") ; [2199865091715407979][1]
    (ListLink
      (ConceptNode "Cyril") ; [6575878972943561186][1]
      (ConceptNode "John") ; [8815061338448900139][1]
    ) ; [14198773644179454410][1]
  ) ; [14712397639524015172][1]
) ; [17378981392261621330][1]
[DEBUG] END TEST: test_conditional_instantiation_1
.
Failed 1 and Skipped 0 of 15 tests
Success rate: 93%
```

**Comment by linas** [comment]
And, from what I can tell, it is always, consistently failing to find that Edward and John are friends - its always this same error.

**Comment by ngeiswei** [comment]
OK, the change in sha must have changed the way the population of sources is being sorted and it must now take a slightly less efficient path. It probably works on my system cause my random generator happens to more "lucky".

Do the problem go away if you double the number of iterations, i.e. 40 to 80?
```
	bc.get_config().set_maximum_iterations(40);
```
If not, does it go away if you use 1000 iterations?

**Comment by linas** [comment]
Setting it to 80 makes it pass 7 out of 7 times, for me. I pushed that change in  9fa6ca1b7061cd20a5d8b4b5191e44136f5d6bc4
