### ISSUE TITLE
Some unit tests require opencog_tester DB?

### ISSUE THREAD

**Issue by jjlatval** [opencog/atomspace#1659]
Hello,

When building Atomspace I encountered an issue with DB unit tests. After checking the output of the tests, it seems that some unit tests are looking for a DB named opencog_tester (the test username) instead of opencog_test. Anyway, this contradicts the test DB setup described in https://github.com/opencog/atomspace/tree/master/tests/persist/sql

As an example, BasicSaveUTest seems to expect an opencog_tester DB:

In BasicSaveUTest::test_odbc_single_atom:
/home/vagrant/atomspace/tests/persist/sql/multi-driver/BasicSaveUTest.cxxtest:138: Error: Test failed: Can't perform SQLConnect rc=-1 (/home/vagrant/atomspace/opencog/persist/sql/multi-driver/odbcxx.cc:180)
[2018-05-04 13:39:55:401] [DEBUG] BEGIN TEST: do_test_fresh_atom
[2018-05-04 13:39:55:407] [WARN] ODBC Driver: (101) [unixODBC]FATAL:  database "opencog_tester" does not exist

After adding an opencog_tester DB identical to opencog_test, I passed the failing tests.

**Comment by linas** [comment]
I've just now updates the README to state:

 * (Optional) Create an entry in `~/.odbc.ini`, as explained above.
   The entry should look like this:
```
[opencog_test]
Description = Unit-Test DB for Opencog unit tests.
Driver      = PostgreSQL
Database    = opencog_test
Servername  = localhost
Port        = 5432
Username    = opencog_tester
Password    = cheese
```
that should hopefully avoid the problem.

**Comment by linas** [comment]
Note, however, that the ODBC bindings are discouraged. Whatever documentation you are writing can (should) mention that they exist, but not go into any detail.  There are two reasons for this:

 * They add an extra layer of complexity to the config process (and thus, an opportunity to make mistakes, as you have personally discovered)
 * Performance is worse than the native drivers, by a factor of about 2x (last time I measured)  

Some users may have arcane reasons for wanting ODBC; for them, it works. Most users will not want this, nor care.
