### ISSUE TITLE
consequent-values not defined in RuleUTest

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1665]
The RuleUTest is failing for me, and it seems to have something to do with an undefined scheme value: `consequent-values` in `rules/conditional-direct-evaluation.scm` here:

https://github.com/opencog/atomspace/blob/master/tests/rule-engine/rules/conditional-direct-evaluation.scm#L46

**Comment by linas** [comment]
I spent several hours trying to debug this unit test, and kept getting strange errors that move around in unexpected ways.

**Comment by linas** [comment]
Hmm. The failure was due to some unrelaed reason, now fixed. But `consequent-values` is still undefined, and still generates a warning.  The unit test now passes, for me.

**Comment by ngeiswei** [comment]
@linas I've looked into it but I don't get any warning. Did you do something particular to get these?

**Comment by linas** [comment]
The warning is printed when guile tries to compile the file. Edit the file once, run it, you will see the warning: something like "variable might be used without definition".  At any rate, visual inspection of the code makes it clear that, as a scheme variable, it is used, but never defined anywhere.  I assume that the value is either '() or #f or #undefined and the atomspace guile layer explicitly (and silently) ignores such things.

**Comment by ngeiswei** [comment]
Ah, yeah, the code is wrong, it doesn't hurt the unit test because it only checks that the rule has no cycle, but it might hurt in the future.
