### ISSUE TITLE
Remove cog-free-variables

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1685]
`cog-free-variables` likely doesn't need to be exposed to the user. Its only use is in https://github.com/opencog/opencog/blob/master/opencog/pln/rules/wip/instantiation.scm which is itself likely obsolete (since instantiation is now implemented in meta-rules like https://github.com/opencog/opencog/blob/master/opencog/pln/meta-rules/predicate/conditional-full-instantiation.scm).

**Comment by linas** [comment]
It seems that the pattern miner has this hard-wired in:
https://github.com/opencog/miner/blob/375baf9b28eea60f3b98d771888d8ae31dc75982/opencog/miner/miner-utils.scm#L857

and it does not seem to be a WIP.  Therefore, this utility cannot be removed, and this issue should be closed, right?

**Comment by ngeiswei** [comment]
Oh, indeed. Not sure what motivated me to create that issue in the first place, BTW.

If needed I could modify the miner as to not need `cog-free-variables`, let me know, but as of right now, I don't see why it was such a big deal.

**Comment by linas** [comment]
> let me know

I kind-of don't care; I was trying to trim down the backlog of open issues.

**Comment by ngeiswei** [comment]
OK, I'm closing for now.
