### ISSUE TITLE
Rename AndLink and NotLink when used with the pattern matcher

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1700]
I've always wondered about having different names for `AndLink` and `NotLink` used for pattern matching. Indeed their semantics are different in this context than they would be in PLN. `OrLink` already is replaced by `ChoiceLink`. Why not do the same for `AndLink` and `NotLink`?

**Comment by linas** [comment]
Choice refers to choosing, such as on a menu: pick one object out of N objects.  That is very different than boolean binary-OR, where one combines binary truth values in a certain way.  viz. there is no boolean OR of "rice or noodles" -- you cannot evaluate "rice or noodles" to get "true or false". Instead, what you can do is to pick one or the other.

Likewise, the pattern matcher does not support NotLink; it instead defines AbsentLink, to say "this pattern is absent from the atomspace." This is again, very very different from a boolean binary NOT, which converts true to false, and v.v.   So: "noodles and not mashed potatoes" does not imply that mashed potatoes are "false" or that noodles are the opposite or set-complement of mashed potatoes.  As a boolen-logic operator "not mashed potatoes" is undefined -- it is neither true not false.  By contrast, "AbsentLink mashed potatoes" is very clear: mashed potatoes must be absent from the result.

AndLink does not have that ambiguity or ill-definition: AndLink has an obvious interpretation as set intersection.  There are no conceptual difficulties in saying "I want steak and potatoes".  The failure/breakdown of semantics is only for OrLink and for NotLink.

**Comment by linas** [comment]
Perhaps we could replace AndLink by ContainsLink or HasLink or IncludesLink or ConsistsOfLink or something like that.

**Comment by ngeiswei** [comment]
I'm ready to close this issue if there's nothing else to add.

**Comment by linas** [comment]
FYI , there is issue #1596 - that AbsentLink works badly in any except the simplest cases. I spent half-a-week on fixing this, but couldn't get it right. Its surpririsingly tricky.
