### ISSUE TITLE
(ListLink 	(Glob "$y")  (Member (Concept "foo") (Concept "bar")) (Glob "$z"))  doesn't match

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#1706]
While fixing failed unit tests #1701 I found that following Glob example doesn't return correct result:
```
(ListLink
	(Concept "I")
	(Concept "love")
	(Member (Concept "foo") (Concept "you")))
;;;	(Concept "you")) ;;; it works

(ListLink
	(Concept "I")
	(Concept "need")
	(Member (Concept "foo") (Concept "you"))
;;;	(Concept "you") ;;; it works
	(Concept "now"))

(define test_globs_on_deep_clauses
	(BindLink
		(VariableList
			(TypedVariable (Glob "$y")
				(TypeSetLink (Type "ConceptNode") (IntervalLink (Number 1) (Number 1))))
			(TypedVariable (Glob "$z") (IntervalLink (Number 0) (Number -1))))
		(ListLink
			(Concept "I")
			(Glob "$y")
			(Member (Concept "foo") (Concept "you"))
;;;			(Concept "you") ;;; it works
			(Glob "$z"))
		(ListLink
			(Concept "Hey!")
			(Concept "I")
			(Glob "$y")
			(Concept "you")
			(Concept "also"))))

(cog-execute! test_globs_on_deep_clauses )
```
expected result:
```
$3 = (SetLink
   (ListLink
      (ConceptNode "Hey!")
      (ConceptNode "I")
      (ConceptNode "need")
      (ConceptNode "you")
      (ConceptNode "also")
   )
   (ListLink
      (ConceptNode "Hey!")
      (ConceptNode "I")
      (ConceptNode "love")
      (ConceptNode "you")
      (ConceptNode "also")
   )
)
```
actual result:
```
$3 = (SetLink
   (ListLink
      (ConceptNode "Hey!")
      (ConceptNode "I")
      (ConceptNode "love")
      (ConceptNode "you")
      (ConceptNode "also")
   )
)
```
The example above is slightly modified variant of the GlobUTest::test_glob_three_globs(void). The different is only that ```(Concept "you")``` is replaced by ```(Member (Concept "foo") (Concept "you"))```.

After matching first result and trying to match second method PatternMatchEngine::glob_compare() checks whether var_grounding already contains glob variable. var_grounding is not cleaned up after first match and it already contains value which is not equal to second match. 

If start term is right under ListLink (not deeper) than var_grounding is cleaned up each time when new incoming item iteration is started.

**Comment by linas** [comment]
Yes, looks like a real bug!

**Comment by linas** [comment]
Normally, the mechanism for cleaning up `var_grounding` is to push it onto a stack, and pop it when back-tracking. So very possibly, this is just missing a push/pop in the right places. (which would provide a small, simple, minimal fix.)

**Comment by linas** [comment]
viz: 
```
var_solutn_stack.push(var_grounding);
POPSTK(var_solutn_stack, var_grounding);
```

**Comment by linas** [comment]
I think this was fixed in #1757

**Comment by linas** [comment]
Umm no, this is still a bug ....

**Comment by linas** [comment]
closing
