### ISSUE TITLE
build python2 and/or python3 bindings

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1707]
Currently, only one or the other is build depending on what is installed.  Instead, it should build bindings for both version, if both devel environments are installed.

**Comment by SomeUserName1** [comment]
PythonEval links to Python 2/3 libraries (via PyIncludeWrapper to Python.h) which means if both versions of python development libraries are installed then 2 versions of PythonEval are needed.

[](https://github.com/opencog/atomspace/blob/6a7cc0d936d3ea62ad3f6b0fd42ba477198d9bf0/opencog/cython/PythonEval.h#L41)
https://github.com/opencog/atomspace/blob/6a7cc0d936d3ea62ad3f6b0fd42ba477198d9bf0/opencog/cython/PyIncludeWrapper.h#L13

 As execution depends on PyEval and the atomspace cython binding depends on execution there need to be separate builds for the python versions at least separate builds of this sub-part
The same applies for opencog: The python module & shell link to Python.h; the server target depends on those two.

So python bindings of different versions require two builds each linked to one of the python versions. That would require to execute the py 2 build of the atomspace and cogserver to use python 2 bindings and the execution of the py 3 build to use python 3 bindings, which is not very convenient. 

So how to proceed?
I've only found [this](https://root-forum.cern.ch/t/compiling-root-with-both-python2-and-python3-bindings/24446/6) from teh CERN forum, relinking the libraries after the build. May this be an approach and how does that interfer with the non-cython parts (server and execution build targets)?

**Comment by linas** [comment]
Hmm. Yeah. The robot guys, e.g. @elggem seemed to have both the python 2 and 3 devel environments installed, and want python2 to always be built. Maybe ask them.

**Comment by vsbogd** [comment]
related issue https://github.com/opencog/cogutil/issues/113

**Comment by AmeBel** [comment]
@SomeUserName1 is experimenting with an approach to run python functions without having to link PythonEval to the respective python libraries. If that works then it should solve the issue.

**Comment by vsbogd** [comment]
Referencing conversation about package manegement https://github.com/opencog/atomspace/pull/1831#discussion_r201624547 here

**Comment by SomeUserName1** [comment]
as rise conf is over i ll start working on this again to hopefully pull request everything until the end of the month

**Comment by SomeUserName1** [comment]
Hi everybody,  after diving deeper into the python stuff i noticed that the cython bindings depend on the PyEval module and the othewr way round (cyclic dependency avoided by the atomspace-api.h). It d be nice to get rid of that (for obvious reasons); further a lot of the PythonEval code seems to be complicated work-arrounds and error prone according to the comments. And finally in order not to build twice for creating both 2 & 3 bindings it'd be handy to dynamically load & use the corresponding python api symbols.

therefore i have some questions on the design of the generic stuff:
would it be okay to move the input pending things to the shell instead of the evaluators?
is it definitely necessary to import and attach an atomspace to the shell by the evaluator? is it okay to let the user attach it by some py/scheme binding (so rather in cython/guile)
how are the scheme bindings provided? is there also some "packageable" like for cython? i m trying to understand in how far the cogserver scheme shell is different from "plain" guile and what the differences are
would there even be a way to get rid of those shells and just provide packages/whatever to use plain guile or python interpreters (achieving multi threadding by multiple shells acting on the same atomspaceby multithreadded functions with propper bindings)

**Comment by SomeUserName1** [comment]
@linas

**Comment by linas** [comment]
Remarks:

1)  The cyclic dependency is icky but hard and disruptive to remove

2) It's not clear to me that the python 2 & 3 API use the same symbols, or that you could build a common library that links to either.  Maybe ...

3) PythonEval is complicated because Python is complicated. Python internals are messy.  I do not beleive you'll find much of anything that can be simplified there.

4) "the shell"?  The cogserver-shell is in opencog, not in the atomspace; it won't work without the cogserver. I don't want the cogserver in the atomspace, its  an inadequate, brain-damaged bit of software itself. The python cogserver-shell doesn't even do stdin/stdout correctly.

5) "import and attach an atomspace in the shell"??  I don't understand. The whole point is to use the atomspce, so ... !?

6) A typical example use of PythonEval is this:  

```
SequentialOrLink
    EvaluationLink
           GroundedPredictNode "py:do_stuff"
           ListLink
                  FooNode "argument 1 for python do_stuff() function"
                  BarLink ...

    EvaluationLink
           GroundedPredictNode "py:do_other_stuff"
           ListLink
                  BarLink ...
```
If/when something triggers and causes the above to run, then PythonEval will be called, passing Foo and Bar as arguments to `do_stuff()`. There's no shell, no input, no output; the atomspace that PythonEval has to be exactly the same one as the one that Foo and Bar atoms live in.  

7) guile has nothing to do with this ... except that in the bove example, you could say `GroundedPredictNode "scm:do_stuff"` instead, which calls `(do_stuff (FooNode "...") (BarlLink ...))`

8) The SchemeEval is 100% guile compatible -- it is already just "the plain interpreter" (compiler, actually).  This is impossible for Python, because Python from a file is not compatible with Python from the Python REPL shell, due to Python white-space and carriage-return handling differences. (viz Python isn't actually compatible with itself, when handling whitespace; its got multiple incompatible styles.)  In general, you want to avoid the python REPL, its broken and doesn't work right.  Running python from a file does work right.

9) The guile REPL (implemented in ice-9)  is a cheesy hack that must be kept at arms length. All of ice-9 is a cheesy hack.  its great if you just are using it at the command line to do stuff -- I do it all the time, but it is not server-quality high-grade software. Its got issues.

10) guile is multi-threaded. Python is not. Python fakes it: it pretends its multi-threaded, its not actually running on multiple cores. 

11) SchemeEval is multi-threaded, and there are unit tests in the atomspace that wail on it to make sure its good.  Its also heavily modified to minimize re-entry costs, so it got tuned to run really efficiently -- as efficiently as I could. If you wreck this, I will have a violent screaming fit: the code is extremely stable, it works well. It must not be broken.

12) It might be possible to improve parts of SchemeEval, but that would definitely be an advanced system-level programming that is a bit beyond where you're at right now.  

13) Current guile is thread-safe, but there is something deeply flawed with how it handles locking -- it seems to live-lock when using more than a handful atomspace-crunching threads. This seems to be some guile-internals thing, has nothing to do with atomspace/opencog. I'd like to see a guile developer fix guile. 

14) Net-net: leave guile alone, you're not going to find anything to improve in there. 

15) Python: fixing the circular-dependency is a nice-to-have, but not urgent. Having a clear-cut python2/3 story is urgent.

**Comment by linas** [comment]
Demos: `examples/atomspace/python.scm` and `examples/atomspace/execute.scm`

WTF. OK, so that's odd. I just now tried to do this:
```
$ guile -l examples/atomspace/python.scm
hello! 4
guile: /atomspace-git/opencog/cython/PythonEval.cc:632: void opencog::PythonEval::build_python_error_message(const char*, std::__cxx11::string&): Assertion `PyBytes_Check(pyErrorString)' failed.
Aborted
```
so something is broken.  Also, its been mentioned that for some unknown reason, the python unit tests are no longer being run -- vis in the past `make test` used to cause cmake to run nosetests. That's not working any more, who knows for how long. So it seems like there are multiple python bugs in the current code.  Hmm. Who was the last person who messed with this stuff???

**Comment by linas** [comment]
Specifically, here: `tests/cython/CMakeLists.txt` lines 64FF

Before you do anything else, you need to get the python unit tests to run again, and to pass.  The python examples also need to run and pass.  Doing any coding without first getting the unit tests to pass is foolish.

**Comment by linas** [comment]
The other examples are here: `examples/python/scheme` and here's what happens:
```
$ python ./bindlink.py
Traceback (most recent call last):
  File "./bindlink.py", line 13, in <module>
    from opencog.atomspace import AtomSpace
ImportError: No module named opencog.atomspace
```
So basically, for me, python is 100% broken, 100% non-functional at this time.  All of this stuff worked fine half a year ago.

**Comment by linas** [comment]
Oh, wait, I'm wrong:
```
python3 ./bindlink.py
The result of pattern matching is:

(SetLink
  (ConceptNode "Frog")
  (ConceptNode "Zebra")
  (ConceptNode "Deer")
)
```
so python3 works for me.  However, `guile -l python.scm` is still failing.

**Comment by SomeUserName1** [comment]
Regarding point 10: 
it might be nitpicking but Python definitely IS running on different cores, it's just not allowing 2 threads on whatever core they are to run at the same time...
How is the atomspace locked? Is it using shared memory/multi-process locks (see unistd.h _POSIX_THREAD_PROCESS_SHARED)? 
If so one could kick off evaluator instances each in an own process enabling simultaneous execution iff the atomspace to work on is not locked

>  Hmm. Who was the last person who messed with this stuff???

None of my changes regarding python got merged (for a good reason) ;)

**Comment by linas** [comment]
closing. Python2 has reached end-of-life.
