### ISSUE TITLE
Atom to_string and to_short_string should not end by a new line

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1728]
This takes some control out of printing Atoms, for instance when logging an atom, since logging system itself adds a newline, it ends up with 2 new lines.

**Comment by ngeiswei** [comment]
Of course to address that issue you do not only need to remove "\n" in https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/Link.cc#L96 and so on, you also need to add it back in various places so that an atom does display nicely over multiple lines, so does `oc_to_string(const HandleSeq&)` over multiple lines, etc. You basically need to check all references where `Atom::to_string`, `Atom::to_short_string` and oc_to_string(const Handle&)` are used and fix them accordingly.

**Comment by navaro1** [comment]
Hey, I will try to solve this issue.

**Comment by linas** [comment]
As of about a month ago, `to_short_string()` no longer has a newline on it.   A unit test should be added for this, because the newlinefree version is a requirement for https://github.com/opencog/atomspace-dht

**Comment by ngeiswei** [comment]
@linas, `Atom::to_short_string` of

```
List
  Concept "A"
  Concept "B"
```

returns

```
(ListLink   (Concept "A")  (Concept "B"))
```

that is the indentation before `(Concept "A")` and `(Concept "B")` is still present. I assume it's OK if that extraneous indentation is removed, let me know otherwise.
