### ISSUE TITLE
No installation path for opencog/atoms/proto/core_types.scm

### ISSUE THREAD

**Issue by Eskender-B** [opencog/atomspace#1742]
There is no installation path for atoms/proto/core_types.scm found [here](https://github.com/opencog/atomspace/blob/d1ae3b8929c35125aa941b1324678b7a7d2275a9/opencog/scm/opencog.scm#L97)

When I try `(use-modules (opencog))` without docker there seem to be no problem as guile loads the file
from my build directory.

However inside docker `(use-modules (opencog))` does not work because the file is not installed in /usr/local/share/opencog/scm/

my temporary fix was the ff
```
$ sudo mkdir -p /usr/local/share/opencog/scm/opencog/atoms/proto/
$ sudo cp /usr/local/share/opencog/scm/opencog/proto/core_types.scm /usr/local/share/opencog/scm/opencog/atoms/proto/core_types.scm

```

**Comment by linas** [comment]
Indeed. I think that pull req #1743 fixes this. The whole atoms/proto thing squeeked past a code review and apparently no one tested on a fresh build :-(

**Comment by linas** [comment]
fixed, right?

**Comment by Eskender-B** [comment]
In the created docker container I see that the file is installed in the right place. But for some reason
doing `(use-modules (opencog))` still gives the ff error
```
scheme@(guile-user)> (use-modules (opencog))
While compiling expression:
In procedure primitive-load-path: Unable to find file "opencog/atoms/proto/core_types.scm" in load path
scheme@(guile-user)>
opencog@07b9e92a3c27:/opencog$ 
```

**Comment by linas** [comment]
Sigh. Quite right. I have not been doing a clean build to test. #1756 should fix this.

**Comment by Eskender-B** [comment]
It works now.
