### ISSUE TITLE
AttentionBank redesign

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1745]
The current AttentionBank design uses atomspace signals to learn about atoms. This has a strong negative impact on atomspace users who are not attentionbank users.  This needs a redesign, to be made more modular, to have a smaller performance footprint, to be less invasive.

Perhaps, maybe?? one should switch the conceptual model from "banking" to "regulation". 

In banking, one maintains a rigidly controlled "balance" so that two crooks, working in concert, cannot over-draft the bank-account by over-drawing funds. Providing this kind of safety is hard: access to the bank balance must be serialized to one location, there must be locks, the balance must be globally visible, etc. To avoid theft, banking is (famously) technologically hard to implement. 

In regulation, one instead has some general operating bounds.  Consider the "blood sugar level" -- you don't want it to be too low, you don't want it to be too high. The exact total amount of sugar in the blood does not matter, as long as it stays in bounds.  Thus, one does not need a "bank balance", one only needs to make sure that those who need it get enough.  Blood-sugar does not need to be monitored from a single, centralized location. We're not safe-guarding blood-sugar from thieving crooks.  blood-sugar can be maintained in a distributed fashion.

An example of regulation is the "Hypothalmic-Pituitary-Adrenal Axis". (see wikipedia)

The current users of AttentionBank need to be examined, and understood re what they are trying to do.  Based on this, the attentionbank, and specifically, its invasive use of signals, should be re-designed, so that it has a smaller impact on the system. 

After redesign, it should be renamed to "AttentionRegulator" or something like that.

**Comment by misgeatgit** [comment]
@Linas The idea you raised is interesting and looks very useful at least in terms of increasing the overall performance of the attention system. Currently the only ECAN agent relying on signals is the Hebbian link creation agent; It observes atoms added to Attentional focus signal and creates an AsymmetricHebbianLink between the newly entered atom and existing atoms in the AF.

**Comment by linas** [comment]
AttentionBank.cc line 51 installs a remove signal into the atomspace, for all atom removals.

I recall that it also used to listen to the `atomAddedSignal` and this design-change was predicated on that. But if there is no more `atomAddedSignal` then most of my concern is moot, and maybe this issue can be closed.

So .. symmetry -- why does the attentionbank need the removed signal (if it's not using the added signal?)

**Comment by linas** [comment]
OK. I'm closing this. The AtomAdded signal, which I thought was there, is not there. Which makes most of what I'm talking about above irrelevant.

I tried to think of some way of making the atom-remove signaling more efficient, but could not really think of anything obvious.  Right now, attentionbank is notified of every atom-remove, whether it cares about it or not.  

I suppose there could be some "I care about this atom" filter in the atomspace itself, which could be a tiny bit more efficient. But it risks getting complex, so maybe I should leave well-enough alone.

**Comment by misgeatgit** [comment]
BTW, The atom added signal is also very useful in some scenarios. I used it for our ECAN experiment in a separate experimental module to keep track of new atoms coming through the NLP pipeline belonging to certain topic category and then periodically get content of the AF in order to determine the intersection  between these categories and the AF to know how much of the AF contains atoms belonging to each categories at a particular instance of time.

**Comment by linas** [comment]
Ugh. I want to get rid of those signals, actually.  For scalability.  It would be better if each different subsystem that generates atoms, or changes TV's. or whatever, provided it's own notification system.   That way, if you want to know about new language atoms, you can get only those, and not the visibility or sound or movement atoms.  If you do want these, then you can subscribe to all of those.

Even language is non-trivial: first, there's a word sequence; then there's a parse, then there's an analysis of the parse. Typically, you'd be interested only in the input or output to just one of those steps, and not all of them.

**Comment by linas** [comment]
I've been using `AnchorNode` to perform local, subsystem notifications.   So one subsystem creates `(Member Anchor "foo") (SomeAtom))` while another subsystem looks for atoms at that AnchorNode and then processes them.   But this is hokey in many ways and entirely inadequate and needs some generic redesign.   But such a redesign is hard -- its not obvious how to make it work well, work nicely.

**Comment by linas** [comment]
#1750 spells this out in detail.
