### ISSUE TITLE
cog-mean vs cog-tv-mean

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1773]
We have the following scheme bindings
```
cog-mean
```
that returns the mean of the TV of the given atom, https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobAtom.cc#L112

And
```
cog-tv-mean
```
that returns the mean of the given TV, https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobTV.cc#L471

But I wonder if it shouldn't be the other way around, `cog-mean` that takes a TV and `cog-tv-mean` that takes an atom. In that case the `tv` indicates the output object type over which the property is being accessed, while current it indicates the input type.

Anyway, it's not very important but  I wonder what you think.

**Comment by vsbogd** [comment]
I agree, that swapping these names seems to be reasonable. 

BTW what it the reason of introducing of cog-tv-mean (in current notation), why it is not defined purely in Scheme code as superposition of cog-mean and cog-tv? Is it because of performance reasons? To not call Sheme/C++ bindings code twice?

**Comment by ngeiswei** [comment]
The scheme version `tv-mean` https://github.com/opencog/atomspace/blob/master/opencog/scm/opencog/base/utilities.scm#L80 used to be defined as
```
(assoc-ref (cog-tv->alist tv) 'mean)
```
Which was replaced by `cog-tv-mean` apparently for efficiency reasons.

**Comment by linas** [comment]
Swapping the names would be reasonable, except that there is a huge amount of code all over the place, and this destablizes things. I don't know about you guys, but I have a lot of code that is not in git, it's scattered across multiple machines, its used either to run experiments, or to crawl over the output of the same, and prepare charts and graphs.  Some of this, I revisit only infrequently, and it would be a pain to track it all down to make the changes.

**Comment by linas** [comment]
The original (ten-year-old) implementation used the `assoc-ref` but somewhere along the way, I discovered that direct references are faster.  For things like counting, it is a significant bottleneck.

Hmm. Actually, cog-tv-count should probably have an "increment" function on it, to avoid fetching, adding one, and then storing ....

**Comment by ngeiswei** [comment]
I understand, @linas, swapping stuff is horribly error prone. On the other hand I'd rather have that sort of clean-ups occur now than later when opencog is more widely used.

According to github that's 50 occurrences (in total) of `cog-tv-mean`, `cog-tv-confidence` and `cog-tv-count` across all opencog repos (atomspace, opencog and tinycog). No usage found on the handsonrobotics or singularitynet repos. No usage found elsewhere on github except for seemingly inactive projects. So it's still fairly localized.

As for your unmerged code, I guess as long as you don't update atomspace or opencog it's fine, but when you do, you'll have to be very careful indeed.

I don't want to force it, but I think it's worth it. (that line is groovy).

**Comment by vsbogd** [comment]
Looks like it is completed. Should it be closed?

**Comment by linas** [comment]
I defer to Nil.

**Comment by ngeiswei** [comment]
I defer to null.
