### ISSUE TITLE
ExecutionOutputLink doesn't support single argument with clear box

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1793]
The following
```
(define twice
   (LambdaLink
      (VariableNode "$X")
      (PlusLink
         (VariableNode "$X")
         (VariableNode "$X")
      )
   )
)
(define exec-twice (ExecutionOutput twice (Number 21)))
(cog-execute! exec-twice)
```
raises the exception
```
Throw to key `C++-EXCEPTION' with args `("cog-execute!" "Not a link! (/home/nilg/OpenCog/atomspace/opencog/atoms/base/Atom.h:252)
Function args:
((ExecutionOutputLink
   (LambdaLink
      (VariableNode \"$X\")
      (PlusLink
         (VariableNode \"$X\")
         (VariableNode \"$X\")
      )
   )
   (NumberNode \"21.000000\")
)
)")'.
```

According to http://wiki.opencog.org/w/ExecutionOutputLink#LambdaLink_and_DefineLink_examples it is supposed to work.

Actually wrapping the argument with a `List` works!

**Comment by ngeiswei** [comment]
Some more information in case a neophyte wishes to take it on.

There is already a unit test for it 
```
ExecutionOutputUTest::test_clear_box_single_argument(void)
```
So go there https://github.com/opencog/atomspace/blob/master/tests/query/ExecutionOutputUTest.cxxtest#L284 and enable that line
https://github.com/opencog/atomspace/blob/master/tests/query/ExecutionOutputUTest.cxxtest#L292
as indicated in its comment above (and of course comment out the line below it).

The unit test should now crash. My recommendation is then run it in gdb (see http://wiki.opencog.org/w/Development_standards#GDB to properly configure it for OpenCog, it isn't already) and find out how to change the code so that it accepts a single argument without a `List` wrapped around it.

**Comment by linas** [comment]
Nil,

I would like to point out that what you are asking for here is exactly the opposite of what you ask for in other places.  Personally, I don't mind the change being requested here: its OK to have this kind of automatic convenience -- to have it work both with, and without the ListLink.  It makes the atomese easier to use.

However, in other places, you've argued for exactly the opposite of this: e.g. with ImplicationScopeLink, EquivalenceScopeLink    From the perspective of ease-of-use and elegance, we should be consistent with how Atomese behaves:  why should there be a special case exception for ExecutionOutputLink? If we have a special-case exception for ExecutionOutputLink, doesn't that imply that we should now get rid of ImplicationScope, EquivalenceScope, etc. and just treat them the same way that we treat ExecutionOutputLink?  .... I'd like to be consistent, one way or the other.

**Comment by ngeiswei** [comment]
Linas, I don't see the connection with `ImplicationScopeLink`. We already have this convenience for `EvaluationLink` and in its publications prior to its implementation (although this isn't necessarily too important). But conceptually it makes sense to me. If we require a `List` maybe we want to require a `List` when writing
```
Member
  List <element>
  <concept>
```
that would be consistent, yet we don't want that.
