### ISSUE TITLE
Python unit test BindlinkTest fails

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#1803]
(1) Python unit tests located at ./tests/cython/bindlink/bindlink.py fails:

```
$ PYTHONPATH=$CURRENT_PY nosetests -vs ./tests/cython/bindlink/
...
terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  Python function 'test_functions.bogus_tv' not found! (/home/vital/projects/opencog/atomspace/opencog/cython/PythonEval.cc:784)
Aborted (core dumped)
```

(2) Python unit tests should be executed by ```make tests``` command.

**Comment by linas** [comment]
This has been a recurring kind of issue, over the years.  It seems to come and go, I don't know why. For me, just saying `make test`, all tests pass; I do not ask why.

BTW, nothing wrong with throwing exceptions, in general, and the python wrapper should have something that can catch the C++ exceptions, and convert them into python exceptions, so that python code could catch them (instead of crashing, like here).  Its not hard -- wrap `pythonEval` in `try {...}catc() {...}` and have the catch call `pyThrowWhatever`.

**Comment by vsbogd** [comment]
This issue is about pure Python unit tests. They are not started by ```make tests``` because ```make tests``` starts only CxxTests. I would say that it is issue as well, as if we have some unit tests they should be run on each build. 

To run this kind of tests one should follow https://github.com/opencog/atomspace/blob/master/tests/cython/README.md and if he does he will find that BindLink unit tests fail.

**Comment by vsbogd** [comment]
Raised https://github.com/opencog/atomspace/pull/1821 to fix Python tests README.md

**Comment by linas** [comment]
last I looked, `make test` runs the nose tests.  It sets up PYTHONPATH and everything else, which is why they pass; when you run nosetests by hand, some part of the setup is not being done correctly.

**Comment by linas** [comment]
OK, that's weird ... I just looked now, it seems that `make test` is no longer running either the cython or the python tests any more.  Once upon a time, it used to run both.  I have no clue how that got broken.

**Comment by linas** [comment]
See `tests/cython/CMakeLists.txt` --  it sets things up, and calls nosetests -- it is no longer doing this, at least, for me.

**Comment by linas** [comment]
The most likely reason why this is broken is that it got broken during the python2+python3 reorganization changes. (viz, the work spurred by issue #1707)

**Comment by linas** [comment]
I believe this bug has been fixed; I am seeing this:
```
$ make test_python
Running Python and Cython tests...
Test project /atomspace-git/build/tests/cython
    Start 1: PythonEvalUTest
1/8 Test #1: PythonEvalUTest ..................   Passed    1.12 sec
    Start 2: PythonUtilitiesUTest
2/8 Test #2: PythonUtilitiesUTest .............   Passed    0.13 sec
    Start 3: Cython
3/8 Test #3: Cython ...........................   Passed    3.14 sec
    Start 4: CythonAtomSpace
4/8 Test #4: CythonAtomSpace ..................   Passed    2.06 sec
    Start 5: CythonUtilities
5/8 Test #5: CythonUtilities ..................   Passed    1.07 sec
    Start 6: CythonBindlink
6/8 Test #6: CythonBindlink ...................   Passed    0.89 sec
    Start 7: CythonBackwardchainer
7/8 Test #7: CythonBackwardchainer ............   Passed    1.66 sec
    Start 8: CythonGuile
8/8 Test #8: CythonGuile ......................   Passed    1.51 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) =  11.61 sec
Built target test_python
```
and also this:
```
        Start 129: PythonEvalUTest
129/136 Test #129: PythonEvalUTest ..................   Passed    1.11 sec
        Start 130: PythonUtilitiesUTest
130/136 Test #130: PythonUtilitiesUTest .............   Passed    0.13 sec
        Start 131: Cython
131/136 Test #131: Cython ...........................   Passed    3.09 sec
        Start 132: CythonAtomSpace
132/136 Test #132: CythonAtomSpace ..................   Passed    2.05 sec
        Start 133: CythonUtilities
133/136 Test #133: CythonUtilities ..................   Passed    0.96 sec
        Start 134: CythonBindlink
134/136 Test #134: CythonBindlink ...................   Passed    0.96 sec
        Start 135: CythonBackwardchainer
135/136 Test #135: CythonBackwardchainer ............   Passed    1.63 sec
        Start 136: CythonGuile
136/136 Test #136: CythonGuile ......................   Passed    1.53 sec

100% tests passed, 0 tests failed out of 136
```

Can this bug be closed now?

**Comment by AmeBel** [comment]
@linas would you please post the full list of your tests? You have six more test as compared to tests run in the docker images.
