### ISSUE TITLE
GlobNode sometimes misses trailing matches

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1825]
Consider the following search:
```
(define b

(BindLink
   (VariableList
     (TypedVariableLink
        (GlobNode "$begin")
        (IntervalLink (NumberNode 0) (NumberNode -1)))
     (TypedVariableLink
        (GlobNode "$end")
        (IntervalLink (NumberNode 0) (NumberNode -1))))
   (List
       (GlobNode "$begin")
       (Concept "foo")
       (GlobNode "$end"))
   (OrderedLink
       (Concept "begin")
       (GlobNode "$begin")
       (Concept "end")
       (GlobNode "$end")))
)
```
where the atomspace contains `(List (Concept "foo")(Concept "foo"))`

Run  `(cog-execute! b)`

The expected output is:
```
(SetLink
   (OrderedLink
      (ConceptNode "begin")
      (ConceptNode "foo")
      (ConceptNode "end")
   )
   (OrderedLink
      (ConceptNode "begin")
      (ConceptNode "end")
      (ConceptNode "foo")
   )
)
```
The current actual output is
```
(SetLink
   (OrderedLink
      (ConceptNode "begin")
      (ConceptNode "foo")
      (ConceptNode "end")
   )
)
```

**Comment by linas** [comment]
This is super-urgent for me, its a blocker bug, so I'll try to fix it asap.

**Comment by linas** [comment]
If instead, the atomspace contains `(List (Concept "foo")(Concept "foo")(Concept "foo")(Concept "foo"))` then, again, only one solution is found, even though four solutions are expected. It appears that there is no retry for a different number of matching possibilities.

**Comment by linas** [comment]
If the body is altered to 
```
(List (List
       (GlobNode "$begin")
       (Concept "foo")
       (GlobNode "$end")))
```
and the data to `(List (List (Concept "foo")(Concept "foo")))`  then everything works, because `explore_up_branches()` does contain the logic to explore all the possibilities.  The fix is to move that logic to a different place ...

**Comment by ngeiswei** [comment]
In the example you use -1 to represent +infinity I suppose, if so this should be added to http://wiki.opencog.org/w/IntervalLink (I would do it but for some reason I cannot log into wiki.opencog/org, crap, I haven't been able for 2 weeks now).

**Comment by linas** [comment]
Ugh, the fix is a simple one-liner fix, where the intermediate state was being incorrectly cleared.  However, that then triggers a different bug...

**Comment by linas** [comment]
Part two of the fix was a two-liner fix. Fixed in #1829

**Comment by linas** [comment]
@ngeiswei  I updated http://wiki.opencog.org/w/IntervalLink 

Re your login, ask @AmeBel he's maintaining that.  (I hope he's also making backups; I used to, but haven't in a long while)

**Comment by linas** [comment]
@AmeBel  when I try to log onto the wiki with `ssh`, I get ` Permission denied (publickey).` which means I cannot create a backup of the wiki site. My last backup was years ago; we would loose a lot of work, if we had to restore from that.

**Comment by ngeiswei** [comment]
Actually, after clearing my cookies (thanks to Cassio's advice) I can log in again :-)

**Comment by AmeBel** [comment]
@linas there is a key for you so I don't know why you couldn't login. Maybe you are using a different key.  With regards to the backup, our host provides a daily backup provided we don't pass the 5GB mark, which we haven't yet.
