### ISSUE TITLE
VectorAPIUTest fails with reason 'no code for module (opencog matrix)'

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#1834]
My opinion this is the reason why VectorAPIUTest fails during clean build. It cannot evaluate ```(load-from-path "tests/matrix/basic-api.scm")``` and then fails to use ```bapi``` function defined there.

```
Running cxxtest tests (6 tests)[2018-07-17 11:13:28:228] [DEBUG] BEGIN TEST: test_basic
Load of data >>>
Got >>>Backtrace:
           9 (apply-smob/1 #<catch-closure 560b7a39d7c0>)
           8 (apply-smob/1 #<catch-closure 560b7a39d6c0>)
In ice-9/boot-9.scm:
   2312:4  7 (save-module-excursion #<procedure 560b7a39ed00 at ice-…>)
In ice-9/eval-string.scm:
     38:6  6 (read-and-eval #<input: string 560b7a7c8620> #:lang _)
In ice-9/eval.scm:
   196:43  5 (_ #f)
   191:27  4 (_ #f)
   223:20  3 (proc #<directory (guile-user) 560b7a03d140>)
In unknown file:
           2 (%resolve-variable (7 . bapi) #<directory (guile-user) …>)
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 560b7a39d680> # #f "Unbo…" …)

ERROR: In procedure apply-smob/1:
Unbound variable: bapi
ABORT: unbound-variable

```

**Comment by vsbogd** [comment]
Adding link to the related issue https://github.com/opencog/atomspace/issues/1748

**Comment by linas** [comment]
It should be loading `tests/query/test_types.scm` which does define both `WordNode` and `AnyNode`.  See lines 89-93 which I quote:
```
   eval->eval("(add-to-load-path \"" PROJECT_SOURCE_DIR "\")");
   eval->eval("(add-to-load-path \"../../..\")");

   eval->eval("(load-from-path \"tests/query/test_types.scm\")");
   eval->eval("(load-from-path \"tests/matrix/basic-api.scm\")");
```

I'm guessing that, for some reason, those evals are failing, probably something to do with `PROJECT_SOURCE_DIR` or something like that.   This kind of thing has happened in the past, to other unit tests.

**Comment by linas** [comment]
I just added some error checking in 282708ce90ccd601372bb2bf753cfba40b143724 which will presumably flag the test_types load.

**Comment by vsbogd** [comment]
I have tried to load it manually via guile, and I see that ```tests/query/test_types.scm``` loads, and guile tries to load ```tests/matrix/basic-api.scm``` but complains that WordNode or AnyNode is not defined. Will put logs here.

**Comment by vsbogd** [comment]
Ok, I see that ```tests/query/test-types.*``` should define these types actually. So issue title is not correct. 
Will look at VectorAPIUtest behavior further to understand what is the root cause. It looks like ```tests/matrix/basic-api.scm``` not loaded but I see that ```PROJECT_SOURCE_DIR``` is correct in my case.

Log of the first test in my case:
```
Running cxxtest tests (6 tests)[2018-07-19 11:02:34:132] [DEBUG] BEGIN TEST: test_basic
Load of data >>>
Got >>>Backtrace:
           9 (apply-smob/1 #<catch-closure 55b89b65e8a0>)
           8 (apply-smob/1 #<catch-closure 55b89b65e7a0>)
In ice-9/boot-9.scm:
   2312:4  7 (save-module-excursion #<procedure 55b89b65fdc0 at ice-…>)
In ice-9/eval-string.scm:
     38:6  6 (read-and-eval #<input: string 55b89b659e00> #:lang _)
In ice-9/eval.scm:
   196:43  5 (_ #f)
   191:27  4 (_ #f)
   223:20  3 (proc #<directory (guile-user) 55b89af8c140>)
In unknown file:
           2 (%resolve-variable (7 . bapi) #<directory (guile-user) …>)
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 55b89b65e760> # #f "Unbo…" …)

ERROR: In procedure apply-smob/1:
Unbound variable: bapi
ABORT: unbound-variable

In VectorAPIUTest::test_basic:
/home/vital/projects/opencog/atomspace-build/tests/matrix/../../../atomspace/tests/matrix/VectorAPIUTest.
cxxtest:133: Error: Test failed: Caught scm error during eval
/home/vital/projects/opencog/atomspace-build/tests/matrix/../../../atomspace/tests/matrix/VectorAPIUTest.
cxxtest:133: Error: Assertion failed: (false == eval->eval_error())
/home/vital/projects/opencog/atomspace-build/tests/matrix/../../../atomspace/tests/matrix/VectorAPIUTest.
cxxtest:133: Error: Test failed: Expecting #t
/home/vital/projects/opencog/atomspace-build/tests/matrix/../../../atomspace/tests/matrix/VectorAPIUTest.
cxxtest:133: Error: Expected (tru == "#t\n"), found ("Backtrace:\n           9 (apply-smob/1 #<catch-clos
ure 55b89b65e8a0>)\n           8 (apply-smob/1 #<catch-closure 55b89b65e7a0>)\nIn ice-9/boot-9.scm:\n   2
312:4  7 (save-module-excursion #<procedure 55b89b65fdc0 at ice-…>)\nIn ice-9/eval-string.scm:\n     38:6
  6 (read-and-eval #<input: string 55b89b659e00> #:lang _)\nIn ice-9/eval.scm:\n   196:43  5 (_ #f)\n   1
91:27  4 (_ #f)\n   223:20  3 (proc #<directory (guile-user) 55b89af8c140>)\nIn unknown file:\n          
 2 (%resolve-variable (7 . bapi) #<directory (guile-user) …>)\nIn ice-9/boot-9.scm:\n   751:25  1 (dispat
ch-exception 0 unbound-variable (#f \"Unbound …\" …))\nIn unknown file:\n           0 (apply-smob/1 #<cat
ch-closure 55b89b65e760> # #f \"Unbo…\" …)\n\nERROR: In procedure apply-smob/1:\nUnbound variable: bapi\n
ABORT: unbound-variable\n" != #t

```

**Comment by vsbogd** [comment]
I have found the reason finally:

```
ERROR: In procedure apply-smob/1:
no code for module (opencog matrix)
```

**Comment by vsbogd** [comment]
Adding 

	eval->eval("(add-to-load-path \"" PROJECT_BINARY_DIR "/opencog/scm\")");
doesn't help because it tries to find object-api.scm in wrong location:
```
Running cxxtest tests (1 test)Got >>>Backtrace:
In tests/matrix/basic-api.scm:
      9:0 19 (_)
In ice-9/boot-9.scm:
  3365:20 18 (process-use-modules _)
   222:29 17 (map1 (((opencog)) ((opencog persist)) ((opencog #))))
   222:29 16 (map1 (((opencog persist)) ((opencog matrix))))
   222:17 15 (map1 (((opencog matrix))))
  3366:31 14 (_ ((opencog matrix)))
  2788:17 13 (resolve-interface (opencog matrix) #:select _ #:hide _ …)
  2714:10 12 (_ (opencog matrix) _ _ #:ensure _)
  2982:16 11 (try-module-autoload _ _)
   2312:4 10 (save-module-excursion #<procedure 558a069fab40 at ice-…>)
  3002:22  9 (_)
In unknown file:
           8 (primitive-load-path "opencog/matrix" #<procedure 558a0…>)
In opencog/matrix/matrix.scm:
     10:0  7 (_)
In ice-9/boot-9.scm:
   2312:4  6 (save-module-excursion #<procedure 558a069fab10 at ice-…>)
   3836:9  5 (_)
   1693:5  4 (%start-stack load-stack _)
   1695:9  3 (_)
In unknown file:
           2 (primitive-load-path "opencog/matrix/matrix/object-api.…")
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 misc-error ("primitive-load-pa…" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 558a06a42540> misc-error # …)

ERROR: In procedure apply-smob/1:
In procedure primitive-load-path: Unable to find file "opencog/matrix/matrix/object-api.scm" in load path
ABORT: misc-error
```

**Comment by linas** [comment]
Foo. The double `matrix/matrix`  is because of the contents of `matrix.scm`.  It needs to be that way, because that's what is needed for the final install location.

This is a hacky fix, but try this:
```
eval->eval("(add-to-load-path \"..\")");
```

**Comment by vsbogd** [comment]
I have tried

    eval->eval("(add-to-load-path \"..\")");
but it doesn't work for me. 

I don't quite understand why VectorAPIUTest tries to load module from ```matrix/matrix``` path. I mean ```basic-api.scm``` includes it as:

    (use-modules (opencog) (opencog persist) (opencog matrix))
```opencog/matrix.scm``` module is present in the ```${PROJECT_BINARY_DIR}/opencog/scm``` only. It seems logical to load ```matrix/object-api.scm``` from ```${PROJECT_BINARY_DIR}/opencog/scm/opencog/matrix/object-api.scm``` but it tries to load it from ```opencog/matrix/matrix/object-api.scm```. 

May be the root cause is that ```matrix.scm``` is symlink actually?

**Comment by linas** [comment]
Study this file carefully: https://github.com/opencog/atomspace/blob/master/opencog/matrix/matrix.scm 

That file is installed to `/usr/local/share/opencog/scm/opencog/` and the name of the module is implicit, from this filename, and the directory its in (the module name is built from this path). The implementation must therefore be installed into `/usr/local/share/opencog/scm/opencog/matrix/` This works great for the install paths, but is awkward when in the build tree. 

Hmm actually, its not in the build tree, even. Maybe we should copy the files into the build tree ... that would probably be enough to solve it. Viz "install" them into the build tree.

**Comment by ferrouswheel** [comment]
I tested replacing the symlink created at `${PROJECT_BINARY_DIR}/opencog/scm/opencog/matrix.scm` with a proper copy of `matrix.scm`, and added `eval->eval("(add-to-load-path \"" PROJECT_BINARY_DIR "/opencog/scm\")");` to the test set up. This made the test pass without require `make install` first.

An alternative fix that also works (tested locally), is to lay out the source matrix scm code closer to its destination layout and then add the source to the guile's load path directly:

```
~/src/atomspace/opencog/matrix $ tree opencog/
opencog/
├── matrix
│   ├── bin-count.scm
│   ├── compute-mi.scm
... etc ...
│   ├── trans-batch.scm
│   └── transpose.scm
└── matrix.scm

1 directory, 18 files
```
and insert `eval->eval("(add-to-load-path \"" PROJECT_SOURCE_DIR "/opencog/matrix\")");` into the `setUp()` of VectorAPIUTest.

Having a valid module structure in the source dir could be more convenient for testing without explicitly having to build the project (e.g. if you've only modified scheme files), but copying to the build directory gives you a nice view of exactly what will be placed into a system folder before running install and avoids an overly nested directory tree.

**Comment by vsbogd** [comment]
Thanks @ferrouswheel! It seems that ```guile``` uses original path of the ```matrix.scm``` to get the full path to the other modules. The fact that copying works confirms it.

I also like the fix with aligning source folder structure with the target one more.

**Comment by linas** [comment]
I would rather have things coped to the build tree.  I hate these deeply nested source trees, they are painful to type at the keyboard, and ugly when trying to create a mental model of what is where.  

It is far more important to make things easy and nice for the human coder, than to make things easy and nice for the unit tests. The unit tests aren't human. They don't care. So, for the human, keep things simple, easy. Then "install" into the build folder, as nee3d for testing. Let the install scripts do the heavy lifting, not the human.

**Comment by ferrouswheel** [comment]
I also dislike deeply nested trees, especially when the directory names
repeat themselves!

My point was less about making it easier for the unit tests, and more that
scm modules are not usable in-place. You must build them with make to get a
functional module layout. Since we've discovered symlinks don't work as
expected, and if we switch to copying, you will no longer be able to edit
the original scm files and have your changes immediately available.

For compiled languages this doesn't matter, but for interpreted languages
I've found it nice to have a usable module structure in my source code.

But I imagine you've written a majority of the scm code, so if you're happy
to run make after every scm source change, then copy-on-build works.

**Comment by linas** [comment]
I think I'd be happy to run make. Here's why:

1) its no worse than what is already being done (running `make install` before testing)

2) during development, I'm in the habit of running `make test` constantly -- every 10, 20 minutes -- because any given change might break not just one unit test, but typically half-a-dozen of them, and you can't guess which ones in advance (esp, when one is convinced that a change "can't possibly break anything at all". I've been surprised that way many, many times.)  

3) If your focusing on any one fixed unit test, you still have to say `make tests` if you alter that unit test (since its in C++)  We are not using any scheme equivalent to nosetests, in part because its the interaction between scheme and the C++ code is where the action is.

That said, `matrix` is an example where there is no C++ code behind it.  (For now. Now that I'm finally beginning to really understand what it does, perhaps it can be ported to C++ for speed. Its got some tight inner loops that could be optimized.  Re: "finally understand": yes, I wrote 100% of the code, so I "understand" it at one level. But at a different level, the what/why/how part was not clear. Its finally becoming clear what parts are important, and what parts are silly cruft.)
