### ISSUE TITLE
Can't connect to postgres backing store in a docker swarm

### ISSUE THREAD

**Issue by enku-io** [opencog/atomspace#1847]
I have a docker swarm with multiple services. One service is based on `opencog/opencog-dev:cli`. There is another service which runs postgres. When trying to connect to the postgres service from the opencog service using
`(sql-open "postgres://postgres_username:postgres_pass@docker_compose service_name_/postgres_db")` command, I get the following error. 
`ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("sql-open" "Failed to execute! (/tmp/atomspace-master/opencog/persist/sql/multi-driver/ll-pg-cxx.cc:119)\nFunction args:\n(postgres://postgres_username:postgres_pass@docker_compose service_name_/postgres_db)")'.`

Log from Postgres Docker Service
`postgres_1  | 2018-07-26 12:14:28.787 UTC [26] postgres_username@postgres_db ERROR:  syntax error at or near "NOT" at character 20`
`postgres_1  | 2018-07-26 12:14:28.787 UTC [26] postgres_username@postgres_db STATEMENT:  CREATE SEQUENCE IF NOT EXISTS uuid_pool START WITH 1 INCREMENT BY 400;`

**Comment by Eskender-B** [comment]
I had kind of the same problem but with connecting with relex. The problem was properly defining the services in the compose file. Editing the compose file fixed my problem. Look my commit [here](https://github.com/opencog/docker/commit/266b372578cc09daff7b3c17b3f54ec150af06b4)

**Comment by enku-io** [comment]
I don't think that's the problem, because I am sure that a database connection has been made. 
Checking `ll-pg-cxx.cc` file, I can see that "Failed to execute" has been outputted after a connection has been made. 
`
LLPGConnection::exec(const char * buff)
{
	if (!is_connected) return NULL;

	LLPGRecordSet* rs = get_record_set();

	rs->_result = PQexec(_pgconn, buff);

	ExecStatusType rest = PQresultStatus(rs->_result);
	if (rest != PGRES_COMMAND_OK and
	    rest != PGRES_EMPTY_QUERY and
	    rest != PGRES_TUPLES_OK)
	{
		opencog::logger().warn("PQresult message: %s",
		               PQresultErrorMessage(rs->_result));
		opencog::logger().warn("PQ query was: %s", buff);
		rs->release();
		PERR("Failed to execute!");
	}

	/* Use numbr of columns to indicate that the query hasn't
	 * given results yet. */
	rs->ncols = -1;
	return rs;
}
`
This is the function that outputs the "Failed to execute message". I believe that one of this three flags has been raised `PGRES_COMMAND_OK`, `PGRES_EMPTY_QUERY` or `PGRES_TUPLES_OK`.

**Comment by linas** [comment]
Please pull the latest atomspace code.

There have been 3 or 4 different fixes for having multiple atomspace users accessing the same postgres DB. I just fixed another one (the last one??) yesterday or the day before.  All of the different bugs would typically print `Failed to execute` and then crash the whole system.

The lines that you quote in `ll-pg-cxx.cc ` are now different.

You can get additional details on the cause of the `Failed to execute` in the log file: the log file will contain the actual SQL error message.

**Comment by linas** [comment]
Sorry, my above reply is generic. If I read your actual error message:
```
syntax error at or near "NOT" at character 20
STATEMENT: CREATE SEQUENCE IF NOT EXISTS uuid_pool START WITH 1 INCREMENT BY 400;
```
This implies that the version of postgres that you are running is too old this statement.

What version are you running?

Without support for that statement, there is no multi-user support: the  `uuid_pool` is used to issue blocks of uuid's to different users, so that they do not conflict with one-another when accessing a shared database.

**Comment by linas** [comment]
OK, I can answer my own question: it appears that `CREATE SEQUENCE IF NOT EXISTS` was first introduced in postgres 9.5, which means that you must be using something older.

There are two possible fixes:

1) Can you upgrade to version 9.5?  Or is this hard or impossible?

2) It might be possible to alter the atomspace code to do something similar, but this would be hard and painful to do.

3) It is possible to alter the atomspace code to disable multi-user support, if the DB is too old.  I assume that, in the long run, you really do want multi-user support, right?

**Comment by enku-io** [comment]
I am running Postgres version 9.3. I can upgrade to 9.5 or later. Thank you for the response.
