### ISSUE TITLE
atomspace won't build under Ubuntu 14.04

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1857]
after the latest changes, I get the following error:
```
$ cmake ..
CMake Error at lib/CMakeLists.txt:8 (export):
  export Unknown arguments.
```

I assume that maybe my version of CMake is too old ??
This is occurring with 
```
$ cmake --version
cmake version 2.8.12.2
``` 

which is the default on version Ubuntu 14.04 -- have we decided that we no longer support Ubuntu 14.04 ?

(Or is this some other, unrelated bug?)

**Comment by vsbogd** [comment]
Root cause is that ```export(EXPORT ...)``` command is absent in CMake 2.8.12. It is used to collect all targets of atomspace and save them in ```AtomSpaceTargets.cmake``` file. I am not sure whether ```export(TARGETS ...)``` which is supported by 2.8.12 can be used instead.

@noskill, did you try using ```export(TARGETS ...)``` instead of explicit exporting by ```export(EXPORT ...)```?

**Comment by noskill** [comment]
@vsbogd @linas There is cmake3 package for ubuntu 14.04 https://packages.ubuntu.com/trusty/cmake3, so it's not a bug. Just install cmake3

**Comment by vsbogd** [comment]
if cmake 3 is required it should be reflected in https://github.com/opencog/atomspace/blob/18ca1e8343c658d799d60bef41c82d88906d1d48/CMakeLists.txt#L13

**Comment by linas** [comment]
Using cmake3 does work. But it also reports errors:
```
CMake Warning (dev) in CMakeFiles/Makefile.cmake:
  Syntax Warning in cmake code at

    CMakeFiles/Makefile.cmake:323:37

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeFiles/Makefile.cmake:
  Syntax Warning in cmake code at

    CMakeFiles/Makefile.cmake:324:35

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by linas** [comment]
closing; this bug went away.
