### ISSUE TITLE
libPythonEval.so not built in Ubuntu 14.04

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#1860]
It appears that python bindings are not being built, apparently because the cython version on ubuntu is too old:
```
-- Python 3.4.3 interpreter found.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.6") 
-- Python 2.7.6 libraries found.
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.6") 
-- Cython ( 0.20.1 >= 0.23.0) was not found. Make sure CYTHON_EXECUTABLE is set.
-- Cython executable not found.
...
The following components WILL NOT be built:
-----------------------------------------------
  ...
   Python bindings        - Python (cython) bindings.
   Python tests           - Python bindings nose tests
   ...
```
even though
```
$ dpkg -l cython
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  cython         0.20.1+git90 amd64        C-Extensions for Python

$ dpkg -l python-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python-dev     2.7.5-5ubunt amd64        header files and a static library
```

I guess cython is too old ... 
```
 $ cython --version
Cython version 0.20.1post0
```
Why is cython version 0.23 needed? Is it really needed, or is this an accidental change in the versin requirements?  Just earlier this year, version 0.20 used to be enough.

**Comment by vsbogd** [comment]
Hi @linas, Please see discussion under https://github.com/opencog/atomspace/pull/1777#issuecomment-400386859. I have upgraded Cython version in https://github.com/opencog/atomspace/pull/1786 to use standard Cython shared_ptr implementation which was introduced in Cython 0.23.

**Comment by linas** [comment]
Hmm. OK. Is there a newer version of cython for ubuntu 14.04?  I suppose we could also just say that ubuntu 14.04 is just too old (and I should probably dist-upgrade this laptop when I have time).

**Comment by vsbogd** [comment]
According to [this answer](https://askubuntu.com/questions/976962/installing-cython-0-24-on-ubuntu-14-04) cython from newer Ubuntu .deb repository can be used without any dependencies. Cython documentation also suggest installing using ```pip```, see [Cython installation instructions](https://cython.readthedocs.io/en/latest/src/quickstart/install.html).

**Comment by linas** [comment]
OK, so I did a `pip install cython`  and I see this:
```
$ cython --version
Cython version 0.28.5
```
Now I say `cmake ..` and I get:
```
CMake Error at /usr/local/share/opencog/cmake/FindCython.cmake:52 (IF):
  if given arguments:

    "DEFINED" "Cython_FIND_VERSION" "AND" "VERSION_LESS" "Cython_FIND_VERSION"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:361 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```

**Comment by vsbogd** [comment]
It seems that code: https://github.com/opencog/cogutil/blob/f1aced35095180f78e68058b1223876c393da10d/cmake/FindCython.cmake#L46-L52 doesn't parse ```CYTH_VERSION``` correctly in your case but I don't see why. On my machine:
```
$ cython --version
Cython version 0.28.3
```
which is similar to yours, and at the first glance should be parsed by regex correctly. Could you please echo ```${_CVERNO}``` before line https://github.com/opencog/cogutil/blob/f1aced35095180f78e68058b1223876c393da10d/cmake/FindCython.cmake#L49

**Comment by linas** [comment]
This:
```
$ cython --version
Cython version 0.28.5
```
and I added these lines
```
   MESSAGE(STATUS "So _CVERNO is this >>>${_CVERNO}<<<")
   MESSAGE(STATUS "So CYTH_VERSION is this >>>${CYTH_VERSION}<<<")
```
which print
```
	To over-ride, make sure PROTOBUF_LIBRARIES and PROTOBUF_INCLUDE_DIRS are set.
-- Python 3.4.3 interpreter found.
-- Python 2.7.6 libraries found.
-- So _CVERNO is this >>><<<
-- So CYTH_VERSION is this >>><<<
```

**Comment by linas** [comment]
I think I fond it:
```
-- So CYTHON_EXECUTABLE is this >>>/usr/bin/cython<<<
$ which cython
/usr/local/bin/cython
$ /usr/bin/cython
bash: /usr/bin/cython: No such file or directory
```
The fix is this:
```
$ rm CMakeCache.txt
```

**Comment by linas** [comment]
closing, since the cmakecache seems to have done it.

**Comment by linas** [comment]
thanks
