### ISSUE TITLE
Use PresentLink for verbatim patterns

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1882]
I wonder if we could use `PresentLink` to avoid most quotations.

For instance, currently
```scheme
(cog-execute! (Get (Present (Evaluation (GroundedPredicate "dummy") (Variable "$X")))))
```
raises an exception because it attempts to run the grounded predicate.

Wouldn't it be cool if it were instead equivalent to
```scheme
(cog-execute! (Get (Quote (Evaluation (GroundedPredicate "dummy") (Unquote (Variable "$X"))))))
```
?

**Comment by linas** [comment]
Knee-jerk reaction is that it's a good idea. 

Be forewarned that the code the code that implements `AbsentLink` is very old, predating most of the newer theory for the pattern matcher. There's another bug that shujing opened that pointed out that `NotLink PresentLink` is broken, and etc. I tried to fix this and making everything consistent, efficient, and kept breaking half-a-dozen unit tests no matter how I rearranged the code. Then I ran out of time.

So, sure, what you propose sounds like a pretty good idea, at the moment. Not sure just how easy or hard it would be to hack it.  Making all the booleans work correctly with present/absent won't be easy.

**Comment by linas** [comment]
Here is my half-finished attempt to cleanup/modernize absentlink https://github.com/linas/atomspace/tree/absent-link-rework

**Comment by linas** [comment]
See also #1596

**Comment by ngeiswei** [comment]
Cool! I'll have a look at your old branch see if I can take a stab at it.

**Comment by linas** [comment]
I think this is fixed in pull req #2172 -- a minimal proof that it works is in `PresentLinkUTest`

**Comment by ngeiswei** [comment]
Excellent, will test it in more depth as I port my code to use PresentLink over the next few weeks.

**Comment by linas** [comment]
OK, please close this issue as soon as you see fit; if you find problems, please open a new issue.

**Comment by ngeiswei** [comment]
@leungmanhin @AmeBel @Necr0x0Der @vsbogd and others, I give you the green-light to use `PresentLink` in your patterns. It makes patterns more readable, quotation less needed and helps the forward chainer to select rule premises.

**Comment by leungmanhin** [comment]
Awesome! I'll try it out

**Comment by linas** [comment]
@ngeiswei -- next step: use `FormulaLink` instead of `GroundedPredicate "scm"foo"`  for the arithmetic formulas.  I think it will make the PLN formulas more readable.  Faster too, as it will avoid a C++-to-guile transition.
