### ISSUE TITLE
excessive number of calls to grounded predicate from rule engine

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#1907]
Grounded predicated from https://github.com/opencog/atomspace/blob/master/tests/cython/backwardchainer/test_bc.py gets executed 8 times, while it should only get executed 4 times.

```
(AndLink
  (InheritanceLink
    (VariableNode "$X")
    (ConceptNode "Items")
  )
  (InheritanceLink
    (VariableNode "$Y") 
    (ConceptNode "Size")
  ) 
  (EvaluationLink
    (GroundedPredicateNode "py:run_predicate") 
    (ListLink 
      (VariableNode "$X")
      (VariableNode "$Y")
    ) 
  )
) 
```

run_predicate gets called with
Item1 small
Item1 large
Item0 small
Item0 large
Item1 small
Item1 large
Item0 small
Item0 large

Clearly there are  only 4 combinations

**Comment by ngeiswei** [comment]
@noskill, maybe it is due to variable matching (I suppose this is what led you to create issue #1908 in the first place).

**Comment by noskill** [comment]
In this case variables are not passed to grounded predicate, I am not sure why. But it still looks like performance bug to me. What if our grounded predicate is costly to compute?

**Comment by noskill** [comment]
@linas You are right, here are two calls to bindlink in BackwardChainer::fulfill_fcs:

first:
```scheme
(BindLink
  (VariableList
    (VariableNode "$Y") ; [5319137675165988851][1]
    (VariableNode "$X") ; [6809970978681772822][1]
  ) ; [13072967251775625710][12]
  (AndLink
    (InheritanceLink
      (VariableNode "$X") ; [6809970978681772822][1]
      (ConceptNode "Items") ; [7784914235235991834][1]
    ) ; [12504770299739150416][1]
    (InheritanceLink
      (VariableNode "$Y") ; [5319137675165988851][1]
      (ConceptNode "Size") ; [246584648763856281][1]
    ) ; [14979144061672662156][1]
    (EvaluationLink
      (GroundedPredicateNode "py:run_predicate") ; [82496316461441465][1]
      (ListLink
        (VariableNode "$X") ; [6809970978681772822][1]
        (VariableNode "$Y") ; [5319137675165988851][1]
      ) ; [13890118523665210292][1]
    ) ; [17497479716809064362][1]
  ) ; [9751367575807793758][1]
  (AndLink
    (InheritanceLink
      (VariableNode "$X") ; [6809970978681772822][1]
      (ConceptNode "Items") ; [7784914235235991834][1]
    ) ; [12504770299739150416][1]
    (InheritanceLink
      (VariableNode "$Y") ; [5319137675165988851][1]
      (ConceptNode "Size") ; [246584648763856281][1]
    ) ; [14979144061672662156][1]
    (EvaluationLink
      (GroundedPredicateNode "py:run_predicate") ; [82496316461441465][1]
      (ListLink
        (VariableNode "$X") ; [6809970978681772822][1]
        (VariableNode "$Y") ; [5319137675165988851][1]
      ) ; [13890118523665210292][1]
    ) ; [17497479716809064362][1]
  ) ; [9751367575807793758][1]
) ; [10975275621032270874][12]
```
second
```
(BindLink
  (VariableList
    (VariableNode "$Y") ; [5319137675165988851][1]
    (VariableNode "$X") ; [6809970978681772822][1]
  ) ; [13072967251775625710][12]
  (AndLink
    (InheritanceLink
      (VariableNode "$X") ; [6809970978681772822][1]
      (ConceptNode "Items") ; [7784914235235991834][1]
    ) ; [12504770299739150416][1]
    (InheritanceLink
      (VariableNode "$Y") ; [5319137675165988851][1]
      (ConceptNode "Size") ; [246584648763856281][1]
    ) ; [14979144061672662156][1]
    (EvaluationLink
      (GroundedPredicateNode "py:run_predicate") ; [82496316461441465][1]
      (ListLink
        (VariableNode "$X") ; [6809970978681772822][1]
        (VariableNode "$Y") ; [5319137675165988851][1]
      ) ; [13890118523665210292][1]
    ) ; [17497479716809064362][1]
  ) ; [9751367575807793758][1]
  (ExecutionOutputLink
    (GroundedSchemaNode "scm: fuzzy-conjunction-introduction-formula") ; [2597239087430947365][1]
    (ListLink
      (AndLink
        (InheritanceLink
          (VariableNode "$X") ; [6809970978681772822][1]
          (ConceptNode "Items") ; [7784914235235991834][1]
        ) ; [12504770299739150416][1]
        (InheritanceLink
          (VariableNode "$Y") ; [5319137675165988851][1]
          (ConceptNode "Size") ; [246584648763856281][1]
        ) ; [14979144061672662156][1]
        (EvaluationLink
          (GroundedPredicateNode "py:run_predicate") ; [82496316461441465][1]
          (ListLink
            (VariableNode "$X") ; [6809970978681772822][1]
            (VariableNode "$Y") ; [5319137675165988851][1]
          ) ; [13890118523665210292][1]
        ) ; [17497479716809064362][1]
      ) ; [9751367575807793758][1]
      (SetLink
        (InheritanceLink
          (VariableNode "$X") ; [6809970978681772822][1]
          (ConceptNode "Items") ; [7784914235235991834][1]
        ) ; [12504770299739150416][1]
        (InheritanceLink
          (VariableNode "$Y") ; [5319137675165988851][1]
          (ConceptNode "Size") ; [246584648763856281][1]
        ) ; [14979144061672662156][1]
        (EvaluationLink
          (GroundedPredicateNode "py:run_predicate") ; [82496316461441465][1]
          (ListLink
            (VariableNode "$X") ; [6809970978681772822][1]
            (VariableNode "$Y") ; [5319137675165988851][1]
          ) ; [13890118523665210292][1]
        ) ; [17497479716809064362][1]
      ) ; [14869497446014253706][12]
    ) ; [17927773580632471987][12]
  ) ; [12861886302267728320][12]
) ; [15866207530526024065][12]

```

**Comment by linas** [comment]
Of the two, the first one seems like junk, to me. The re-write is identical to the search pattern, so you could save some cpu time by having a null rewrite term. In that case, the only point of running that rule is because `py:run_predicate` has some side-effect, and the goal was to force it to run, so it would have that side effect.  But if it has no side effect, then that rule is pointless. 

The second one is weird too; it repeats the same term twice, once in an AndLink, once in a SetLink. There would be less atomspace pollution if the SetLink was converted to an AndLink, also. 

But ... `fuzzy-conjunction-introduction-formula` seems to be accepting more-or-less the same argument, twice. which seems odd or pointless or incomplete or wrong. So I have no understanding of what was supposed to happen here. 

Based on earlier discussions with Nil, there was a suggestion that the chainer code has to handle some general case, and this sometimes results in special-cases that are meaningless or pointless.  Since the chainer code is complex, he might not want to fix it so that it avoids these meaningless/pointless cases. But ... still. This seems like its "obviously wrong", so it seems like it should somehow be foxed. But thyis is beyond me, right now.

**Comment by ngeiswei** [comment]
Everything I'm seeing is normal.

The first bind link comes from iteration 1, it's not meaningless, it answers the user's query in the most direct way, looking for knowledge that is already in the atomspace. The tricky bit here is that the query is a mixture of real and virtual clauses, but maybe it's another issue.

The second bind link is iteration 2, it takes the bind link of iteration 1 and expand it to construct a bind link to answer with more indirect knowledge, not just what is in atomspace, but what can be inferred from it, here by the application of fuzzy conjunction.

If you don't want to run the bind link from iteration 1, hmm, maybe we can add some user option to control that sort of things, like avoiding running/fulfilling inference trees are not do satisfy some criteria.

**Comment by ngeiswei** [comment]
The redundancy in the second bind link comes from the format used to represent rules rewriting term

```
ExecutionOutput
  <formula>
  List
    <conclusion>
    <premise-1>
    ...
    <premise-2>
```

with the twist that unordered premises can be wrapped in a Set link, as to avoid over representation of inference trees.

See for more https://wiki.opencog.org/w/URE_Configuration_Format#Defining_Rules

**Comment by noskill** [comment]
By the way, if ExecutionOutput link is used in BindLink in both condition and conclusion then it will be executed twice:

```scheme
(add-to-load-path ".")

(use-modules (opencog))
(use-modules (opencog query))
(use-modules (opencog exec))


(Inheritance (Concept "red") (Concept "color"))
(Inheritance (Concept "blue") (Concept "color"))
(Inheritance (Concept "green") (Concept "color"))


(define (schema2 A B)
    (display "Executing schema2 with ")
    (display (list (cog-name A) (cog-name B)))
    (newline)
    (if (equal? (cog-name A) (cog-name B))
        (Concept "Same color")
        (Concept "Different color")))


(define (classify A)
    (display "Executing predicate with ")
    (display (cog-name A))
    (newline)
    (if (equal? (cog-name A) "Same color")
        (stv 1 1)
        (stv 0 1)))

        
(define bind-link
    (BindLink
        (VariableList
            (Variable "$X")
            (Variable "$Y"))
        (And
            (Inheritance
                (Variable "$X")
                (Concept "color"))
            (Inheritance
                (Variable "$Y")
                (Concept "color"))
            (Evaluation
                (GroundedPredicate "scm: classify")
                (ExecutionOutput
                    (GroundedSchema "scm: schema2")
                    (List
                         (Variable "$X")
                         (Variable "$Y"))
                )
            ))
        (ExecutionOutput
            (GroundedSchema "scm: schema2")
                (List
                   (Variable "$X")
                   (Variable "$Y")))
        )
)
(define result (cog-execute! bind-link))
```

It seems that we can just return whatever was returned from grounded schema during first call to it.

**Comment by linas** [comment]
> The first bind link 

If the only goal is to get a yes/no answer for "does this pattern exist?", then using a  `SatisfactionLink` is more efficient. 

The first bindlink is completely valid; it is just a usage that I never expected, and its surprising, to me. But OK.  For me, bindlink is always "does it exist, and if so then do something", so failing to "do something" is ... valid but surprising.

> that unordered premises can be wrapped in a Set link,

Keep in mind that AndLink is also unordered.

**Comment by noskill** [comment]
@linas I had a bit different use case: whether GroundedSchemaNode is random or not return it's output as it was when pattern was matched. My idea is that for many cases we can treat GroundedSchemaNode as deterministic during the inference.

**Comment by noskill** [comment]
> That would hold only if schema2 was stateless. Unfortunately, to the pattern matcher its a black box: we don't know what it does.

In any case some assumptions should be made. Even if schema2 is random, pattern matcher won't call it a few more times to see if it's lucky. What worse caching doesn't reduce the search space:

let's say we have schema1 to schemaN and two concept nodes nodes A and B:
let's say  (schema1 A B)... (schemaN A B)  fails to match for (schemaN A B). Then pattern matcher would try (schema1 B A)..  (schemaN A B).. all the 2^N combinations.

**Comment by linas** [comment]
> GroundedSchemaNode return it's output as it was when pattern was matched. 

This seems like a good idea. Care to write it up in much greater detail, as a distinct github issue? We could mark it as "enhancement", and then debate everything that's good and bad about it.

> two concept nodes nodes A and B:

Except that, "in real life", the atomspace contains K=10K or 100K or 1M concept nodes, and so grounded predicates used to perform compares might have to process K^2 combinations.

Now you could argue and say something like "for my problem K is guaranteed to always be a small number", which is an OK argument.  Just not universal...

What I'm seeing, from practical experience, is that K follows a Zipf distribution: there are one or two things where K is a million, and a million things where K is one or two. (and a thousand things where K is a thousand)   My hunt for "ideal algorithms" is a hunt for algos that work well, given Zipf-style distributions.  This does seem to be "universal".

**Comment by noskill** [comment]
new enhancement issue to further discuss proposed changes https://github.com/opencog/atomspace/issues/1911

**Comment by linas** [comment]
I just re-read your comment above, and realized I completely misunderstood it.

The pattern matcher does NOT attempt all possible 2^N reorderings of clauses. It picks one, and does only that. However, if a clause does have an unordered link in it, then, yes there are 2^N reorderings that get attempted. I do not recall if this would also force a re-evaluation of each schema, for each re-ordering, or whether it saves the results in the temp space, until all orderings are tried.

**Comment by noskill** [comment]
@linas Ok, closing the issue since bindlink rewrite clause is exception for when recalculation happens
