### ISSUE TITLE
Multi-repo entanglement

### ISSUE THREAD

**Issue by kasimebrahim** [opencog/atomspace#1923]
I was renaming proto->value based on #1880. The problem is I have to change [cogutil/cmake/OpenCog/AtomTypes.cmake#L44-47](https://github.com/opencog/cogutil/blob/d5a2f292d0872ffdf6a1570943addce6f87cfac3/cmake/OpenCogAtomTypes.cmake#L44) on cogutil to work with the renamed atomespace directory and I was thinking of removing the entanglement.
editing OpenCogMacros.cmake to include
<pre>
    SET(oneValueArgs SCRIPT_FILE INHERITANCE_FILE SCM_FILE PYTHON_FILE)
    SET(multiValueArgs HEADER_FILE DEFINITIONS_FILE)
    CMAKE_PARSE_ARGUMENTS(OTYPES "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
</pre>
and editing the call OPENCOG_ADD_ATOM_TYPES in atomspace to 
<pre>
OPENCOG_ADD_ATOM_TYPES(SCRIPT_FILE atom_types.script
  HEADER_FILE atom_types.h opencog/atoms/proto/types.h
  DEFINITIONS_FILE atom_types.definitions opencog/atoms/proto/NameServer.h opencog/atoms/proto/atom_types.h opencog/atoms/proto/types.h
  INHERITANCE_FILE atom_types.inheritance
  SCM_FILE core_types.scm
  PYTHON_FILE core_types.pyx)
</pre>
will fix the problem. If you think it is a good idea I can put a PR.

**Comment by linas** [comment]
There are multiple issues. First, the OpenCogAtomTypes.cmake should never have been moved to cogutils; that's a mistake. Moving it back to the atomspace repo would be a welcome pull request.

**Comment by linas** [comment]
Actually, all three files, `OpenCogAtomTypes.cmake`,  `OpenCogFunctions.cmake`, `OpenCogMacros.cmake` should never have been moved to cogutils, and all three should be moved back to the atomspace. 

I am hoping that this will be easy, and that it will untangle whatever you saw as being tangled.  I'm hoping that this will be a very easy pull request.

**Comment by linas** [comment]
FYI, it appears to be pull req opencog/cogutils#120 that incorrectly moved those files.

**Comment by linas** [comment]
Partly resolved in pull req #1924 and in opencog/opencog#3352

**Comment by linas** [comment]
and opencog/agi-bio#80

**Comment by linas** [comment]
This can be closed after opencog/cogutil#139 is merged.

**Comment by linas** [comment]
next time @kasimebrahim please mention the associated issue in pull reqs -- it helps keep everything tied together.

**Comment by kasimebrahim** [comment]
Will do.

**Comment by linas** [comment]
closing; its all merged.
