### ISSUE TITLE
Counting atoms

### ISSUE THREAD

**Issue by stellarspot** [opencog/atomspace#2077]
Suppose there are baskets with balls and balls can have different colors.
It needs to calculate number of balls or number of green balls for the given basket.

There is the cog-arity method but it can't be used in expressions like find baskets which has more than 5 green balls.

I tried to map each found green ball to (Number 1) using LambdaLink but it returns a set of ones and because all (Number 1) are unique it always contains only one one.

The wiki also describes FoldLink but I have not found examples how to properly run it.

What is the right way to count number of atoms in expressions and conditions?

**Comment by linas** [comment]
Try using `ArityLink` -- it should return a `NumberNode` counting whatever it wraps.

It only makes sense to wrap something executable ... if it's not executable, then the arity is always fixed and knowable in advance, and thus pointless.

**Comment by linas** [comment]
Here: try this:
```
(use-modules (opencog) (opencog exec))
(define g2 (GetLink
  (VariableList
   (TypedVariable (VariableNode "$num1") (Type 'NumberNode))
   (TypedVariable (VariableNode "$num2") (Type 'NumberNode)))
  (And
   (Present (VariableNode "$num1"))
   (Present (VariableNode "$num2"))
   (GreaterThanLink (VariableNode "$num1") (VariableNode "$num2")))))

(cog-execute! g2)
(cog-execute! (Arity g2))
(Number 1)

(cog-execute! g2)
(cog-execute! (Arity g2))

(Number 2)
(cog-execute! g2)
(cog-execute! (Arity g2))
(cog-execute! (Arity g2))
(cog-execute! (Arity g2))
(cog-execute! (Arity g2))
```

**Comment by noskill** [comment]
https://wiki.opencog.org/w/ArityLink says arity link is deprecated

**Comment by linas** [comment]
:-) Excellent!

The wiki page is correct.  You have three choices:

1. Ignore it, use ArityLink anyway, and make some future maintainer curse your name, when they try to remove ArityLink, and find your code.

2. Use ArityValueOf .. which doesn't currently exist, but should be very easy to add, by copying `ValueOfLink` and adjusting it.

3. Fix the whole `SetLink` mess. This is a huge and impossible task at this time. Well, its possible, but a difficult and delicate task. open-heart surgery.  

I suggest 2. right now. But I also don't really understand what you are trying to do. It is possible that maybe 1. is the best solution for your problem; I don't know. (and that if/when 3. is fixed, then we can un-deprecate 1.)

**Comment by ngeiswei** [comment]
@linas I don't understand why `ArityLink` is so bad. I understand that it can be implemented using more generalized constructs, like say `FoldLink` combined with `PlusLink` and `OutgoingSetOfLink`, on the other hand it is part of the C++/Scheme/Python/Haskell API, why not be part of the Atomese API?

**Comment by linas** [comment]
"Bad" is a relative term.  ArityLink returns NumberNodes, and after running for a while, the atomspace gets filled with lots of useless, pointless NumberNodes. They're just garbage lying around.

Another problem is SetLink -- the robot behavior trees process hundreds of GetLinks and BindLinks per second, and each one produces a SetLink, and after half an hour of running, the AtomSpace gets filled with thousands and thousands of really useless, really pointless SetLinks that do nothing at all, except hold old, obsolete, no-longer-needed search results. Some of these are wrapped in ArityLink ... 

So, basically, the atomspace fills up with  garbage - SetLinks and ArityLinks being two big offenders, and there's no garbage-collection mechanism for deleting them. Of course you can delete them manually; there was some script on ghost that did this every so often.   There was the very old idea that maybe attention allocation and VLTI could be used for garbage collection. Poke on this for a bit, and you see that this is a cute idea that is very incomplete, and very far from being a practical solution.

The third alternative, that I currently like the best: don't create the garbage in the first place.  Avoid using NumberNodes - try to use Values. Avoid SetLinks for search results, replace by something else. And avoid ArityLinks, which wrap SetLinks and spew NumberNodes.

**Comment by ngeiswei** [comment]
https://wiki.opencog.org/w/Discussion

**Comment by noskill** [comment]
> "Bad" is a relative term. ArityLink returns NumberNodes, and after running for a while, the atomspace gets filled with lots of useless, pointless NumberNodes. They're just garbage lying around.

This is not really a problem, since you can use temporary atomspace. And this logic applies to any link or node, since you can return any atom from bindlink.

**Comment by linas** [comment]
Responding on mailing list.

**Comment by linas** [comment]
Moving discussion to mailing list.

On Tue, Feb 26, 2019 at 3:00 AM Anatoly Belikov <notifications@github.com>
wrote:

> "Bad" is a relative term. ArityLink returns NumberNodes, and after running
> for a while, the atomspace gets filled with lots of useless, pointless
> NumberNodes. They're just garbage lying around.
>
> This is not really a problem, since you can use temporary atomspace. And
> this logic applies to any link or node, since you can return any atom from
> bindlink.
>

There is currently no practical, easy, straight-forward way to copy atoms
from the temp atomspace, back into the main one.  Yes, it would be nice if
we could leave behind the no-longer-needed NumberNodes and SetLinks in the
temp atomspace, and watch them go "poof" when the temp space is deleted ..
but the results of those computations, we typically want to keep. If the
result was the creation of a new atom, how can one put  it in the main
atomspace?

--linas

-- 
cassette tapes - analog TV - film cameras - you

**Comment by noskill** [comment]
Ok, maybe we need another link - copy to atomspace link? Something like:
(CopyOutputLink
         (AtomSpaceLink "Parent")
         (BindLink (...)
)

So that BindLink is in some temporary atomspace, but results will be copied to some other atomspace.
