### ISSUE TITLE
execute_atom in cython binding can't execute ValueOfLink

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2124]
k = Predicate("key")
jk = ConceptNode("my atom")
jk.set_value(k, FloatValue(1, 2, 3))
bindlink.execute_atom(atomspace, ValueOfLink(jk, k))

```
*** RuntimeError: Not executable! (ValueOfLink
  (ConceptNode "my atom") 
  (PredicateNode "key") 
) 
```

This example works in scheme

**Comment by noskill** [comment]
singnet fork issue, will be resolved after merge

**Comment by vsbogd** [comment]
Just to mention, unit test is: https://github.com/opencog/atomspace/blob/9a7562af66c79c9b01c3db1cc7e740b6011ceb7e/tests/cython/atomspace/test_do_execute.py#L18-L27
