### ISSUE TITLE
Clang compilation

### ISSUE THREAD

**Issue by maparent** [opencog/atomspace#2163]
This is an umbrella issue to discuss issues with compiling on clang.

**Comment by maparent** [comment]
Among issues that would need attention:
Clang refuses to pass objects in variadic functions, which seems is optional in C++11, according to https://stackoverflow.com/a/14432703/439048
This creates issues with the factory calls in `ValueFactory.h:118`
I am trying to think of better ways to have variadic factory functions, but I would certainly appreciate the viewpoint of the authors.

**Comment by maparent** [comment]
Finally solved the factory issue with a minor syntax tweak.

**Comment by linas** [comment]
Yeah, that factory code is tricky, and works in a non-obvious away...
