### ISSUE TITLE
PatternMatcher: Implement PresentLink

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#218]
A proposal for PresentLink is given here:  http://wiki.opencog.org/w/PresentLink -- it seems like a good idea, based on the long discussions in issue #132 

This is marked as an enhancement, and is relatively low priority: there is an easy work-around: one can use an AndLink and wrap multiple arity-1 ChoiceLinks to get the same effect as PresentLink.

I think the wiki page describes PresentLink closely enough that there should be no confusion about how to implement it.

**Comment by linas** [comment]
Pull request #294 provides basic support for using PresentLink inside of a SequentialAndLink.  More complex usage cases are not tested and probably won't work right.

**Comment by linas** [comment]
Pull req #302 adds more support

**Comment by ngeiswei** [comment]
@linas, I'm closing that issue, I think you'd agree that future problems related to `PresentLink` should be treated in separate issues.

**Comment by linas** [comment]
Yes. OK.  As noted elsewhere, `Not Present` fails to behave like `Absent` and fixing this is kind-of tricky (#1822)
