### ISSUE TITLE
Recursion with DefinedSchema crashes

### ISSUE THREAD

**Issue by buj** [opencog/atomspace#2193]
Inspiration from the example with SequentialAndLink and printing stuff to console: [https://github.com/opencog/atomspace/blob/master/examples/atomspace/recursive-loop.scm](https://github.com/opencog/atomspace/blob/master/examples/atomspace/recursive-loop.scm)
The above mentioned uses evaluatable links (`DefinedPredicate` and `SequentialAnd`) to achieve recursion. So I thought of what would happen with `DefinedSchema` instead:
```
(Define
   (DefinedSchema "factorial")
   (Lambda
      (TypedVariable
         (Variable "$n")
         (Type "NumberNode")
      )
      (Cond
         (GreaterThan
            (Variable "$n")
            (Number 0)
         )
         (Times
            (Variable "$n")
            (ExecutionOutput
               (DefinedSchema "factorial")
               (Minus
                  (Variable "$n")
                  (Number 1)
               )
            )
         )
         (Number 1)
      )
   )
)

(cog-execute! (ExecutionOutput (DefinedSchema "factorial") (Number 5)))
```
It crashes; tried the same in python, also crashes.

Other than that, is there some link type corresponding to: `begin {statement1; statement2; statement3; ...} end`? This could be used in a similar way to `SequentialAndLink` in the abovementioned example---execute many statements, the result is the result of the last one.

**Comment by linas** [comment]
Well, this is certainly an unexpected use of the atomspace.  But I guess its valid. 

It appears that execution causes infinite recursion, where the definition is substituted for repeatedly, until the stack is blown out, and then it crashes. I'm looking to see how it might be fixed now.

The reason I said that this is an unexpected use of the AtomSpace is that the AtomSpace is intended to be a knowledge-store, and for it to be effective for that, algorithms have to be able to crawl over the contents of the atomspace, and perform transformations on it.  By writing executable code in atomese,  your creating data structures that no ordinary algo can understand and process.  There's nothing terribly wrong with that, its just .. pushing the limits.  Computing factorials  in Atomese is going to be a thousand times slower (literally) than any other programming language... and worse, Atomese is not a human-friendly language.  Its not meant for human programmers.  Just saying ...

**Comment by linas** [comment]
So, this is fixed in pull rq #2194

**Comment by ngeiswei** [comment]
Maybe this example could be added in the example folder. I know it is not a typical use of Atomese but it is such a classical example. I could see MOSES learning that kind of programs.

**Comment by linas** [comment]
> it is such a classical example. 

It is, but it feels like the beginning of a slide down a slippery slope. I dunno. Maybe it's OK, but in the long run, I really want to refocus on discerning patterns and learning patterns, rather than going down the rabbit-hole of building a better evaluation/execution engine...  I mean, I guess its harmless that this works, but atomese is inspired by CIL or gimple, its not really a replacement for CIL or gimple...

**Comment by buj** [comment]
My reasoning why this was worth filing a bug was, that even though it is not meant for human programmers, ultimately humans are the ones designing the systems (that discern patterns/...). And some level of understanding of this is thus required, even for humans. I had some intuitions/expectations/model about how the stuff should work, tried it out, and it turned out to not work that way... and I was unable to create a better "model" in my mind, that would explain this bug.

I believe it is good if behaviour of a certain link can be explained in simple terms, other than "here's the code in C++". If it cannot, then doing any reasoning with the link will prove difficult, because the meaning of the link is difficult to (100% accurately) capture. Though one may instead decide to capture not the meaning of the link itself, but rather "the way it is used". And also, if we only do some heuristic reasoning, then complex links are not such a big problem.

But I totally understand that this is not the main focus of OpenCog, I'll be sure to take a look into more important matters eventually (URE/PLN/...?).

**Comment by linas** [comment]
@buj  This was a fine bug to open. And the example you posted should have worked. And its now fixed, so it does work.  Your example is now memorialized in a unit test that passes. (`tests/query/exec-factorial.scm`)  So all is good.

What you are witnessing is this: you tried something that no one ever tried before (because no one ever needed to, I guess) and you found a bug. A real bug; it is reasonable to expect this to work. 

I added some extra words of caution for you, mostly because you're a newbie here, and I'm trying to .. I dunno .. set realistic expecations.

Anyway, I'm closing this, its now fixed.

**Comment by linas** [comment]
@ngeiswei changed my mind about the demo: its here: #2197

@buj a better demo would use Values, and the `ValueOfLink` for numerical sources.  Unlike `NumberNodes`, Values don't "pollute" the atomspace.  Some of the examples in the `examples/atomspace` dir show how, in particular, `formulas.scm` -- a recursive demo of factorial or something similar, working on values, would be cool, and would be a "recommended" way of doing math with the atomspace.
