### ISSUE TITLE
Problem evaluating DefinedPredicate

### ISSUE THREAD

**Issue by buj** [opencog/atomspace#2214]
I'm getting some counterintuitive results with DefinedPredicates. Basically, I set up a small genealogy database (consisting of a few `InheritanceLinks`). Now I want to query it and find out if some `A` is a parent of `B`, that is, if there is an `InheritanceLink` with strength > 0.5 and confidence > 0.5. I devise three different methods, which should merely differ on the syntactic level; but they return different results (one is obviously correct and the other not so much).

The code shall explain the rest:
```
; Populate the atomspace with facts.
(define anna (Concept "anna"))
(define mama (Concept "mama"))
(Inheritance (stv 1. 1.) anna mama)


; Auxiliary methods for debugging.
(define (prt-atom x)
  (display x)
  (stv 1. 1.)
)
(define (prt-mean x)
  (display "mean is ")
  (display (cog-mean x))
  (newline)
  (stv 1. 1.)
)
(define (prt-confidence x)
  (display "confidence is ")
  (display (cog-confidence x))
  (newline)
  (stv 1. 1.)
)

; Something is "true-enough" if both its strength and confidence are
; above 0.5. This also prints debugging info.
(Define
  (DefinedPredicate "true-enough")
  (Lambda
    (SequentialAnd
      (True (ExecutionOutput
        (GroundedSchema "scm:prt-atom")
        (Variable "$x")
      ))
      (True (ExecutionOutput
        (GroundedSchema "scm:prt-mean")
        (Variable "$x")
      ))
      (True (ExecutionOutput
        (GroundedSchema "scm:prt-confidence")
        (Variable "$x")
      ))
      (GreaterThan
        (StrengthOf (Variable "$x"))
        (Number 0.5)
      )
      (GreaterThan
        (ConfidenceOf (Variable "$x"))
        (Number 0.5)
      )
      (True (ExecutionOutput
        (GroundedSchema "scm:prt-atom")
        (Concept "success!")
      ))
    )
  )
)
; Convenience method.
(define (true-enough x)
  (cog-evaluate!
    (Evaluation
      (DefinedPredicate "true-enough")
      x
    )
  )
)

; Essentially the same as "true-enough", except that it immediately
; puts the two variables into an inheritance link (thus saving some
; typing).
(Define
  (DefinedPredicate "aux")
  (Lambda
    (VariableList
      (Variable "$x")
      (Variable "$y")
    )
    (Evaluation
      (DefinedPredicate "true-enough")
      (Inheritance (Variable "$x") (Variable "$y"))
    )
  )
)
(define (aux x y)
  (cog-evaluate!
    (Evaluation
      (DefinedPredicate "aux")
      (List x y)
    )
  )
)

; This also does not work, seems like wrapping stuff inside the
; inheritance link is a problem.
(Define
  (DefinedPredicate "aux-anna")
  (Lambda
    (Evaluation
      (DefinedPredicate "true-enough")
      (Inheritance anna (Variable "$x"))
    )
  )
)
(define (aux-anna x)
  (cog-evaluate!
    (Evaluation
      (DefinedPredicate "aux-anna")
      x
    )
  )
)
```
With this loaded, we run the three experiments:
```
(true-enough (Inheritance anna mama))
(aux anna mama)
(aux-anna mama)
```
In all three experiments, the debugging info says that both the strength and the confidence of the atom are 1. However, only the first experiment successfully reaches the end of `true-enough` (and prints `success!`)---the remaining two, for some reason, return `(stv 0 1)` instead of `(stv 1 1)`.

I also tried the same experiment, but with the `InheritanceLinks` in queries wrapped inside `LocalQuoteLink`s, as I found out that `InheritanceLink`s themselves are evaluatable. This change however did not affect the results of the experiments.

**Comment by linas** [comment]
Yeah, its a bug. The ValueOf link types  are fairly recent, and apparently had an unforeesen bug.

**Comment by ngeiswei** [comment]
@buj, you might want to have a look at https://wiki.opencog.org/wikihome/index.php/Scheme#Logger which can be more convenient that `display` in some situations.

**Comment by linas** [comment]
Fixed in pull req #2216 -- as stated there: If an atom is not in an atomspace, we don't really know what TV it is supposed to have. The TruthValueOf, StrengthOf and ConfidenceOf links weren't working correctly.

**Comment by buj** [comment]
(just to check my understanding)

So, the problem was that these links constructed a new `InheritanceLink` in some temporary "scratch" atomspace during beta reduction (i.e. when substituting for variables). This link was completely independent from the original link `(Inheritance anna mama)`, thus it did not have any valuation. When `StrengthOf`/... were called on that link, it returned the standard `(stv 1. 0.)` which of course did not pass the `true-enough` test.

Is this correct?

**Comment by linas** [comment]
Actually, they were not in any atomspace. (Atoms are not automatically placed into an atomspace when created, because there is a significant overhead to inserting them. That overhead seems pointless if they are temporary, or soon-to-be-discarded)  When these Atoms are created, they get the DEFAULT_TV which is true-but-not-confident.

If they had been placed in the temporary atomspace, things would have worked: the scratch atomspaces are all backed-up-by/derived-from/sit-on-top-of a main atomspace, and so the Atoms would have passed through, and would have been found in the main atomspace.

I think this is an important lesson which not a lot of people think about very much: the reason for having an atomspace is to have a single, master copy of an atom that is always there, and it "holds stuff" (i.e. Values) and even if you ignore it for a long time, when you come back to it, it will still be there, holding those Values.  This is not deep, but its also easily forgotten :-/

**Comment by linas** [comment]
closing, this is fixed; open a new issue for new problems :-)

**Comment by linas** [comment]
Oh, the other lesson is that the internal implementation "does stuff with temporaries", and all of that should be completely invisible to you, as the user. Here, the temporaries were mis-handled.
