### ISSUE TITLE
Counterintuitive behaviour of PredicateFormula

### ISSUE THREAD

**Issue by buj** [opencog/atomspace#2218]
Consider the following PredicateFormulas:
```
(use-modules (opencog) (opencog exec))

(define formula1
  (PredicateFormula
    (Number 1)
    (Number 1)
  )
)
(define formula2
  (PredicateFormula
    (Times
      (Number 1)
      (Number 1)
    )
    (Number 1)
  )
)
(define formula3
  (PredicateFormula
    (Number 1)
    (Times
      (Number 1)
      (Number 1)
    )
  )
)
(define apple-is-green (Concept "apple-is-green" (stv 1 0.5)))
(define apple-is-red (Concept "apple-is-red" (stv 0.9 0.6)))
(define formula4
  (PredicateFormula
    (Number 1)
    (Times
      (Number 1)
      (Number 0.5)
      (StrengthOf apple-is-green)
      (ConfidenceOf apple-is-red)
    )
  )
)
(cog-evaluate! formula2)
```
Now, one would expect all four to run without problems. But in fact only `formula1` and `formula4` succeed; the remaining two formulas crash (segfault). Which is counterintuitive---if something runs with `(Number 1)`, one would expect it to run with an arbitrary expression resulting in a number, right?

I believe I have a quick fix, if this is approved (i.e. "this is SO DAMN SERIOUS to warrant a fix"), I'll start work on it.

For those interested: basically, the issue is that the PredicateFormula supports NumberNodes in a kind-of hacky way: it must be either a pure NumberNode, or something which reduces to a FloatValue. Stuff crashes if the argument is neither a NumberNode, but is something executable that reduces to non-FloatValue.

**Comment by linas** [comment]
Yes, this should be fixed.  These are very lightly used at the moment, but I think @ngeiswei is planning to replace all the  `scm:formula` callouts in PLN with this.  Actually, you may want to volunteer to help him w/ this. There are two advantages:

* one avoids the CPU overhead of entering guile, just to multiply a few numbers (this is in the dozens-of-microseconds range e.g. 20K to 50K per second)
* it makes the PLN formulas more readable, as all kinds of ExOut and GroundedPredicate nodes are no longer needed.

There's also a long-term advantage: formulas are treated in the same way as everything else: they become first-class objects, and can now be data-mined, either by moses, or the pattern miner.

**Comment by linas** [comment]
Yes, please fix.  It should be easy -- just a rearrangement of the existing code. Extend the `FormulaUTest` too.

**Comment by buj** [comment]
I'll start work right away.

Regarding replacing `scm:formula` with PredicateFormulas, I can help with that too once we are ready for the transition. Though currently, the `scm:formula`s do more than just calculate the conclusion's truth value---they also set the conclusion's truth value to that. After the transition, this would have to be done somehow automagically by the URE, I suppose.

**Comment by linas** [comment]
> done somehow automagically by the URE

Figuring out stuff like that is part of the work. A possibility that has not yet been thought about would be to invent a `SetTruthValueLink` or something like that.  This is all new territory, and has been lightly explored.

**Comment by ngeiswei** [comment]
To properly deal with second order probabilities we'll probably need to introduce some special operator (like a memoized Monte Carlo simulator or something) but otherwise, yes, having the formulae encoded in pure atomese is desired, especially for meta-learning.
