### ISSUE TITLE
Atomspace cmake configuration incomplete

### ISSUE THREAD

**Issue by hanimunir** [opencog/atomspace#2236]
I am trying to install atomspace. after runing cmake .. command, i am getting this output with configuration incomplete.

-- Build type: Release
-- CogUtil version 2.0.3 found.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   serialization
--   system
--   thread
-- Boost version 105400 found.
-- CxxTest found.
-- Gearman found.
-- Guile (2.2.4 >= 2.2.2) was found.
-- Protobuf was found.
-- Python 3.4.3 interpreter found.
-- Python 2.7.6 libraries found.
-- Cython ( 0.29.1 >= 0.23.0) found.
-- Python destination dir found: /usr/local/lib/python2.7/dist-packages
-- Python install dir: /usr/local/lib/python2.7/dist-packages/opencog
-- Using nosetests executable /usr/local/bin/nosetests-2.7
-- Stack found.
-- UnixODBC was not found; ODBC persistence subsystem will not be built.
To over-ride, make sure UnixODBC_LIBRARIES and UnixODBC_INCLUDE_DIRS are set.
-- PostgresSQL 11.3 (Ubuntu 11.3-1.pgdg14.04+1) was found.
-- Valgrind Prefix: 
-- VALGRIND was found.
-- VALGRIND devel headers found.
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.0.4
-- ZeroMQ was found.
-- Setting python RPATH to /usr/local/lib/python2.7/dist-packages/opencog
CMake Error at lib/CMakeLists.txt:10 (export):
  export Unknown arguments.

CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:48 (MESSAGE):
  /usr/bin/psql: psql: FATAL: Peer authentication failed for user
  "opencog_tester"

CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:80 (MESSAGE):
  Postgres database not configured for unit tests! See the README!

-- found cython and nosetest, enabling python unit tests

Building for Ubuntu 14.04.6 LTS

The following components will be built:
-----------------------------------------------
   AtomSpace              - A weighted and typed graph database.
   Doxygen                - Code documentation.
   Gearman                - Distributed processing capability.
   Haskell bindings       - Haskell bindings.
   Python bindings        - Python (cython) bindings.
   Python tests           - Python bindings nose tests.
   Scheme bindings        - Scheme bindings and shell.
   SQL Postgres bindings  - Save/Restore of AtomSpace to Postgres database.
   ZeroMQ persistence     - Save/Restore of AtomSpace to ZeroMQ server.
   Unit tests             - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   SQL ODBC bindings      - Save/Restore of AtomSpace to database via ODBC.

-- Configuring incomplete, errors occurred!
See also "/home/hanimunir/OPENCOG/atomspace/build/CMakeFiles/CMakeOutput.log".
See also "/home/hanimunir/OPENCOG/atomspace/build/CMakeFiles/CMakeError.log".

Please help me.

**Comment by linas** [comment]
Interesting. Since you have the postgres devel environment installed, it tries to run that, but you have not actually configured.  You have three choices:
* uninstall postgres devel
* do what the warning suggests
* edit the cmake by hand, and stub out the postgres build.
I suppose we should fix this so that the postgress config problem is just a warning, not an error.

**Comment by linas** [comment]
oh sorry, ignore the last comment; the error is elsewhere:
```
CMake Error at lib/CMakeLists.txt:10 (export):
export Unknown arguments.
```

**Comment by linas** [comment]
... and that error suggests that you are using a an old version of CMake, that does not know what "export" means.

Ubuntu 14.04.6 LTS is more than 5 years old, and even Ubuntu doesn't support it any more.  Do you have access to something newer?

**Comment by linas** [comment]
The other possibility is to comment out line 10 of `lib/CMakeLists.txt` and hope for the best ...
