### ISSUE TITLE
atomspace persist error 

### ISSUE THREAD

**Issue by hanimunir** [opencog/atomspace#2237]
when runing sudo make install command for atomspace. I am getting this error.

hanimunir@ubuntu:~/OPENCOG/atomspace/build$ sudo make install
[  0%] Built target opencog_atom_types
[  0%] Linking CXX shared library libatom_types.so
[  0%] Built target atom_types
[  0%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_hanimunir_OPENCOG_atomspace_opencog_atoms_atom_types
[  0%] Linking CXX shared library libvalue.so
[  2%] Built target value
[  2%] Linking CXX shared library libtruthvalue.so
[  5%] Built target truthvalue
[  5%] Linking CXX shared library libatombase.so
[  8%] Built target atombase
[  8%] Linking CXX shared library libatomcore.so
[ 25%] Built target atomcore
[ 25%] Built target py_atomspace_header
[ 25%] Linking CXX shared library libPythonEval.so
[ 25%] Built target PythonEval
[ 25%] Linking CXX shared library libclearbox.so
[ 28%] Built target clearbox
[ 28%] Linking CXX shared library libexecution.so
[ 31%] Built target execution
[ 31%] Linking CXX shared library libquery-engine.so
[ 37%] Built target query-engine
[ 37%] Linking CXX shared library liblambda.so
[ 40%] Built target lambda
[ 40%] Linking CXX shared library libatomspace.so
[ 42%] Built target atomspace
[ 42%] Linking CXX shared library libsmob.so
[ 48%] Built target smob
[ 51%] Linking CXX shared library libexec.so
[ 51%] Built target exec
[ 51%] Linking CXX shared library libatomspaceutils.so
[ 54%] Built target atomspaceutils
[ 57%] Linking CXX shared library libdist-gearman.so
[ 57%] Built target dist-gearman
[ 57%] Linking CXX shared library libpersist.so
[ 60%] Built target persist
make[2]: *** No rule to make target '/usr/lib/libpq.so', needed by 'opencog/persist/sql/multi-driver/libpersist-pg.so'.  Stop.
CMakeFiles/Makefile2:1581: recipe for target 'opencog/persist/sql/multi-driver/CMakeFiles/persist-pg.dir/all' failed
make[1]: *** [opencog/persist/sql/multi-driver/CMakeFiles/persist-pg.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
 HELP ME.

**Comment by linas** [comment]
it appears you ran `cmake ..` and then, after that, you removed `postgres-dev`.  You need to re-run `cmake ..` again.

**Comment by linas** [comment]
at least, that is my best guess. `/usr/lib/libpq.so` is provided by postgres. If it cannot be found, it means it is not installed.  Since cmake tried to build it, it means it was installed at some earlier time.

**Comment by hanimunir** [comment]
OUTPUT of cmake..

-- Build type: Release
-- CogUtil version 2.0.3 found.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Boost version 105800 found.
-- CxxTest found.
-- Gearman found.
-- Guile (2.2.4 >= 2.2.2) was found.
-- Protobuf was found.
-- Python 3.5.2 interpreter found.
-- Python 2.7.12 libraries found.
-- Cython ( 0.29.1 >= 0.23.0) found.
-- Python destination dir found: /usr/local/lib/python2.7/dist-packages
-- Python install dir: /usr/local/lib/python2.7/dist-packages/opencog
-- Using nosetests executable /usr/local/bin/nosetests-2.7
-- Stack found.
-- UnixODBC was not found; ODBC persistence subsystem will not be built.
To over-ride, make sure UnixODBC_LIBRARIES and UnixODBC_INCLUDE_DIRS are set.
-- PostgresSQL 11.4 (Ubuntu 11.4-1.pgdg16.04+1) was found.
-- Valgrind Prefix: 
-- VALGRIND was found.
-- VALGRIND devel headers found.
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.1.4
-- ZeroMQ was found.
-- Setting python RPATH to /usr/local/lib/python2.7/dist-packages/opencog
CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:48 (MESSAGE):
  /usr/bin/psql: psql: FATAL: Peer authentication failed for user
  "opencog_tester"



CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:80 (MESSAGE):
  Postgres database not configured for unit tests! See the README!


-- found cython and nosetest, enabling python unit tests

Building for Ubuntu 16.04.6 LTS

The following components will be built:
-----------------------------------------------
   AtomSpace              - A weighted and typed graph database.
   Doxygen                - Code documentation.
   Gearman                - Distributed processing capability.
   Haskell bindings       - Haskell bindings.
   Python bindings        - Python (cython) bindings.
   Python tests           - Python bindings nose tests.
   Scheme bindings        - Scheme bindings and shell.
   SQL Postgres bindings  - Save/Restore of AtomSpace to Postgres database.
   ZeroMQ persistence     - Save/Restore of AtomSpace to ZeroMQ server.
   Unit tests             - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   SQL ODBC bindings      - Save/Restore of AtomSpace to database via ODBC.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/hanimunir/OPENCOG/atomspace/build

**Comment by linas** [comment]
This is Ubuntu? What does `dpkg -l postgresql-client`  and `libpq-dev` say? They should be installed.

**Comment by hanimunir** [comment]
Yes this is ubuntu. libpq-devis installed. 

output of dpkg -l postgresql-client:
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  postgresql-cli 11+201.pgdg1 all          front-end programs for PostgreSQL

I am new to opencog.

**Comment by linas** [comment]
you also need the postgres devel environment -- libpg-dev.

**Comment by linas** [comment]
err, libpq-dev

**Comment by hanimunir** [comment]
May be getting this error due to these warnings i  am getting during execution of cmake .. :

CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:48 (MESSAGE):
  /usr/bin/psql: psql: FATAL: Peer authentication failed for user
  "opencog_tester"



CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:80 (MESSAGE):
  Postgres database not configured for unit tests! See the README!

**Comment by linas** [comment]
No, that is a warning. It just says you haven't configured. That is different from compiling, which needs to have header files and libraries installed.

**Comment by linas** [comment]
I see you are using postgres 11 -- that is very very new. It is possible that CMake does not correctly find postgresql11 -- The cogutils script `cogutils/cmake/FindPGSQL.cmake` is the one responsible for finding it, and it should find the libraries as well.

Also, this is unlikely but you may need to run `ldconfig` as root.

YOu can verify library locations with `/sbin/ldconfig -p`  -- there should be a `libpq` listed.

**Comment by hanimunir** [comment]
Output of sudo apt-get install libpq-dev 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpq-dev is already the newest version (11.4-1.pgdg16.04+1).
The following packages were automatically installed and are no longer required:
  g++-4.8 libicu52 linux-headers-4.4.0-148 linux-headers-4.4.0-148-generic
  linux-image-4.4.0-148-generic linux-modules-4.4.0-148-generic
  linux-modules-extra-4.4.0-148-generic

**Comment by hanimunir** [comment]
output of ldconfig

/sbin/ldconfig.real: /usr/local/lib/libguile-2.2.so.1.3.1-gdb.scm is not an ELF file - it has the wrong magic bytes at the start.

**Comment by hanimunir** [comment]
libpa is listed.

       libpq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpq.so.5
	libpq.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpq.so

**Comment by hanimunir** [comment]
err. libpq is listed

**Comment by linas** [comment]
OK, do this:
```
rm -r build
mkdir build
cd buiold
cmake ..
make -j
```

I beleive that will fix it. I think that by using `sudo` you created a root-owned `Cmakefiles.txt` file containing an incorrect path to libpq.so and your later attempts to fix this failed because the file was root owned and you did not have write permissions.

**Comment by linas** [comment]
I assume this is fixed, since you seem to be running example code now.
