### ISSUE TITLE
Sporadic failure of cython BinkLink test.

### ISSUE THREAD

**Issue by ferrouswheel** [opencog/atomspace#2242]
Once in a dozen times the CythonBindLink test gives me this error:

```
137: Test command: /usr/bin/nosetests3 "-vs" "/home/joel/work/opencog/atomspace/tests/cython/bindlink/"
137: Environment variables: 
137:  PYTHONPATH=/home/joel/work/opencog/atomspace/build/opencog/cython/:/home/joel/work/opencog/atomspace/opencog/python/:/home/joel/work/opencog/atomspace/tests/cython/bindlink
137: Test timeout computed to be: 10000000
137: test_bindlink (test_bindlink.BindlinkTest) ... ok
137: test_evaluate_atom (test_bindlink.BindlinkTest) ... terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
137:   what():  boost::filesystem::directory_iterator::construct: No such file or directory: "/home/joel/work/opencog/atomspace/build/opencog/cython/test_functions"
1/1 Test #137: CythonBindlink ...................***Exception: Child aborted  0.16 sec
```

That file doesn't exist, and it's probably looking for `/home/joel/work/opencog/atomspace/tests/cython/bindlink/test_functions.py`.

I tried to catch the exception in gdb but couldn't reproduce it while attached to the process.

**Comment by linas** [comment]
Use `ulimit -a` to see your limits, and then use `ulimit -c unlimited` so that a core file is left behind. You can then aim gdb at the core file.

**Comment by linas** [comment]
be sure to set `ulimit -c 0` after you're done; otherwise your file system will fill up with random core files.

**Comment by ferrouswheel** [comment]
Ah yes, silly me for forgetting about ulimit and core dumps!

The results of a couple of `stat` calls were not being checked, which means the stat struct occasionally had semi-valid data... and this let the PythonEval module continue searching for a python module longer than it should have.
