### ISSUE TITLE
CMake Error at scm/CMakeLists.txt:1 (ADD_GUILE_MODULE):   Unknown CMake command "ADD_GUILE_MODULE".

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2267]
After cleaning out everything and a fresh install, I am now getting this error:
```
CMake Error at scm/CMakeLists.txt:1 (ADD_GUILE_MODULE):
  Unknown CMake command "ADD_GUILE_MODULE".
```

**Comment by linas** [comment]
Ahh ... apparently, the install location changed, from `${COGUTIL_DATA_DIR}` to `${CMAKE_SOURCE_DIR}` and the filename changed from `OpenCogFunctions.cmake` to `OpenCogGuile.cmake`  ... and there aren't any backwards-compat layers introduced.

@ferrouswheel you might want to consider adding backwards-compat files for this stuff, because, at some point, someone is going to try to merge the opencog repos back into the singnet repos, and things will break. 

... or alternately, you can do nothing, and let singnet break. That will force them to at least start thinking about system test procedures before they declare stable branches and start admitting unstable code.  Unfortunately, they already accept unstable code, so ... I dunno. Maybe they should just get broken anyway. Anyway .. backwards compat is usually desirable.

**Comment by linas** [comment]
Oh, hang on, the path is now literally the source dir, except that of course, the source dir has no copy whatsoever of `OpenCogMacros.cmake`  -- only the install dir has a copy of that. How is this even supposed to work?  You've got to have this file installed, so that others can use it!

**Comment by linas** [comment]
Oh. 

Apparently this file is installed into ` /usr/local/share/opencog/cmake/` .. so how is CMake supposed to find this path? It's a very opencog-specific install path...

**Comment by linas** [comment]
`CMAKE_CURRENT_LIST_DIR` is apparently the source directory, and `CMAKE_MODULE_PATH` is supposed to be a list where modules are searched (empty in my system), and `CMAKE_ROOT` is `/usr/share/cmake-3.7` 

... so I'm thinking that `OpenCogGuile.cmake` needs to be installed into `${CMAKE_ROOT}/Modules` instead of `${CMAKE_SOURCE_DIR}/opencog` ...  I'm gonna hack around this for now.  This is too confusing.

**Comment by linas** [comment]
@ferrouswheel You changed all of this up with your recent refactoring ... can you explain how CMake knows how to find the `OpenCogGuile.cmake` file? Because, for me, it is not being found; and I'm hacking my way around this by manually copying it into `/usr/share/cmake-3.7/Modules` ...

**Comment by linas** [comment]
Ugh.

After that hack, I'm now getting 
```
While compiling expression:
no code for module (opencog nlp lg-parse)
```
... was any of this stuff tested?  My fault, I should have done more through testing before merging the pull requests.   This is annoying.

**Comment by ferrouswheel** [comment]
This is the commit that renamed the file.

https://github.com/opencog/atomspace/commit/65a099d59c597c655135805376c45c8b56e883fc

**Comment by ferrouswheel** [comment]
Yes it was tested, and CI passed.

**Comment by linas** [comment]
Yeah, well, if you do a clean install on a fresh system, cmake cannot find that file. I just spun up a new container and it fails ...

**Comment by ferrouswheel** [comment]
need to be more specific about the docker image. linux distribution,
version, all the rest, ideally what dockerfile.

Amen also updated the opencog-deps image recently to ubuntu 18.04. Are you
using that or some custom build?

**Comment by linas** [comment]
I use LXC, not docker (because LXC retains state -- needed for maintaining databases for the language learning project) -- all of those containers are on ubuntu 16.04 LTC; its too much work to try  to upgrade to 18.04 right now, that's not an option.

**Comment by ferrouswheel** [comment]
So you mention singnet in a previous comment. Are you using
opecog/atomspace or singnet/atomspace ?

**Comment by linas** [comment]
The second failure is URE-related, its fixed by https://github.com/opencog/opencog/pull/3580

**Comment by linas** [comment]
The first failure is because `INCLUDE("${CMAKE_SOURCE_DIR}/cmake/OpenCogGuile.cmake")` is just wrong ... the original path, `INCLUDE("${COGUTIL_DATA_DIR}/cmake/` is correct; the core problem seems to be that `OpenCogFunctions.cmake` doesn't exist any more, and so anything that expect this fails hard.   I'll re-add that file shortly. The rest of the CMake magic I'm blowing off for now; I don't understand it, but the work-arounds seem to fix it.
`

**Comment by ferrouswheel** [comment]
OpenCogGuile *is* OpenCogFunctions.

Renamed because you suggested it.

Please don't duplicate files. Just fix the dependency.

**Comment by linas** [comment]
So pull req #2268 fixes this -- basically, a file was removed that points to the actual code.  I restored the missing file, and just stuck the redirects into it.

**Comment by linas** [comment]
> Just fix the dependency.

Can't. Where is it? who has it?  It's not like you and me are the only users of opencog on this planet .... there are others. who the heck knows what dependencies they've got where and how. In general, changes need to stay backwards-compatible precisely so that stable systems don't get broken. That's what the word "Stable" means -- things don't break after an update.

**Comment by ferrouswheel** [comment]
Wow Linas, I didn't know what stable means!

There have been plenty of backwards incompatible changes. e.g. the URE
being removed. So it seem disingenuous to pretend it matters here.

If we can force people to build an entire different repo, we can get them
to use the correct cmake include.

**Comment by linas** [comment]
Yes, I should have tested more, and yes, I should have been more careful staging the updates. It was .. unexpected.  

At this time, opencog does not have any system acceptance tests, so its hard to tell what changes might be breaking changes ... one just has to guess, and cross-fingers and hope for the best.   Judgment call. This time, we got unlucky, and missed a spot.

**Comment by linas** [comment]
Look, URE being removed was one of the breaking changes.  But Nil did a clean job of that, except for making NLP depend on URE, which was the other bug.

Don't get this attitude that since no one uses opencog, it doesn't matter how badly we fuck up.  I'm using opencog, and these changes just screwed up a bunch of systems.  Two fixes were needed, they were not that hard, but I lost a days worth of work as a result. I planned to do something else today, and now I can't.  So don't pretend that it's OK to introduce faults into a system because no one will notice them, that no one cares ... if nothing else, *I* care.

**Comment by linas** [comment]
I'm sorry we're arguing.  I apologize, I should know better.

**Comment by ferrouswheel** [comment]
Yeah sorry. The fix is reasonable. It pulls in all cmake files instead of
just guile related ones, but I guess that means a single cmake dependency
for downstream projects and is easier to maintain in future (we can call
the other files whatever we like so long as OpenCogFunctions is updated)

I will try to be aware of downstream effects in future.
