### ISSUE TITLE
Circle-CI is not running the actual code that in in the pull req

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2281]
Circle-ci appears to be testing an earlier version of the code, 
and NOT the code in the pull req!

This is easily verified: intentionally introduce a bug. Create a pull req.
The unit tests will pass. Merge the pull req.  Now create a second 
pull req, fixing that bug. The unit tests will fail!

It doesn't have to be as drastic as the above -- just find some print
statement, change what it prints.  Circle-ci will no print the changed printf,
it will print the old one.

Likewise for compiler warnings -- create some code that generates
a warning,  you won't see that warning in the current run, you'll see
it in the next run.

I've done all three of the above, unintentionally, over the last few weeks,
and was surprised by the results. But now the pattern is clear: circle-ci
is not testing the pull req; it is testing what has already been merged.

**Comment by vsbogd** [comment]
Looks like it works so after https://github.com/opencog/atomspace/pull/2266

**Comment by vsbogd** [comment]
@ngeiswei, what is the reason of replacing CircleCI `-checkout` by manual checkout?

**Comment by ngeiswei** [comment]
It seems faster but maybe I'm mistaken.

**Comment by vsbogd** [comment]
But it checkouts current `master` instead of proper branch. Do you think CircleCI checkouts history as well? Probably it is a git restriction, recently I found that it is possible to clone from branch, event from tag, but it seems it is not possible clone from commit.

**Comment by AmeBel** [comment]
Yap #2266 explains it. circle-ci `checkout` keyword will clone the branch that triggers the build. By always cloning master, pull-requests are not tested.

**Comment by ngeiswei** [comment]
OK, my bad.

**Comment by ferrouswheel** [comment]
If you're going to mess with the CI,  please at least get it reviewed by someone before merging it. Getting it wrong messes up everyone's development flow.

**Comment by linas** [comment]
So I think this has been fixed everywhere, now...
