### ISSUE TITLE
examples/atomspace/property.scm does not work as expected

### ISSUE THREAD

**Issue by astroseger** [opencog/atomspace#2298]
It seems [examples/atomspace/property.scm](https://github.com/opencog/atomspace/blob/master/examples/atomspace/property.scm) doesn't work as excepted. 

It is written that last ```cog-execute!``` should return ```0.6 as the value.``` but it returns

```
(SetLink
   (ListLink
      (ConceptNode "asdf")
      (PredicateNode "truthiness")
      (NumberNode "0.500000")
   )
   (ListLink
      (ConceptNode "qwerty")
      (PredicateNode "truthiness")
      (NumberNode "0.600000")
   )
)
```

**Comment by linas** [comment]
Fixed with #2299 

The demo code was written in an older style, with an ambiguous collection of bound vars.
It used to work, but with recent changes making bound var handling more strict, it started to fail.
So -- fix the example.

**Comment by vsbogd** [comment]
@linas, I cannot see why previous code doesn't work:
```scm
(DefineLink
	(DefinedSchema "get property")
	(Lambda
		(VariableList (Variable "$atom") (Variable "$property"))
		(Get
			(State (List (Variable "$atom") (Variable "$property"))
				(Variable "$n"))
			)))
```
and new code does:
```scm
(DefineLink
	(DefinedSchema "get property")
	(Lambda
		(VariableList (Variable "$atom") (Variable "$property"))
		(Get
			(Variable "$n")
			(State (List (Variable "$atom") (Variable "$property"))
				(Variable "$n"))
			)))
```
How adding the variable changed the thing?
Without variable `GetLink` should match only state with passed `$atom` and `$property` but it matches atom: `(ConceptNode "asdf")` which is absent in original call:
```scm
(cog-execute!
	(ExecutionOutput
		(DefinedSchema "get property")
		(List (Concept "qwerty") (Predicate "truthiness"))
	))
```
How does it happens?

**Comment by linas** [comment]
Without the explicit variable declaration,  the code assumes that the GetLink is:
```
GetLink 
    (VariableList ((Variable "$atom") (Variable "$property")) (Variable "$n"))
    (State (List (Variable "$atom") (Variable "$property")) (Variable "$n"))
```
This is alpha-equivalent to 
```
GetLink 
    (VariableList ((Variable "$a") (Variable "$b")) (Variable "$c"))
    (State (List (Variable "$a") (Variable "$b")) (Variable "$c"))
```
So the old code was equivalent to
```
(DefineLink
	(DefinedSchema "get property")
	(Lambda
		(VariableList (Variable "$atom") (Variable "$property"))
                GetLink 
                       (VariableList ((Variable "$a") (Variable "$b")) (Variable "$c"))
                      (State (List (Variable "$a") (Variable "$b")) (Variable "$c"))
```
and that is perfectly valid, it just doesn't give the answer you want.

**Comment by linas** [comment]
well, I misplaced a few parens, there, but I think you see the problem now ...

**Comment by vsbogd** [comment]
Yes, I got it. Should `Lambda` notify user that `(Variable "$atom")` and `(Variable "$property")` are not used?

**Comment by vsbogd** [comment]
Probably not very good idea, as Lambda can ignore argument and return constant.

**Comment by linas** [comment]
> Should Lambda notify user

No. There are explicit cases in PLN, (and elsewhere, e.g. the old robot code), where we have functions of three variables, but want a function of only two, so one of the variables is dropped. (This is called "projecting")

Given this and #2304 a reasonable change might be to force all variables to always be explicitly declared.  However, it might be the case that PLN likes to have implicit variables ... not sure.

I think once one get's used to the idea of bound variables, and how they differ from free variables, these mistakes become less confusing.

**Comment by ngeiswei** [comment]
PLN wouldn't have a problem with enforcing all variables to be explicitly declared/bound.
