### ISSUE TITLE
Run all examples from examples/atomspace as functional tests

### ISSUE THREAD

**Issue by astroseger** [opencog/atomspace#2300]
I would propose to automatically run all examples from [examples/atomspace](https://github.com/opencog/atomspace/tree/master/examples/atomspace) as tests. Some comments which says "something should be created" could be replaced by explicit asserts.

**Comment by linas** [comment]
Many (most?) of the examples are already in the unit tests. I would rather not do this; it clutters the examples with extra stuff.

**Comment by AmeBel** [comment]
@astroseger The work in https://github.com/singnet/opencog-tutorials was in that direction.

**Comment by linas** [comment]
Closing. Stale.
