### ISSUE TITLE
Canonical VariableList inference isn't consistent

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2329]
Consider the following

```scheme
(define X (Variable "X"))
(define Y (Variable "Y"))

(define lxy (Lambda (Inheritance (And X Y) Y)))
(define lyx (Lambda (Inheritance (And Y X) X)))
```

`lxy` and `lyx` are, to the uninformed user, alpha-equivalent. However the atomspace does not detect them as such, as it can be seen

```scheme
scheme@(guile-user)> (cog-handle lxy)
$3 = 12252611381647628989
scheme@(guile-user)> (cog-handle lyx)
$4 = 13289207854925892108
```

The reason is because the variable list is constructed according to the prefix order of variable appearances in the body of the scope. However when links are unordered, that ordering ultimately depends on the names of the variables. In my view, it's a bug, not a feature.

I think it can be fixed by modifying `VarScraper::find_vars` in `Variables.cc` to account for the unordered links, instead of blindly following the prefix order. I haven't put my finger on it yet, but I'm working on it. Any relevant comment is welcome.

**Comment by ngeiswei** [comment]
OK, I got the insight I was looking for. Variable declaration order is only relevant in so far as the structure of the body contains asymmetries. I think we can recursively construct valid orderings based on whether a link is ordered or unordered (which will determine how these orderings are combined). Then in the end if more than one ordering remain, we can pick anyone, it won't affect the behavior of the pattern anyway.

**Comment by linas** [comment]
> when links are unordered, that ordering ultimately depends on the names of the variables. In my view, it's a bug, not a feature.

Yes, that seems correct. I'm trying to think of an elegant solution now.

**Comment by linas** [comment]
> an elegant solution

Heh. No luck. Seems to require some hard-core mucking about in `ScopeLink::term_hash` which will add considerable complexity.  Are you doing this?  Maybe while mucking around, something elegant will become obvious, but maybe not.

**Comment by ngeiswei** [comment]
I don't think you need to touch `ScopeLink::term_hash`, only need to find the correct default ordering of the variables in `VarScraper::find_vars`. I think I have a solution but I need to implement it, the devil is in the details.

**Comment by linas** [comment]
There's a note in each of those routines saying that each is almost exactly a copy of the other, with some minor changes to adapt to the situation... "the details" were icky, because the solution has to be recursive...

**Comment by ngeiswei** [comment]
Oh, you're right! I was assuming that the hash was calculated based on the (inferred if absent) vardecl. So I'll be careful about that. Maybe there's a way to refactor the hash code to avoid such code structure redundancy.

**Comment by linas** [comment]
Nil,

I have just now come to the conclusion that your example is actually a user-error (and should be detected and flagged as such).  Lambdas have two distinct use cases:

* Alpha-equivalence, using merkle-tree hashing
* Beta-reduction, using `Put`.

This bug report is about the first one.  But consider now what would happen if you used that `Lambda` in a `Put`.  Consider:

```
(define A (Concept "A"))
(define B (Concept "B"))
(Put lxy  A B)
```
What, exactly, should happen? Do you expect to get `(Inheritance (And A B) A)` or might you get `(Inheritance (And A B) B)`  ?  I hope you see the problem: when you go to plug in `A` and `B`, its completely undefined as to whether `A` gets plugged in for `X`, or whether `A` gets plugged into `Y`.

I think the actual core issue is that the lambda itself is ill-defined. Note, BTW, that the else-where proposed `VariableSet` does not cure it. Consider:
```
(Put (Lambda (VariableSet X Y)   (Inheritance (And X Y) Y)) (UnorderedLink A B))
```
Even making everything unordered is still not a solution:
```
(Put (Lambda (VariableSet X Y)   (Set (And X Y) Y)) (UnorderedLink A B))
```
is also undefined.   The core issue is that the Lambda itself is undefined: we don't know how to bind to it, and, as a side effect,. we don't know how to unambiguously compute the Merkle tree hash

**Comment by linas** [comment]
BTW, there is a comment in the hash code:  https://github.com/opencog/atomspace/blob/26f73776dd689f6b6db0c7642a29c0f9f2374189/opencog/atoms/core/ScopeLink.cc#L230-L234  that is now suspect: unordered links do maintain a specific order.  Although conceptually "abelian", they are not actually so in the representation.  This means that the plus sign in 

https://github.com/opencog/atomspace/blob/26f73776dd689f6b6db0c7642a29c0f9f2374189/opencog/atoms/core/ScopeLink.cc#L248
https://github.com/opencog/atomspace/blob/26f73776dd689f6b6db0c7642a29c0f9f2374189/opencog/atoms/core/ScopeLink.cc#L254
https://github.com/opencog/atomspace/blob/26f73776dd689f6b6db0c7642a29c0f9f2374189/opencog/atoms/core/ScopeLink.cc#L259

is probably wrong.  I will open a distinct bug report for this.

**Comment by ngeiswei** [comment]
If the intent is to use `PutLink` or any operation that is vardecl-order-sensitive, then, I agree, using an empty vardecl in the scope is a bad idea, but I think the user knows that. The advantage comes when the vardecl of the scope is order insensistive, which actually happens often, BindLink, etc.
