### ISSUE TITLE
Support for vector of values of multiple type for atom valuation

### ISSUE THREAD

**Issue by Habush** [opencog/atomspace#2334]
In the current implementation of [Valuation](https://github.com/opencog/atomspace/blob/edfab55f312a2bedad9f460fd615631cfbcd7afe/opencog/atoms/base/Valuation.h), it doesn't support holding values of multiple Value types (i.e a `vector` of `ValuePtr`s). It will be more flexible to hold an array of values in addition to a single value in a Valuation of an atom.
It would be better if the type of `_values` member of `Valuation.h` is `boost::variant<ValuePtr, std::vector<ValuePtr>>` instead of `ValuePtr`.  That way, a Valuation can support both a single value and multiple values.

I can send a PR to fix this

**Comment by linas** [comment]
Look again, it's already there: its called `LinkValue`  So for example
```
(cog-set-value! 
   (Concept "foo")
   (Predicate "some key")
   (LinkValue
           (StringValue "xa" "bush" "hasn't" "read" "his" "ssb")
           (FloatValue 1 2 3 4)
           (SimpleTruthValue 0.8 0.99)))
```

**Comment by linas** [comment]
And you can nest the `LinkValue`s so you can have an arbitrary tree of them.  Closing, as I think this is what you wanted.

**Comment by linas** [comment]
There are technical reasons for doing it this way, instead of some other way, mostly having to do with performance and complexity. The technical reasons were given in another, related issue, I've lost track of it, though.
