### ISSUE TITLE
Pattern Matcher ignores TruthValues of non-virtual links but uses TruthValues of virtual Links

### ISSUE THREAD

**Issue by astroseger** [opencog/atomspace#2369]
It seems pattern matcher ignore TruthValues of non-virtual links but it does not neglect TruthValues of virtual links. If it is a desired behavior and not a bug then it is confusing for users.

An example then PM ignores truth value:
```python
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog
from opencog.bindlink import execute_atom

atomspace = AtomSpace()
initialize_opencog(atomspace)

el = EvaluationLink(PredicateNode("test"), ConceptNode("hello"))
el.tv = TruthValue(0,0)

bl = BindLink(AndLink(el), ConceptNode("success"))
execute_atom(atomspace, bl)
# SetLink will not be empty
```

**Comment by linas** [comment]
> pattern matcher ignore TruthValues of non-virtual links but it does not neglect TruthValues of virtual links. 

Yes, that is correct.

> If it is a desired behavior and not a bug then it is confusing for users.

Yes, it is confusing.  This is a historical accident, and it is baked into the code, and is kind-of needed to preserve backwards compatibilty.  Maybe this could be fixed, but it would have to be done slowly and carefully, to avoid breaking existing code.

The "new" way of doing this is to use `PresentLink`: like so:
```
el = EvaluationLink(PredicateNode("test"), ConceptNode("hello"))
el.tv = TruthValue(0,0)

bl = BindLink(AndLink(PresentLink(el)), ConceptNode("success"))
```
That way, `PresentLink` is true, if it exists in the atomspace, else it is false.  (in this example, it exists, by tautology)

The is also the `TruthValueOfLink`, which is closer to what you want: 
```
el = EvaluationLink(PredicateNode("test"), ConceptNode("hello"))
el.tv = TruthValue(0,0)

bl = BindLink(AndLink(TruthValueOfLink(el)), ConceptNode("success"))
```
I don't know if the above works. If it doesn't work, then it seems like a bug or "not yet implemented".  The `TruthValueOfLink(el))` would return `(stv 0 0)` which can then be cast to false.

**Comment by linas** [comment]
Actually, it should probably be https://wiki.opencog.org/w/StrengthOfLink and not https://wiki.opencog.org/w/TruthValueOfLink  and yes, although it should work, it does not. This is a bug (well, unimplemented feature)

The following fails; it probably should have worked:
```
(use-modules (opencog)(opencog exec))

(define el (Evaluation (Predicate "test") (Concept "hello") (stv 0 1)))

(define bl (Bind (And (StrengthOf el)) (Concept "foo")))

(cog-execute! bl)
```

**Comment by linas** [comment]
Actually, the following is even more correct, and bonus: it works!
```
(define blgt (Bind (And (GreaterThan (StrengthOf el) (Number 0.1)))
   (Concept "foo")))

(cog-execute! blgt)
```

**Comment by linas** [comment]
Closing, I think this is resolved.
