### ISSUE TITLE
Introduce Value::is_unordered_link

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2423]
Based on that comment

https://github.com/opencog/atomspace/pull/2421#discussion_r354794102

I think it would be wise to introduce a

```C++
bool Value::is_unordered_link() const;
```

method, and use it instead of instances such as

https://github.com/opencog/atomspace/blob/2bca608896ff9c93492754842eb1dd8aad8b2380/opencog/atoms/core/FreeLink.cc#L60

there seems to be about a dozen instances of such (including one in the ure repo), which I think is large enough to justify it.

Let me know what you think.

**Comment by linas** [comment]
Sure I think its harmless. Maybe even a tiny performance boost.

**Comment by ngeiswei** [comment]
Why would it bring a (tiny) performance boost?

**Comment by ngeiswei** [comment]
Oh, do you mean to implement it as

```c++
virtual bool UnorderedLink::is_unordered_link() const
{
	return true;
}
```

?

**Comment by ngeiswei** [comment]
Is that what you have in mind

https://github.com/ngeiswei/atomspace/commit/1563b2704c28b84e2f7318091a32884e954f76e3

?

**Comment by linas** [comment]
yes!

**Comment by linas** [comment]
The `if(nameserver().isA(get_type()..` is mostly a lookup in the atom-types array.  I think the compiler inlines most of the function calls, so what's left is just that array lookup, and a possible dcache miss or dtlb miss from the array lookup. 

By contrast, the `virtual bool iswhatever()` is a function pointer call through a vtable that cannot be inlined, so its probably more instructions. But maybe less dcache misses, becuase no more array lookup. But then, maybe icache misses. But the vtable is smaller than the atom-types table, so .... 

I dunno its hard to guess what the compiler might do for these two cases, and its hard to guess how many cache misses might result.  Its a toss-up.

**Comment by linas** [comment]
Actually, if the compiler is really smart, it can just place the return code from `is_unordere_link()` in the vtable, and then just look that up, without any function calls at all!  This would require only a small amount of vtable magic, so its possible that modern compilers already do this ...  I mean, if they can already do link-time-optimizations, this is surely an easier trick ...

**Comment by linas** [comment]
BTW, if you are looking for performance optimizations, I just opened #2429 describing a deeply-rooted one that could make a fairly large difference.

**Comment by vsbogd** [comment]
Looks like in most of the `isA(type, UNORDERED_LINK)` usages it is clear from the context that `type` is a subtype of the `Link`. Would adding `is_unordered_link` into `Link` class be enough? And it would affect less number of classes.

**Comment by ngeiswei** [comment]
@vsbogd, the problem with adding `is_unordered_link` to `Link` only is that it then cannot be called from a `Handle`, which is the more frequent use.

**Comment by vsbogd** [comment]
@ngeiswei, It it possible using `is_unordered_link(Handle)` or `Handle::is_unordered_link` then. It may be as simple as:
```
return LinkCast(handle)->is_unordered_link();
```

**Comment by linas** [comment]
LinkCast is hugely inefficient. Any of the *Cast methods are dozens of instructions, lord knows how many cache misses.  They're terrible.

**Comment by ngeiswei** [comment]
I think issue https://github.com/opencog/atomspace/issues/2423 fixes that so I'm closing.
