### ISSUE TITLE
pass atomspace to grounded schema and predicate functions

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2430]
Passing atomspace in GroundedSchema and GroundedPredicate callback functions would allow us(with method from https://github.com/opencog/atomspace/issues/2428)  to get rid of global variables used in schema and python bindings.

This can be implemented for example with adding new syntax for GroundedSchemaNode:
GroundedSchemaNode("scm(atomspace): my_callback")

**Comment by linas** [comment]
It's already possible in scheme, so no changes need to be done. This is a python-only issue.
