### ISSUE TITLE
Why PGSQL is marked required?

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2431]
I see that PGSQL package is marked required in `opencog/atomspace` `CMakeLists.txt`:
https://github.com/opencog/atomspace/blob/89f2083fa7b85c0d757c55767a07cd31ab74afa3/CMakeLists.txt#L237

At the same time `atomspace` library can be built without PGSQL and sometimes persistent layer is not required and it is much simpler to build without it (I tried this while compiling `atomspace` for the RaspberryPi). Is it safe to remove `requried` from the `find_package`?

**Comment by linas** [comment]
Dunno. But there's not very many useful things you can do without it.   So maybe not exactly "required to build", but "pretty useless without it".

**Comment by vsbogd** [comment]
In my case URE rules are kept in the code and on each iteration new information is added into a child atomspace, an inference is performed and then the child atomspace is deleted so the persistence is not required.

**Comment by linas** [comment]
and what happens to the inference?  It's converted to something and .. discarded?

**Comment by vsbogd** [comment]
Results of the inference are demonstrated on UI, it is a result of frame analysis and in simple case it is not required to store them as part of the knowledge base. In more complex cases for sure some results can be kept into knowledge base to improve next inference results and so on.

**Comment by linas** [comment]
I mean, I guess you can change it from `required` to `optional` if it's really that important -- but making it required is more of a political statement - a kind of 'pay attention, here's where the action is' kind of statement.

**Comment by linas** [comment]
Closing; some recent pull req made pgsql optional.
