### ISSUE TITLE
Compilation error on Mac OS

### ISSUE THREAD

**Issue by Habush** [opencog/atomspace#2465]
While compiling the atomspace locally on my Mac OS (10.14.6), I get the follwing error:

> /Users/xabush/opencog/atomspace/opencog/cython/PythonEval.cc:1389:14: error: use of
>       undeclared identifier 'pipe2'
>     int rc = pipe2(pipefd, 0);  // O_NONBLOCK);

It looks like `pipe2` isn't available in OS X. is there a way to fix this?

**Comment by linas** [comment]
I think you need to install the unix-compatibility layers for macos. 

Anyway, you're the first person in maybe a decade who's tried opencog on macos, so if this is the only problem .. that's actually marvelous.  Submit pull reqs as needed for anything else you trip across.

**Comment by vsbogd** [comment]
For this specific line:
```C++
int rc = pipe2(pipefd, 0);  // O_NONBLOCK);
```
replacing it by:
```C++
int rc = pipe(pipefd);
```
Should solve the compilation issue.

**Comment by Habush** [comment]
@vsbogd suggestion fixes the issue
