### ISSUE TITLE
Variables::extend bug/miss-behavior

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2485]
`Variables::extend` does not work properly when the same variable has 2 different types. Consider for instance the following unit test

https://github.com/opencog/atomspace/blob/950762c2c55498050a2d2632da24d73065b4bfbb/tests/atoms/core/VariablesUTest.cxxtest#L83-L108

Since the `(TypedVariable <var> (Type <type-name>))` construct checks the exact type, it should not consider the type intersection according to the hierarchy of types but rather type equality.

The culprit code is

https://github.com/opencog/atomspace/blob/950762c2c55498050a2d2632da24d73065b4bfbb/opencog/atoms/core/Variables.cc#L1269-L1279

But ultimately a correct fix should take into account the cases where `TypeInhLink` is used, which should then consider type intersection according to the type hierarchy.

Also, it is to be noted that the default type of an undeclared variable is

```
TypeInhNode "Atom"
```

not

```
TypeNode "Atom"
```

**Comment by linas** [comment]
seems like a correct analysis. Patch forthcoming?

**Comment by ngeiswei** [comment]
I think @kasimebrahim is looking into it.

**Comment by linas** [comment]
So is #2496 a complete fix for this issue? Can this be closed, or is there more?

**Comment by ngeiswei** [comment]
I'm closing, @kasimebrahim feel free to re-open if we've forgotten something.
