### ISSUE TITLE
AtomSpace readonly scheme bug

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2556]
The following manages to modify the TV of an atom in a readonly atomspace

```
(Concept "A")
(cog-atomspace-ro!)
(Concept "A" (stv 0.1 0.1))
```

I'm almost sure it is a bug. I might look at it or, in the meantime, use `cog-set-tv!` which behaves as expected.

**Comment by linas** [comment]
sounds like a bug. Presumably even a simple bug.

So, out of curiosity, where are you using this? the ro atomspace were created for agi-bio, but I don't think they every used them.

**Comment by linas** [comment]
The bug is here: `SchemeSmobNew.cc` calls `h->setTruthValue(tv);` at line 410 and 529 and maybe other places.  It should be calling `AtomSpace::set_truthvalue()` instead.   Its past my bedtime so I won't fix now... have at it if you want.

**Comment by ngeiswei** [comment]
> It should be calling AtomSpace::set_truthvalue() instead

Thanks, I'll fix it.

> So, out of curiosity, where are you using this?

I'm testing it with the pattern miner, like to make sure memoized info (stored as Value) do not affect the user's kb (in the context of agi-bio actually).

**Comment by linas** [comment]
I was thinking, a better API might be to have a COW copy-on-write bit in temp atomspaces. So if you use a temp atomspace, and change the truth-value then the atom is copied, and the changed TV is made only in the temp atomspace.  So, like a read-only parent, but instead a "sanitary" temp atomspace.

**Comment by linas** [comment]
@ngeiswei Please take a look at #2559 -- it might accomplish what 
you want with read-only, except with an easier-to-use API.  (i.e. you
don't have to actually set the parent to be read-only -- it is still protected.)

**Comment by ngeiswei** [comment]
Wow, yes much simpler in my case, will use it instead when I get a chance.

**Comment by linas** [comment]
Also - FYI its turned on by default in the pattern matcher
