### ISSUE TITLE
Create ContainerLink

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2562]
As described in https://wiki.opencog.org/w/ContainerLink and based on the requirements raised in MOZI-AI/knowledge-import#10

**Comment by ngeiswei** [comment]
@linas I think there are variable names inconsistencies in

https://wiki.opencog.org/w/ContainerLink#Multiple_subcomponents.2C_again
https://wiki.opencog.org/w/ContainerLink#User_callbacks_via_GPN.27s

**Comment by ngeiswei** [comment]
@linas I think there are variable names inconsistencies in

https://wiki.opencog.org/w/ContainerLink#Multiple_subcomponents.2C_again
https://wiki.opencog.org/w/ContainerLink#User_callbacks_via_GPN.27s

**Comment by linas** [comment]
> variable names inconsistencies 

Yep. Now fixed.  (This means you read this carefully; the fix is exactly what you might have guessed it should be.)

**Comment by noskill** [comment]
Looks good, but what does "How to specify differences in heights? " refers to?

**Comment by linas** [comment]
> How to specify differences in heights

Say you wanted only the containers of `(Concept "A")` that are two levels deep, but not one or three. So the this would match:
```
(Evaluation (Predicate "foo") (List (Concept "A")))
```
but these would not:
```
   (Member (Concept "A") (Concept 'stuff"))    -- only one deep
```
and
```
(Evaluation (Predicate "foo") (List (Set (Concept "A")))) ; three deep
```
To fix this, I need a 
```
    (HeightLink (Variable "X") (Concept "A"))
```
which returns `NumberNode` 2 1 and 3 for the above cases.  Not sure what to call it: HieghtLink" or "GradeLink" or "AboveLink" or something like that. Ideas?

**Comment by noskill** [comment]
I see, that is depth of a tree. So for general graph it is not defined:

```
List(A, B), List(B, C), List(C, A)
```

**Comment by noskill** [comment]
For trees i found it is quite convenient in prolog. In prolog you can compute some number, like Depth, on each step of tree traversal and say that tree matches if Depth < 5 or something like that.

**Comment by noskill** [comment]
I discovered for myself that there exist some theory and libraries for graph rewriting, like graph grammars. 

https://en.wikipedia.org/wiki/Graph_rewriting#References

Might be useful for atomese validation, i still need to gain better knowledge of it.

**Comment by linas** [comment]
OK, I'm gonna wander wildly off-topic.

> not defined: `List(A, B), List(B, C)`

You're welcome to propose a new link or node type that does this :-)  Nothing in the atomspace chains together "bare" list-links.  However, (there's a bunch of howevers) First: "we" i.e. Ben, more than a decade ago, when he wrote the early opencog books,  likes his links "named" and thus `(Evaluation (Predicate "some name")   (List A B))` and PLN was the thing that was going to chain these together.

Since then, we now have three/four ways of chaining. PLN turned into URE and is a classic backward/forward chainer.  PLN is "just" a set of rules computing truth values on the chain (instead of crisp true/false of prolog.)  Next .. OpenPsi is a kind-of forward-chainer that tries to deal with combinatoric explosion.  And my very favorite, highly recommended: https://github.com/opencog/generate which chains together not single edges, but arbitrary "jigsaw puzzle pieces".

> https://en.wikipedia.org/wiki/Graph_rewriting

The problem is the AtomSpace, and Atomese is maybe ten years older than that wikipedia article ... so we had to invent stuff "on our own", before anyone else was doing this stuff.  This means that some things are weird or inefficient or RAM-wasteful, because the path was quite confusing with unexpected turns in it.

> Might be useful for atomese validation, i still need to gain better knowledge of it.

Please do this. Someone needs to do this. I would, except that I kind-of go crazy when I read that stuff; I've been doing this too long and get frustrated whenever I see inferior solutions, and worse: they become popular. So someone needs to go over this stuff, and digest it, and bring it in contact with opencog.  ... 

Open a new issue for each and every new idea you get.  I'm sure I'll happily tell you how idiotic those ideas are, but if you keep arguing, maybe something good or great can come out of it.  You've done this before.

**Comment by linas** [comment]
Closing. Pull req #2601 provides the last of the implementation. I'm burnt out on this.
