### ISSUE TITLE
Multiple atomspaces & incoming set oddity

### ISSUE THREAD

**Issue by williampma** [opencog/atomspace#259]
Some oddity I found with multiple atomspaces
```
	AtomSpace as;
	AtomSpace ex(&as);

	Handle a1 = as.add_atom(createNode(CONCEPT_NODE, "test"));
	Handle e1 = ex.add_atom(createLink(LIST_LINK, a1));

	std::cout << a1->getIncomingSet().size() << std::endl;
```
it will print "1".  ie. codes that are working solely in the main atomspace will still see the stuff in the expansion.

For example, even if I created a PatternMatcherCallback on `as`, it will still returns some results that are in `ex` because it will follow the incoming set of a constant in `as` and found the grounding in `ex`.

Not a big issue just thought I would point it out.

**Comment by linas** [comment]
The getIncomingSet call will return atoms, even if they are not in any atomspace at all.   For example:
```
   Handle a1 = createNode(CONCEPT_NODE, "test");
   Handle e1 = createLink(LIST_LINK, a1);

    std::cout << a1->getIncomingSet().size() << std::endl;
```
The concept of "incoming set" is independent of atomspace membership; they are not connected with each other in any way.

**Comment by linas** [comment]
... so, if you wanted to only pattrn match to atoms that belong to a specific atomspace, you have two choices:
1) alter one of the callbacks to check atomspace membership.
2) Create a new  GPN that does the check.  e.g.
```
EvaluationLink
     GroundedPredicateNode "scm: check_atomspace_membership"
     ListLink
          VariableNode "$X"

(define (check_atomspace atom)  (if (eq? (cog-atomspace atom) myspace) (stv 1 0) (stv 0 0))) 
```

Solution 2 is slower but .. better, because it does not require constructing a new pattern matcher callback.

**Comment by linas** [comment]
closing, seems like there's nothing to do here.
