### ISSUE TITLE
importing AtomSpace or types throws error (python 2)

### ISSUE THREAD

**Issue by einalex** [opencog/atomspace#2628]
```
Traceback (most recent call last):
  File "/home/rasberry/catkin_ws/src/rasberry_hri/scripts/experimenter_node", line 7, in <module>
    from experiments.experimenter import Experimenter
  File "/home/rasberry/catkin_ws/src/rasberry_hri/src/experiments/experimenter.py", line 5, in <module>
    from experiment import Experiment
  File "/home/rasberry/catkin_ws/src/rasberry_hri/src/experiments/experiment.py", line 22, in <module>
    from utils import start_process
  File "/home/rasberry/catkin_ws/src/rasberry_hri/src/utils.py", line 12, in <module>
    from opencog.atomspace import AtomSpace, types, TruthValue
  File "opencog/nameserver.pyx", line 59, in init opencog.atomspace (/home/rasberry/git/atomspace/build/opencog/cython/opencog/atomspace.cpp:15789)
TypeError: type() argument 1 must be string, not unicode
```

**Comment by linas** [comment]
Can you port your code to python3?

**Comment by einalex** [comment]
Porting isn't the problem unfortunately, that'd be easy.
Our platform runs on ros kinetic and there are some more python 2 dependencies. So I can't move forward.

**Comment by linas** [comment]
The cython maintainers/champions are  ... unresponsive... so I'm going to do some guess-work. Does the patch below fix it for you?
```
--- a/opencog/cython/opencog/nameserver.pyx
+++ b/opencog/cython/opencog/nameserver.pyx
@@ -56,7 +56,7 @@ cdef generate_type_module():
     types["NO_TYPE"] = NOTYPE
     return types
 
-types = type('atom_types', (), generate_type_module())
+types = type("atom_types", (), generate_type_module())
 
 #This function is for refreshing new types
 #ex. When you import a cython module which include non-core atom ty
```
I've got some other ideas, but try that first.

**Comment by linas** [comment]
This might work:
```
--- a/opencog/cython/opencog/CMakeLists.txt
+++ b/opencog/cython/opencog/CMakeLists.txt
@@ -21,7 +21,7 @@ INCLUDE_DIRECTORIES(
        ${CMAKE_CURRENT_BINARY_DIR}
 )
 
-SET(CYTHON_FLAGS "-3" "-f")
+SET(CYTHON_FLAGS "-2" "-f")
 
 # Use this as a guide:
 # https://github.com/OpenKinect/libfreenect/blob/master/wrappers/python/CMakeLists.txt
```

**Comment by einalex** [comment]
I'll give your first suggestion a try.
I'm compiling the whole opencog stack with python 3 disabled, because for some reason if python 3 is enabled, it doesn't produce python 2 bindings.

**Comment by einalex** [comment]
hrm, that didn't work unfortunately.

**Comment by linas** [comment]
Pull req #1519 did most of the porting from python2 to python3 and after that, both variants worked.  For a while the unit tests tried to test both versions, but that was klunky and got disabled.  I reviewed the contents of #1519, and it looks like  the line `types = type('atom_types', (), generate_type_module())` was unchanged since the dawn of time, so the error message `type() argument 1 must be string, not unicode` is somehow misleading. Which is why I'm thinking the CMakefile diff might do the trick.

**Comment by linas** [comment]
I found this comment:
```
# Search for Python3 first, and use that, if found. Else use Python2.
# To use Python2 only from the build directory run the following
# rm CMakeCache.txt && cmake -DCMAKE_DISABLE_FIND_PACKAGE_Python3Interp=TRUE ..
```

**Comment by einalex** [comment]
yes, I do that :/
the error also doesn't make a lot of sense to me as the first parameter is defined as 'bla' python2 by default already interprets that as a str, not unicode.

**Comment by linas** [comment]
So if you `make -DCMAKE_DISABLE_FIND_PACKAGE_Python3Interp=TRUE ..` and also change `SET(CYTHON_FLAGS "-2" "-f")` doesn't that fix things?

**Comment by einalex** [comment]
If I set it explicitely to b'atom_types' it works. So my guess is this is a cython (not python) issue and someone has globally set all strings to be interpreted as unicode regardless of the python version being used.

**Comment by einalex** [comment]
haven't tried the CYTHON_FLAGS yet. will do so now

**Comment by einalex** [comment]
setting CYTHON_FLAGS doesn't work.

**Comment by linas** [comment]
> setting CYTHON_FLAGS doesn't help.

Something still doesn't make sense, because this used to work in python2 without the `b` ...

Anyway, I can change it to `b'atom_types'` but causes the (python3) unit tests to fail.  So the one remaining trick is to find how to conditionally compile based on the version ...

**Comment by linas** [comment]
What if you change it to
```
types = type(str(b'atom_types'), (), generate_type_module())
```

**Comment by einalex** [comment]
that gives me the initial error, as expected

**Comment by einalex** [comment]
changing that part of the code doesn't look like a viable solution anyway. if I fix it I find the next string/unicode problem in 
```
Traceback (most recent call last):
  File "/home/rasberry/catkin_ws/src/rasberry_hri/scripts/scheduler_node", line 11, in <module>
    from bdi.scheduler import Scheduler
  File "/home/rasberry/catkin_ws/src/rasberry_hri/src/bdi/scheduler.py", line 30, in <module>
    log.set_level("DEBUG")
  File "opencog/logger.pyx", line 85, in opencog.logger.Logger.set_level (/home/rasberry/git/atomspace/build/opencog/cython/opencog/logger.cpp:1501)
```
There are likely to be a lot of them.

**Comment by linas** [comment]
I'm stumped. It used to work, for python2, and although there have been many changes, I don't recall seeing anything that would have caused this. There is no global setting that would cause this. Therefor, I'm thinking that its cython itself that is causing this.

Do you know `git bisect`? I sort-of hate to burden you with this,  cause its incredibly tedious and boring. but if you go back ... say two years, does it work then? If so, then its NOT cython, but something in our code-base. After that `git bisect` will automate finding which change caused the trouble.  If you do this, then starting at 55f6621b9deb202854da574945fb59ee339bc043 is a good place to start, its before the first set of python3 work was started.

**Comment by linas** [comment]
Be sure to remove auto-generated files in the build dir, just in case you are running python2 on files that were autogened by python3.

**Comment by einalex** [comment]
yeah, that did the trick...although I don't know why.
I tend to run `cmake ..` in the already used build dir but that does report it is using python2 and I can't import any python3 opencog modules since they aren't built.

**Comment by einalex** [comment]
This is caused by setting the language level to 3 in line 24 here.
https://github.com/opencog/atomspace/commit/a8a283c43edcad4bfbddbd6ed4c3aa13658ff7a7#diff-b2a0056d82a840e582eaca71a428b0f3R24
If this was set dependent on which python version is used to compile it, or dependent on the state of the `CMAKE_DISABLE_FIND_PACKAGE_Python3Interp` variable, that'd solve the problem.

**Comment by linas** [comment]
How about this:
```
IF (2.7.0 VERSION_LESS ${PYTHON_VERSION_STRING})
   SET(CYTHON_FLAGS "-2" "-f")
ELSE
   SET(CYTHON_FLAGS "-3" "-f")
ENDIF
```

**Comment by einalex** [comment]
I'm not cmake expert, but this reads like if (2.7.0 < version_the_user_has) to me, which would be wrong.
This looks like it makes more sense:
```
IF (${PYTHON_VERSION_STRING} VERSION_LESS 3.0.0)
   SET(CYTHON_FLAGS "-2" "-f")
ELSE
   SET(CYTHON_FLAGS "-3" "-f")
ENDIF
```

but again, not a cmake expert.

I just commented out the line, which should produce default behavior in both the 2 and 3 cases.
It certainly works under py2

**Comment by linas** [comment]
Yes... silly me. There also is no `PYTHON_VERSION_STRING` for some reason. I'll get it working for python 3 but will ask you to double-check.

**Comment by linas** [comment]
> which should produce default behavior in both the 2 and 3 cases.

Apparently that is not true, cython defaults to version 2, even if version-3 python libs are installed. Or at least, that was how we arrived at the patch from @ntoxeg ...

**Comment by einalex** [comment]
Strange, their documentation says otherwise...maybe they changed it at a later version.

**Comment by linas** [comment]
which documentation?

**Comment by einalex** [comment]
https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#python-string-types-in-cython-code

Ah, I misread. It doesn't set the compile option dynamically. That's the issue. Well, we can fix that :)

**Comment by ntoxeg** [comment]
@einalex Switching to Python 2 mode will simply not work - these two versions are not compatible (different syntax, etc.).

As Python 2 is no longer officially supported by The Python Software Foundation I'd recommend porting any remaining Python 2 code to Python 3 ASAP.
Otherwise, you will have to use an older checkout of AtomSpace (before the transition happened).

**Comment by linas** [comment]
@notexg it appears that the atomspace supports both python2 and python3, once the patch in #2646 is applied.

The cor issue is that in the robotics world, ROS Kinetic was a huge success, and robots all over the planet run on Kinetic, which requires python 2.  Now, of course, ROS has had half a dozen or maybe a dozen new releases since Kinetic, .. which was released .. 5-6 years ago?  But there was something very special about Kinetic, and much of the robotics world continues to run on it. Just saying.

Supporting python2 in the atomspace is currently "easy", so if we don't break it, it should work.

**Comment by einalex** [comment]
@ntoxeg It is very possible to write code that works under both versions. 
If it were up to me, I wouldn't have started with python2 to begin with, but I'm not going to fight against the incompatibility problems of 10 different software projects I'm forced to use, some of which don't even have a python 3 version of their code.

Sometimes, "just moving on" doesn't work.

**Comment by linas** [comment]
Please close if #2646 works

**Comment by einalex** [comment]
works.
