### ISSUE TITLE
Python3 style @property decorators work under Python2 only for new-style classes.

### ISSUE THREAD

**Issue by einalex** [opencog/atomspace#2643]
So can we derive all of the top-level classes from `object`?
Like here for example
https://github.com/opencog/atomspace/blob/master/opencog/cython/opencog/value.pyx#L19

Then we can use the Python3 style `@property` decorators under Python2 as well and we don't lose the ability to set the values.

That'd be awesome :)

**Comment by vsbogd** [comment]
I don't see any blockers for that.

**Comment by einalex** [comment]
I just found out that cdef classes can't inherit from python classes, Value is a cdef class, so we have to instead make the child classes inherit from the cdef classes as well as from object.

**Comment by vsbogd** [comment]
Ok, but it probably will not solve the problem as `Value` also have properties.

**Comment by einalex** [comment]
https://groups.google.com/forum/#!searchin/cython-users/TypeError$3A$20$27property$27$20object$20is$20not$20callable%7Csort:date/cython-users/eYZDaXdTiis/rJ43TePeDAAJ

it looks like the version of Cython we're using might not support the .setter version of @property

**Comment by einalex** [comment]
yes, it was added in 0.24
https://cython.readthedocs.io/en/latest/src/changes.html#id105

**Comment by vsbogd** [comment]
Latest opencog version uses Cython 0.29.17

**Comment by einalex** [comment]
-- Found Cython: /usr/bin/cython (Required is at least version "0.23.0") 
-- Cython ( 0.23.4 >= 0.23.0) found.

doesn't look like it was added to to the requirements

**Comment by linas** [comment]
> -- Found Cython: /usr/bin/cython (Required is at least version "0.23.0")
> -- Cython ( 0.23.4 >= 0.23.0) found.

If we change it to 0.29, then you will be screwed @einalex ... so are you sure you want this?

If you do upgrade, then is that enough to solve this issue, or does something more need to be done?

**Comment by einalex** [comment]
No, I upgraded to 0.29 using pip3. Works fine. I'll revert my added object inheritance and check if it works without it.

**Comment by einalex** [comment]
Works. Updating the required cython version to 0.29 fixes this.

**Comment by linas** [comment]
fixed in opencog/cogutil#229
