### ISSUE TITLE
Constant Clauses still mis-handled.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#2651]
Constant clauses are mis-tested and mis-handled.

**Comment by linas** [comment]
This:
```
(use-modules (opencog) (opencog exec))
(cog-execute!
   (Bind
      (And
         (Inheritance (Concept "A") (Concept "B"))
         (Concept "A"))
      (Concept "C")))
```
should yield the empty set. That is because after the constants are removed, there is nothing left, and so nothing is found, and so there is nothing to be re-written. This is currently failing because the pattern is accidentally being spilt into multiple components, which should not happen.

**Comment by linas** [comment]
Ahhh .. this is actually a left-over side-effect from #2649 ... the code was assuming that `(Inheritance (Concept "A") (Concept "B"))` is evaluatable, so it was evaluating the outer-most `And` clause. The `And` was coded as `result=true; while (result) { result = result and term; }` so that  empty `And` is evaluating to true.  That seems .. wrong ...

**Comment by linas** [comment]
Ugh. Trying to fix this opens a can of worms. I don't see the point of trying to "fix" this, its a weird corner case. Closing.

**Comment by ngeiswei** [comment]
> so that empty And is evaluating to true. That seems .. wrong ...

Well, empty And evaluating to true is consistent with classical logic (because true is the neutral element of And), so I think it's right. Likewise, an empty Or should evaluate to false.

**Comment by linas** [comment]
Yeah, but in all other cases, when the search finds nothing, there are no results to report... that is, the empty set  is reported. Yet here ... no search is performed, and the result of not searching is  .. something ... instead of nothing.
