### ISSUE TITLE
Cyclic dependency truthvalue -> execution -> atombase -> truthvalue

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2689]
After https://github.com/opencog/atomspace/commit/5b1642d8edb869c3d21182b40859f23a78035204 `libtruthvalue` depends on `EvaluationLink` which is part of the `libexecution`. This dependency introduces cyclic dependency `truthvalue -> execution -> atombase -> truthvalue`.

**Comment by linas** [comment]
There are half-a-dozen or a dozen of these circular dependencies. ... at the moment, they are harmless.

**Comment by linas** [comment]
This may have been fixed in  #2738 There are probably still some other cyclic dependencies, but that pull req should have un-stippered one of the more difficult ones.  Closing this issue, as I I think the usual linking procedures resolve this.

**Comment by Habush** [comment]
I had similar linker issue when trying to load `bioscience` python module. I was using `gcc` version 7.7. Switching to `clang` version 10.0 fixed the cyclic dependency issue.
