### ISSUE TITLE
Type checking in Variable substitution failed.

### ISSUE THREAD

**Issue by kasimebrahim** [opencog/atomspace#2717]
Given this variable declaration and pattern,
<pre>
Handle vdecl = 
(VariableSet
  (TypedVariableLink
    (VariableNode "$a")
    (TypeNode "ConceptNode")
  )
  (TypedVariableLink
    (VariableNode "$b")
    (TypeNode "ConceptNode")
  )
)

Handle func =
(PresentLink
  (InheritanceLink
    (VariableNode "$a")
    (VariableNode "$b")
  )
)
</pre>

this variable substitution map works fine as expected
<pre>
HandleMap vm =
 {{(VARIABLE_NODE, "$a"), (CONCEPT_NODE, "A")},
  {(VARIABLE_NODE, "$b"), (CONCEPT_NODE, "B")}};

Handle res = vars.substitute(func, vm);

res = (PresentLink
  (InheritanceLink
    (ConceptNode "A")
    (ConceptNode "B")
  )
) 
</pre>

But removing the second pair from the map, `HandleMap vm = {{(VARIABLE_NODE, "$a"), (CONCEPT_NODE, "A")}}` fails.
The problem is `FreeVariables::make_sequence` generates a trivial mapping[sort of] for the missing variable $b `{{$b, $b}}`. Then the type checking in `Handle Variables::substitute(const Handle& func, const HandleSeq& args, bool silent)` fails because `$b` doesn't pass the type restriction in `vdecl`.

All my solutions seemed to me a bit hacky, What do you think is the best way to fix this?
By the way I needed this to support types in pattern mining.

**Comment by linas** [comment]
I'm not sure. If you just have a map, and don't care about type-checking, then just call
```
Replacement::replace_nocheck(const Handle&, const HandleMap&);
```
This is a static method, (no instance needed) it will  just plug whatever is in the map into the first arg. The `vars.substitute()` ends up calling this function, after doing type-checking.

**Comment by linas** [comment]
Its a bit of a mess, but the inhertance hierarch is `struct Variables : public FreeVariables` and so `struct Variables` adds a bunch of variable-type utlities to `FreeVariables` -- this includes substituion with type checking.

Next, `struct FreeVariables : Replacement` and so `FreeVariables` adds a bunch of utllities for finding variables and it also provides `substitute_nocheck` for substitution without any checking.

Finally `struct Replacement` inherits from nothing at all, it just does substitution, without checking, but it does honor quotes and scoped things.

**Comment by linas** [comment]
Oh. Heh. I just read the code, and re-read what you wrote, and so you already know all this stuff. I'm pretty sure that using the raw `Replacement::replace_nocheck()` will solve your problem.

**Comment by linas** [comment]
Closing, I assume this is now not-a-bug; please reopen if the suggestions didn't work.
