### ISSUE TITLE
Syntax error while parsing Atomese that contains custom atom types

### ISSUE THREAD

**Issue by Habush** [opencog/atomspace#2751]
I am using the [AtomSexpr](https://github.com/opencog/atomspace/blob/master/opencog/persist/sexpr/Sexpr.h) parser to parse an Atomese file containing custom atom types define [here](https://github.com/opencog/agi-bio/blob/master/bioscience/types/atom_types.script).  I am importing the `<opencog/bioscience/types/atom_types>` header and linking the `bioscience-types` library, however the parser fails with the following error:

> what():  Error at line 5 unknown Atom type: GeneNode (/home/hedra/OpenCOg/atomspace/opencog/persist/sexpr/AtomSexpr.cc:104)
Aborted (core dumped)

I thought by including the `atom_types` header, it will add the new types to the `NameServer` and will recognize the new types. You can find the code I am using [here](https://github.com/Habush/atomspace-rpc/blob/master/src/manager/AtomSpaceManager.cpp) which is part of [atomspace-rpc](https://github.com/Habush/atomspace-rpc)

How can I fix this or what am I missing?

**Comment by linas** [comment]
Yes, this should work. It should not require adding the header file; the nameserver should be able to recognize the names without the header file.

I think that what is happening is that the library containing the bio-science types is not being loaded.  There are several ways to add new types to the nameserver; the default is simply to link to the library that defines them. The library constructor will then run, and the types get automatically loaded.  

In short -- it should be enough to just link to `libbioscience-types.so` ...

... except you say you already tried that? Hmmm. So, add `${NO_AS_NEEDED}` to the CMakefile, right before linking bioscience-types.  It should be predefined ... if not then add  `SET(NO_AS_NEEDED "-Wl,--no-as-needed")`  to the CMakefile.  Apple may have some special ideas about this flag.

The long explanation is this:  `./bioscience/types/BioScienceTypes.cc` says `#define INITNAME bioscience_types_init` and if you look at `#include <opencog/atoms/atom_types/atom_types.cc>` you see 
```
extern "C" {
// Calling this forces this shared-lib to load, thus calling the
// constructor above, thus causing the atom types to be loaded into
// the atomspace.
void INITNAME(void)
{
   /* No-op */
}
```
and the constructor it is talking about is just above: `static __attribute__ ((constructor)) void init(void)`

This is the constructor that runs when the library is loaded, and it adds all the types to the nameserver. You can put a `printf` in it, and when everything works, the printf should be printed. 

But sometimes, the linker decides that the library is not needed, and so the types never load ... The `-Wl,--no-as-needed` flag forces the linker to load the library anyway, no matter what.  That should fix this.

The other work-around, kind-of ugly, is to explicitly call `bioscience_types_init()` early on, before you start using the nameserver.

**Comment by Habush** [comment]
Thanks @linas . Adding `${NO_AS_NEEDED}` fixed the issue. 

For future reference here is the excerpt of the CMakefile:

```
include(OpenCogGccOptions) ## This is where NO_AS_NEEDED is defined
target_link_libraries(atom_server
            ${NO_AS_NEEDED}
            ${BIOSCIENCE_LIB})
```
