### ISSUE TITLE
How to rename a node name

### ISSUE THREAD

**Issue by tanksha** [opencog/atomspace#2770]
Is there a way to update a node name keeping the links? I have the following
```
(MemberLink
    (GeneNode "NOV")
    (UberonNode "UBERON:0001013"))
(MemberLink
    (GeneNode "NOV")
    (CellNode "CL:0002097"))
(EvaluationLink
    (PredicateNode "interacts_with")
    (SetLink
        (GeneNode "NOV")
        (GeneNode "HOXA1")))
```
And GeneNode "NOV" is now updated to GeneNode "CCN3" and I wanted to update the graph replacing NOV by CCN3. How can i do that?

**Comment by noskill** [comment]
Linas implemented a JoinLink for such usecases https://wiki.opencog.org/w/JoinLink#Replacement_Examples

**Comment by noskill** [comment]
```scheme 
(cog-execute! (MaximalJoin
   (PresentLink (GeneNode "NOV"))
   (ReplacementLink (GeneNode "NOV") (GeneNode "CCN3"))))
```

plus (cog-delete-recursive! (GeneNode "NOV")) should do the trick.

**Comment by tanksha** [comment]
Thank you Anatoly, It works as expected.
