### ISSUE TITLE
traverse-roots fails on optional atomspace

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2773]
It looks like `traverse-roots` fails on given optional atomspace, as the following code demonstrates

```scheme
(use-modules (opencog))
(define new-as (cog-new-atomspace))
(define old-as (cog-set-atomspace! new-as))
(Inheritance (Concept "A") (Concept "B"))
(cog-set-atomspace! old-as)
(cog-prt-atomspace new-as)
```

which outputs

```scheme
(ConceptNode "B")
(ConceptNode "A")
(InheritanceLink
  (ConceptNode "A")
  (ConceptNode "B"))
```

**Comment by linas** [comment]
Closing; this got fixed when AtomSpace frames got implemented. The current output is
```
(InheritanceLink
  (ConceptNode "A")
  (ConceptNode "B"))
```

Also, save and restore of this to RocksStorageNode works (because frames are fully supported there).  It does not yet work over the network (because there's only preliminary frame support in CogStorageNode)
