### ISSUE TITLE
 Unbound variable: fetch-atom

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/atomspace#2785]
I'm trying to follow the instruction on setting up persistence, and I can enter the `guile` console and even `  (use-modules (opencog))`, but then on ` (use-modules (opencog persist) (opencog persist-sql))` I'm met with an error:
```
While compiling expression:
Unbound variable: fetch-atom
```
What am I doing wrong? 
I haven't used opencog in a while, and might have missed something major that makes fixing this obvious, like `fetch-atom` being deprecated or something.

**Comment by noskill** [comment]
Perhaps some persistence libraries haven't been build or installed. Could you please show cmake output?

**Comment by StrangeTcy** [comment]
```
CMake Deprecation Warning at CMakeLists.txt:20 (CMAKE_POLICY):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
-- CogUtil version 2.0.3 found.
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.46") found components: filesystem system 
-- Boost version 106501 found.
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- CxxTest found.
-- Gearman found.
-- Guile (2.2.3 >= 2.2.2) was found.
-- Looking for secure_getenv
-- Looking for secure_getenv - not found
-- Found Python3Interp: /usr/bin/python3  
-- Python 3.6.9 interpreter found.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Python 3.6.9 libraries found.
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Found Cython: /usr/local/bin/cython (Required is at least version "0.24.0") 
-- Cython ( 0.29.2 >= 0.24.0) found.
-- Python destination dir found: /usr/local/lib/python3.6/dist-packages
-- Python install dir: /usr/local/lib/python3.6/dist-packages/opencog
-- Using nosetests executable /usr/bin/nosetests3
-- Stack found.
-- UnixODBC was not found; ODBC persistence subsystem will not be built.
To over-ride, make sure UnixODBC_LIBRARIES and UnixODBC_INCLUDE_DIRS are set.
-- Found PGSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found suitable version "13.1 (Ubuntu 13.1-1.pgdg18.04+1)", minimum required is "9.5") 
-- PostgresSQL 13.1 (Ubuntu 13.1-1.pgdg18.04+1) was found.
-- Valgrind Prefix: 
-- Found VALGRIND: /usr/include/valgrind  
-- VALGRIND was found.
-- VALGRIND devel headers found.
-- Setting python RPATH to /usr/local/lib/python3.6/dist-packages/opencog
CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:48 (MESSAGE):
  /usr/bin/psql: psql: error: FATAL: Peer authentication failed for user
  "opencog_tester"



CMake Warning at tests/persist/sql/multi-driver/CMakeLists.txt:88 (MESSAGE):
  Postgres database not configured for unit tests! See the README!


-- found cython and nosetest, enabling python unit tests
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen missing components: dot

Building for Ubuntu 18.04.5 LTS

The following components will be built:
-----------------------------------------------
   Doxygen                - Code documentation.
   Gearman                - Distributed processing capability.
   Haskell bindings       - Haskell bindings.
   Python bindings        - Python (cython) bindings.
   Python tests           - Python bindings nose tests.
   Scheme bindings        - Scheme bindings and shell.
   SQL Postgres bindings  - Save/Restore of AtomSpace to Postgres database.
   Unit tests             - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   SQL ODBC bindings      - Save/Restore of AtomSpace to database via ODBC.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/enoch/opencog/singularitynet/atomspace/build

```

**Comment by noskill** [comment]
Ok, honestly i don't see what is wrong here. I can only suggest deleting libpersist.so from the filesystem and run the script to check if guile actually loads the extension. If you get something like ```In procedure dynamic-link: file: "opencog/libpersist", message: "file not found```. If it does i would try to debug persist.scm(the file where fetch-atom is defined) with print statements, check if libpersist.so contains sn-fetch-atom and fetch-atom with ```nm -DC libpersist.so|grep fetch-atom```

On my machine:
```
nm -DC /usr/local/lib/opencog/libpersist.so|grep fetch_atom
0000000000021870 T opencog::PersistSCM::sn_fetch_atom(opencog::Handle, opencog::Handle)
00000000000200b0 T opencog::PersistSCM::dflt_fetch_atom(opencog::Handle)
0000000000029a20 T opencog::StorageNode::fetch_atom(opencog::Handle const&)
```

**Comment by StrangeTcy** [comment]
Ok, after a fresh reinstall of atomspace and opencog the guile part works OK, but a python script
```
from opencog.scheme import scheme_eval
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog, finalize_opencog
from opencog.atomspace import AtomSpace, types

atomspace = AtomSpace()
initialize_opencog(atomspace)

scheme_load_atomspace = \
"(use-modules (opencog))\
(use-modules (opencog persist) (opencog persist-sql))\
(sql-open \"postgres:///mycogdata?user=enoch\")\
(sql-load)\
"

scheme_eval(atomspace, scheme_load_atomspace)
print ("The atomspace contains atoms: {}".format(atomspace.get_atoms_by_type(types.Atom)))
```
fails with this error:

> scheme_eval(atomspace, scheme_load_atomspace)                                                                             [8/125]
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>     scheme_eval(atomspace, scheme_load_atomspace)
>   File "scheme.pyx", line 44, in opencog.scheme.scheme_eval
> RuntimeError: Python-Scheme Wrapper: Failed to execute '(use-modules (opencog))(use-modules (opencog persist) (opencog persist-sql))$
> sql-open "postgres:///mycogdata?user=enoch")(sql-load)'
> Backtrace:
>           19 (apply-smob/1 #<catch-closure 7244f40>)
>           18 (apply-smob/1 #<catch-closure 7244dc0>)
> In ice-9/boot-9.scm:
>    2312:4 17 (save-module-excursion #<procedure 743d680 at ice-9/eval-string.scm:66:9 ()>)
> In ice-9/eval-string.scm:
>      38:6 16 (read-and-eval #<input: string 7443cb0> #:lang _)
> In ice-9/eval.scm:
>    721:20 15 (primitive-eval (use-modules (opencog persist) (opencog persist-sql)))
> In ice-9/psyntax.scm:
>   1235:36 14 (expand-top-sequence ((use-modules (opencog persist) (opencog persist-sql))) _ _ #f e (eval) (hygiene guile-user))
>   1182:24 13 (parse _ (("placeholder" placeholder)) ((top) #(ribcage () () ())) _ e (eval) (hygiene guile-user))
>    285:10 12 (parse _ (("placeholder" placeholder)) (()) _ c&e (eval) (hygiene guile-user))
> In ice-9/boot-9.scm:
>   3365:20 11 (process-use-modules _)
>    222:17 10 (map1 (((opencog persist)) ((opencog persist-sql))))
>   3366:31  9 (_ ((opencog persist)))
>   2788:17  8 (resolve-interface (opencog persist) #:select _ #:hide _ #:prefix _ #:renamer _ #:version _)
>   2714:10  7 (_ (opencog persist) _ _ #:ensure _)
>   2982:16  6 (try-module-autoload _ _)
>    2312:4  5 (save-module-excursion #<procedure 4d693c0 at ice-9/boot-9.scm:2983:17 ()>)
>   3002:22  4 (_)
> In unknown file:
>            3 (primitive-load-path "opencog/persist" #<procedure 7248880 at ice-9/boot-9.scm:2989:32 ()>)
> In opencog/persist.scm:
>      15:0  2 (_)
> In ice-9/boot-9.scm:
>    751:25  1 (dispatch-exception 0 misc-error (#f "Unbound variable: ~s" (fetch-atom) #f))
> In unknown file:
>            0 (apply-smob/1 #<catch-closure 7244d80> misc-error #f "Unbound variable: ~s" (fetch-atom) #f)
> 
> ERROR: In procedure apply-smob/1:
> Unbound variable: fetch-atom
> ABORT: misc-error
>  (/home/enoch/opencog/singularitynet/atomspace/opencog/cython/opencog/PyScheme.cc:63)

**Comment by linas** [comment]
My apologies, I've been away and am seeing this only now.

> a fresh reinstall of atomspace

I'm glad this fixed things. Did you also remove the old files, before reinstalling? In particular, this error:

> but a python script

So you are saying that, if you type in, by hand, what that python script is saying, then it works, but the python scriptitself does not?

This suggests that perhaps some older, incompatible opencog-python script is still being linked to. So the reinstall did install newer files, but may have left behind older versions in older directories that are still being linked to.  Maybe in `/usr/local/lib/python3.5/dist-packages/` or something like that...? Or maybe python is picking up an older `pyc` file, instead of recompiling?  We really need a `make uninstall` that really does clobber old stuff before installing new stuff.

Unfortunately, debugging errors like this is enormously difficult ...

**Comment by linas** [comment]
Hi @StrangeTcy I just tried what you posted in https://github.com/opencog/atomspace/issues/2785#issuecomment-751211403 with python3 and it worked fine (after replacing the login with `postgres://opencog_tester:cheese@localhost/opencog_test`)

Note: FYI (important FYI!) RocksDB works, and is a *lot* faster than Postgres. So, from now on out, I will recommend that all users use RocksDB instead.  There are demos both in this repo [examples/atomspace/persistence.scm](../tree/master/examples/atomspace/persistence.scm) and in the [atomspac-e-RocksDB git tree](https://github.com/opencog/atomspace-rocks).

**Comment by linas** [comment]
Closing, this appears to be resolved. If there are still problems, please open a new issue.
