### ISSUE TITLE
Fail to find the HyperTable library in cmake

### ISSUE THREAD

**Issue by kim135797531** [opencog/atomspace#28]
Hello,

When I'm trying to cmake, I'm getting the following error even I installed HyperTable library.

` "Hypertable not found; the experimental distributed persistence DB needs it." `

After finding cause of this problem, I can build with successfully when I changed to content of lib/FindHyperTable.cmake

`FIND_LIBRARY(HYPER_DFS_BROKER NAMES HyperDfsBroker PATHS ${HYPER_LIB_PATHS})`
to
`FIND_LIBRARY(HYPER_DFS_BROKER NAMES HyperFsBroker PATHS ${HYPER_LIB_PATHS})`

HyperDfsBroker to HyperFsBroker works with me, but I'm not sure why name of library in HyperTable is different.

I'm using Ubuntu 14.04 LTS x64 and I installed HyperTable library by aptitude. Version of library is 0.9.8.4.

Thanks,
DongMin

**Comment by linas** [comment]
hyertable is broken and unsupported. Don't use it.

**Comment by kim135797531** [comment]
Oh, I see. Thanks :)
