### ISSUE TITLE
Setting thread names using prctl syscall 

### ISSUE THREAD

**Issue by Habush** [opencog/atomspace#2842]
Setting thread names using [prctl](https://man7.org/linux/man-pages/man2/prctl.2.html) syscall results in the atomspace only building on Linux as the syscall is specific to Linux. This was added in #2832.

**Comment by linas** [comment]
I assume you are building on Apple; to stub it out, you just need to add something like
''`
#ifdef MACOS
#define prctl(a,b,c,d,e) {}
#endif
```
to `cogutils/opencog/util/platform.h` and then make sure `platform.h` is included where needed. ... If there's an equivalent call on apple, then it can be added to `platform.cc` (which, after reading, looks like its old messy and needs a major cleanup.)  That's probably the best solution.
