### ISSUE TITLE
build failure in commit #e02336f on ubuntu 21.10

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#2881]
<pre>[ 63%] <font color="#26A269">Building CXX object opencog/atoms/pattern/CMakeFiles/pattern.dir/MeetLink.cc.o</font>
<b>/home/mozi/oc/atomspace/opencog/atoms/pattern/MeetLink.cc:</b> In member function ‘<b>virtual opencog::QueueValuePtr opencog::MeetLink::do_execute(opencog::AtomSpace*, bool)</b>’:
<b>/home/mozi/oc/atomspace/opencog/atoms/pattern/MeetLink.cc:67:31:</b> <font color="#C01C28"><b>error: </b></font>passing ‘<b>const opencog::StandardException</b>’ as ‘<b>this</b>’ argument discards qualifiers [<font color="#C01C28"><b>-fpermissive</b></font>]
   67 |                 <font color="#C01C28"><b>ex.set_message(msg.c_str())</b></font>;
      |                 <font color="#C01C28"><b>~~~~~~~~~~~~~~^~~~~~~~~~~~~</b></font>
In file included from <b>/usr/local/include/opencog/util/oc_assert.h:29</b>,
                 from <b>/home/mozi/oc/atomspace/opencog/atoms/pattern/MeetLink.cc:22</b>:
<b>/usr/local/include/opencog/util/exceptions.h:88:10:</b> <font color="#2AA1B3"><b>note: </b></font>  in call to ‘<b>void opencog::StandardException::set_message(const char*)</b>’
   88 |     void <font color="#2AA1B3"><b>set_message</b></font>(const char *);
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~</b></font>
make[2]: *** [opencog/atoms/pattern/CMakeFiles/pattern.dir/build.make:121: opencog/atoms/pattern/CMakeFiles/pattern.dir/MeetLink.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
<b>/home/mozi/oc/atomspace/opencog/atoms/pattern/QueryLink.cc:</b> In member function ‘<b>virtual opencog::QueueValuePtr opencog::QueryLink::do_execute(opencog::AtomSpace*, bool)</b>’:
<b>/home/mozi/oc/atomspace/opencog/atoms/pattern/QueryLink.cc:184:31:</b> <font color="#C01C28"><b>error: </b></font>passing ‘<b>const opencog::StandardException</b>’ as ‘<b>this</b>’ argument discards qualifiers [<font color="#C01C28"><b>-fpermissive</b></font>]
  184 |                 <font color="#C01C28"><b>ex.set_message(msg.c_str())</b></font>;
      |                 <font color="#C01C28"><b>~~~~~~~~~~~~~~^~~~~~~~~~~~~</b></font>
In file included from <b>/usr/local/include/opencog/util/oc_assert.h:29</b>,
                 from <b>/home/mozi/oc/atomspace/opencog/atoms/pattern/QueryLink.cc:26</b>:
<b>/usr/local/include/opencog/util/exceptions.h:88:10:</b> <font color="#2AA1B3"><b>note: </b></font>  in call to ‘<b>void opencog::StandardException::set_message(const char*)</b>’
   88 |     void <font color="#2AA1B3"><b>set_message</b></font>(const char *);
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~</b></font>
make[2]: *** [opencog/atoms/pattern/CMakeFiles/pattern.dir/build.make:199: opencog/atoms/pattern/CMakeFiles/pattern.dir/QueryLink.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2693: opencog/atoms/pattern/CMakeFiles/pattern.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
</pre>

**Comment by mjsduncan** [comment]
never mind, cogutil wasn't current

**Comment by linas** [comment]
Yeah, sorry, the need to change cogutils is rare, but it happens...
