### ISSUE TITLE
Possible erroneous behavior of BindLink

### ISSUE THREAD

**Issue by contrast-zone** [opencog/atomspace#2918]
BindLink with OrLink possibly doesn't work correctly when rewriting a predicate with one element list, while GetLink seems to handle the same pattern correctly.

When in guile prompt we enter a declaration:

    ;John attends college
    (Evaluation
      (Predicate "Attends college")
      (List
        (Concept "John")))

then graph rewriting BindLink command:
    
    (cog-execute!
      (Bind
        ;if X attends school or X attends college
        (Or
          (Evaluation
            (Predicate "Attends school")
            (List
              (Variable "$X")))
    
          (Evaluation
            (Predicate "Attends college")
            (List
              (Variable "$X"))))
    
        ;then X is a student
        (Evaluation
          (Predicate "Is student")
          (List
            (Variable "$X")))))
    
the output is, unexpectedly:

    (SetLink)

while entering GetLink command to guile prompt:

    (cog-execute!
      (Get
        ;X attends school or X attends college
        (Or
          (Evaluation
            (Predicate "Attends school")
            (List
              (Variable "$X")))
    
          (Evaluation
            (Predicate "Attends college")
            (List
              (Variable "$X"))))))

expectedly displays:

    (SetLink
      (ConceptNode "John"))

The same situation, but with the first disjunction element instead of the second, seems to work corectly. Thus:
    
    (Evaluation
      (Predicate "Attends school")
      (List
        (Concept "John")))
    
    ;trigger graph rewriting
    (cog-execute!
      (Bind
        ;if X attends school or X attends college
        (Or
          (Evaluation
            (Predicate "Attends school")
            (List
              (Variable "$X")))
    
          (Evaluation
            (Predicate "Attends college")
            (List
              (Variable "$X"))))
    
        (Evaluation
          (Predicate "Is student")
            (List
              (Concept "John")))))

displays expectedly:

    (SetLink
      (EvaluationLink
        (PredicateNode "Is student")
        (ListLink
          (ConceptNode "John"))))

This behavior is observed in guile prompt by replacing every whitespace (including newlines) with a single space in the above code.

This is my first issue report, I hope I'm not intruding too much.

**Comment by linas** [comment]
> OrLink possibly doesn't work correctly

Based on what you wrote, I'd say "for sure doesn't work correctly".  The `OrLink`, and disjunctions in general, are surprisingly difficult to handle correctly. It's quite interesting, theoretically-speaking.  For this case, you *might* have better luck by using `ChoiceLink` instead of `OrLInk`. No promises, though.  The difference between these two is that choice is menu-choice: "pick this or that or that, but pick only one".  Whereas "or" is logical-or: "this is true or that is true or some are true or they're all true".   

Anyway, I will fix this ASAP, which means it might take a few days or a week.

> This is my first issue report, I hope I'm not intruding too much.

Not at all.  And you found a doozey, too; I would have thought that bugs like this were squished long ago.

**Comment by contrast-zone** [comment]
No big hurry, it's not that I'm stuck, or something. I just build up upon AtomSpace work, hoping everything will work one fine day. As I understand, OC is declared as a WIP, so please, take your time.

**Comment by contrast-zone** [comment]
BTW, `ChoiceLink` works fine in the above cases.

**Comment by linas** [comment]
> OC is declared as a WIP

The AtomSpace should be rock-solid and more-or-less bulletproof. I'm aware of all sorts of infelicities, but there shouldn't be any bugs that "ordinary people" can find (aside from those surrounding the `OrLink`; that has been a pain point for many years.)

**Comment by linas** [comment]
And, while I have your attention, something completely off-topic, but: in the https://github.com/opencog/learn project I have large datasets with interesting info in them. I have plenty of ways of seeing this myself, but I can't think of any easy way to expose what I see to other people. One of the datasets shows relationships between tens of thousands of words, and I'm wondering: how can I open this up to some interactive web query or browser or chat, here you might ask "find similar words" or ... I dunno I'm not even sure how to explain it.  The project is going very well, I'm getting good results, but I can't figure out how to make it exciting for anyone else but me...

**Comment by linas** [comment]
Closing. Fixed in pull req #2919. The fix was simple; recent work to make OrLink work with GetLink was never propagated over to BindLink.  Basically, an if-statement was missing.
