### ISSUE TITLE
Update README: package cmake3 is missing in Ubuntu 22.10 repository but package cmake is there

### ISSUE THREAD

**Issue by ivan-karlovich** [opencog/atomspace#3023]
There is no package cmake3 in Ubuntu 22.10 repository. At the same time package cmake is present there. The reported version is 3.24.3:
```
$ sudo apt install cmake3
...
E: Unable to locate package cmake3
$ sudo apt install cmake
...
$ cmake --version
cmake version 3.24.3
```

Probably, makes sense to update README to reflect this fact.

**Comment by linas** [comment]
Thanks!  Fixed in f97b0541bfa24b6a1977ae0c5f80ad27bc5bbcff

Those instructions were written long ago, back when cmake2 and cmake3 had to peacefully co-exist.
