### ISSUE TITLE
Suggestion: Table of Contents for ram-cpu.pdf

### ISSUE THREAD

**Issue by gl-yziquel** [opencog/atomspace#3042]
The RAM-CPU pdf seems to be a foundational document of AtomSpace, insofar, at least, that it documents the core low-level structure of the atomspace.

https://github.com/opencog/atomspace/blob/master/opencog/sheaf/docs/ram-cpu.pdf

A table of contents would be something appreciable: it would provide a nice overview of the document, and would ease getting in all this documentation.

**Comment by linas** [comment]
Your wish is my command. Done.

I'm not sure if it's low-level or high-level. It is a presentation of the abstract theory. One can certainly use the AtomSpace, learn the examples, create new extensions, build new apps, all without reading this document. However, if you want to understand *why* it is the way it is, then its a must read.

**Comment by linas** [comment]
I spent the day doing other general cleanup and minor editing of that text. Latest is available now.

**Comment by gl-yziquel** [comment]
Thank you so much.
