### ISSUE TITLE
Empty VariableList seems to prevent any matchs from occurring.

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#320]
```
guile> (cog-bind (BindLink (VariableList '()) (AndLink (VariableNode "x"))(VariableNode"x")))
(SetLink
)
guile> (cog-bind (BindLink  (AndLink (VariableNode "x"))(VariableNode"x")))
; result content of the atomspace
```
Is this intentional?

**Comment by williampma** [comment]
Sure it is.  It means (VariableNode "x") should be matched as is.  Kind of like QuoteLink.

If that is not intentional, there will be heaps of trouble for the current implementation of URE.

**Comment by AmeBel** [comment]
How will this affect ure?

**Comment by williampma** [comment]
Because URE will generate empty VariableList.

**Comment by linas** [comment]
Yes, that seems to be working as designed.   One could maybe make the argument that the first thing should maybe return `(SetLink (VariableNode "x"))`  which maybe could sort-of make sense ... its a corner case I haven't thought about.

**Comment by linas** [comment]
BTW, there are now more situations where you can use PresentLink which can maybe help disambiguate what you meant/wanted to happen.  (You still cannot combine PresentLik with NotLink, though)

**Comment by AmeBel** [comment]
ok thanks
