### ISSUE TITLE
Enabling DEBUG print in PatternMatchEngine.cc doesn't compile

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#33]
I'm getting the following error
```C++
/home/nilg/OpenCog/atomspace/opencog/query/PatternMatchEngine.cc:569:9: error: ‘perm_count’ was not declared in this scope
         perm_count[Unorder(hp, hg)], num_perms, hp.value(),
```
and it's not obvious to me what perm_count should be replaced by.

**Comment by ngeiswei** [comment]
Well actually the problem is weirder than that; enabling DEBUG in PatternMatchEngine.cc doesn't enable it in PatternMatchEngine.h, thus perm_count and perm_count_stack are not defined.

Moving the DEBUG define in PatternMatchEngine.h doesn't fix things cause it then clashes with Logger::DEBUG later on (in some utest).

A solution would be to rename DEBUG by a unique macro name. For now I'm just gonna add a comment in PatternMatchEngine.cc, beside the DEBUG definition telling that not only
```C++
#define DEBUG
```
must be uncommented, but also
```
#ifdef DEBUG
```
and
```
#endif
```
must be commented out in order to have perm_count and perm_count_stack defined.

**Comment by ngeiswei** [comment]
I think this can be closed, the comment I've added in commit https://github.com/ngeiswei/atomspace/commit/8bf3b46125436fc0c46264d01664d68bbc3c1621 should be enough, but I'll let the main author of the code decide.

**Comment by linas** [comment]
I currently enable debug by defining it in PatternMatchCallback.h, which is included everywhere, and thus enables it in multiple files.

I'm pushing a large change a bit later today; watch out for conflicts.

**Comment by linas** [comment]
closing
