### ISSUE TITLE
opencog/scm/opencog.scm should be moved to the opencog repo

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#38]
I'm not completely sure, it just seems to me this file should be in the opencog repository.

**Comment by linas** [comment]
It can't be, its the base module from which all other modules are derived.

However, opentcog does need a (opencog atomtypes) module

**Comment by linas** [comment]
I just pushed 3470e323e6e6e814cb3710e1c5653189b14b245c and now you should be able to say `(use-modules (opencog atom-types))`  and get all the NLP, embodiment and space-time types loaded...

**Comment by linas** [comment]
closing, I think this is resolved; re-open if not.
