### ISSUE TITLE
Remove Link and Node suffixes to the atom types

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#385]
I'm not sure about that one, and I don't want to distract you guys with yet another perhaps premature or useless code cleaning (think caml vs snake case). But this could shorten a lot the Atomese code and save Atomese coders a bit of time.

So for instance instead of

```scheme
(ForAllLink
   (VariableNode "$X")
   (InheritanceLink
       (ConceptNode "coyote")
       (VariableNode "$X")))
```

we'd write

```scheme
(ForAll
   (Variable "$X")
   (Inheritance
      (Concept "coyote")
      (Variable "$X")))
```

2 atoms are already following that convention VariableList and TypeChoice, and I'm thinking why not the others...

So what do you think, is it worth it? Would it bring confusion to the user? Of course any mistake would immediately being caught at run-time, but still.

I think I'd be in favor such a change but I'd like to hear from you guys.

**Comment by bgoertzel** [comment]
I like this idea OK... it also paves the way for potential changes making Variable and Number and such not really be "nodes" in the current sense...

**Comment by linas** [comment]
Not a bad idea; the tricky part is that the automated tools to build the nodes ad links use the suffix o figure out which ones to build.  viz `lib/OpenCogAtomTypes.cmake`  So step 1 would be to redesign that script, first.

**Comment by linas** [comment]
Done for the core atom types, in pull req #473

**Comment by linas** [comment]
non-core atom types done in opencog/opencog#1971

Note that a cmake clean is needed to trigger this.

open a new issue if you were expecting something more than this.
