### ISSUE TITLE
Unable to install atomspace

### ISSUE THREAD

**Issue by misgeatgit** [opencog/atomspace#393]
After pulling the latest atomspace and building, am getting the following error during 'sudo make install'

``
CMake Error at opencog/persist/zmq/atomspace/cmake_install.cmake:56 (FILE):
  file INSTALL cannot find
  "$HOME/OPENCOG/atomspace/opencog/persist/zmq/atomspace/ZMQMessages.pb.h".
``

**Comment by AmeBel** [comment]
try now
