### ISSUE TITLE
build break: URECommons unit tests don't complie, backward chainer blows up

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#41]
The URECommons unit tests do not compile. After some minimal hacs to stub out the parts that don't compile, the BackwardChainerUTest blows up: it uses up all available RAM in about 60 seconds, and then grinds the swap disk.  Am disabling these for now.

**Comment by williampma** [comment]
Humm.. segmentation fault on calling Instantiator.  Must be related to https://github.com/opencog/atomspace/commit/f287fd78a1484b6aac22cc4a1795e3b508e1b2a6

Happens when trying to Instantiate
```
 (InheritanceLink (stv 1.000000 0.000000)
  (VariableNode "$Z") ; [128]
  (ConceptNode "green") ; [130]
) ; [131]
```
with mapping
```
(VariableNode "$Z") ; [128]
----->
(QuoteLink (stv 1.000000 0.000000)
  (VariableNode "$Z") ; [128]
) ; [190]
```

I need to understand what the change to the Instantiator is doing first.

The URECommons has nothing to do with it, since BackwardChainer doesn't use URECommons at all.

**Comment by linas** [comment]
Oh, that's interesting.  I'm guessing that the instantiator did not notice that there is a QuoteLink there, and went into infinite regress, substituting for Z.  Right? Is that what you are implying?   QuoteLinks are suppose to be a "don't go past this spot" marker, but the instantiator code is old, pre-dating the quotelinks, and probably was never modified to track them.

**Comment by linas** [comment]
I can fix that quick, if that is what you think is happening, just not tonight.

**Comment by williampma** [comment]
The Instantiator is not suppose to care about QuoteLink right?

I am using it to quickly recreate an atom and replace some sub-atoms using my own mapping (in this case want to wrap a QuoteLink around the VariableNode).

**Comment by ngeiswei** [comment]
URECommons compiles and passes for me, has anything been fixed? Can that issue be closed?

**Comment by linas** [comment]
William,
Instantiator should care about QuoteLink.  It should not instantiate
anytyhing under quote link

Nil,
I commented out a bunch of URECommmons code to get it to compile.  Any,
none of teh URE-related unit tests pass.

**Comment by ngeiswei** [comment]
They used to pass last Friday, we've got to identify what commit makes them fail.

I've just tried f287fd7 but at some point (I don't know which test) myRAM got overloaded and I had to restart my system.

**Comment by williampma** [comment]
I am pretty sure URECommons test is fail is by https://github.com/opencog/atomspace/commit/72cad99be855561cc9538ce6f0fc05e8c33a97ff

and BackwardChainer test is by f287fd7

**Comment by ngeiswei** [comment]
OK. And on my side I could observe that at 9737528 nothing (except RuleUTest) breaks.

**Comment by misgeatgit** [comment]
I have a fix for that but am trying to figure out why ForwardChainerUTest
is failing on my machine. The previous failed due to some methods I removed
in a commit I removed a bunch of obsolute ones from the URECommons.

**Comment by linas** [comment]
yes  72cad99 is the one that broke the build

I think I understand why f287fd7 is triggering the break, but it will take me another 6-8 hours for a proper fix. This change exposes multiple issues.

**Comment by linas** [comment]
Closing. Between  pull req #45 and #44 I think this is resolved. I get this:

```
      Start 60: RuleUTest
60/75 Test #60: RuleUTest .............................***Failed    1.34 sec
      Start 61: ForwardChainerUTest
61/75 Test #61: ForwardChainerUTest ...................   Passed    0.45 sec
      Start 62: BackwardChainerUTest
62/75 Test #62: BackwardChainerUTest ..................   Passed    0.69 sec
      Start 63: URECommonsUTest
63/75 Test #63: URECommonsUTest .......................   Passed    0.44 sec
      Start 64: JsonicControlPolicyParamLoaderUTest
64/75 Test #64: JsonicControlPolicyParamLoaderUTest ...   Passed    0.35 sec
      Start 65: DefaultForwardChainerCBUTest
65/75 Test #65: DefaultForwardChainerCBUTest ..........   Passed    0.34 sec
      Start 66: FCMemoryUTest
66/75 Test #66: FCMemoryUTest .........................   Passed    0.24 sec

```

**Comment by linas** [comment]
I also get 
```
	 36 - ExecutionOutputUTest (Failed)
	 48 - EvaluationUTest (Failed)
``` 
but that is my fault. will try too fix soon.

**Comment by williampma** [comment]
Thanks, Linas!

**Comment by linas** [comment]
I think I'm done messing with atomspace internals for a while. I hope. I had to fix-up, add, tweak things to get them to work right, but that seems to be done now.
