### ISSUE TITLE
Universal average quantification and instantiation proposal

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#426]
## Overview

This proposal explains why we probably don't need ForAllLink or even
AverageLink for universal quantification (in the near future at
least), all we would need is LambdaLink over predicates and
ImplicationLink.

There is a detailed proposal below, followed by an example, then a
discussion about how it relates to the pattern matcher.
## Proposal

I'll state it as succession of hypotheses, recalls, definitions and
ideas:
- ~1. [Hypothesis] For any practical purpose in the near term we can use
  AverageLink instead of ForAllLink. I'm not saying that ForAll (as
  defined in the PLN book) is useless, just that we can already build a
  cool demo using average quantification only.
- ~2. [Recall] According to
  http://wiki.opencog.org/wikihome/index.php/AverageLink#PLN_Semantics

``` atomese
AverageLink <TV>
   <variables>
   <predicate body>
```

is equivalent to

``` atomese
P <TV>
```

where P is a predicate with same variables and body.
- ~3. [Definition] A LambdaLink over variables and a predicate body may
  define a predicate. Let's call it PredLambdaLink, just to make sure
  it's a LambdaLink over a predicate (maybe in practice we may jump use
  a LambdaLink, but I want to make it clear it's a predicate).
- ~4. [Definition] The TV over a PredLambdaLink is thus the right place
  to represent the TV of a predicate. For instance

``` atomese
PredLambdaLink <0.01, 0.9>
   TypedVariableLink
      VariableNode "$particle"
      TypeNode "ConceptNode"
   EvaluationLink
      PredicateNode "negatively-charged"
      VariableNode "$particle"
```

means that over the universe of ConceptNodes, 0.01 in average have the
property "negatively-charged". Which is equivalent to

``` atomese
AverageLink <0.01, 0.9>
   TypedVariableLink
      VariableNode "$particle"
      TypeNode "ConceptNode"
   EvaluationLink
      PredicateNode "negatively-charged"
      VariableNode "$particle"
```

also equivalent to

``` atomese
PredicateNode "negatively-charged" <0.01, 0.9>
```
- ~5. [Idea] One should be able to apply universal instantiation on a
  predicate itself! No need of AverageLink for that.
- ~6. [Hypothesis] When stating quantified claims, one is usually
  interested in a restricted context. There is also a great practical
  benefit: finding instances that matter is a lot easier.

So for instance, in the absence of any other knowledge about the
ConceptNode "Sun", one would instantiate the predicate above as
follows

``` atomese
EvaluationLink <0.01, 0.9>
   PredicateNode "negatively-charged"
   ConceptNode "Sun"
```

However, if a precondition is added, like

``` atomese
PredicateNode "is-standard-model-particle"
```

we can discard "Sun" as a valid instantiation term.
- ~7. [Idea] One can use an ImplicationLink for expressing universally
  conditioned average quantification. For instance

``` atomese
ImplicationLink <0.47, 0.8>
   PredicateNode "is-standard-model-particle"
   PredicateNode "negatively-charged"
```

really expresses that over the restricted domain of standard model
particles, 0.47 in average have the property
"negatively-charged". This comes from the definition of
ImplicationLink over predicate as defined in the PLN book.
- ~8. [Definition] Expressing conditioned average quantification using
  ImplicationLink like

``` atomese
ImplicationLink
   PredLambdaLink
      <variables>
      <implicant-body>
   PredLambdaLink
      <variables>
      <implicand-body>
```

is correct but verbose, and can even be confusing for someone who
doesn't understand the higher order logic of it (too bad
though). Besides, in order to be meaningful, <variables> must be the
same in both the implicant and the implicand. For those reasons (and
those reasons only!), we define the following sugar syntax

``` atomese
ImplicationLink
   <variables>
   <implicant-body>
   <implicand-body>
```

Hey, we're back to what Ben and/or Linas suggested a while ago!
Thought this time it makes sense, as sugar syntax!
- ~9. [Idea] Just like one can apply universal instantiation over
  PredLambdaLink (unconditioned average quantification). One should be
  able to apply universal instantiation over ImplicationLink
  (conditioned average quantification). In such a case the instance
  produced is not

``` atomese
ImplicationLink
   <instantiated-implicant-body>
   <instantiated-implicand-body>
```

it is merely

``` atomese
<instantiated-implicand-body>
```

because the implicant is merely a precondition, but it is not the
universal claim itself.
- ~10. [Recall] You might think; isn't universall conditioned average
  quantification the job of ContextLink? Remember that ContextLink is
  sugar syntax, nothing more.

Specifically

``` atomese
ContextLink
   PredicateNode C
   PredicateNode P
```

is equivalent to

``` atomese
ImplicationLink
   PredicateNode C
   PredicateNode P
```
- ~11. [Definition] One could create the same sugar syntax over
  ContextLink regarding lambda, that is

``` atomese
ContextLink
   PredLambdaLink
      <variables>
      <C-body>
   PredLambdaLink
      <variables>
      <P-body>
```

would be equivalent to

``` atomese
ContextLink
   <variables>
   <C-body>
   <P-body>
```
## Example

Let's express the following universally conditioned statement: If
individual X takes substance Y, and Y contains Z, then X takes Z

``` atomese
ImplicationLink <0.9 0.9>
   VariableList
      TypedVariableLink
         VariableNode "$X"
         TypeNode "ConceptNode"
      TypedVariableLink
         VariableNode "$Y"
         TypeNode "ConceptNode"
      TypedVariableLink
         VariableNode "$Z"
         TypeNode "ConceptNode"
   AndLink
      EvaluationLink
         PredicateNode "take"
         ListLink
            VariableNode "$X"
            VariableNode "$Y"
      EvaluationLink
         PredicateNode "contain"
         ListLink
            VariableNode "$Y"
            VariableNode "$Z"
   EvaluationLink
      PredicateNode "take"
      ListLink
         VariableNode "$X"
         VariableNode "$Z"
```

Let's also assume the following concepts

``` atomese
ConceptNode "PLN"
ConceptNode "John"
ConceptNode "Coffee"
ConceptNode "Caffeine"
```

And the following evaluations

``` atomese
EvaluationLink <1, 0.9>
   PredicateNode "take"
   ListLink
      ConceptNode "John"
      ConceptNode "Coffee"
```

``` atomese
EvaluationLink <1, 0.9>
   PredicateNode "contain"
   ListLink
      ConceptNode "Coffee"
      ConceptNode "Caffeine"
```

Let's now apply universal instantiation to it, using cog-bind over the
hypothetical implication-instantiation-rule scheme rule (that
automatically finds instantiation terms):

``` scheme
(cog-bind implication-instantiation-rule <ImplicationLink>)
```

where obviously <ImplicationLink> stands for the implication defines
above. Such a rule would probably not bother trying to create
instances such as

``` atomese
EvaluationLink
   PredicateNode "take"
   ListLink
      ConceptNode "PLN"
      ConceptNode "Coffee"
```

because such instance likely doesn't meet the condition anyway (in a
close-world assumption it wouldn't at all). So it will directly create
sensible instances like

``` atomese
EvaluationLink <0.9, 0.9>
   PredicateNode "take"
   ListLink
      ConceptNode "John"
      ConceptNode "Caffeine"
```
## Discussion, PM vs implication instantiation

Implication instantiation obviously looks a lot like pattern
matching. And it is definitely tempting to unify both, but I think we
should be careful, as currently designed and implemented this is not
what the pattern matcher is doing.

First, the TV on the implicand, is calculated according to PLN, rather
than a arbitrary formula provided by the user. Although one might use
a grounded predicate as implicand instead of a predicate, and use it
to calculate the TV of the instance (but beware; to be consistent with
PLN, the TV over the ImplicationLink would still need to be correct,
or perhaps have a null confidence to dodged the inconsistence).

Second, the BindLink's implicand can be any atom (generally is a
schema returning any atom), while the ImplicationLink implicand can
only be a predicate (or a schema returning a predicate).

Can we unify them? I certainly think so, by making use of PresentLink
and other clever ideas.

Do we want to unify them? Maybe... I don't know. I personally wouldn't
rush and would rather wait till I grow more understanding about it.

In any case today they are not the same, so let's be careful not to
get confused.

**Comment by AmeBel** [comment]
What is the difference between `preconditioned average quantification` and `universally conditioned average quantification`?

**Comment by ngeiswei** [comment]
@AmeBel none.

**Comment by ngeiswei** [comment]
Also, all this makes me realize, there isn't much difference between a schema and a predicate, in both cases you need to compose getTV with a underlying schema to get the predicate. I had already noticed that while working on deep type, which seemed to be paradoxical. Maybe it's not that paradoxical, just requires a bit more attention.

**Comment by AmeBel** [comment]
If you are refering to `GroundedSchemaNode` and `GroundedPredicateNode`, then I don't get what you mean. Their semantics from the pattern-matcher perspective is quite different. My guess is you are talking about the haskell binding, with your reference to `deep type`

**Comment by linas** [comment]
Short comment: you are confusing LambdaLink with ScopeLink; they are
not the same. LambdaLink is the base class for functions; ScopeLink is
the base class for anything that scopes variables, this includes
GetLink and BindLink (which scope, but are not functions) and also
ThereExists, Forall, Average., etc which also scope, but are not
functions.

The nameing convention, distinguishing lambda from scoping, is
consistent with both common usage in lambda calculus, for lambda, and
with the notion of scoping and binding, e.g. in c/c++ and programming
in general... as well as the notion in calculus, were an integral over
x scopes x but is not a lambda.

**Comment by linas** [comment]
Hi Nil,

AverageLink <TV>
>    <variables>
>    <predicate body>
>
>
The code, as currently written, makes the variable declaration optional: if
there is no explicit variable declaration made, then the code locates all
the variables in the body.

> is equivalent to
>
> P <TV>
>
> where P is a predicate with same variables and body.
>
Yes.

>
>
>    1. [Recall] You might think; isn't preconditioned average
>    quantification the job of ContextLink? Remember that ContextLink is sugar
>    syntax, nothing more.
>
> Specifically
>
> ContextLink
>    PredicateNode C
>    PredicateNode P
>
> is equivalent to
>
> ImplicationLink
>    PredicateNode C
>    PredicateNode P
>
>
Umm, I'm not sure this is correct. I think it was supposed to be

 ImplicationLink
   PredicateNode C
   PredicateNode (P and C)

that is, in context C, and deductions, implications, reasoning that you do
is valid only in context C and not in the entire universe, in general.
Contexts are meant to be "frames" or even "alternate universes".  In the
universe C where C="Joe is guilty", then P="joe will go to jail" has a very
high TV.  There is another parallel universe where C="Joe is not guilty"
and P="Joe will not go to jail" has a very high TV.  Both of these
universes are simultaneously possible until the jury makes it's decision;
after  which, only one universe is possible, not both.

This is NOT the same as saying "if Joe is guilty, then Joe will go to
jail"; its similar, but the way that the TV's are handled is different;
 the distinction is most convenient for both bayesian inference, and for
inference in frames, in general. The use of frames makes complex reasoning
tasks easier.

>
>    1. Discussion, PM vs implication instantiation
>
> Implication instantiation obviously looks a lot like pattern
> matching. And it is definitely tempting to unify both, but I think we
> should be careful, as currently designed and implemented this is not
> what the pattern matcher is doing.
>
Right.  PLN deals with declarative knowledge. The pattern matcher deals
with imperative knowledge. I put together a wiki page which contrasts the
two, here:

http://wiki.opencog.org/wikihome/index.php/Link_comparison

We need to be able to make both declarative and imperative assertions, even
though they feel "similar" and its tempting to "unify" them.

--linas


>

**Comment by ngeiswei** [comment]
@AmeBel regarding my schema ~= predicate conjecture, it's not related to the PM or the Haskell binding, but I need more thinking before I may say more about it.

**Comment by ngeiswei** [comment]
@linas I understand very well the difference between ScopeLink and LambdaLink in Atomese. No I'm not confusing them...

**Comment by ngeiswei** [comment]
@linas 
```atomese
ImplicationLink
   P
   Q
```
is equivalent to
```atomese
ImplicationLink
   P
   Q and P
```

**Comment by ngeiswei** [comment]
@linas I think the same sugar syntax definition should be considered for BindLink, that is

```atomese
BindLink
   <variables>
   <pattern-body>
   <rewrite-body>
```

should be equivalent to

```atomese
BindLink
   LambdaLink
      <variables>
      <pattern-body>
   LambdaLink ; or FunctionLink
      <variables>
      <rewrite-body>
```

That is the user, in possession of predicates and rewrite schemata should be given the possibilities to define a BindLink as follows

```atomese
BindLink
   <pattern>
   <rewrite>
```

where `<pattern>` and `<rewrite>` aren't bodies only but are directly predicate and schema (e.i. got their body abstracted away with a lambda or such).

**Comment by linas** [comment]
See also #823

**Comment by ngeiswei** [comment]
It's implemented and documented, I'm closing.

**Comment by linas** [comment]
Hi,

On Tue, Oct 20, 2015 at 2:30 AM, ngeiswei <notifications@github.com> wrote:

> @linas <https://github.com/linas> I think the same sugar syntax
> definition should be considered for BindLink, that is
>
> BindLink
>    <variables>
>    <pattern-body>
>    <rewrite-body>
>
> should be equivalent to
>
> BindLink
>    LambdaLink
>       <variables>
>       <pattern-body>
>    LambdaLink ; or FunctionLink
>       <variables>
>       <rewrite-body>
>
>
I don't understand what that means. Can you explain?

It is possible that I don't understand the concept of "lambda
abstraction".  I don't understand how the above makes any sense.

After lambda abstraction, all that one has left are some combinators,
right? What does it mean to have a BindLink over combinators?

That is,

LambdaLink
      <variables>
      <pattern-body>

is a combinator, right?  Or is it something else?

 That is the user, in possession of predicates and rewrite schemata should
> be given the possibilities to define a BindLink as follows
>
> BindLink
>    <pattern>
>    <rewrite>
>
>
Perhaps you are thinking of GetLink and PutLink?  That is,

BindLink
   <pattern>
   <rewrite>

is equivalent to

    PutLink
        <rewrite>
        GetLink
             <pattern>


--linas

**Comment by linas** [comment]
Where is is documented? I'm not sure I understand everything being done here.  For example, there is this statement, I quote: from #issuecomment-149441455
```
ImplicationLink
   P
   Q
```
is equivalent to
```
ImplicationLink
   P
   Q and P
```

I don't understand that at all: these are clearly different, how is it that they can be equivalent?  There's a classical example for this: let P == "I have a dollar" and Q == "I have a candy bar".  Excluding the 1% of rich people, the other 99% always have P-> Q but never P-> (P and Q) That is, for the 99%, its never true that "if I have a dollar then I have a dollar and I have a candy bar".

**Comment by linas** [comment]
To be clear: it may well be the case that PLN has a rule that, given as input
```
ImplicationLink
   P
   Q
```
produces, as output:
```
ImplicationLink
   P
   Q and P
```
However, this rewrite should be an explicit rule in the PLN rulebase.  It is not a rule that should be implicitly assumed in the C++ code, because its false: e.g. the vending machine example,  which exchanges dollars for candy bars, would not have a rule that allows this re-write.

**Comment by ngeiswei** [comment]
At the time I wrote that there was no GetLink and PutLink, so yes it was I meant by
```
Bind
   Lambda
      <vardecl>
      <pattern>
   Lambda
      <vardecl>
      <rewrite>
```
And the Put/Get mechanics is probably more elegant.

**Comment by ngeiswei** [comment]
@linas, I don't know where I said that `P->Q == P->Q&P` was hard coded, there is indeed such a PLN rule. This is universally true in probability theory and classical logic.
