### ISSUE TITLE
atom_types.h not found

### ISSUE THREAD

**Issue by kendricktan** [opencog/atomspace#455]
I clone the repository, and installed all the prerequisites, and it comes up with this warning:

    fatal error: opencog/atomspace/atom_types.h: No such file or directory

OS: Fedora 22
GNU Make 4.0
cmake version 3.3.2

**Comment by issacnitin** [comment]
Close the terminal, open new terminal and try cmake for opencog again

**Comment by kendricktan** [comment]
Thanks for the input, unfortunately it still shows up with that error even after re-cloning it and reinstalling cogutils. Anybody else? :\

**Comment by misgeatgit** [comment]
Have you installed atomspace?

**Comment by kendricktan** [comment]
^thats what i'm trying to do right now

**Comment by AmeBel** [comment]
confused, how will you install something that isn't built yet? or is this occuring for the opencog repo?

**Comment by kendricktan** [comment]
i was just following the steps necessary to build atomspace, 

    cd to project root dir
    mkdir build
    cd build
    cmake ..
    make

However, upon make it throws that error...

I'm confused too.

**Comment by linas** [comment]
`atom_types.h` is automatically built by `lib/OpenCogAtomTypes.cmake`  ... it is supposed to be invoked automatically, whenever some file needs to use `atom_types.h`; the CMakefiles have a explicit ADD_DEPEDENCY for it.

I'm guessing that this step is silently failing somehow...

**Comment by AmeBel** [comment]
@kendricktan I used https://github.com/opencog/ocpkg/blob/master/install-fedora-dependencies.sh to setup a `fedora:22` docker container and got a lot of cmake warnings that don't occur on `cmake 2.8.12.2` inside an `ubuntu:14.04` docker-container. But, was able to build, test and install using `cmake 3.3.2` inside a the `fedora:22` container.

**Comment by kendricktan** [comment]
@AmeBel i saw the recent patch and it fixed the issue.
Cheers. :+1:

**Comment by AmeBel** [comment]
@kendricktan Great, if there are any fixes or feature-additons to the installation script, or any were else for that matter, don't hesitate to send a pull-request. Since our reference development envrionment environment is `ubuntu:14.04` the scripts for the other distros do get stale and issues like yours are our signals for a cleanup .

Hope to here from you soon, have fun :smile:

**Comment by eehmke** [comment]
With Mint 17.2 (Ubuntu 14.04.3) the problem is still present when trying to make atomspace. cmake has version 2.8.12.2-0ubuntu3.

**Comment by AmeBel** [comment]
@eehmke have you tried to use octool for setup? see http://wiki.opencog.org/wikihome/index.php/Ocpkg

**Comment by eehmke** [comment]
Indeed the octool clears the problem. Excuse my ignorance & thanks

**Comment by AmeBel** [comment]
glad to be of help, have fun :smile:
