### ISSUE TITLE
InitiateSearchCB::variable_search only search over the rarest type

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#485]
There is code in InitiateSearchCB::variable_search to only search grounding with the rarest variable type, see

```c++
	// Find the rarest variable type;
	...
```

and the code following.

I understand the drive to save computational resources behind this decision but that isn't what the user expects when using a TypeChoice. Clearly the pattern matcher should offer the possibility to perform a full search of all types.

I guess the right fix is to code another callback that overwrite variable_search to offer that.

Anyway comment or idea is welcome though.

**Comment by ngeiswei** [comment]
Actually reviewing the code further I think the right fix should be done here, not in another callback. The right fix is to choose the variable with the rarest type set, not type singleton.

**Comment by linas** [comment]
Yes, its a bug.  Each possible type choice should have been explored.  The patch looks good to me.
