### ISSUE TITLE
guile is optional according to cmake rules

### ISSUE THREAD

**Issue by sudoman** [opencog/atomspace#491]
If one doesn't have guile-dev installed, one can successfully call "cmake .." and begin to "make". however compilation will fail as it is a required dependecy.

It would be helpful to set guile as a dependency according to cmake.

**Comment by ngeiswei** [comment]
PErsonally I think guile should be mandatory and we should remove all the HAVE_GUILE conditional macros, too many things depends on it.

**Comment by linas** [comment]
Fixed in pull req #1047
