### ISSUE TITLE
Atomspace::get_link fails for Links with no Outgoing Set

### ISSUE THREAD

**Issue by rTreutlein** [opencog/atomspace#498]
Recently my Haskell Test started failing and i tracked down the issue to FalseLink/TrueLink. If my TestData contained these Links then adding the Link worked, while retrieving the Link always Failed.

The Following Test Code adds a TrueLink to the Atomspace and then tries to retrieve it. But the get_link function will only return a Undefined Handle. The most likely cause seems to be that these Links have no OutgoingSet. But so far we have been unable to figure out what exactly causes this issue.

Also what is the reason that these are Links and not Nodes?

    void testZeroArityLinks()
    {
        HandleSeq hs = {};
        Handle ha  = atomSpace->add_link(TRUE_LINK,hs,true);
        Handle hg  = atomSpace->get_link(TRUE_LINK,hs);
        LinkPtr l  = LinkCast(ha);
        Handle hgl = atomSpace->get_link(TRUE_LINK,l->getOutgoingSet());

        Handle un = Handle::UNDEFINED;
        printf("UUID add: %lu\n",ha.value());
        printf("UUID get: %lu\n",hg.value());
        printf("UUID get: %lu\n",hgl.value());
        printf("UUID und: %lu\n",un.value());
        TS_ASSERT(ha == hg);
    }

**Comment by williampma** [comment]
It's random, sometime it works, sometime it doesn't

```
UUID add: 58
UUID get: 58
UUID get: 58
UUID und: 18446744073709551615
.OK!
```
or
```
UUID add: 58
UUID get: 18446744073709551615
UUID get: 18446744073709551615
UUID und: 18446744073709551615
```

**Comment by williampma** [comment]
Changing 
```
    Handle ha  = atomSpace->add_link(TRUE_LINK,hs,true);
```
to 
```
    Handle ha  = atomSpace->add_link(TRUE_LINK,hs,false);
```
make the test OK everytime.

The problem is on the the atom adding side.  When async is "true",  `put_atom_into_index(atom)` is not called and the linkIndex of the atom type is empty.

**Comment by rTreutlein** [comment]
Thanks but the Haskell test doesn't set async to true and fails when trying to get a FalseLink/TrueLink. Well ill have another look at it.

**Comment by linas** [comment]
FWIW, the async flag controls code that is "incomplete"; it was meant to speed-up/parallelize working with the atomspace, but was never completed.  It or some variant of it is still a good idea, but it needs more work. Taking the default value is guaranteed to be OK.

**Comment by rTreutlein** [comment]
Found the issue in the Haskell Bindings. Fix will be in my next Pull-request.
