### ISSUE TITLE
Move Haskell Bindings + Test to their own Repo

### ISSUE THREAD

**Issue by rTreutlein** [opencog/atomspace#502]
I feel like the Haskell Bindings don't belong in the Atomspace Repo, they are a separate thing. So i would like to move them into their own Repository. Only the C-Wrapper would stay in Atomspace.

The main issue i am trying to solve is that if you want to use the bindings you need their source. If they are in the Atomspace which can be anywhere on the disk this is problematic. If however they are in there own Repo i can just point to that. (Pointing to the whole Atomspace repo on git seems excessive.)

Additionally we would not have to build and test the Haskell bindings every-time the Atomspace gets build/tested.

**Comment by pennachin** [comment]
I don't know anything about the Haskell binding but if we move it to its own repo AND don't build/test the binding when the Atomspace repo changes, how do we prevent breakage?

**Comment by ngeiswei** [comment]
I would tend to agree with Cassio, it seems better to have the binding remain in the atomspace repo. @rTreutlein I only partially understand your issue, do you want to chat about it in Slack?

**Comment by rTreutlein** [comment]
I talked with Nil and we will just add the Haskell Bindigns to Hackage. That has to be manually maintained but also solves my problem.
