### ISSUE TITLE
Why are createNode and createLink(different-link-types) "temporary hack"s?

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#530]
I am repeatedly encountering these typedefs `createNode, createBindLink , createLink, ...` while reading. Why are they commented as "temporary hack"? What would be a `non-temporary` implementation?

**Comment by linas** [comment]
I think the intent was to create some very clever overload of opreator new() but I don't see how, and it no longer seems important.

**Comment by linas** [comment]
Or some clever template declaration...
