### ISSUE TITLE
Scheme example doesn't run as expected

### ISSUE THREAD

**Issue by catchchaos** [opencog/atomspace#535]
The example at

https://github.com/opencog/atomspace/blob/master/examples/pattern-matcher/sequence.scm

to demonstrate usage of GroundedPredicateNode doesn't seem to work. After defining the functions, calling them as mentioned in the comments results in a C++ exception.

The error message states that an EvaluationLink needs to passed. Perhaps the comments need to be modified to illustrate how to run the code.

**Comment by linas** [comment]
Can you be more specific?  What is the actual error? It works for me.

**Comment by catchchaos** [comment]
When I key in
>(start-again)

as given in line 119, I get the following error-
ERROR: In procedure opencog-extension:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-evaluate!" "Expecting to get an EvaluationLink! (/tmp/atomspace-master/opencog/atoms/execution/EvaluationLink.cc:150)")'.

I'm not too sure what to make of this.

**Comment by linas** [comment]
You appear to have a (very?) old copy of the atomspace. line 150 of `opencog/atoms/execution/EvaluationLink.cc` does not have that exception in it. In the current code, that exception is at line 432.

Do a `git pull` and then `make` and then `sudo make install`  and then try again.

**Comment by linas** [comment]
Oh, and make sure you are pulling from the correct location. `git remote -v` will print out where you are pulling from.

**Comment by linas** [comment]
closing, I assume this is resolved.

**Comment by catchchaos** [comment]
Yeah that did it!
Thanks a lot and sorry for the late response.
