### ISSUE TITLE
Implement MapLink

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#568]
As described here: https://groups.google.com/d/msg/opencog/O2vRjQBU4ko/ntbmZ2kQCQAJ
```
Seems like the Map I want is sorta like BindLink but

-- restricted to apply a rewrite rule to the elements in a particular list L
-- returning the outputs of rewriting the elements of L in order, thus producing another list

We could make

MapLink 
     $variabledeclarations
     P
     Q
     L

that applies the rewrite rule P=>Q to the elements of L in order and outputs a list...

We could almost define MapLink as equivalent to

BindLink
    $variabledeclarations
    AND
          P
          element of L
     Q

but that doesn't work because it's not guaranteed to return the results of applying P to the elemens of L in order.
```

**Comment by linas** [comment]
The actual implementation could be quite simple: Compare P and elements of L top-down, extracting values for varaibles, and just past them into Q.

**Comment by linas** [comment]
On further reflection, the following might be better, or at least, equivalent, and more convneient in certain cases. Maybe should implement both.

PutLink
    Q
    ExtractLink
          $variable decls
           P
           L

**Comment by AmeBel** [comment]
how is ExtractLink different from FilterLink

**Comment by linas** [comment]
FilterLink is equivalent to 
```
PutLink
    P
    ExtractLink
          $variable decls
           P
           L
```
or
```
MapLink 
     $variabledeclarations
     P
     P
     L
```

**Comment by AmeBel** [comment]
It seems the only difference is in the return type FilterLink return the patterns explicitly in a SetLink/ListLink while ExtarctLink does the return implicitly and can't be used without nesting in  a PutLink, right?

**Comment by linas** [comment]
No.  In all three cases, if L is a Set then Map, Extract and Filter return a Set.   If L is a Link, then A Link is returned. All three throw an error if L is not a set of a link.  (well, I guess we could make it handle anything else as if it were a singleton).

All three (Map, Extract and Filter) return a set/link with exactly the same arity: i.e. the subset/sublist of L that matches the "filter" P.

From here, the differ.   Extract is easiest to explain.  Extract compares P side-by-side to each element of L, and extracts a value from L for each variable in P.  If the <variable-decls> listed N variables, then 
Extract returns a list of N values in 1 to 1 correspondence with the variables.

Map performs the above steps, but then takes those values, and plugs them into the variable slots in Q, (to create a "grounded instance" of Q)  The returned set/list is a set/list of grounded Q's.

Filter behaves just like Map, except that Q is taken to be P.  Note that, for any given element of L, the corresponding "grounded instance of P" is that element (or the empty set, if the type of P and the type of the element of L don't match). 

Note that Extract is exactly like Map, where Q is taken to be  (List (Varaible 1) ... (Variable N))

All three can be used with Put, but not the same kind of Put.  Since Filter returns elements of L, that Put has to accept elements of L.    Since Map returns grounded Q's, that Put would have to accept grounded Qs as input. And since Extract returns lists of values, that Put would have to accept lists of values as input.

Anyway, I plan to implement this late tonight or tomorrow.  I think I need it for the chatbot.

**Comment by linas** [comment]
updated above comment with typo fixes and etc. to clarify the meaing ...

**Comment by linas** [comment]
Implemented in pull req #575 although the actual syntax difffers from the above.

**Comment by linas** [comment]
Examples added in pull req #580.

**Comment by linas** [comment]
Documented here: http://wiki.opencog.org/wikihome/index.php/MapLink
