### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by JonasWechsler** [opencog/atomspace#605]
Hi,

I'm trying to install Atomspace. Cmake seems to run fine, but when I run make, the build completes 90% and then gives the following error:
<pre>[ 91%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc: In member function ‘virtual opencog::Rule* opencog::ForwardChainer::choose_rule(opencog::Handle, bool)’:
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:270:7: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
     if(nullptr != rule)
       ^
[ 92%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCLogger.cc.o
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/FCLogger.cc: In lambda function:
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/FCLogger.cc:33:7: error: ‘class opencog::Logger’ has no member named ‘setComponent’
   tmp.setComponent("ForwardChainer");
       ^
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCLogger.cc.o] Error 1
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2
make: *** [all] Error 2
</pre>
I'm running Ubuntu 14.04 and I installed all prerequisites.

Here is the full output:
<pre>
➜ build git:(master)>cmake ..
-- Build type: Release
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105400 found.
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- Cxxtest was not found. Make sure CXXTEST_BIN_DIR is set.
-- CxxTest missing: needed for unit tests.
-- Gearman not found.
-- Guile (2.0.9 >= 2.0.9) was found.
-- HyperTable was not found. Make sure HYPERTABLE_LIBRARY and HYPERTABLE_INCLUDE_DIR are set.
-- Hypertable not found; the experimental distributed persistence DB needs it.
-- Protobuf was not found. Make sure PROTOBUF_LIBRARY and PROTOBUF_INCLUDE_DIR are set.
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Protobuf compiler was not found; embodiment PAI can't be built without it.
	To over-ride, make sure PROTOBUF_PROTOC_EXECUTABLE is set.
-- Python libs found.
-- Could NOT find Cython (missing:  CYTHON_EXECUTABLE) (Required is at least version "0.19.0")
-- Cython ( >= 0.19.0) was not found. Make sure CYTHON_EXECUTABLE is set.
-- Cython executable not found.
-- Stack was not found. Haskell bindings will not be built.
-- UnixODBC was not found; persistence subsystem will not be built.
To over-ride, make sure UnixODBC_LIBRARIES and UnixODBC_INCLUDE_DIRS are set.
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Required version of ZeroMQ was not found. Make sure the ZMQ_LIBRARY environment variable is set.
-- ZeroMQ library or its C++ header file was not found; 
To over-ride, make sure that the environment variable ZMQ_LIBRARY is set.
Installation instructions: http://zeromq.org/intro:get-the-software

The following components will be built:
-----------------------------------------------
   AtomSpace           - A weighted and typed hypergraph database.
   Doxygen             - Code documentation.
   Scheme bindings     - Scheme bindings and shell.

The following components WILL NOT be built:
-----------------------------------------------
   Gearman             - Distributed processing capability.
   Haskell bindings    - Haskell bindings.
   Hypertable          - HyperTable for scalable persistance (experimental).
   Python bindings     - Python (cython) bindings.
   Python tests        - Python bindings nose tests.
   SQL persistance     - Save/Restore of AtomSpace to database.
   ZeroMQ persistence  - Save/Restore of AtomSpace to ZeroMQ server.
   Unit tests          - Unit tests.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jonas/atomspace/build
➜ build git:(master)>make
Scanning dependencies of target truthvalue
[  1%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/AttentionValue.cc.o
[  1%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/CountTruthValue.cc.o
[  2%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/FuzzyTruthValue.cc.o
[  3%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/GenericTruthValue.cc.o
[  4%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/IndefiniteTruthValue.cc.o
[  5%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/NullTruthValue.cc.o
[  6%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/ProbabilisticTruthValue.cc.o
[  7%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/SimpleTruthValue.cc.o
[  8%] Building CXX object opencog/truthvalue/CMakeFiles/truthvalue.dir/TruthValue.cc.o
Linking CXX shared library libtruthvalue.so
[  8%] Built target truthvalue
Scanning dependencies of target opencog_atom_types
[  9%] Built target opencog_atom_types
Scanning dependencies of target atombase
[ 10%] Building CXX object opencog/atoms/base/CMakeFiles/atombase.dir/Atom.cc.o
[ 11%] Building CXX object opencog/atoms/base/CMakeFiles/atombase.dir/ClassServer.cc.o
[ 13%] Building CXX object opencog/atoms/base/CMakeFiles/atombase.dir/Handle.cc.o
[ 14%] Building CXX object opencog/atoms/base/CMakeFiles/atombase.dir/Link.cc.o
[ 15%] Building CXX object opencog/atoms/base/CMakeFiles/atombase.dir/Node.cc.o
Linking CXX shared library libatombase.so
[ 16%] Built target atombase
Scanning dependencies of target atomcore
[ 16%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/ArityLink.cc.o
[ 17%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/DefineLink.cc.o
[ 18%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/DeleteLink.cc.o
[ 19%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/FreeLink.cc.o
[ 20%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/FunctionLink.cc.o
[ 21%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/ImplicationLink.cc.o
[ 22%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/LambdaLink.cc.o
[ 23%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/MapLink.cc.o
[ 25%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/PutLink.cc.o
[ 25%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/RandomChoice.cc.o
[ 26%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/RandomNumber.cc.o
[ 27%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/ScopeLink.cc.o
[ 28%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/SleepLink.cc.o
[ 29%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/StateLink.cc.o
[ 30%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/TimeLink.cc.o
[ 31%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/TypedAtomLink.cc.o
[ 32%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/UniqueLink.cc.o
[ 33%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/Variables.cc.o
[ 33%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/VariableList.cc.o
Linking CXX shared library libatomcore.so
[ 33%] Built target atomcore
Scanning dependencies of target atomutils
[ 34%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/AtomUtils.cc.o
[ 34%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/FindUtils.cc.o
[ 35%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/FuzzyMatch.cc.o
[ 36%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/FuzzyMatchBasic.cc.o
[ 38%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/Neighbors.cc.o
[ 39%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/TypeUtils.cc.o
Linking CXX shared library libatomutils.so
[ 39%] Built target atomutils
Scanning dependencies of target lambda
[ 40%] Building CXX object opencog/atoms/pattern/CMakeFiles/lambda.dir/BindLink.cc.o
[ 41%] Building CXX object opencog/atoms/pattern/CMakeFiles/lambda.dir/PatternLink.cc.o
[ 42%] Building CXX object opencog/atoms/pattern/CMakeFiles/lambda.dir/PatternUtils.cc.o
Linking CXX shared library liblambda.so
[ 42%] Built target lambda
Scanning dependencies of target atomspace
[ 43%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/AtomSpace.cc.o
[ 44%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/AtomSpaceInit.cc.o
[ 45%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/AtomTable.cc.o
[ 46%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/AttentionBank.cc.o
[ 47%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/BackingStore.cc.o
[ 48%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/FixedIntegerIndex.cc.o
[ 50%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/HandleSeqIndex.cc.o
[ 50%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/ImportanceIndex.cc.o
[ 51%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/LinkIndex.cc.o
[ 52%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/NodeIndex.cc.o
[ 53%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/TLB.cc.o
[ 54%] Building CXX object opencog/atomspace/CMakeFiles/atomspace.dir/TypeIndex.cc.o
Linking CXX shared library libatomspace.so
[ 54%] Built target atomspace
Scanning dependencies of target smob
[ 55%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeEval.cc.o
[ 56%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeModule.cc.o
[ 57%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemePrimitive.cc.o
[ 58%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmob.cc.o
[ 59%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobAtom.cc.o
[ 59%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobAS.cc.o
[ 60%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobAV.cc.o
[ 61%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobGC.cc.o
[ 63%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobNew.cc.o
[ 64%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobTV.cc.o
[ 65%] Building CXX object opencog/guile/CMakeFiles/smob.dir/SchemeSmobAF.cc.o
[ 66%] Building CXX object opencog/guile/CMakeFiles/smob.dir/LoggerSCM.cc.o
[ 67%] Building CXX object opencog/guile/CMakeFiles/smob.dir/load-file.cc.o
Linking CXX shared library libsmob.so
[ 67%] Built target smob
Scanning dependencies of target clearbox
[ 68%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/ArithmeticLink.cc.o
[ 69%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/DivideLink.cc.o
[ 70%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/FoldLink.cc.o
[ 71%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/MinusLink.cc.o
[ 71%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/PlusLink.cc.o
[ 72%] Building CXX object opencog/atoms/reduct/CMakeFiles/clearbox.dir/TimesLink.cc.o
Linking CXX shared library libclearbox.so
[ 72%] Built target clearbox
Scanning dependencies of target query
[ 72%] Building CXX object opencog/query/CMakeFiles/query.dir/AttentionalFocusCB.cc.o
[ 73%] Building CXX object opencog/query/CMakeFiles/query.dir/DefaultPatternMatchCB.cc.o
[ 75%] Building CXX object opencog/query/CMakeFiles/query.dir/Implicator.cc.o
[ 76%] Building CXX object opencog/query/CMakeFiles/query.dir/InitiateSearchCB.cc.o
[ 77%] Building CXX object opencog/query/CMakeFiles/query.dir/PatternMatch.cc.o
[ 78%] Building CXX object opencog/query/CMakeFiles/query.dir/PatternMatchEngine.cc.o
[ 79%] Building CXX object opencog/query/CMakeFiles/query.dir/PatternSCM.cc.o
[ 80%] Building CXX object opencog/query/CMakeFiles/query.dir/Recognizer.cc.o
[ 81%] Building CXX object opencog/query/CMakeFiles/query.dir/Satisfier.cc.o
Linking CXX shared library libquery.so
[ 81%] Built target query
Scanning dependencies of target execution
[ 82%] Building CXX object opencog/atoms/execution/CMakeFiles/execution.dir/EvaluationLink.cc.o
[ 82%] Building CXX object opencog/atoms/execution/CMakeFiles/execution.dir/ExecutionOutputLink.cc.o
[ 83%] Building CXX object opencog/atoms/execution/CMakeFiles/execution.dir/Instantiator.cc.o
[ 84%] Building CXX object opencog/atoms/execution/CMakeFiles/execution.dir/ExecSCM.cc.o
Linking CXX shared library libexecution.so
[ 84%] Built target execution
Scanning dependencies of target atomspaceutils
[ 85%] Building CXX object opencog/atomspaceutils/CMakeFiles/atomspaceutils.dir/AtomSpaceUtils.cc.o
Linking CXX shared library libatomspaceutils.so
[ 85%] Built target atomspaceutils
Scanning dependencies of target ruleengine
[ 85%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/BackwardChainer.cc.o
[ 86%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/BackwardChainerPMCB.cc.o
[ 88%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/Target.cc.o
[ 89%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/backwardchainer/UnifyPMCB.cc.o
[ 90%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCStat.cc.o
[ 91%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc: In member function ‘virtual opencog::Rule* opencog::ForwardChainer::choose_rule(opencog::Handle, bool)’:
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:270:7: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
     if(nullptr != rule)
       ^
[ 92%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCLogger.cc.o
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/FCLogger.cc: In lambda function:
/home/jonas/atomspace/opencog/rule-engine/forwardchainer/FCLogger.cc:33:7: error: ‘class opencog::Logger’ has no member named ‘setComponent’
   tmp.setComponent("ForwardChainer");
       ^
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCLogger.cc.o] Error 1
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2
make: *** [all] Error 2
</pre>
Any help is appreciated, thanks.

**Comment by misgeatgit** [comment]
Intsall the latest [cog-utils](https://github.com/opencog/cogutils) and try to rebuild the atomspace.

**Comment by JonasWechsler** [comment]
That worked, thanks.
