### ISSUE TITLE
Serious pattern-matcher performance degradation.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#634]
See the conversation in pull request #628 -- some change causes a 10x or 12x slowdown in performance.

**Comment by inflector** [comment]
Summary of prior conversation:

In the Python benchmark, the timing for bindlink was 28µs prior to commit https://github.com/opencog/atomspace/commit/13be76e0f24603c43fe67a745da473fad97e570e, and 346µs after the commit.

One potential significant difference that might affect timing, is that the change moved the temp atomspace from a stack variable to a new class member variable.

linas commented:
>as I look at the diff, it is highly counter-intuitive. The goal of pulling it off the stack, and putting it into the object was to remove the overhead of running the constructors repeatedly, on the stack -- the constructors would run once, and that's it. That this would cause a 10x slowdown is remarkable.

**Comment by inflector** [comment]
Pull request #666 in conjunction with @linas's implementation of transient atomspaces, largely fixes this slowdown.

**Comment by linas** [comment]
work o' the devil.

**Comment by linas** [comment]
closing, I think this is fixed.
