### ISSUE TITLE
Crash in pattern matcher

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#635]
See the commit  for pull #633 -- the  GetLinkUTest::test_disconnected_const_eval() unit test.

**Comment by jswiergo** [comment]
I think this assertion is too strict:
https://github.com/opencog/atomspace/blob/master/opencog/query/PatternMatch.cc#L69-L70
Constant evaluatable component is not "virtual" but it need to be evaluated to check its truth value.

**Comment by linas** [comment]
Hmm. Yes, that throw looks like its left over from an earlier design.

**Comment by linas** [comment]
merged #689
