### ISSUE TITLE
QuoteLink doesn't work with DefinedPredicateNode

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#646]
## Atomspace content
```scheme
(define (foo arg)
    (stv 1 1)
)

(define z-eval
    (EvaluationLink
        (GroundedPredicateNode "scm: foo")
        (ListLink (Node "argument"))))
(define dpn1 (psi-add-goal-selector "test" z-eval "Increase"))

(define z-def
    (DefineLink
         (DefinedPredicateNode "test")
         z-eval
    )
)

(define z-get
    (GetLink
       (TypedVariableLink
          (VariableNode "$effect")
          (TypeNode "ConceptNode")
       )
       (EvaluationLink
          (PredicateNode "some property of dpn")
          (ListLink
             (QuoteLink (DefinedPredicateNode "test"))
             (VariableNode "$effect")
          )
       )
    )
)

(EvaluationLink
   (PredicateNode "some property of dpn")
   (ListLink
      (DefinedPredicateNode "test")
      (ConceptNode "result")
   )
)
```

## Error
```scheme
guile> (cog-execute! z-get)
Backtrace:
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 33127e0> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 33127e0>]
In ice-9/boot-9.scm:
 157: 8 [catch #t #<catch-closure 33123c0> ...]
In unknown file:
   ?: 7 [apply-smob/1 #<catch-closure 33123c0>]
   ?: 6 [call-with-input-string "(cog-execute! z-get)\n" ...]
In ice-9/boot-9.scm:
2320: 5 [save-module-excursion #<procedure 2eb80f0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 4 [read-and-eval #<input: string 189b9c0> #:lang ...]
  37: 3 [lp (cog-execute! z-get)]
In unknown file:
   ?: 2 [opencog-extension cog-execute! (#)]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 2fc9800 at ice-9/boot-9.scm:97:6 (thrown-k . args)> C++-EXCEPTION ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 3312380> C++-EXCEPTION ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-execute!: map::at
ABORT: C++-EXCEPTION
```

**Comment by ngeiswei** [comment]
Good spotting @AmeBel , I guess I could give a stab at it since I know the QuoteLink code well. I'm in the middle of a task which might take me another day or so. Can that wait, or do you need this as rapidly as possible?

**Comment by AmeBel** [comment]
Thanks, it is not urgent, i am using `cog-chase-link` for now.

**Comment by jswiergo** [comment]
There is something wrong with cog-execute! case. Works fine if you call:
```
guile> (cog-satisfying-set z-get)
```

**Comment by linas** [comment]
The functions `cog-bind`, `cog-satisfying-set` and so on are a bit archaic.  I believe that they could probably all be replaced by just `cog-execute!` -- off the top of my head, I cannot really think of any rsason why we need to  still have `cog-satisfying-set` and `cog-bind`, other than that a bunch of code still uses them ... right?

**Comment by linas** [comment]
I opened bug #686 to continue with the above idea.

**Comment by linas** [comment]
Heh. 5 minutes later, I'm already changing my mind about #686 ... maybe its a bad idea. Very unclear.

**Comment by jswiergo** [comment]
The difference between cog-execute! and cog-satisfying-set comes from pull request https://github.com/opencog/atomspace/pull/499

The Instantiator of cog-execute! removes first level QuoteLinks here:
https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/Instantiator.cc#L99-L102
and calls satisfying_set method later:
https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/Instantiator.cc#L313
But the cog-satisfing-set just call this method without any preprocessing.

This is incorrect if the first level QuoteLinks are placed below some kind of atoms e.g. GetLink or ExecutionOutputLink that take care of handling QuoteLinks on their own. We need to avoid discarding quotes for this kind of atoms in the place of the Instantiator code pointed above. It will be done later according given atom type semantics.

I will send pull request with the fix.

**Comment by linas** [comment]
closing. I think  this is fixed. When I run above, I get
```
(SetLink
   (ConceptNode "result")
)
```

**Comment by linas** [comment]
thanks @jswiergo
