### ISSUE TITLE
Do not substitute GSN argument in weird circumstance

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#647]
EDIT: for a much short way to reproduce it see the message below

https://github.com/opencog/atomspace/issues/647#issuecomment-185086396

============

Let's define a simple BindLink

```scheme
(define bl
  (BindLink
    (VariableList
      (TypedVariableLink
        (VariableNode "$Q")
        (TypeNode "PredicateNode")
      )
    )
    (VariableNode "$Q")
    (ExecutionOutputLink
      (GroundedSchemaNode "scm: implication-construction-formula")
      (ListLink
        (PredicateNode "P")
        (VariableNode "$Q")
      )
    )
  )
)
```

And another identical one with the addition of (NotLink (EqualLink ...), which triggers the bug

```scheme
(define bl-bug
  (BindLink
    (VariableList
      (TypedVariableLink
        (VariableNode "$Q")
        (TypeNode "PredicateNode")
      )
    )
    (AndLink
      (NotLink (EqualLink (Predicate "P") (VariableNode "$Q")))
      (VariableNode "$Q"))
    (ExecutionOutputLink
      (GroundedSchemaNode "scm: implication-construction-formula")
      (ListLink
        (PredicateNode "P")
        (VariableNode "$Q")
      )
    )
  )
)
```

Let's load `implication-construction-formula`

```scheme
(load "<OPENCOG_ROOT>/opencog/opencog/pln/rules/implication-construction-rule.scm")
```

Let's prepare to run these 2 BindLinks

```scheme
(use-modules (opencog query))
(PredicateNode "Q" (stv 1 1))
```

Let's run the healthy one

```scheme
(cog-bind bl)
$5 = (SetLink
   (ImplicationLink (stv 1 0.99999982)
      (PredicateNode "P")
      (PredicateNode "Q" (stv 1 0.99999982))
   )
)
```

Let's run the buggy one

```scheme
(cog-bind bl-bug)
$6 = (SetLink
)
```

After deeper inspection, I observed that in the buggy one, the GSN
implication-construction-formula doesn't get its variable $Q properly
substituted.

**Comment by ngeiswei** [comment]
@linas you don't need to worry about it, I'm on it. However, if you happen to have some idea popping, feel free to share.

**Comment by ngeiswei** [comment]
Here's a minimal way to reproduce it.

```scheme
(define gl-bug
  (GetLink
    (VariableList
      (TypedVariableLink
        (VariableNode "$Q")
        (TypeNode "PredicateNode")
      )
    )
    (AndLink
      (NotLink
        (EqualLink
          (PredicateNode "P")
          (VariableNode "$Q")
        )
      )
      (VariableNode "$Q")
    )
  )
)
(PredicateNode "Q" (stv 1 1))
(use-modules (opencog query))
(cog-satisfying-set gl-bug)
ERROR: In procedure opencog-extension:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-satisfying-set" "map::at")'.
```

**Comment by linas** [comment]
Yep, looks like a bug to me. I see no reason why that wouldn't work.  FYI, it woll make no difference at all, but you should probably use `(Present (Variable "$Q"))` only because that makes it slightly easier to read/understand. It makes no difference for the actual execution. ... should make no difference. There is a slight chance that the bug might not trigger!?

The log file should have a full stack trace in it, telling you where the C++ exception is being thrown. Its some out-of-bounds array/set reference.

**Comment by linas** [comment]
Uhh .. also, your "minimal way" does not reproduce the bug for me. It seems to work just fine.

**Comment by linas** [comment]
And your maximal way does not reproduce the bug for me either.   This is using the atomspace from this morning.  it seems to work just fine.

**Comment by ngeiswei** [comment]
After rebooting my desktop this morning I cannot reproduce this problem, neither on the master, nor on my branch.

That kind of thing really creeps me out (and wastes time). I'm clueless, maybe a memory corruption. Shit.

**Comment by ngeiswei** [comment]
This morning the bug is back. :-( :-( :-(

I'm gonna get to the bottom of this!!!

**Comment by ngeiswei** [comment]
I think I've fixed it :-). The craze came from the indeterminism in the order of clauses.
