### ISSUE TITLE
DefinedType not allowed in TypedVariableLink

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#648]
Is the following a missing feature or intentional? Just curious.

First modifying the type-signature example at [line 62](https://github.com/opencog/atomspace/blob/master/examples/pattern-matcher/type-signature.scm#L62) to be
```scheme
(DefineLink
    (DefinedType "predicate-type")
    (Signature
        (EvaluationLink
            (TypeChoice
                (TypeNode "PredicateNode")
                (TypeNode "AnchorNode"))
            (ListLink
                (Type "ConceptNode") (Type "ConceptNode")))))

; A search pattern that looks for predicates or grounded predicates.
(define predicate-search
	(GetLink
		(TypedVariable
			(Variable "$x")
            (DefinedType "predicate-type"))
		(AndLink (Variable "$x"))))
```
Then loading it gives, the following error
```scheme
scheme@(guile-user)> (load "type-signature.scm")
;;; note: source file /atomspace/examples/pattern-matcher/type-signature.scm
;;;       newer than compiled /home/opencog/.cache/guile/ccache/2.0-LE-8-2.0/atomspace/examples/pattern-matcher/type-signature.scm.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /atomspace/examples/pattern-matcher/type-signature.scm
;;; compiled /home/opencog/.cache/guile/ccache/2.0-LE-8-2.0/atomspace/examples/pattern-matcher/type-signature.scm.go
ERROR: In procedure cog-new-link:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-new-link" "Unexpected contents in TypedVariableLink\nExpected type specifier (e.g. TypeNode, TypeChoice, etc.), got DefinedTypeNode (/tmp/atomspace-master/opencog/atoms/core/VariableList.cc:228)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
```

**Comment by linas** [comment]
Its a bug, an incomplete implementation.

**Comment by linas** [comment]
pull request #649 should fix this.  I did not test it very carefully.  It could use a unit test, I suppose.

**Comment by linas** [comment]
I guess that a unit test for this is still needed.

**Comment by AmeBel** [comment]
Would #659 suffice.

I just mirrored other testes, but found it weird(in that it broke my uneducated assumption) using scheme to test c++ functions, behavior. I guess the reason to do that is b/c of the verbosity of writing atoms in c++. Is there any other reason?

**Comment by linas** [comment]
Yes #659 would work. But instead, just copy it into DeepTypesUTest 

Yes, the use of scheme in all of those unit tests is simply to avoid writing tedious, hard-to-read C++ code.

Back in the good-old-days, it doubled as a unit test for scheme, to make sure it didn't get broekn.

Someone clever and with too much time on their hands could probably invent some way of reducing the amount of boiler-plate and cut-n-paste in the unit tests. But this is a real low priority.

**Comment by AmeBel** [comment]
updated test and merged
