### ISSUE TITLE
Jenkins is failing due to error pulling image from docker.io

### ISSUE THREAD

**Issue by inflector** [opencog/atomspace#667]
From the Jenkins Console:
```
e995b1e6d4c2: Pulling image (latest) from docker.io/opencog/cogutils, endpoint: https://registry-1.docker.io/v1/
e995b1e6d4c2: Error pulling image (latest) from docker.io/opencog/cogutils, endpoint: https://registry-1.docker.io/v1/, Get https://registry-1.docker.io/v1/images/e995b1e6d4c2bd9c2fa161d9ecb81ae8769bed0cd4a18086c5690af48cddbf4d/ancestry: net/http: TLS handshake timeout
```

**Comment by wenwei-dev** [comment]
I think it's may because the docker hub is migrating to a newer version. So the service is not stable these days. That's one of the reasons that I suggest we should not update our image too often. 
 
Rerun it should fix it.

**Comment by AmeBel** [comment]
@wenwei-dev you can commit the succesfully built images locally. You can move the link-grammar installation from `opencog/opencog-dev:cli` to `opencog/opencog-deps` so you could do the same with opencog/opencog-dev:cli image.

**Comment by AmeBel** [comment]
moved link-grammar installation to base image on https://github.com/opencog/docker/pull/85.

**Comment by linas** [comment]
Closing, this seems to no longer be an issue.
