### ISSUE TITLE
cog-pop-atomsapce scheme function hangs

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/atomspace#717]
scheme@(guile-user)> (cog-push-atomspace)
$1 = #\<atomspace 0x118d630\>
scheme@(guile-user)> (cog-pop-atomspace)
. . . \<enter la la land here\>

Tried to isolate the problem by running each line of the function on its own at the command line, but then it doesn't hang doing that. strange...

**Comment by linas** [comment]
it deadlocked in garbage collection. Fixed in #720
