### ISSUE TITLE
Build problem in Ubuntu 14.10

### ISSUE THREAD

**Issue by tigros** [opencog/atomspace#73]
Keep getting opencog/atomspace_api.h: No such file or directory when trying to build atomspace.

Tried all sort of things, removing python3/cython3, also can't seem to find where atomspace_api.h is generated and I did look believe you me :)

Here's what the output looks like:

admin2@ubuntu:~/Documents/atomspace/build$ uname -a
Linux ubuntu 4.1.0-rc4+ #1 SMP Sun May 24 11:52:18 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux

admin2@ubuntu:~/Documents/atomspace/build$ cmake ..
-- Build type: Release
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105500 found.
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- GHC was found.
-- GSL found.
-- Guile (2.0.11 >= 2.0.0) was found.
-- HyperTable was not found. Make sure HYPERTABLE_LIBRARY and HYPERTABLE_INCLUDE_DIR are set.
-- Hypertable not found; the experimental distributed persistence DB needs it.
-- Python libs found.
-- Cython ( 0.23 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/dist-packages
-- Found Intel TBB
-- 
-- UnixODBC was found.
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.0.4
-- ZeroMQ was found.
CMake Warning at tests/persist/sql/CMakeLists.txt:45 (MESSAGE):
  /usr/bin/psql: psql: could not connect to server: Connection refused

  	Is the server running on host "localhost" (127.0.0.1) and accepting

  	TCP/IP connections on port 5432?

CMake Warning at tests/persist/sql/CMakeLists.txt:60 (MESSAGE):
  Postgres database not configured for unit tests! See the README!

The following components will be built:
-----------------------------------------------
   AtomSpace        - A weighted and typed hypergraph database.
   Cython bindings  - Cython (python) bindings.
   Doxygen          - Code documentation.
   Python tests     - Python bindings nose tests.
   Scheme bindings  - Scheme bindings and shell.
   SQL persistance  - Save/Restore of AtomSpace to database.
   TBB              - Intel TBB (Threaded Building Blocks) for multithreading.
   Unit tests       - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   Hypertable       - HyperTable for scalable persistance (experimental).

-- Configuring done
-- Generating done
-- Build files have been written to: /home/admin2/Documents/atomspace/build
admin2@ubuntu:~/Documents/atomspace/build$ make -j6
[  0%] Cythonizing logger.pyx
[  2%] [  2%] [  4%] [  4%] [  6%] Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_reader.cpp.o
Generating opencog types
Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_value.cpp.o
Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_writer.cpp.o
Building CXX object opencog/cython/CMakeFiles/PythonEval.dir/PythonEval.cc.o
-- Atom type name: Notype
-- Atom type name: Atom
-- Atom type name: Node
-- Atom type name: Link
-- Atom type name: ConceptNode
-- Atom type name: NumberNode
-- Atom type name: OrderedLink
-- Atom type name: UnorderedLink
-- Atom type name: SetLink
-- Atom type name: ListLink
-- Atom type name: MemberLink
-- Atom type name: SubsetLink
-- Atom type name: IntensionalInheritanceLink
-- Atom type name: ExtensionalSimilarityLink
-- Atom type name: IntensionalSimilarityLink
-- Atom type name: AndLink
-- Atom type name: OrLink
-- Atom type name: NotLink
-- Atom type name: SequentialAndLink
-- Atom type name: AbsentLink
-- Atom type name: ChoiceLink
-- Atom type name: ContextLink
-- Atom type name: TypeNode
-- Atom type name: TypeChoice
-- Atom type name: VariableNode
-- Atom type name: TypedVariableLink
-- Atom type name: VariableList
-- Atom type name: QuoteLink
-- Atom type name: ScopeLink
-- Atom type name: DefineLink
-- Atom type name: BetaRedex
-- Atom type name: PatternLink
-- Atom type name: GetLink
-- Atom type name: SatisfactionLink
-- Atom type name: BindLink
-- Custom atom type name specified: "ForAllLink"
-- Atom type name: ForAllLink
-- Atom type name: ExistsLink
-- Atom type name: AverageLink
-- Atom type name: SatisfyingSetLink
-- Atom type name: ScholemLink
-- Atom type name: ImplicationLink
-- Atom type name: EquivalenceLink
-- Atom type name: AssociativeLink
-- Atom type name: InheritanceLink
-- Atom type name: SimilarityLink
-- Atom type name: AttractionLink
-- Atom type name: FreeLink
-- Atom type name: PutLink
-- Atom type name: EvaluationLink
-- Atom type name: ExecutionLink
-- Atom type name: ProcedureNode
-- Atom type name: GroundedProcedureNode
-- Atom type name: SchemaNode
-- Atom type name: GroundedSchemaNode
-- Atom type name: PredicateNode
-- Atom type name: GroundedPredicateNode
-- Atom type name: DefinedRelationshipNode
-- Atom type name: SchemaExecutionLink
-- Atom type name: SchemaEvaluationLink
-- Atom type name: AnchorNode
-- Atom type name: QuantityLink
-- Atom type name: VirtualLink
-- Atom type name: GreaterThanLink
-- Atom type name: EqualLink
-- Atom type name: FunctionLink
-- Atom type name: ExecutionOutputLink
-- Atom type name: FoldLink
-- Atom type name: ArithmeticLink
-- Atom type name: PlusLink
-- Atom type name: TimesLink
-- Atom type name: DeleteLink
-- Atom type name: AssignLink
-- Atom type name: InsertLink
-- Atom type name: RemoveLink
[  6%] Built target opencog_atom_types
[  6%] Building CXX object opencog/atomutils/CMakeFiles/atomutils.dir/AtomUtils.cc.o
Scanning dependencies of target logger_cython
[  6%] Building CXX object opencog/cython/opencog/CMakeFiles/logger_cython.dir/logger.cpp.o
/home/admin2/Documents/atomspace/opencog/cython/PythonEval.cc:39:35: fatal error: opencog/atomspace_api.h: No such file or directory
 #include "opencog/atomspace_api.h"
                                   ^
compilation terminated.
[  9%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/FreeLink.cc.o
Linking CXX shared library logger.so
[  9%] Built target logger_cython
[ 11%] Building CXX object opencog/atomspaceutils/CMakeFiles/atomspaceutils.dir/AtomSpaceUtils.cc.o
[ 11%] Building CXX object opencog/atoms/core/CMakeFiles/atomcore.dir/PutLink.cc.o
Linking CXX shared library libatomutils.so
[ 11%] Built target atomutils
opencog/cython/CMakeFiles/PythonEval.dir/build.make:54: recipe for target 'opencog/cython/CMakeFiles/PythonEval.dir/PythonEval.cc.o' failed
make[2]: *** [opencog/cython/CMakeFiles/PythonEval.dir/PythonEval.cc.o] Error 1
CMakeFiles/Makefile2:1354: recipe for target 'opencog/cython/CMakeFiles/PythonEval.dir/all' failed
make[1]: *** [opencog/cython/CMakeFiles/PythonEval.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libatomspaceutils.so
[ 11%] Built target atomspaceutils
Linking CXX shared library libatomcore.so
[ 11%] Built target atomcore
Linking CXX shared library libjson_spirit.so
[ 11%] Built target json_spirit
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

Any help would be appreciated!

Thanks.

**Comment by linas** [comment]
atomspace_api is a filed that is autogenerated by cython from the atomspace.pyx file   It is placed in the build directory. For me, it is located in `./build/opencog/cython/opencog/atomspace_api.h`   Perhaps you forgot to install cython, or have a version of cython that is too old or new, or have your build directory in a weird place.

**Comment by tigros** [comment]
Thank you, that helped! I went into atomspace/build/opencog/cython/opencog and ran make, finally got  atomspace_api.h created, now atomspace/build/make finishes ok. I think there's an issue somewhere so that it is not running make on that particular location. My cython version is  0.23dev, I did compile it from source too while troubleshooting.

**Comment by chenesan** [comment]
I also met this problem when I try to do a fresh build of atomspace. I can't build the whole atomspace only by "make" command in build/. I have to "make" in build/opencog/cython/opencog/ at first then I can build the whole atomspace successfully.

**Comment by linas** [comment]
OK, I think this is fixed in d04cc327074bea48da3e2f094fde35ecfe1dd23a

**Comment by hanimunir** [comment]
I am new to opencog. while installing atomspace. get this error. I have successfully installed UnixODBC 2.3.7. But still getting following error:

UnixODBC was not found; ODBC persistence subsystem will not be built.
To over-ride, make sure UnixODBC_LIBRARIES and UnixODBC_INCLUDE_DIRS are set.

Please help me.

**Comment by linas** [comment]
It's not an error, it's an informational message.  Almost surely you don't need it.

**Comment by linas** [comment]
anyway @hanimunir please open new bug reports when experiencing problems, do nt append to old and unrelated ones.
