### ISSUE TITLE
make error in atomspace ForwardChainer

### ISSUE THREAD

**Issue by edpell** [opencog/atomspace#736]
I get this error in make
[ 84%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/FCStat.cc.o
[ 84%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc: In member function ‘opencog::UnorderedHandleSet opencog::ForwardChainer::derive_rules(const opencog::Handle&, const opencog::Handle&, const opencog::Rule*)’:
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:412:17: error: converting to ‘opencog::UnorderedHandleSet {aka std::unordered_set<opencog::Handle, opencog::handle_hash>}’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = opencog::Handle; _Hash = opencog::handle_hash; _Pred = std::equal_to<opencog::Handle>; _Alloc = std::allocator<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = opencog::handle_hash; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<opencog::Handle>]’
         return {};
                 ^
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:445:17: error: converting to ‘opencog::UnorderedHandleSet {aka std::unordered_set<opencog::Handle, opencog::handle_hash>}’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = opencog::Handle; _Hash = opencog::handle_hash; _Pred = std::equal_to<opencog::Handle>; _Alloc = std::allocator<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = opencog::handle_hash; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<opencog::Handle>]’
         return {};
                 ^
opencog/rule-engine/CMakeFiles/ruleengine.dir/build.make:192: recipe for target 'opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o' failed
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o] Error 1
CMakeFiles/Makefile2:1597: recipe for target 'opencog/rule-engine/CMakeFiles/ruleengine.dir/all' failed
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
ed@edlinux:~/atomspace/build$ 

I was able to cmake, make, test and install coguntils

**Comment by ngeiswei** [comment]
Hi, it works for me (gcc 4.8.4). What is your version of gcc?

**Comment by edpell** [comment]
I am using 
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)

**Comment by ngeiswei** [comment]
Could you test again?

**Comment by edpell** [comment]
Same error but different context. 

[ 75%] Built target test_pg_storage
Linking CXX shared library libzmqatoms.so
[ 79%] Built target zmqatoms
[ 79%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc: In member function ‘opencog::UnorderedHandleSet opencog::ForwardChainer::derive_rules(const opencog::Handle&, const opencog::Handle&, const opencog::Rule*)’:
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:412:17: error: converting to ‘opencog::UnorderedHandleSet {aka std::unordered_set<opencog::Handle, opencog::handle_hash>}’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = opencog::Handle; _Hash = opencog::handle_hash; _Pred = std::equal_to<opencog::Handle>; _Alloc = std::allocator<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = opencog::handle_hash; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<opencog::Handle>]’
         return {};
                 ^
/home/ed/atomspace/opencog/rule-engine/forwardchainer/ForwardChainer.cc:445:17: error: converting to ‘opencog::UnorderedHandleSet {aka std::unordered_set<opencog::Handle, opencog::handle_hash>}’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = opencog::Handle; _Hash = opencog::handle_hash; _Pred = std::equal_to<opencog::Handle>; _Alloc = std::allocator<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = opencog::handle_hash; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<opencog::Handle>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<opencog::Handle>]’
         return {};
                 ^
opencog/rule-engine/CMakeFiles/ruleengine.dir/build.make:192: recipe for target 'opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o' failed
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/forwardchainer/ForwardChainer.cc.o] Error 1
CMakeFiles/Makefile2:1597: recipe for target 'opencog/rule-engine/CMakeFiles/ruleengine.dir/all' failed
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
ed@edlinux:~/atomspace/build$

**Comment by ngeiswei** [comment]
Have you pulled the last changes? Your code isn't obviously up to date.

**Comment by linas** [comment]
I just merged #737 .. maybe that fixes it?

**Comment by edpell** [comment]
Linas, that did it. It builds fine now. Thanks.

**Comment by linas** [comment]
closing, fixed by #737
