### ISSUE TITLE
Segmentation fault when ForwardChainer is called

### ISSUE THREAD

**Issue by misgeatgit** [opencog/atomspace#759]
Here is what I did.

    guile> (define af_set 
       (SetLink
         (EvaluationLink (stv 1 0.99999982) (av 8 1 0)
          (PredicateNode "friends")
          (ListLink
             (ConceptNode "Gary" (stv 0.16670001 0.99999982))
            (ConceptNode "Helen" (stv 0.16670001 0.99999982))
          )
      )
       (EvaluationLink (stv 0.28 0.80000001) (av 8 1 0)
          (PredicateNode "friends")
          (ListLink
            (ConceptNode "Smoker-807e0a99-f0cf-433b-b040-0c8e6f47408b")
            (ConceptNode "NonSmoker-03feb085-7a3c-4914-ac60-f0e4ed388348")
         )
       )
        (EvaluationLink (stv 1 0.99999982) (av 8 1 0)
          (PredicateNode "smokes")
          (ListLink
             (ConceptNode "Edward" (stv 0.16670001 0.99999982))
         )
      )
       (EvaluationLink (stv 1 0.99999982) (av 8 1 0)
          (PredicateNode "friends")
         (ListLink
            (ConceptNode "Anna" (stv 0.16670001 0.99999982))
            (ConceptNode "Edward" (stv 0.16670001 0.99999982))
        )
       )
    )   
    guile > (load "PATH_TO/rule_base.scm")

    guile > (define rb (ConceptNode "SMOKES_RB"))

    guile > (define source (EvaluationLink 
      (PredicateNode "cancer") 
      (ListLink
      (ConceptNode "Smoker-2484a646-d7e1-4f4b-99cd-cdff56a6ffef") 
      ) ))

    guile > (use-modules (opencog) (opencog rule-engine))

    guile>(cog-fc source rb af_set)
    Connection closed by foreign host.

The rule base is found here https://github.com/misgeatgit/opencog/tree/ecan-wbench/opencog/attention/experiment/data/smokes.

**Comment by ngeiswei** [comment]
Hey @misgeatgit I didn't test the forward chainer when using attentional set so bugs have obviously sneaked in. Could you create a unit test for it and then I can help to fix it.

**Comment by misgeatgit** [comment]
OK, I will do that. I could revert to the previous working state for my immediate use.

**Comment by misgeatgit** [comment]
@ngeiswei  I have opened  another issue https://github.com/opencog/atomspace/issues/763 which seems the root cause of the above issue. So, I would like to close this one for now.

**Comment by ngeiswei** [comment]
I tried it doesn't crash. I believe my last PR https://github.com/opencog/atomspace/pull/766 fixes it.
