### ISSUE TITLE
Bindlink segfault

### ISSUE THREAD

**Issue by misgeatgit** [opencog/atomspace#763]
The following code is causing a segfault.
   
       void bindtest(void){
        
         AtomSpace as;
         SchemeEval eval(&as);

         Handle evalh =
            eval.eval_h(
                    R"(EvaluationLink 
	                     (PredicateNode "cancer")
		              (ListLink  (ConceptNode "Smoker-fd03fc34-8fd4-403f-944a-09fe9304ddf5") 
		        ) )");

         Handle hbl =eval.eval_h( R"(BindLink 
                                (VariableList 
                                    (VariableNode "$A")   )
                                 (VariableNode "$A") 
				(VariableNode "$A")
				)");

         Handle result = bindlink(&as, hbl);
        }

**Comment by linas** [comment]
Oh, right. This is the bug I kept pointing Nil at: the BindLink is invalid, and its crashing because it leads to an infinite loop, thus blowing out the stack.  Its a but in the forward chainer.

**Comment by misgeatgit** [comment]
@linas but this important for the forward chainer and if I am not mistaken the backward chainer als relies on this for unifying variables with a source in a smaller atomspace.

**Comment by ngeiswei** [comment]
Yeah, I don't know if that's cause it's using the modus ponens, but the modus ponens is wrongly under specified. The only reason I didn't fix it is because it breaks the backward chainer utest, but for a bad reason. I'm about to practically start rewriting the BC, but I guess I could fix the modus ponens and disable the breaking BC utest for now (cause this BC rewriting is gonna take a while).

Although @misgeatgit if you could narrow down even further issue #759 so that the example is even more minimal, that would be very helpful. Maybe the problem doesn't come from the modus ponens after all.

**Comment by linas** [comment]
I've got a patch that will explicitly throw an error if it detects an infinite loop. I will push that in maybe half an hour or so.  It currently passes the unit tests

**Comment by linas** [comment]
I'm seeing a totally bizarre bug, very consistent, very reproducible:  If the BC unit test has
```
config().set("SCM_PRELOAD", "empty-file.scm");
load_scm_files_from_config(as_);
```
then the test pases; if I remove these two lines, the test fails, hitting the infinite-loop bug. The file "empty-file.scm" has to exist, but otherwise it can be empty.

**Comment by linas** [comment]
Found it ... kind-of ... there is some sort of crazy quasi-indeterminism in the backward chainer.  Calling guile garbage collection during the unit test changes how the unit test behaves.  If I garbage collect, the test passes, if I don't, the test fails.

**Comment by linas** [comment]
Pull request #764 and specifically commit ad410f5 adds an infinite-loop detector that halts the above run-away process (and converts it to a throw)

**Comment by misgeatgit** [comment]
@ngeiswei  this issue is the narrowed down version of #759

**Comment by ngeiswei** [comment]
Looping 5 times over the same _pattern seems to detect false negatives, I've raised that to 100 in #766 and the BC utests pass as well as what seemed to produce this bug #759.
