### ISSUE TITLE
Comparing TRUE_TV returned from evauating a pattern is not equal to (stv 1 1) in scheme

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#773]
Expected output `#4` to be the same as output `#5`.
```scheme
scheme@(guile-user)> (use-modules (opencog) (opencog exec))
scheme@(guile-user)> (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna")))
$1 = (stv 1 1)
scheme@(guile-user)> (cog-tv? (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna"))))
$2 = #t
scheme@(guile-user)> (cog-tv? (stv 1 1))
$3 = #t
scheme@(guile-user)> (equal? (stv 1 1) (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna"))))
$4 = #f
scheme@(guile-user)> (equal? (stv 1 1) (stv 1 1))
$5 = #t
```

**Comment by misgeatgit** [comment]
Typing 
      (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna"))) returns (stv 1 1) maybe the two STV objects are being compared by their address.

**Comment by ngeiswei** [comment]
`equal?` is supposed to compare by content, maybe this comes from floating point micro differences.

**Comment by AmeBel** [comment]
@ngeiswei that looks to be it.
```scheme
scheme@(guile-user)> (tv-mean (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna")) ))      
$14 = 1.0                                                                                                        
scheme@(guile-user)> (tv-conf (cog-evaluate! (EqualLink (ConceptNode "bananna") (ConceptNode "bananna")) ))      
$15 = 1.0                                                                                                        
scheme@(guile-user)> (tv-mean (stv 1 1))                                                                         
$16 = 1.0                                                                                                        
scheme@(guile-user)> (tv-conf (stv 1 1))                                                                         
$17 = 0.9999998211860657                                                                                         
```

**Comment by linas** [comment]
The `equal?` operator is converted into the C++ `scm_equal_p` subroutine, here:

https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmob.cc#L80

truth values are here:

https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmob.cc#L142

which calls this:
https://github.com/opencog/atomspace/blob/master/opencog/truthvalue/SimpleTruthValue.h#L60

which calls this: 
https://github.com/opencog/atomspace/blob/master/opencog/truthvalue/SimpleTruthValue.cc#L118

which uses `#define FLOAT_ACCEPTABLE_MEAN_ERROR 0.000001` and also `#define FLOAT_ACCEPTABLE_COUNT_ERROR 0.0002`  so the compare should have worked fine.

If it doesn't then something in this chain is broken ... maybe equal_p didn't get called?  Maybe operator==() didn't get called?  Maybe the math in there is bad?

**Comment by AmeBel** [comment]
@ https://github.com/opencog/atomspace/blob/master/opencog/truthvalue/SimpleTruthValue.cc#L127
` fabs(1.0 - (stv->count/count))` gives

2.23517e+25 for `(equal? (stv 1 1)  (cog-evaluate! (Equal (Concept "bananna") (Concept "bananna"))))  `
and 1 for `(equal?  (cog-evaluate! (Equal (Concept "bananna") (Concept "bananna")) ) (stv 1 1))`.
So, why such a big difference?

On this line, https://github.com/opencog/atomspace/blob/master/opencog/guile/SchemeSmobTV.cc#L241 a confidence of 1 is calculated to be `4.47392e+09`, while the count of `TruthValue::TRUE_TV() ` is `1.0e35`. That seems to be the culprit.

**Comment by linas** [comment]
OK, storing count seems like a bad idea. It doesn't allow a uniform distribution. I'll fix this.

**Comment by linas** [comment]
Pull requ #774 should fix this.

**Comment by linas** [comment]
Different versions of this bug have been biting for the last 8 years.  Apparently, the idea of storing a count, and assuming it obeys an approximate Gaussian probability distribution was a poor design choice, because the conversion kept failing in all sorts of corner cases, and had various rounding errors. This time, the tails of the gaussian distribution were mis-calculated.

I changed the code to use a uniform distribution throughout.  There is not any code that actually seems to require the gaussian.

**Comment by AmeBel** [comment]
Thanks.

**Comment by linas** [comment]
p.s. For may want to try IdenticalLink instead of EqualLink.  http://wiki.opencog.org/w/IdenticalLink checks for syntactic equaltiy, while http://wiki.opencog.org/wikihome/index.php/EqualLink checks semantic equality.  Identical is faster.
