### ISSUE TITLE
Haskell should not use UUID''s in it's implementation.

### ISSUE THREAD

**Issue by linas** [opencog/atomspace#796]
The use of UUID's in the haskell bindings is a design flaw, it results in various issues, e.g. #792

**Comment by linas** [comment]
The design reasons for this are explained here:
https://github.com/opencog/atomspace/pull/930#issuecomment-253945092

**Comment by rTreutlein** [comment]
@linas: I am working on this now.

**Comment by linas** [comment]
Thanks!

**Comment by linas** [comment]
closing, I think this is fixed. Or whatever, no longer an issue for the atomsapce.
