### ISSUE TITLE
Add more convenient scheme bindings

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#798]
I find myself often with the need to use the following functions coded in C++.

1. get_distant_neighbors in `<ATOMSPACE_ROOT>/opencog/atomutils/Neighbors.h`
2. has_free_vars in `<ATOMSPACE_ROOT>/opencog/atomutils/FindUtils.h`

These 2 functions are not that trivial to recode in scheme, of course they may, but then if say the definition of what makes a variable free changes then it requires to correct the scheme implementation as well, etc. For that reason I'd like to add them in the scheme bindings.

Let me know @linas if that's a bad or a good idea.

**Comment by ngeiswei** [comment]
I've added binding for is_closed, see http://wiki.opencog.org/wikihome/index.php/Scheme#cog-closed.3F_atom

**Comment by linas** [comment]
Sorry for late response .. sounds like a great idea to me.  Recoding these grungy algorithms in pure scheme would be a terrible idea.

The only plausible alternative I see might be to invent some sort of `IsClosedLink` or something like that, but its not clear how that could work.   The semantics of a DistantNeighborsLink would be even harder to imagine, but doing so could be enlightening.

**Comment by ngeiswei** [comment]
Yeah, I'm letting aside distant neighbor for now as I can often replace it by a slightly more convoluted use of the pattern matcher.

**Comment by linas** [comment]
Can we close this? I think it was solved in pull req #814
