### ISSUE TITLE
cog-evaluate! uses crisp boolean TruthValues for AndLink

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#823]
For example:

```
(define (test1) (stv .85 1))
(define (test2) (stv .7 1))

(cog-evaluate! (And
    (Evaluation (GroundedPredicate "scm: test1") (List))
    (Evaluation (GroundedPredicate "scm: test2") (List))
))
```

and it returns

```
$6 = (stv 1 1)
```

In this case when we are using openpsi, how much the context of a particular rule is satisfied is not reflected by the TV it returns

**Comment by linas** [comment]
The default behavior for AndLink, SequentialAndLink, OrLink, SequentialOrLink, NotLink when used like this, is to round the TV strength to zero or one, and perform crisp logic on it.

At some point, there was discussion, an some stubs in the C++ code, to employ other formulas.

The primary problem was to figure out *which* formulas to use: something from PLN? Something from fuzzy logic? Something from (axiomatic) probability? Something else?  

Should there be a FuzzyAndLink? Maybe a PLNAndLink?  Maybe a ProbabilisticAndLink?  Well, that all seems goofy, so maybe instead there should be a FuzzyTV and a PLNTV and an AxiomaticProbabilityTV?    That seems like a better solution!    (I guess PLNTV is what STV is meant to be... so we should not need to invent a new PLNTV)

The C++ class for each different TV type could then implement formulas for And, Or, Not.

**Comment by bgoertzel** [comment]
Ok ... well for now we urgently need the functionality of PLNAndLink ...
what is the fastest non-horrible way to get that working?

**Comment by ngeiswei** [comment]
Guys, I think I have a solution for that, but it would require to implement a new TV type (that would subsume all the others), definitely not doable by mid-July.

**Comment by ngeiswei** [comment]
With respect to a temporary workaround, @leungmanhin can't you just implement a fuzzy-cog-evaluate! in scheme that would recognize this situation and calculate the min instead?

**Comment by ngeiswei** [comment]
@leungmanhin could you point us in the code exactly where this cog-evaluate! is triggered?

**Comment by leungmanhin** [comment]
@ngeiswei `cog-evaluate!` is triggered in openpsi https://github.com/opencog/opencog/blob/master/opencog/openpsi/main.scm#L63

Since doing `cog-evaluate!` for each of them return the TV I am expecting, e.g.
```
(cog-evaluate! (Evaluation (GroundedPredicate "scm: test2") (List)))
```
gives
```
$2 = (stv 0.69999999 1)
```
so I think we can evaluate them one by one and calculate afterwards

**Comment by ngeiswei** [comment]
Yes, I guess you should calculate the actual TV afterward (using the min here I think). We don't have a generic evaluator yet. cog-evaluate! is very pattern matcher centric, ultimately we need something PLN centric, but that won't happen before the demo, so you'll have to hack around for now.

**Comment by linas** [comment]
Well, its not so much pattern-matcher-centric, as it is crisp-logic-centric.  The original pattern matcher had slots in it to plug in different formulas for combining TV's, but these never got used (no one asked for this, until just now).

This got removed in later iterations, and replaced by a proposal to create and IntersectionLink and a UnionLink, that behave "just like " AndLink, OrLink, except that they treat TV's as  probabilities (set measures) i.e. set-union, set-intersection.  These are not implemented anywhere, but there are a few place-holder slots for this, in a few places.

A further extension would be to create yet more link types, generalizing And/Or in various ways, and associated with various whizzy formulas for combining the truth values.    Thus, the way that the TV's get combined would be determined by the link types you use.   That is, the And?or link types can generalize to some arbitrary mathematical operator, and whatever that oeperator does, that is how the TV's get handled.

**Comment by ngeiswei** [comment]
BTW, the potential solution I mentioned involves #833 + some dedicated PLN-like interpreter (that might generalize cog-evaluate!, TBD).

**Comment by linas** [comment]
Instead of changing cog-evaluate!, create a new routine, cog-super-evaluate! or something like that.

The proposal in #833 is about creating a new TV type, and given the large amount of pain that TV's inflict on the system architecture, I suggest that finishing up protoatoms, and using those, is the correct long-term solution.

**Comment by linas** [comment]
Nil is currently solving this by using the following form in the pattern matcher:
```
(EvaluationLink
      (GroundedPredicateNode "scm: true-enough") 
      (InheritanceLink
        (VariableNode "$B-6266d6f2")
        (VariableNode "$B-6229393a")))
```

which is basically looking for the InheritanceLink, and accepting it only if it is "true enough".

**Comment by ngeiswei** [comment]
The backward chainer solves this problem BTW. See https://github.com/opencog/opencog/tree/master/examples/pln/propositional

Assuming the set of rules only includes propositional evaluation, the complexity should be similar to that of an interpreter.
