### ISSUE TITLE
Fail to load atoms from postgres

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#826]
In short, sometimes I get `ERROR: Throw to key `C++-EXCEPTION' with args `("pgsql-load" "bad_weak_ptr")'` when loading a database, and sometimes it gives Segfault when I try to load atoms from two databases into the atomspace... here is what I did:
- Download and extract the data from: https://github.com/opencog/test-datasets/releases/download/current/aiml-current.tar.gz
- Create two databases, "aiml_generic" and "aiml_futurist"

```
createdb aiml_generic
createdb aiml_futurist

cat /atomspace/opencog/persist/sql/postgres/pg_atom.sql | psql aiml_generic
cat /atomspace/opencog/persist/sql/postgres/pg_atom.sql | psql aiml_futurist
```
- Go to Guile, load two of the data files and store them to the databases, e.g. for `generic-aiml-rules-Jul-05-2016.scm`:

```
(use-modules (opencog) (opencog atom-types) (opencog persist-pgsql) (opencog openpsi))
(primitive-load "/home/opencog/src/res/generic-aiml-rules-Jul-05-2016.scm")
(pgsql-open "aiml_generic" "opencog_user" "cheese")
(pgsql-store)
(pgsql-close)
```
- Restart guile and do the same for `futurist-aiml-rules-Jul-05-2016.scm`

```
(use-modules (opencog) (opencog atom-types) (opencog persist-pgsql) (opencog openpsi))
(primitive-load "/home/opencog/src/res/futurist-aiml-rules-Jul-05-2016.scm")
(pgsql-open "aiml_futurist" "opencog_user" "cheese")
(pgsql-store)
(pgsql-close)
```
- Then try to load from one of databases, say "aiml_generic" after restarting guile again, this may happen:

```
scheme@(guile-user)> (use-modules (opencog) (opencog atom-types) (opencog persist-pgsql) (opencog openpsi))
scheme@(guile-user)> (pgsql-open "aiml_generic" "opencog_user" "cheese")
  Reserving UUIDs up to 779132 Atoms table max.
$1 = ()
scheme@(guile-user)> (pgsql-load)
  Reserving UUIDs up to 779132 Atoms table max.
  Max Height is 22
  Loaded      10000 atoms.
  Loaded      20000 atoms.
  Loaded      30000 atoms.
  Loaded      40000 atoms.
  Loaded 40614 atoms at height 0
ERROR: In procedure opencog-extension:
ERROR: Throw to key `C++-EXCEPTION' with args `("pgsql-load" "bad_weak_ptr")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]>
```
- If the above succeeded, try to load from another database as well, e.g. aiml_futurist, then this will happen:

```
scheme@(guile-user)> (pgsql-close)
scheme@(guile-user)> (pgsql-open "aiml_futurist" "opencog_user" "cheese")
  Reserving UUIDs up to 398699 Atoms table max.
$5 = ()
scheme@(guile-user)> (pgsql-load)
  Reserving UUIDs up to 398699 Atoms table max.
  Max Height is 7
  Loaded 1547 atoms at height 0
Segmentation fault (core dumped)
```

Not sure what is wrong...

**Comment by linas** [comment]
ahh, yes, well, that won't work, at least, not as currently designed.  Here's why:

Every time you restart opencog, the UUID counter is rest to zero, so that atoms are issued UUID's of 1,2,3... There is a routine to manage this, but I don't think it has a scheme wrapper, I don't recall.

 When you create two different databases, you create two different sets of atoms, but having the same UUID's: So, in one database, UUID 42 might be ConceptNode "foo"  while in the other, it might be an InheritanceLink.   This will definitely lead to crashes.

There are several solutions to this. The simplest short-term solution is to reserve a block of UUID's, say, from 10M to 11M for the first database, and from 11M to 12M for the second one.  That way, each DB has room for a million atoms, and as long as you store fewer than that, the UUID's will not collide.

The long-term solution is to remap UUID's inside the database, itself.  This requires new tricky code.

You can reserve UUID's by calling one of
```
TLB::reserve_extent
TLB::reserve_range
TLB::reserve_upto
```

An even easier short-term solution is to not use multiple databases.

**Comment by linas** [comment]
I could add code to solve this/these problems -- its typical system programming code -- but I suspect Ben would rather have me do other things.  Curtis had system programming experience; but no one else on our team currently has this kind of experience ...

**Comment by leungmanhin** [comment]
I also tried to store all of them in one database, I guess for the same reason I'll have to load them to a clean atomspace before starting anything (e.g. ros-behavior-scripting and chatbot) to avoid getting the error, which should be fine, btw on my computer loading from postgres is only slightly faster than loading the same set of atoms from scm files... I think even if it doesn't work for some reason we could still load the atoms from scm files, so it seems this is not really urgent at the moment and it's best for you to concentrate on other more important things I guess, thanks!

**Comment by linas** [comment]
Yes. If the goal is to load static data, loading from scm files is just fine.  The goal of postgres was to work with dynamic data, which is constantly changing.

**Comment by linas** [comment]
Forward work on this issue was blocked by issue #923 but now forward progress is now possible, because that was fixed. Issues remain; see the related bugs #792 and #998

**Comment by linas** [comment]
There have been major updated to the postgres backend, I believe that this issue can no longer happen; the offending code has been removed.
