### ISSUE TITLE
Bug in Atomspace Backward Chaining Example

### ISSUE THREAD

**Issue by dai-dao** [opencog/atomspace#830]
Hi,

I have successfully built atomspace. Then I have to make the c++-api example separately, which was also successful.

When I run the ureexample, which is the backward chaining Criminal Example, I got this error:

```
terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  UREConfigReader - invalid rulebase specified! (~/Desktop/OPENCOG/atomspace/opencog/rule-engine/UREConfigReader.cc:39)
```

Any tips on how to debug this? I'd really appreciate it

Thanks

**Comment by ngeiswei** [comment]
Hi, thanks for pointing this out. The backward chainer is currently broken and in the middle of being recoded. Once ready I'll revisit this example to fix it. Should be ready in a few weeks to a few months.

**Comment by dai-dao** [comment]
I've determined the issue is the c++ function to retrieve the Node handle from atom space. For some reason the return is null. Could you give some pointers about debugging atomspace scheme?

**Comment by linas** [comment]
The handle is presumably null, because no such atom, of the given name, exists.  Probably because there is a typo in the name of the rulebse being accessed.  You should be able to find a stack trace in the `opencog.log` file.

**Comment by dai-dao** [comment]
I needed to change the relative paths to the relevant .scm file, and that error goes away. However I encountered another error:

```
Variable not groundable: (VariableNode "$A") ; [46][1]
```

which is invoked in the c++ backchainer code somewhere. 

Closing this issue since there's already similar issues #172, #132. Potential fix is possibly deep inside the scheme code
