### ISSUE TITLE
VariableNodes are being grounded by VariableNodes, without a QuoteLink

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/atomspace#863]
It seems VariableNodes are being grounded by VariableNodes of different names found in same pattern in another hypergraph, without using a QuoteLink.

### Atomspace content
```scheme
(add-to-load-path "/usr/local/share/opencog/scm")
(use-modules (opencog) (opencog exec))
(define room-state (AnchorNode "Room State"))
(define room-empty (ConceptNode "room empty"))
(define room-nonempty (ConceptNode "room nonempty"))

(DefineLink
	(DefinedPredicateNode "Check if room non-empty-bug")
	(SatisfactionLink
		(SequentialAndLink
			; If someone is visible...
			(PresentLink (EvaluationLink (PredicateNode "visible face")
					(ListLink (VariableNode "$face-id"))))
			; Change the status of the room to "non-empty"
			(TrueLink (PutLink
					(StateLink room-state (VariableNode "$x"))
					room-nonempty)))))

(DefineLink
	(DefinedPredicateNode "Check if room non-empty-fixed")
	(SatisfactionLink
			(TypedVariable
				(VariableNode "$face-id-fixed")
				(TypeNode "NumberNode"))
		(SequentialAndLink
			; If someone is visible...
			(PresentLink (EvaluationLink (PredicateNode "visible face")
					(ListLink (VariableNode "$face-id-fixed"))))
			; Change the status of the room to "non-empty"
			(TrueLink (PutLink
					(StateLink room-state (VariableNode "$x"))
					room-nonempty)))))

(define (t1)(cog-evaluate! (DefinedPredicateNode "Check if room non-empty-bug")))
(define (t2)(cog-evaluate! (DefinedPredicateNode "Check if room non-empty-fixed")))
```
### Test run
```scheme
scheme@(guile-user)> (t1)
$1 = (stv 1 1)
scheme@(guile-user)> (t2)
$2 = (stv 0 1)
```
### Expected result
```scheme
scheme@(guile-user)> (t1)
$1 = (stv 0 1)
```

**Comment by AmeBel** [comment]
@linas would you please check this out. This might be causing unexpected errors, 
another example
```scheme
scheme@(guile-user)> (cog-execute! (Get 
(PresentLink
    (EvaluationLink (PredicateNode "visible face")
        (ListLink (VariableNode "$face-id"))))))
$6 = (SetLink
   (VariableNode "$face-id-fixed")
)

```

**Comment by linas** [comment]
I skimmed this just now, will look at it closely later. Note, however, that returning variables grounded by variables is normal and expected; if you want to not get these, they use a type declaration  e.g. declare `(VariableNode "$face-id")` to be of type NumberNode, or whatever.

**Comment by linas** [comment]
Phew. I finally looked at this in detail.   This is not a bug, its working as designed -- its doing exactly what it's supposed to do, and the proposed fix is exactly the right way to get the right answer. 

Yes, the result is surprising, if you are not expecting it.  However, this is the only way I know of for searching for variables inside of other expressions -- that is, for using "predicates" in the sense of classical predicate logic, as opposed to just using "propositions", in the sense of classical propositional logic.  (Propositions never have variables in them, by definition. Predicates usually do.)
