### ISSUE TITLE
Proposal to represent Back Inference Tree as Atomese program

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#903]
# Motivation

Representing a Back Inference Tree (or BIT) directly in the AtomSpace allows us to visualize with an AtomSpace visualizer how a BIT gets expanded and reduced as the inference goes. I suggest here to attempt to represent it directly as an Atomese program that encodes a forward chaining strategy!
# Words of Caution

I think my attempt is semi failed because it makes the BIT bloated and introduces computational overhead (EDIT: it turned very successful, at the end, must read the whole thing to understand). For that reason I might not use it yet, and use a C++ representation instead. However, for demo purpose, or real inferences once the aforementioned issues have been addressed, this should definitely be the way to go.

I merely present an example, the representational transformation algorithm not being the hard part.
## Disclaimers about this example
1. It leaves out the fitness functions. I will probably represent the fitness function associated to each target as a C++ structure, again till Atomese becomes powerful enough. The fitness function is only relevant for BIT expansion anyway, not its representation.
2. Only and-branches are represented. To recall, a BIT is an or-and-tree. Or-branches for the multiplicity of rules that can match a target. And-branches for the multiplicity of premises that must be fulfilled in order to apply a rule. I believe that or-branches are easy to represent, merely incoming links of and-branches over same target, therefore they are ignored.
# Example

EDIT: look at https://github.com/opencog/atomspace/issues/903#issuecomment-251353253 for the final proposal.
## Legend
1. A to F are concepts
2. $W to $Z are variables
3. D stands for deduction
4. X->Y stands for Inheritance X Y
## BIT example

```
           A->F
            |
            D
            |
      A->$X ,  $X->F
       /          \
      D            D
     /              \
A->$Y,$Y->$X   $X->$Z,$Z->F
                 |
                 D
                 |
           $X->$W,$W->$Z
```
## AtomSpace KB

```
A->B
B->C
C->D
D->E
E->F
```

You can see that given the KB, in order to be able to derive A->F, one needs to expand the BIT multiple times.
## BIT expansion and Atomese representation

Let's look at the representation of the BIT as it expands.
### First 2 levels of the BIT

```
           A->F
            |
            D
            |
      A->$X ,  $X->F
```

Associated hypergraph:

```
Put
  $X
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
  Get
    VariableList $X
    And
      A->$X
      $X->F
```

This is merely a deduction rule application. A BindLink could have been used but as you'll see, as we build the hypergraph incrementally it is better to use a combination of Put, Get, and as it turns out, Map links.
### First 3 levels of the BIT

```
           A->F
            |
            D
            |
      A->$X ,  $X->F
       /          \
      D            D
     /              \
A->$Y,$Y->$X   $X->$Z,$Z->F
```

Associated hypergraph:

```
Put
  $X
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
  MapLink
    Scope
      $X
      List
        A->$X
        $X->F
    Put
      VariableList $X $Y $Z
      List
        ExecutionOutput
          Deduction
          List A->$Y $Y->$X A->$X
        ExecutionOutput
          Deduction
          List $X->$Z $Z->F $X->F
      Get
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
```

Notice 2 things:
1. The inner Get grows and contains all the target leaves of the BIT. That is because we only want to bother applying the forward inference if it has groundings. If so, we are guarantied that the forward inference will go unstopped, and the entire and-tree can be reduced. If not, we need to expand it further. That is how Ari Heljakka BC worked, and I strongly believe for performance reasons is the way it should be done as well. I stress that cause it's not what is described in http://wiki.opencog.org/w/Unified_rule_engine#Overall_Backward_Chaining_Process and of course not what was implemented by William Ma.
2. We use Map in the middle. This is the overhead I was talking about. That is because I need a way to pass the results from the children targets to the parent. The problem is that the Map does redundant work to turn the results of rule applications of the children into variable->ground mappings, and these mappings are mere subsets of the initial results from the inner Get. I don't see a good way to do otherwise. I see how a SequenceLink could be used to control the order so that the children are reduced first, but it's kinda ugly, and then I don't see how to stop the Get from being rerun (which would be much more time consuming). It might not be such a big overhead though, likely linear, but I'm sure we can do better.
### Hypergraph of the whole BIT:

```
Put
  $X
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
  MapLink
    Scope
      $X
      List
        A->$X
        $X->F
    Put
      VariableList $X $Y $Z
      List
        ExecutionOutput
          Deduction
          List A->$Y $Y->$X A->$X
        ExecutionOutput
          Deduction
          List $X->Z Z->F $X->F
    MapLink
      Scope
        $X $Y $Z
        List
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
      Put
        $X $Y $Z $W
        List
          A->$Y
          $Y->$X
          ExecOut
            Deduction
            List $X->$W $W->$Z $X->$Z
          $Z->F
        Get
          VariableList $X $Y $Z $W
          And
            A->$Y
            $Y->$X
            $X->$W
            $W->$Z
            $Z->F
```
# Conclusion

I'm still undecided whether to go with the C++ representation or that one. As I've already coded half of the C++ representation, I might just try both and compare. Ultimately I know the hypergraph representation can be improved and it's just a first attempt.

**Comment by ngeiswei** [comment]
Actually, a possible solution would be to define a `MapPutLink` that would like a PutLink, except it would output the grounding restricted to the variables in the put body, instead of the substituted bodies. So it would essentially be like the composition of a Map and Put as above but without the computational overhead of the Map. So assuming such a `MapPut` link

```
MapPut
   <variable declaration>
   <variable output>
   <rewrite rule>
   <groundings>
```

the Atomese hypergraph of the whole BIT looks like:

```
Put
  $X
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
  MapPut
    VariableList $X $Y $Z
    $X
    List
      ExecutionOutput
        Deduction
        List A->$Y $Y->$X A->$X
      ExecutionOutput
        Deduction
        List $X->Z Z->F $X->F
    MapPut
      VariableList $X $Y $Z $W
      VariableList $X $Y $Z
      List
        A->$Y
        $Y->$X
        ExecOut
          Deduction
          List $X->$W $W->$Z $X->$Z
        $Z->F
      Get
        VariableList $X $Y $Z $W
        And
          A->$Y
          $Y->$X
          $X->$W
          $W->$Z
          $Z->F
```

**Comment by linas** [comment]
The wikipedia article https://en.wikipedia.org/wiki/Natural_deduction explains the standard notation for this, with lines, and suggests that you'r notation is "upside-down"? Is tht right, or do I misunderstand?  So the textbook notation for the first example would be:
```
     A, $X->$W,$W->$Z                             F, $X->$W,$W->$Z
 ------------------------------    intro                   -----------------------  intro
           A->$Y,$Y->$X                                    $X->$Z,$Z->F
       -------------------------------------------------------------------------  elimin
                                A->$X ,  $X->F
                              ------------------------  elimin
                                          A->F 
```
Or something like that.  I can't quite tell what rules are getting used at each step.  I guessed that introduction and elimination rules are being used, but I'm confused about what is really happening.

Or did you literally mean the below? If so, what rules are they?
```
        A->F
 -----------------------  (what rule is this??) 
      A->$X ,  $X->F
 -----------------------------------------  (what rule is this??) 
A->$Y,$Y->$X   $X->$Z,$Z->F
----------------------------------------- (what rule is this??) 
           $X->$W,$W->$Z
```

**Comment by linas** [comment]
OK, this I think I understand:
```
Put
  $X
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
  Get
    VariableList $X
    And
      A->$X
      $X->F
```
Since you are worried about alpha-conversion in another thread, then plese be aware that the only "correct" way to write the above would be to alpha convert it into what it really means:

```
Put
  $Y
  Execution
    Deduction
    List A->$Y $Y->F A->F
  Get
    VariableList $X
    And
      A->$X
      $X->F
```
That is, the variable $X in the GetLink has nothing at all to do with the variable $Y in the Putlink.

Notice that I changed ExecutionOutput to Execution -- I believe this is what you want, since you are trying to record the result of the deduction.   The "natural" notation for this would be
```
A->$X ,  $X->F
------------------  Elimination (axiom of inheritance)
     A->F
```
so indeed, the diagrams got written upside-down...

**Comment by linas** [comment]
The alpha-converted form of this:
```
    Put
      VariableList $X $Y $Z
      List
        ExecutionOutput
          Deduction
          List A->$Y $Y->$X A->$X
        ExecutionOutput
          Deduction
          List $X->$Z $Z->F $X->F
      Get
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
```

is this:

```
    Put
      VariableList $P $Q $R
      List
        Execution
          Deduction
          List A->$Q $Q->$P A->$R
        Execution
          Deduction
          List $P->$R $R->F $P->F
      Get
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
```

However, the way you use this can't be right:  the PutLink simply returns a ListLink containing two execution links.  But then you sent to to a MapLink .... which would return exactly zero results, because what the execution links that the putlink returned do NOT match the pattern in the MapLink, so the pattern matching fails, and nothing happens.

**Comment by linas** [comment]
To get it to do what I think you want it to do, you'd have to write:
```
Put
  VaraiableList $S $R $T
  Execution
    Deduction
    List A->$S $S->F A->F
Map
   Scope
       VariableList $U $V $W
       List
        Execution
          Deduction
          List A->$V $V->$U A->$U
        Execution
          Deduction
          List $U->$W $W->F $U->F
    Put
      VariableList $P $Q $R
      List
        Execution
          Deduction
          List A->$Q $Q->$P A->$P
        Execution
          Deduction
          List $P->$R $R->F $P->F
      Get
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
```
Then this should actually work, as written.

**Comment by linas** [comment]
Re performance, it is kind-of too early to worry about performance. ... although, clearly, the huge CPU-waster will be the GetLink, and everything else will execute in the blink of an eye, compared to that initial Get.  The CPU time spent in pattern matching inside the MapLink is just trivial compared to the GetLink.   So I advicse against worrying about that, just right now.

**Comment by linas** [comment]
I'm slightly confused about the intent of this.  I thought the point of BIT was to somehow record a trace of some kind.   I guess that this is what the ExecutionLinks are doing? They are recording the results of the inference?  If so, then I guess this all makes sense...

The big complicated Get/Map/Put infrastructure above is an actual search pattern that performs a single step of backwards-inference.  I.e. when you execute it, the actual backwards-inference will actually occur.  and the intermediate stages will get recorded into ExecutionLinks. 

If this is really the intent, you can certainly hand-optimize this by manually removing the kind-of-pointless MapLink ...-- you could instead, just write this:

```
    Put
      VariableList $P $Q $R
      List
        Execution
          Deduction
          List A->$Q $Q->$P A->$P
        Execution
          Deduction
          List $P->$R $R->F $P->F
        Execution
          Deduction
          List A->$P $P->F A->F
      Get
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
```
You can even make this much more compact, and avoid the fiddle-faddle of alpha conversion and just use a BindLink:
```
BindLink
        VariableList $X $Y $Z
        And
          A->$Y
          $Y->$X
          $X->$Z
          $Z->F
  List
        Execution
          Deduction
          List A->$Y $Y->$X A->$X
        Execution
          Deduction
          List $X->$Z $Z->F $X->F
        Execution
          Deduction
          List A->$X $X->F A->F
```
which just collapses the Get and Put into one, and is a whole LOT tinier and easier to read than the expression using the MapLinks in it .

I mean .. I had to spend a LOT of time thinking abut what you were trying to do .. whereas that one BindLink just does exactly the same thing, but is much easier to understand.

**Comment by linas** [comment]
Side question: what technical problem does the BIT solve? Why do you need it?

**Comment by ngeiswei** [comment]
Linas said:
"However, the way you use this can't be right: the PutLink simply returns a ListLink containing two execution links. But then you sent to to a MapLink .... which would return exactly zero results, because what the execution links that the putlink returned do NOT match the pattern in the MapLink, so the pattern matching fails, and nothing happens."

I believe the `MapLink` does match the pattern of the `PutLink` (I ran something similar). Please note that it is an `ExecutionOutput` NOT a `Execution`, so the `PutLink`'s output is the output of the rule applied in a forward way.

**Comment by ngeiswei** [comment]
Regarding `MapLink` CPU overhead, yeah, I'm sure you're right. I just concerned about the case where the inner `GetLink` returns a massive amount of matches, and then the overhead would be non-negligible, though I agree, likely just a linear overhead w.r.t. the `Get` output.

**Comment by ngeiswei** [comment]
The point of the BIT is not to record a trace, it is to build a forward chaining strategy to infer a given target.

**Comment by ngeiswei** [comment]
Here's the reason I need alpha conversion. Let's the consider the simple example
```
          $X->$Y     $Y->F
          ---------------- (Deduction rule)
A->$X     $X->F
--------------- (Deduction rule)
     A->F
```
As represented as Put and Get (or Map) links, yes, we don't need to worry about variable names. However as a forward inference that we try to satisfy we do need to worry about them, because if we assume that the `$X` in `A->$X` is the same one in `$X->$Y` we can above load of useless matches that would not trigger subsequent rule implication, it is a massive pruning that we must take advantage of (please let me know if that part isn't clear, I can expand it isn't). So essentially we need a global scope of the BIT (or rather each and-branch of it).

**Comment by ngeiswei** [comment]
OK, this + your last suggestion with the compact BindLink
representation is leading me to this for representation the whole
BIT given at the start

```
BindLink
  VariableList $W $X $Y $Z
  And
    A->$Y
    $Y->$X
    $X->$W
    $W->$Z
    $Z->F
  ExecutionOutput
    Deduction
    List
      ExecutionOutput
        Deduction
        List
          A->$Y
          $Y->$X
          A->$X
      ExecutionOutput
        Deduction
        List
          ExecutionOutput
            Deduction
            List
              $X->$W
              $W->$Z
              $X->$Z
          $Z->F
          $X->F
      A->F
```

well, that's the elegant compact representation I was after! :-)

Now I how you can see why I need alpha conversion, the whole and-branch of the BIT has a global scope!

**Comment by ngeiswei** [comment]
OK, let's build incrementally (still using the up-side-down
representation to not waste time retyping it).

### First 2 levels of the BIT

```
           A->F
            |
            D
            |
      A->$X ,  $X->F
```

Associated hypergraph using `BindLink`:

```
BindLink
  $X
  And
    A->$X
    $X->F
  ExecutionOutput
    Deduction
    List A->$X $X->F A->F
```

### First 3 levels of the BIT

```
           A->F
            |
            D
            |
      A->$X ,  $X->F
       /          \
      D            D
     /              \
A->$Y,$Y->$X   $X->$Z,$Z->F
```

Associated hypergraph using `BindLink`:

```
BindLink
  VariableList $X $Y $Z
  And
    A->$Y
    $Y->$X
    $X->$Z
    $Z->F
  ExecutionOutput
    Deduction
    List
      ExecutionOutput
        Deduction
        List A->$Y $Y->$X A->$X
      ExecutionOutput
        Deduction
        List $X->$Z $Z->F $X->F
      A->F
```

**Comment by ngeiswei** [comment]
@linas I understand what confused you that the `ExecutionOutput` was a `Execution`, this must be the last argument which is the conclusion. Note that this is because that is how the deduction rule is defined. The default assumption in the URE is that the last argument of the `ExecutionOutput` is represents the pattern of the conclusion of the rule, this or one must explicitly defined that conclusion pattern in the "backward form" see http://wiki.opencog.org/w/URE_Configuration_Format#Defining_Rules for more details.

**Comment by linas** [comment]
Re: Execution vs ExecutionOutput: --  some 2-3 years ago, I was using ExecutionLink for that thing which holds only inputs, and does not know what the conclusion is. You said that this was wrong, that it was in conflict with the definition in the book, and went through the entire code base to replace ExecutionLink with ExecutionOutputLink, ... and that's fine. But you seem to now be reversing yourself, and are in distinct conflict with the wiki, as it is today:  http://wiki.opencog.org/w/ExecutionLink which holds the result, and http://wiki.opencog.org/w/ExecutionOutputLink which does NOT hold the conclusion.  So why the flip-flop?

**Comment by linas** [comment]
I still don't understand the statements about alpha conversion. The BindLink, as written, needs no alpha-conversion at all, while the get/put variant seems like it should, but doesn't because the code "does the right thing" for get/put links.

**Comment by linas** [comment]
Yes, in a large dataset, the initial get-part of the bindlink is likely to return just huge avalanches of deductions. That is where, I believe, that exploration of ecan would be very well-spent.

**Comment by ngeiswei** [comment]
Re: Execution vs ExecutionOutput: The fact that a pattern of the rule conclusion may be present in the arguments of the ExecutionOutput is coincidental and could be completely avoided if the backward form were to become mandatory.

**Comment by ngeiswei** [comment]
The BindLink is built on top alpha converted deductions!

Specifically, assuming that the deduction rule is
```
$X->$Y
$Y->$Z
|-
$X->$Z
```
then the BindLink defined in https://github.com/opencog/atomspace/issues/903#issuecomment-251285655 is generated with the following alpha conversions from the deduction rule
1. First expansion: `$Y` is rewritten into `$X`,
2. second left expansion: `$Z` is rewritten into `$X`, right expansion: `$Y` is rewritten into `$Z`,
3. last expansion: `$Y` is rewritten into `$W`.

Of course it's rather confusing because the names used during the alpha conversion are very similar to the original names, but if you replace the above by random suffixes it will become very clear. For instance

1. First expansion: `$Y` is rewritten into `$Y-2f64`,
2. second left expansion: `$Z` is rewritten into `$Z-15a6`, right expansion: `$Y` is rewritten into `$Y-5a9e`,
3. last expansion: `$Y` is rewritten into `$Y-b678`.

then the BindLink looks like:

```
BindLink
  VariableList $Y-b678 $Y-2f64 $Y-5a9e $Y-5a9e
  And
    A->$Y-5a9e
    $Y->$Y-2f64
    $Y-2f64->$Y-b678
    $Y-b678->$Y-5a9e
    $Y-5a9e->F
  ExecutionOutput
    Deduction
    List
      ExecutionOutput
        Deduction
        List A->$Y $Y->$Y-2f64 A->$Y-2f64
      ExecutionOutput
        Deduction
        List
          ExecutionOutput
            Deduction
            List $Y-2f64->$Y-b678 $Y-b678->$Y-5a9e $Y-2f64->$Y-5a9e
          $Y-5a9e->F
          $Y-2f64->F
      A->F
```

which is necessary to build the global scoped BindLink representing a certain cascade of forward rule applications.

**Comment by ngeiswei** [comment]
@linas, w.r.t. Execution vs ExecutionOutput, do you think it would make things clearer if we rename `ExecutionOutputLink` by `ApplyLink`?

**Comment by ngeiswei** [comment]
I realized that this representation relies on the assumption that the formula's inputs corresponds exactly to the premises, it's the only way to have the output of a rule be directly used as input of another one.

So I have 2 options

1. Enforce that assumption. I don't think all rules respects that, but I don't see why they couldn't, in fact it's probably simpler/more regular if they do

2. Add links or schema nodes to perform the necessary transformation to connect the output of a rule to the input of another one.

I'll try to go with 1. which I think is a totally acceptable requirement.

**Comment by linas** [comment]
Well, my internet was down 4 days, and then a hot bug intervened, so I am only now getting back to this conversation.

I still have no clue whatsoever as to why alpha-conversion is needed, or what that has got to do with anything at all being discussed here.  It seems like a red herring.

I also cannot tell why ExecutionOutput is needed: This is a "special" link type, meant to be used to invoke scheme/python functions that return atoms (not TV's) as a return value.  You seem to want to define it as being something else, and I am worried that, if you do that, things will just break.  From what I can tell, you are trying to record some data, as opposed to creating a structure that can be executed.

**Comment by ngeiswei** [comment]
No, the structure is to be executed.

**Comment by ngeiswei** [comment]
Inference tree representation is well supported by Atomese, except for meta rules which requires another issue, so I'm closing.
