### ISSUE TITLE
Feature or bug?

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#910]
### Content of `test.scm`

```scheme
(use-modules (opencog))
(use-modules (opencog query))

;; -----------------------------------------------------------------------------
;; Helper functions

(define (content-1)
    (MemberLink
      (ConceptNode "Socrates@81011e61-27a7-4001-a63b-3b569478bced")
      (SatisfyingSetLink
         (VariableNode "$X")
         (EvaluationLink
            (PredicateNode "breathe@ea723bda-70bb-47c0-8930-b344fb47a4d1")
            (ListLink
               (VariableNode "$X")
               (ConceptNode "air@76357ee3-d334-4b5f-b49e-323b294310b6")
            )
         )
      )
    )
)

(define (content-2)
; MemberLink having the same Variable name as rule
    (MemberLink
      (ConceptNode "Socrates@81011e61-27a7-4001-a63b-3b569478bced")
      (SatisfyingSetLink
         (VariableNode "$X-M2E")
         (EvaluationLink
            (PredicateNode "breathe@ea723bda-70bb-47c0-8930-b344fb47a4d1")
            (ListLink
                (VariableNode "$X-M2E")
               (ConceptNode "air@76357ee3-d334-4b5f-b49e-323b294310b6")
            )
         )
      )
    )
)

;; -----------------------------------------------------------------------------
; From "opencog/pln/rules/member-to-evaluation-rule.scm"
(define (member-to-evaluation-2-1-rule)
    (BindLink
        (VariableList
          (VariableNode "$B")
          (VariableNode "$C")
          (TypedVariableLink
             (VariableNode "$D")
             (TypeNode "PredicateNode")
          )
        )
        (MemberLink
          (VariableNode "$B")
          (SatisfyingSetLink
             (VariableNode "$X-M2E")
             (EvaluationLink
                (VariableNode "$D")
                (ListLink
                   (VariableNode "$X-M2E")
                   (VariableNode "$C")
                )
             )
          )
        )
        (ExecutionOutputLink
          (GroundedSchemaNode "scm: member-to-evaluation-formula")
          (ListLink
             (EvaluationLink
                (VariableNode "$D")
                (ListLink
                   (VariableNode "$B")
                   (VariableNode "$C")
                )
             )
             (MemberLink
                (VariableNode "$B")
                (SatisfyingSetLink
                   (VariableNode "$X-M2E")
                   (EvaluationLink
                      (VariableNode "$D")
                      (ListLink
                         (VariableNode "$X-M2E")
                         (VariableNode "$C")
                      )
                   )
                )
             )
          )
        )
    )
)

(define (member-to-evaluation-formula EVAL MEM)
    (cog-set-tv! EVAL (cog-tv MEM)))

;; -----------------------------------------------------------------------------

(define (test-1)
    (clear)
    (content-1)
    (cog-bind  (member-to-evaluation-2-1-rule))
)

(define (test-2)
    (clear)
    (content-2)
    (cog-bind  (member-to-evaluation-2-1-rule))
)
```

### Steps to reproduce
```scheme
scheme@(guile-user)> (load "test.scm")
scheme@(guile-user)> (test-1)
$1 = (SetLink
)

scheme@(guile-user)> (test-2)
$2 = (SetLink
   (EvaluationLink
      (PredicateNode "breathe@ea723bda-70bb-47c0-8930-b344fb47a4d1")
      (ListLink
         (ConceptNode "Socrates@81011e61-27a7-4001-a63b-3b569478bced")
         (ConceptNode "air@76357ee3-d334-4b5f-b49e-323b294310b6")
      )
   )
)

```

### Question
Why `(test-1)` has no result while `(test-2)` has one?

**Comment by ngeiswei** [comment]
I don't think it's a bug because the variable `(VariableNode "$X-M2E")` is not scoped in the `BindLink`, so it should literally match.

**Comment by AmeBel** [comment]
So `(VariableNode "$X-M2E")` is a free variable and as such the pattern-matcher implicitly  considers it as `(Quote (VariableNode "$X-M2E"))`?

**Comment by ngeiswei** [comment]
Indeed, that is because there is a variable declaration as first argument of the scope, if it weren't, then `$X-M2E` would have been considered scoped.

**Comment by AmeBel** [comment]
Thanks

**Comment by linas** [comment]
There are some confused/wrong comments above.

-- the variable (VariableNode "$X-M2E") is bound, it is not free anywhere at all.

-- saying `(clear)` is well-known to royally screw up the atomspace. It should never be used. Its should not even exist.  All bets are off, if you ever use clear -- pretty much nothing will work any more.

 -- because the variable (VariableNode "$X-M2E") is bound in all contexts, the test-1 should have worked. This is a valid bug.

**Comment by linas** [comment]
One issue is that some old half-finished code never got finished -- specifically, the old alpha-conversion code :-(  that was supposed to make this work.  I was probably interrupted while coding, and just forgot to finish this.  Working on it now.

**Comment by ngeiswei** [comment]
@linas I see, so you're saying that the pattern matcher should implicitly alpha-convert on the fly, so that the two equivalent SatisfyingSetLinks should match, right? Sounds reasonable to me...

**Comment by AmeBel** [comment]
@linas when you say ` the variable (VariableNode "$X-M2E") is bound` do you mean that any unquoted VariableNode, in the implicant of a BindLink, is implicitly bound to all possible atom types, unless it is typed using `TypedVariableLink` ?

**Comment by ngeiswei** [comment]
@AmeBel I think @linas means that `$X-M2E` is bound to the `SatisfyingSetLink` not the BindLink. It doesn't have a type definition so it has the type `Atom` by default.

**Comment by linas** [comment]
What Nil said:  `SatisfyingSetLink`  inherits from `ScopeLink,` and so the `(VariableNode "$X-M2E")` is interpreted as a variable declaration (without any type constraints on it).

**Comment by linas** [comment]
Anyway, pull request #927 fixes this: `(content-1)` and `(content-2)` will return exactly the same link.  Whether the variable name will be $X or $X-M2E will depend on the order in which they got called.

**Comment by linas** [comment]
Hmmm. pull req #927 fixes a bug, but not the bug above.  Strange.. investigating some more.

**Comment by linas** [comment]
Ahh. OK, I see the issue. There is a bug in the pattern matcher: it is looking at bound variables, when it should not be.  Interesting. I have to think about that a bit.

**Comment by linas** [comment]
OK, pull request #931 fixes this.

**Comment by AmeBel** [comment]
@linas  Thanks

**Comment by linas** [comment]
FYI, My fix is causing ForwardChainerUTest to fail, and I realized just now that this is a "real bug" and I am working on it.

**Comment by linas** [comment]
Pull req #937 cleans up yet another related issue that I spotted.
