### ISSUE TITLE
AIML rules loading becomes very slow...

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#940]
It used to take a few minutes to load all of the rules, but now it takes so much longer and it seems to get even slower over time and never finish...

To reproduce it:
- Download and extract the files: https://github.com/opencog/test-datasets/releases/download/current/oc_public_aiml.tar.gz
- Go to `Guile` and do:

```
(use-modules (opencog) (opencog nlp) (opencog openpsi))
(primitive-load "/home/leungmanhin/Downloads/oc_aiml/generic-Oct-20-2016.scm")
```

It's possibly related to the recent changes in ImplicationLink/ScopeLink, and it becomes slower after applying the changes made in https://github.com/opencog/atomspace/commit/2be97b30fd61676dbf26e2351021733c01ca52da

**Comment by linas** [comment]
Ooof. That hurts. Yes, that is the most likely explanation for the slowdown.  Just when I thought I was done fixing emergencies...

**Comment by linas** [comment]
BTW, I have the perfect solution for this, its half-implemented, but then my graphics card died, which lead to a major 4-day ordeal of an operating system backup and reinstall.  I've had a lot of major fails this last few weeks. (including the refridgrator...) will have a solution for this shortly.

**Comment by linas** [comment]
I think/home that pull req #957 fuixes this, but have not yet tested.

**Comment by leungmanhin** [comment]
thanks Linas, unfortunately it's still very slow to load the rules... (~40 mins for loading generic)

**Comment by linas** [comment]
ok investigating this now

**Comment by linas** [comment]
OK, I've got a partial fix, but can't check it in until tomorrow. When I converted to hashes, I forgot to remove a piece of expensive code (which was kind-of the whole point of having the hashes)

**Comment by linas** [comment]
Pull req #970 fixes this.

**Comment by AmeBel** [comment]
~34 sec now

**Comment by leungmanhin** [comment]
yes fixed, thanks!

**Comment by linas** [comment]
"~34 sec now" -- is this about the same as before? a little faster? A lot faster? The original report says "a few minutes" -- so is it actually 4x faster?

**Comment by leungmanhin** [comment]
"~34 sec" is the time for loading only the generic rules on a desktop computer in the office, I tested it on the old Han demo laptop and it took roughly the same as before
