### ISSUE TITLE
Core dump - undefined symbol: _ZN7opencog4Atom13getTruthValueEv

### ISSUE THREAD

**Issue by wenwei-dev** [opencog/atomspace#946]
This is the revisions of OpenCog stack I'm using. 

[cogutils] master e06bdda - (4 days ago) Add yet another exception type. - Linas Vepstas
[atomspace] master 270fc9b - (17 hours ago) Should work with any kind of lambda - Linas Vepstas
[opencog] master c9b230c - (7 days ago) Restore test ot previous version - Linas Vepstas (HEAD, origin/master, master)
[ros-behavior-scripting] master 47526e4 - (3 weeks ago) removed extra comments - mandeep
[relex] master 0c50e1d - (3 days ago) Reorder code for eaier readability - Linas Vepstas (HEAD, origin/master, master)

When I go to ros-behavior-scripting/src and run `guile -l btree-psi.scm`
I get this error: 
```
ImportError: /usr/local/share/opencog/python/opencog/atomspace.so: undefined symbol: _ZN7opencog4Atom13getTruthValueEv
Segmentation fault (core dumped)
```

**Comment by AmeBel** [comment]
Misgana fixed it by removing  the install and reinstalling.
