### ISSUE TITLE
Pattern matcher should catch exception

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#958]
If an exception is thrown while grounding a solution, the pattern matcher should skip it rather than crashing.

To produce this behavior, run the pattern matcher over the following

``` scheme
;; Failing bind link
(define get-bindlink
(BindLink
  (VariableList
    (TypedVariableLink
      (VariableNode "$A-648d8b51") ; [56][45]
      (TypeChoice
        (TypeNode "LambdaLink") ; [3][1]
        (TypeNode "PredicateNode") ; [4][1]
      ) ; [5][1]
    ) ; [57][45]
    (TypedVariableLink
      (VariableNode "$A-4c2b3a57") ; [49][45]
      (TypeChoice
        (TypeNode "LambdaLink") ; [3][1]
        (TypeNode "PredicateNode") ; [4][1]
      ) ; [5][1]
    ) ; [50][45]
  ) ; [58][45]
  (AndLink
    (ImplicationLink
      (VariableNode "$A-4c2b3a57") ; [49][45]
      (PredicateNode "T") ; [32][1]
    ) ; [51][45]
    (VariableNode "$A-648d8b51") ; [56][45]
    (ImplicationLink
      (VariableNode "$A-648d8b51") ; [56][45]
      (VariableNode "$A-4c2b3a57") ; [49][45]
    ) ; [59][45]
  ) ; [63][45]
  (ExecutionOutputLink
    (GroundedSchemaNode "scm: crisp-modus-ponens-formula") ; [12][1]
    (ListLink
      (ExecutionOutputLink
        (GroundedSchemaNode "scm: crisp-modus-ponens-formula") ; [12][1]
        (ListLink
          (VariableNode "$A-648d8b51") ; [56][45]
          (ImplicationLink
            (VariableNode "$A-648d8b51") ; [56][45]
            (VariableNode "$A-4c2b3a57") ; [49][45]
          ) ; [59][45]
          (VariableNode "$A-4c2b3a57") ; [49][45]
        ) ; [61][45]
      ) ; [62][45]
      (ImplicationLink
        (ExecutionOutputLink
          (GroundedSchemaNode "scm: crisp-modus-ponens-formula") ; [12][1]
          (ListLink
            (VariableNode "$A-648d8b51") ; [56][45]
            (ImplicationLink
              (VariableNode "$A-648d8b51") ; [56][45]
              (VariableNode "$A-4c2b3a57") ; [49][45]
            ) ; [59][45]
            (VariableNode "$A-4c2b3a57") ; [49][45]
          ) ; [61][45]
        ) ; [62][45]
        (PredicateNode "T") ; [32][1]
      ) ; [64][45]
      (PredicateNode "T") ; [32][1]
    ) ; [65][45]
  ) ; [66][45]
) ; [67][45]
)

;; Schema returning undefined handle
(define (crisp-modus-ponens-formula A AB B)
  (cog-logger-debug "crisp-modus-ponens-formula A = ~a AB = ~a B = ~a" A AB B)
    (let (  (sA (cog-stv-strength A))
            (cA (cog-stv-confidence A))
            (sAB (cog-stv-strength AB))
            (cAB (cog-stv-confidence AB)))
        (if (and (>= sA 0.5) (>= cA 0.5) (>= sAB 0.5) (>= cAB 0.5))
            (cog-set-tv! B (stv 1 1))
            (cog-undefined-handle))))

;; Grounds
(Implication (stv 1 1)
 (Predicate "R")
 (Predicate "S"))

(Implication (stv 1 1)
 (Predicate "S")
 (Predicate "T"))
```

**Comment by ngeiswei** [comment]
The output of `ExecutionOutputLink [61]` is undefined because "R" TV's is not (stv 1 1). Therefore the ImplicationLink will be ill-formed and raise an exception. The pattern matcher should catch it and keep running.

**Comment by linas** [comment]
Hm. But you are explicitly calling (cog-undefined-handle)~  I could have sworn I removed that, precisely to avoid abuse like this.

However, in general yes, it is much too easy to make the atomspace crash, just by giving it bad data.  I am crossing my fingers that the removal of the UUID's will simplify a lot of the crazier code, and this should help remove one are where problems show up.

Also, the code for (cog-undefined-handle) should be removed .  I am thinking to switching to using exceptions everywhere, instead of returning undefined handles, that way, it will be impossible to ever have an undefined handle. But all this sees like low priority, given all the other crazy stuff I'm supposed to do.

**Comment by linas** [comment]
closing, user error.

**Comment by ngeiswei** [comment]
Yes, but in the original code it doesn't use undefined handle and it still crashes.

**Comment by ngeiswei** [comment]
I've removed the undefined handle from the unit test and it still fails. I think the right fix is to wrap https://github.com/opencog/atomspace/blob/master/opencog/query/Implicator.cc#L52 in a try/catch construct.

@linas I understand you want to treat that as a user failure, but that implies the user to guaranty that the rewrite rule of a BindLink always produces something valid, and in the context of the URE that is hard to enforce. In particular when a rule turns out to be no applicable you don't want the rule to return something, it is better to return nothing, or Handle::UNDEFINED as it used to be.

**Comment by linas** [comment]
I thought about this some more, and maybe its an OK usage, although its a bit of an abuse -- you are trying to perform a pattern match after pattern matching has completed. If you want to reject certain types of clauses, then add a term that actually rejects those -- e.g. something that check for a TV value of 1 1, and rejects the match.  

That is, a bindlink is supposed to be: "if (P) then (Q)" and you are turning it into "if(P) then (if also P-prime then(Q)" -- just move the P-prime check into P. and then you won't have this problem.

Anyway, if you want to do post-match matching like this, then you should also use a silent, not a signalling exception, else the log file will get all clogged up.

Also: performance and efficiency -- doing those crazy variable names will cause the atomspace to get large for no good reason, which hurts performance. It might make adding links slow, although the alpha-conversion code should be able to weed out any duplicates efficiently, I think.

**Comment by ngeiswei** [comment]
I agree, ideally the nested condition should be moved to P, it's just currently easier to program that inside Q.

**Comment by linas** [comment]
OK. I am still trying to fix bug #950, which I want to do before looking at this. That one is blastedly complex.

**Comment by linas** [comment]
I'm still confused. In the notes to pull #962, you state that https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/ImplicationLink.cc#L65-L67 is throwing an error. Here, you state that you don't want to have that error be thrown.  Isn't the simplest fix to just not throw? That way, you don't mess up the test.   I mean, what's the point of checking for an error condition, if you then decide to ignore the error condition?

**Comment by ngeiswei** [comment]
But you don't want to build an ill-formed ImplicationLink, so a way or another the ctor must be aborted, I think throwing an exception is the right way to cleanly abort the ctor.

**Comment by ngeiswei** [comment]
This is fixed so I'm closing. As per Linas' report #972 the use of exception might an inefficient way to handle the problem, the right to proceed I suppose is to not build an ill-formed link to begin with by having say the factory checks preconditions, for instance, but that's another issue.

**Comment by linas** [comment]
exceptions are fine if they are infrequent. The problem was with using them in the main code execution path, every time.
