### ISSUE TITLE
Derived AtomSpace's getHandlesByType() bug?

### ISSUE THREAD

**Issue by williampma** [opencog/atomspace#97]
Some inconsistency while working with InitiateSearchCB::link_type_search() lead me to this problem:

Empty AtomSpace _as:
```
	AtomSpace temp(_as);

	_as->addNode(CONCEPT_NODE, "lalala");
	temp.addNode(CONCEPT_NODE, "kakaka");

	HandleSeq handle_set;
	temp.getHandlesByType(handle_set, CONCEPT_NODE);
```

I expected `handle_set` will be size 2, but instead got size 1.  Only "kakaka" was found, even though "lalala" should also be considered part of "temp"?

**Comment by williampma** [comment]
I can sort of see the problem.

AtomTable's `getHandlesByType` only look at its `typeIndex` member, but `typeIndex` does not contain information on the parent's `typeIndex`...

Perhaps to fix this I just need to change the function to also copy `_environ->getHandlesByType`...?

**Comment by linas** [comment]
Yes, I think that is the correct semantics and the correct fix.
