### ISSUE TITLE
TrumpLink

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#990]
Could be useful.

**Comment by misgeatgit** [comment]
:smile:

**Comment by ngeiswei** [comment]
As I was writing the title of issue #991 my fingers mechanically typed "who-should-not-be-named" and my fingers uncontrollably slipped on the Ctrl+Enter shortcut key and sent, I'm not even kidding.

**Comment by linas** [comment]
What a disaster.  We're going to have a mentally deranged person running the country.  Ancient Rome fell, is this the beginning of the end for the US?

**Comment by ngeiswei** [comment]
May the opensourcetopia rise and liberate us all!

**Comment by ngeiswei** [comment]
Oh, well, all this seems actually rather irrelevant, I'm closing.
